### ISSUE TITLE
Additional metadata for processors on CPU details (graphs) display?

### ISSUE THREAD

**Issue by robertroessler** [winsiderss/systeminformer#1083]
As we begin to explore the new worlds of Windows 11 and 12-th Gen Intel CPUs - and their interactions - it could be nice to be able to see some additional data for each of the "logical processors".

Basically, I have 3 possible "enhancements" so far:

1) for Win10/Win11, some visual indication of the physical cores _and_ their associated logical processors (like a very thin dotted line around each physical core's grouping? Yes, this is a very preliminary suggestion, and doesn't handle very well logical processors that are on the same core but on different rows of the display)

2) an indication of the type of physical core "type" (like **P** or **E** at the start of the %-usage display?)

3) an indication of "parked" status (like replacing the graph area of a parked core / logical processor with cross-hatching?) - and yes, this may have relevance pre-Windows 11 / 12th-Gen Intel CPUs

Aside from the obvious eye-candy aspects - which may or may not be enough to justify dev time - I am thinking features like these could be of real help in seeing the results of the schedulers (both H/W and S/W) and their interactions with workloads.

And increased visibility into these underlying processes _could_ eventually lead to increased understanding.

**Comment by dmex** [comment]
> indication of the type of physical core "type" (like P or E

The latest nightly build now shows E-Core or P-Core in the tooltip when hovering the mouse over the processor graphs 👍
