### ISSUE TITLE
Failed to generate dump files.

### ISSUE THREAD

**Issue by rqueizan** [winsiderss/systeminformer#1120]
### Brief description of your issue

On another computer, when I run the PH in the administrator session, it generates the dump on the administrator's desktop.
However, on mine own computer run PH as administrator and it doesn't generate the DUMP files.

### Steps to reproduce (optional)

Install Process Hacker Nigtly Build: 3.0.4554.
Run it as administrator from another user account.
Wait for an invalid access memory location error.
Click on generate a Normaldump or Minidump.

### Expected behavior (optional)

It should generate a Dump file on the desktop.

### Actual behavior (optional)

It does not generate the Dump file or notify any error, it simply closes.

### Environment (optional)

```shell
Process Hacker Nigtly Build: 3.0.4554
Windows 11 Enterprise 64 bits, 32GB RAM, Ryzem 5 4600 12 cores.
```

**Comment by dmex** [comment]
> Run it from another user account... does not generate the dump file

It's saving the crash dump to the other desktop because that user is running the program?

**Comment by as-muncher** [comment]
I've found that Process Hacker 3.0.4600 didn't generate a normal crash dump when it crashed but it did create a minidump the next time I made it crash and chose that option.

**Comment by rqueizan** [comment]
For my part, the application has not failed again, Process Hacker 3.0.4600.
