### ISSUE TITLE
CPU Usage precision

### ISSUE THREAD

**Issue by mdblack98** [winsiderss/systeminformer#1134]
### Description of the feature, modification, idea or suggestion

I've been doing a lot of work on some apps using the CPU usage to reduce CPU usage.
I'm getting down in the weeds now with CPU usage less than 0.01 -- so if the CPU usage for the graph EVER drops below 0.01 can we get 3 digits of precision?  Or make it an up/down control widget for precision next to the Show  one graph per CPU?

ProcessHacker has been tremendously helpful.

**Comment by mdblack98** [comment]
In the process properties for starters.We've been working on minimizing CPU usage on numerous utilities and starting to get into the weeds.As it stands now we get the graph but no scale -- it just shows 0.00% (K: 0.00%, u: 0.00%) which of course doesn't make much sense when you can see a graph with values.
Mike

 

    On Thursday, March 17, 2022, 10:50:31 AM CDT, dmex ***@***.***> wrote:  
 
 



can we get 3 digits of precision


The precision is already configurable but uses a hard-coded value of 2.


precision next to the Show one graph per CPU


Do you only want the cpu columns/graph values configurable? Making every float/double configurable would take some time so if you can give me a specific list of columns/values then it would be quicker/easier to just do those now and the others later.

—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dmex** [comment]
The latest nightly build includes a new setting named `MaxPrecisionUnit` for changing the precision up to 32 digits. I've added this to the process properties graphs but what others could be updated?

**Comment by mdblack98** [comment]
Thanks!

I notice the label on the CPU graph peak still shows 2-digits instead of the MaxPrecision.


I don't know of any others that need to be using this unless you did it on the main window too.  But I might make that a separate setting as I'm not sure I'd want to see that many digits all the time.  Maybe on the right-click menu for the main window?

Mike 







On Thursday, March 24, 2022, 11:07:29 PM CDT, dmex ***@***.***> wrote: 







The latest nightly build includes a new setting named MaxPrecisionUnit for changing the precision up to 32 digits. I've added this to the process properties graphs but what others could be updated?

**Comment by dmex** [comment]
> I notice the label on the CPU graph

It's a work in progress. There's about 100 different places that need updating to fully integrate the setting.

>  But I might make that a separate setting as I'm not sure I'd want to see that many digits all the time.  Maybe on the right-click menu for the main window?

It's all or nothing. more than one setting won't be maintainable.

**Comment by mdblack98** [comment]
Is the value rounded up or down?

I guess adding it to the main window would be desirable then....to see all the process chewing up very little CPU that could be improved.

Mike










On Friday, March 25, 2022, 07:37:21 AM CDT, dmex ***@***.***> wrote: 







>  
> I notice the label on the CPU graph
> 

It's a work in progress. There's about 100 different places that need updating to fully integrate the setting.

>  
> But I might make that a separate setting as I'm not sure I'd want to see that many digits all the time. Maybe on the right-click menu for the main window?
> 

It's all or nothing. more than one setting won't be maintainable.

**Comment by dmex** [comment]
> Is the value rounded up or down?

Rounding wasn't implemented.

**Comment by mdblack98** [comment]
If you didn't deliberately round then you are probably getting "nearest" rounding.
I would think for any percentage value or such one would round up since zero is never an answer when CPU is above zero for example.  So even 0.004 CPU usage should show as 0.01 with 2 digits of precision instead of 0.00

So that should just be this
double  round = 1/(2*10^PhMaxPrecisionUnit);
PhInitFormatF(&format[0], ((DOUBLE)processItem->CpuKernelUsage + processItem->CpuUserUsage) * 100 + round, PhMaxPrecisionUnit););

Mike







On Saturday, March 26, 2022, 02:58:57 AM CDT, dmex ***@***.***> wrote: 







>  
> Is the value rounded up or down?
> 

Rounding wasn't implemented.

**Comment by dmex** [comment]
> 0.004 CPU usage should show as 0.01 with 2 digits of precision instead of 0.00

 You need to enable the View menu > Show CPU below 0.01 option.

**Comment by dmex** [comment]
Closed by `PhMaxPrecisionUnit` setting 804b243d0118f610615051490f5117773d1a3713 👍
