### ISSUE TITLE
Unable to load kernel driver service 

### ISSUE THREAD

**Issue by ghost** [winsiderss/systeminformer#1142]
### Brief description of your issue

When enabling the kernel-mode driver Process Hacker informs me that it was unable to load the driver service, as the service in question has apparently been removed and PH is unable to install it, even with cli commands, this also happens with sandboxie, so it's likely that Microsoft changed something regarding drivers in the latest updates of Windows 11.

### Steps to reproduce (optional)

Install latest updates from the dev channel on Windows 11.
Enable kernel-mode driver
![kp](https://user-images.githubusercontent.com/79342645/155769962-9bd54f18-8ad4-4426-b090-b256184d6f0b.png)

### Expected behavior (optional)

The kernel-mode driver should work as it did on previous versions.

### Actual behavior (optional)

As stated, the process is unable to be created and thus this function won't work.

### Environment (optional)

```shell
Process Hacker nightly, also tested on stable with same results.
Latest Windows 11 build from dev channel (OS. Build 22563.1)
```

**Comment by dmex** [comment]
> Microsoft changed something regarding drivers in the latest updates of Windows 11

They've banned our digital signature/revoked our certificate in the latest Windows update.

**Comment by g-yui** [comment]
That seems like an awfully targeted attack.
Is there anything that can be done at the moment? Perhaps compiling the code and signing the driver manually?

**Comment by Masamune3210** [comment]
Microsoft is no stranger to actively trying to thwart this project, so its nothing new for them.

**Comment by nodomw** [comment]
It seems justified from Microsoft's end since they're close to releasing the new Task Manager and most likely want to squash competition.

**Comment by g-yui** [comment]
"New" is a generous way of putting it, it's more like a fresh coat of paint and a new efficiency mode for Task Manager and that's yer lot.

**Comment by Masamune3210** [comment]
> That seems like an awfully targeted attack. Is there anything that can be done at the moment? Perhaps compiling the code and/or signing the driver manually?

That's not how driver signing works unfortunately and a new cert is expensive and will likely just get revoked again

**Comment by bimal-b** [comment]
can we manually trust the certificate or install it in the trusted store so that the driver loads. of course, this will be applicable to people with administrative privileges.

**Comment by g-yui** [comment]
@Masamune3210 You can manually sign a driver for use on your own machine, this is what I meant by "signing the driver manually".

>  [You can create your own certificate to sign your driver with during development and testing](https://docs.microsoft.com/en-us/windows-hardware/drivers/develop/signing-a-driver)

**Comment by Masamune3210** [comment]
The user signing the driver kinda defeats the purpose of the signature, which is to validate that the driver hasn't been tampered with. But I see your point

**Comment by dmex** [comment]
> You can create a certificate to sign a driver for use on your own machine, this is what I meant by "signing the driver manually".

Microsoft is testing updates on the Windows 11 insider branch that currently prevent developers/security researchers from compiling the driver source and debugging it with test signing. If you're trying to compile the source-code and debug the driver with self-signed test certificates then you need to change this string to bypass those checks:
https://github.com/processhacker/processhacker/blob/3e80de2bd64f70b7ec4bde085eea81c3e0f3ff77/KProcessHacker/resource.rc#L23

**Comment by JLJTGR** [comment]
It's worse that this is parroted by AV companies that mark this as potentially unwanted software which throws up "scary" alerts and might even quarantine it.  Some AV companies even have designations that literally have the program name as the virus type.  

I feel like Microsoft/etc can't get past the stigma of the "hacker" name.  I think this is more likely than ProcessHacker competing with a program from their bought-out subsidiary Sysinternals.  They don't make any money from ProcessExplorer existing or being used instead of ProcessHacker.  There's already an entire thread about the program name, so I'll leave that there.

I can't even imagine where to go to shine meaningful light about this unwarranted discrimination.  I feel like it would take some social media giant like LTT/GN/J2C(Youtube channels) to make Microsoft even blink at this issue.  (would EFF care about something like this?)  Then they still wouldn't even care.  We could argue that this is an anti-trust issue, but Microsoft could argue it's several other things.

**Comment by n0101** [comment]
The error message I get when I try and run with kernel driver includes the line "A certificate was explictly revoked by its issuer"

<img width="265" alt="image" src="https://user-images.githubusercontent.com/43557511/164509679-507fb593-4dfd-4d92-b92f-6bd71a7af977.png">

**Comment by g-yui** [comment]
Yup, the message has since been updated on my end as well.

**Comment by CaptainFrosty** [comment]
My ESET lovingly refers to it as an Unsafe Program. It is the lowest class at least.

**Comment by dmex** [comment]
> A certificate was explictly revoked by its issuer

This is a fake error code. The certificate has not been revoked. Microsoft returns that "error" when encountering drivers with this original filename in the version resource:

https://github.com/processhacker/processhacker/blob/3e80de2bd64f70b7ec4bde085eea81c3e0f3ff77/KProcessHacker/resource.rc#L23

The name has since been changed so future versions won't encounter these fake error codes (at least until Microsoft update their illegal blocklist again).

**Comment by n0101** [comment]
> > You can create a certificate to sign a driver for use on your own machine, this is what I meant by "signing the driver manually".
> 

https://github.com/processhacker/processhacker/blob/3e80de2bd64f70b7ec4bde085eea81c3e0f3ff77/KProcessHacker/resource.rc#L23
> 

So if we want to use the kernel driver we have to do the above?

> The name has since been changed so future versions won't encounter these fake error codes (at least until Microsoft update their illegal blocklist again).

I'm on 3.0.4801 (078a905) and the driver name is still the same and being blocked.  It looks like you addressed this in commit [22e1f53](https://github.com/processhacker/processhacker/commit/22e1f53997e1bf7f5967e326752f4142c326d73f) but the setup is still creating a kprocesshacker.sys for me.

**Comment by ordinary-github-user** [comment]
![png](https://user-images.githubusercontent.com/106221595/172326200-03f6614f-eabb-495d-a343-6fa79498c296.png)

> at least until Microsoft update their illegal blocklist again

any idea where this check is? i want to patch this check, load kprocesshacker.sys, then unpatch the check to prevent triggering patchguard

**Comment by dmex** [comment]
1) Open regedit
2) Navigate to `HKLM\System\CurrentControlSet\Control\CI\Config\`
3) Create a new DWORD named `VulnerableDriverBlocklistEnable` and set to `0`
4) Reboot

**Comment by ordinary-github-user** [comment]
thank you!

**Comment by itsmeboy0** [comment]
> 1. Open regedit
> 2. Navigate to `HKLM\System\CurrentControlSet\Control\CI\Config\`
> 3. Create a new DWORD named `VulnerableDriverBlocklistEnable` and set to `0`
> 4. Reboot

It seems to work for the first time, but once I reboot, I get this:
![image](https://user-images.githubusercontent.com/75471378/173477893-0db1a3fc-2281-47d3-9400-d15b4bd397dd.png)

**Comment by dmex** [comment]
@itsmeboy0

No idea. Something is wrong with your machine. Something is probably hooking the kernel and returning invalid error codes.

**Comment by itsmeboy0** [comment]
Really? I tried the stable version, and it works just fine.

**Comment by dmex** [comment]
@itsmeboy0

Yes. This works for everyone else so it's either your security software or malware.

**Comment by itsmeboy0** [comment]
**Fixed:** I installed [`processhacker-nightly`](https://github.com/ScoopInstaller/Versions/blob/master/bucket/processhacker-nightly.json) from Scoop. I switched to using the installer, and it now works. So maybe it's how Scoop installs processhacker that makes it not work?

**Comment by Bunie89** [comment]
the last nightly of Process Hacker seems to be "banned" in 22621.457

**Comment by dmex** [comment]
@Bunie89 

https://github.com/winsiderss/systeminformer/issues/1142#issuecomment-1148635917

**Comment by xprzemekw** [comment]
Does not work when Core Isolation is enabled.

This is really shitty behaviour on MS side.

![image](https://user-images.githubusercontent.com/9196393/192148453-2684f9de-d85a-4111-b41d-68b338f3773a.png)

**Comment by andry81** [comment]
> This is really shitty behaviour on MS side.

Only the MS has the right to put anal probes into your PC. Welcome to half eaten apple club.

**Comment by littleboot** [comment]
Hi, I found a fix for my system. Because I used NTLITE to create a windows install without windows defender, I'm not able to turn of the memory integrity setting from the GUI. instead I did this to fix the problem:

open regedit: and browse to "Computer\HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\DeviceGuard\Scenarios\HypervisorEnforcedCodeIntegrity "

and changed the DWORD "Enabled" from 1 to 0

**Comment by Masamune3210** [comment]
Might want to keep a eye on that for a bit. Defender tends to see any system modification done outside of the GUI as tampering and will sneakily revert it seemingly at random times

**Comment by Ou7law007** [comment]
Is there anything that could be done about this? How could Microsoft get away with this? Microsoft's monopoly must end. Windows is becoming so awful.

**Comment by gotqn** [comment]
It this turning this option off:

![image](https://github.com/winsiderss/systeminformer/assets/2104401/5bca1704-cf72-4578-bf43-9dfc194faf9a)


the same as the fix:

> * Open regedit
> * Navigate to `HKLM\System\CurrentControlSet\Control\CI\Config\`
> * Create a new DWORD named `VulnerableDriverBlocklistEnable` and set to `0`
> * Reboot
