### ISSUE TITLE
wrong cpu topology shown

### ISSUE THREAD

**Issue by shuffle2** [winsiderss/systeminformer#1146]
### Brief description of your issue

on amd 3990x (set in uefi to appear as 1 numa node with 64C/128T), process hacker's "system information" dialog reports topology incorrectly, and doesn't seem to report cpu usage information correctly.

### Actual behavior (optional)

![image](https://user-images.githubusercontent.com/113063/157573114-001e2e1a-74c2-4635-96d0-31eee0df66ca.png)
(task manager and PH showing cpu stats at same time)

**Comment by shuffle2** [comment]
Running the current nightly, there is some improvement I guess ("logical processors" = 2 * "cores", now). However, the core count is still 32 while it should be 64. That was also what I was getting at with "doesn't seem to report cpu usage information correctly" (admittedly unclearly): it seems process hacker is showing only the first 64 logical processors. The hardware has 64 cores and 128 threads, which windows exposes as 2 separate processor groups for legacy reasons. See https://docs.microsoft.com/en-us/windows/win32/procthread/processor-groups for some background and recent changes on win11. So, naively, I would expect a cpu graph for each logical processor. which, fwiw, is what procexp shows: 
![image](https://user-images.githubusercontent.com/113063/158448058-50ef38b9-116d-4c6a-bb80-45dd702a42b7.png)

**Comment by dmex** [comment]
> process hacker is showing only the first 64 logical processors

I've implemented group support in the latest nightly build and we now support 2048 processors 👍 

The latest nightly should now correctly report utilization and the number of processors.

> recent changes on win11

Windows 11 seems to have some major issues with AMD 3990x and multiple applications. I recommend not using Windows 11 when you have more than 64 processors. I've started a discussion thread with Microsoft about some of the issues we've found and will update the thread when I have more information.

**Comment by shuffle2** [comment]
> The latest nightly should now correctly report utilization and the number of processors.

Yes, seems to work. Nice!

> I've started a discussion thread with Microsoft about some of the issues we've found and will update the thread when I have more information.

Would be interested to hear (eventually).

**Comment by dmex** [comment]
> Would be interested to hear (eventually).

Any programs using these functions will not work correctly on Windows 11 (basically every program ever written):

1) CPUID
2) GetSystemInfo:
    dwNumberOfProcessors
    dwActiveProcessorMask
3) GetSystemTimes:
    lpIdleTime
    lpKernelTime
    lpUserTime
4) GetThreadTimes/GetProcessTimes:
    lpKernelTime
    lpUserTime
5) NtQuerySystemInformation with classes:
    SystemBasicInformation
    SystemInterruptInformation
    SystemLogicalProcessorInformation
    SystemProcessorPerformanceInformation
    SystemProcessorIdleInformation
    SystemProcessorPowerInformation
    SystemProcessorIdleCycleTimeInformation
    SystemProcessorPerformanceDistribution
    SystemProcessorCycleTimeInformation

Some examples:

> First issue (CPUID):
> 
> 1: program calls SetThreadAffinityMask()/SetThreadGroupAffinity() (processor 1, group 0)
>** scheduler switches thread onto group 1
> 2: program calls CPUID attempting to detect features of processor 1, group 0 but instead information is returned from processor 1, group 1.
> 
> 
> Second issue (GetSystemInfo: ARM64 processors and also CPU hotswap/hotplugging on AMD/Intel):
> ActiveProcessorCount: 80
> Group 0: 64 processors.
> Group 1: 16 processors.
> 
> 1: scheduler switches thread onto group 1
> 2: program calls GetSystemInfo() and dwNumberOfProcessors returns 16
> 3: program calls HeapAlloc(sizeof(T) * 16)
> ** scheduler switches thread onto group 0
> 4: multiple ioctl and system call failures. Incorrect buffer size for current processor group 0 (required 64 but passed 16 instead).
> 
> Since GetSystemInfo is not deprecated, every last application is using GetSystemInfo is affected.
> 
> Third issue (GetSystemTimes):
> 1: scheduler switches thread onto group 0
> 2: program calls GetSystemTimes()
> 3: program calls Sleep(1000)
> ** scheduler switches thread onto group 1
> 4: program calls GetSystemTimes()
> 5: arithmetic underflow/overflow. Subtracting the two values unexpectedly produces an unsigned minus and breaks calculations for deltas/percentages.
> 
> Forth issue (GetThreadTimes/GetProcessTimes):
> The GetProcessTimes and GetThreadTimes functions return statistics that are accumulated from multiple processor groups. Applications compare those against the values returned by GetSystemTimes. It's not possible to use GetSystemTimes on Windows 7/8/10/11 since GetSystemTimes doesn't accumulate statistics for all processor groups.
> 
> Since GetProcessTimes is not deprecated, every application using GetProcessTimes is affected.
