### ISSUE TITLE
sorting columns

### ISSUE THREAD

**Issue by Kizaemon** [winsiderss/systeminformer#1159]
### Description of the feature, modification, idea or suggestion

I am long time PH user, and love the program. Thank you very much!

The function I miss most is a better column management for the grids.

I usually add all available and newly added columns to all grids.
The newly added columns are then appended to the end of the list.
The order of the columns becomes unnatural.

The only way to resort 100s of columns is using the "Choose columns..." dialog, which is very tedious.

I wonder if you could consider adding several new features in future:

1) Column Group Identifier for each column (e.g. CPU, Process, Memory, I/O, Network, ...)
Thus the columns can be treated by their origin and not just alphabetically.

2) A function (a button) to reset column order to some natural pre-defined order, from an internal template.

3) Perhaps a better column manager, where the columns can be rearranged and grouped more efficiently.

4) Perhaps a function to import/export column order and widths for better portability.

**Comment by dmex** [comment]
You can save column sets/layouts and quickly change the layouts using these menus: 

![image](https://user-images.githubusercontent.com/1306177/168422895-0f0f6266-1e4f-4ddc-9d20-6fc8ae6b566d.png)
