### ISSUE TITLE
Allow negation of search results 

### ISSUE THREAD

**Issue by redsigma** [winsiderss/systeminformer#1231]
### Description of the feature, modification, idea or suggestion

I dont know if the title is correct but I'll try to explain what i want.

Currently in the search bar, if i type `skype` it will show all processes named skype. I'd like to have a feature where if i type `!skype` it will show every process except skype

**Where would this help**
In my case i have ~80 svchost.exe processes running. I have checked all of them and they are legit processes(services).  Having a feature that can temporarily hide them would be convenient.

This feature might be a workaround for #796 

### Proposed implementation details (optional)

**Optional**
The above feature can be expanded by adding labels to processes and you can search by these labels. For example I can label `Teams.exe` and `Skype.exe` as `ms-apps` and when I search for `l:ms-apps` it will only show those apps

An idea on how to implement this (it's just an assumption), would be to make the labels point to the absolute path of the process. However some processes have the same path (processes such as `svchost.exe`), so in their case they will point to the service name.

**Comment by jxy-s** [comment]
Latest build (3.0.7348) supports regex and case sensitive search boxes in all areas of the project:

![image](https://github.com/winsiderss/systeminformer/assets/11687482/e43c3f25-2910-4ad9-8fa7-726bbd18e65d)

**Comment by redsigma** [comment]
> Latest build (`3.0.7348`) supports regex and case sensitive search boxes in all areas of the project:
> 
> ![image](https://private-user-images.githubusercontent.com/11687482/287789296-e43c3f25-2910-4ad9-8fa7-726bbd18e65d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTE3ODg3MDYsIm5iZiI6MTcxMTc4ODQwNiwicGF0aCI6Ii8xMTY4NzQ4Mi8yODc3ODkyOTYtZTQzYzNmMjUtMjkxMC00YWQ5LThmYTctNzI2YmJkMThlNjVkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzMwVDA4NDY0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWU5N2UzNWMyMTJkNjI4NDM5NjY4NGFjOGIwYjZlNDIzNDlkYTk4MDA5Yjg2MjRhYTAyMThjNzhmMTY0M2ExMzEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PoraY-Mfsch94UOdC4wzLTKNzk4rtlLALTxyAK1WwCg)


Below are some regexes I crafted for `showing all apps except TeamViewer` (which is called TeamViewer_Service.exe)

First approach
---
`\b(?!team)\w+\.exe`   - this excludes every that starts with `team` and ends with anything else

Second approach
---
`\b(?!team\b)\w+\.exe`  - this excludes only team.exe  (useful for exact match)

Third approach
---
`^(?=.*view).*\.exe$`  - this excludes  everything that contains `view` 


Caveats with the above regexes
---
Using them in the Network tab will also hide any `Waiting connections` or any word that doesnt even have .exe in the name.


@jxy-s As you can see these regexes are not easy to type and they force the user to memorize them or note them down. I think there should be at least some premade regexes available. Maybe by right clicking on that regex button and have some `negate` option showing a dropdown

**Comment by jxy-s** [comment]
> Using them in the Network tab will also hide any Waiting connections or any word that doesnt even have .exe in the name.

The solution is adding something about "Waiting connections" to your expression:  `(?=.*view).*\.exe|Waiting`

> @jxy-s As you can see these regexes are not easy to type and they force the user to memorize them or note them down. I think there should be at least some premade regexes available. Maybe by right clicking on that regex button and have some negate regex option showing in a dropdown.

> However I think that maintaining these regexes might become complicated depending on executable names and paths. I think that having a NOT switch at the application level, would offer better control over the results, rather than forcing the users to make a regex.

It is unfortunately not that simple. Negating a search is more complicated than it seems. What should be done if a user negates a search? Any item not containing that information should match. Many cells will match. Very likely, even the row the user expected to negate away. For example, `(?!team)` on the network tab - well the `Local address` doesn't contain `team`, so should that be kept? What if that local address is for a process with the `Name`: `TeamViewer_Service.exe`? We could cook up some criteria of hierarchy with the search, but that intrudes more hidden complexity and confusion.

It is very subjective what the user wishes to keep or not. Regular expressions gives you all the control you would need to achieve the matching criteria.

**Comment by redsigma** [comment]
> > Using them in the Network tab will also hide any Waiting connections or any word that doesnt even have .exe in the name.
> 
> The solution is adding something about "Waiting connections" to your expression: `(?=.*view).*\.exe|Waiting`
> 
> > @jxy-s As you can see these regexes are not easy to type and they force the user to memorize them or note them down. I think there should be at least some premade regexes available. Maybe by right clicking on that regex button and have some negate regex option showing in a dropdown.
> 
> > However I think that maintaining these regexes might become complicated depending on executable names and paths. I think that having a NOT switch at the application level, would offer better control over the results, rather than forcing the users to make a regex.
> 
> It is unfortunately not that simple. Negating a search is more complicated than it seems. What should be done if a user negates a search? Any item not containing that information should match. Many cells will match. Very likely, even the row the user expected to negate away. For example, `(?!team)` on the network tab - well the `Local address` doesn't contain `team`, so should that be kept? What if that local address is for a process with the `Name`: `TeamViewer_Service.exe`? We could cook up some criteria of hierarchy with the search, but that intrudes more hidden complexity and confusion.
> 
> It is very subjective what the user wishes to keep or not. Regular expressions gives you all the control you would need to achieve the matching criteria.

Thank you for the detailed response, now I understand why it would be tricky to implement it. When I search for something I am usually focusing on the Name column alone. I am not sure how the logic of a normal search filters out the items that dont match the search,  but for a negation I have this approach in mind: 

We search for `(?!team)` and it's gonna hide all items where at least 1 column contains the word `team`

The disadvantage of this is that it might hide stuff that has the `team` word in places you're not aware, such as Description, Verified Signer, or even the absolute path. But I think this "issue" happens with a normal search too, because when you do a search with `team`, it might return results which you didn't expect (because again the word `team` was burried in other places)

---

I feel that a better way to implement negation would be to introduce another feature called per-column filtering. For example with a syntax like this:
`name\\firefox`  -> this will search only in the Name tab and returns all rows matching this
`displayname\\Remote Desktop`  -> this will search only in the DisplayName tab and return all matched rows

If we have the above feature, then I think negation would be more viable. Also per-column filtering isnt needed for every column but only for the ones that are very used such as Name and FileName.

---

And about the `(?=.*view).*\.exe|Waiting` solution which you mentioned. I could indeed hardcode the text in the regex but what if something else shows up, it will be hidden again and I wont know that. I only found out that `Waiting connections` was wrongly hidden just by accident.

**Comment by jxy-s** [comment]
> @jxy-s Do you think this per-column filtering feature would be viable to implement. I Could make a separate issue for it.

Yes, I think an option for only searching in a specific column would be a more sane approach to that. There is already an existing enhancement request here: https://github.com/winsiderss/systeminformer/issues/1876

> If we have the above feature, then I think negation would be more viable. Also per-column filtering isnt needed for every column but only for the ones that are very used such as Name and FileName.

I agree. And I would go further to say searching in general would be more viable.

> And about the (?=.*view).*\.exe|Waiting solution which you mentioned. I could indeed hardcode the text in the regex but what if something else shows up, it will be hidden again and I wont know that. I only found out that Waiting connections was wrongly hidden just by accident.

I think that's a problem with search (or more broadly filtering) in general, not just regex or negation (discussed here: https://github.com/winsiderss/systeminformer/issues/796). If you don't want to hide things, don't filter/search.
