### ISSUE TITLE
Making thread boosting better.

### ISSUE THREAD

**Issue by Dajova** [winsiderss/systeminformer#1244]
### Description of the feature, modification, idea or suggestion

So i kinda love [this](https://github.com/processhacker/processhacker/issues/1145) feature where it actually boost the performance on basically any process i apply it on... Only problem is that it doesnt seem to save/stick between session, even when its saved for the process itself and/or the IFEO way. Would love to see it actually stick and saved, so i dont have to enter PH everytime i want to get some more performance out of certain processes...

**Comment by dmex** [comment]
> doesnt seem to save/stick between session, even when its saved for the process itself and/or the IFEO way

The boost feature doesn't get persisted like those other options.

**Comment by dmex** [comment]
![image](https://user-images.githubusercontent.com/1306177/181137045-78fbfc72-27c0-4a9d-9ff0-7f5b4f332078.png)
