### ISSUE TITLE
Whats this now?

### ISSUE THREAD

**Issue by ImSpecial** [winsiderss/systeminformer#1253]
Seems like a lot of stuff is going on now, a new owner? New name, etc.

So what's happening, why the changes?

**Comment by dmex** [comment]
https://twitter.com/aionescu/status/1536494552105766912

**Comment by ImSpecial** [comment]
I see... As long as you are still involved with PH(RIP), this news seems not so alarming I suppose, a signed driver is welcoming news though.

**Comment by ionescu007** [comment]
@dmex is not going anywhere!!!

**Comment by Darthagnon** [comment]
If anyone wants the last version before the rebranding, v3.0.4953, [here's a mirror](https://github.com/ProcessHackerRepoTool/nightly-builds-mirror/releases/tag/3.0.4953)

**Comment by Masamune3210** [comment]
Mind you, the kernel driver in the old version is not going to likely work with any vaguely up to date system with default settings,as Microsoft a while ago blacklisted the driver iirc. Also, please don't spam on multiple issues

**Comment by ImSpecial** [comment]
v3.0.4953 works 100% on Windows 10 Pro (64-bit), 22H2 / 19045.2251

Mind you I have the one from Dex's site (before it was removed...), and not from the above posters fork.

**Comment by dmex** [comment]
> not from the above posters fork.

@ImSpecial The link he posted to `ProcessHackerRepoTool` was an official mirror created with my account 😉

I've taken it down since we're now using si-builds: https://github.com/winsiderss/si-builds

**Comment by Darthagnon** [comment]
Sorry for multiposting. I've attached a zip with SHA256 of the final version since the repo is now gone.
[processhacker-3.0.4953-final.zip](https://github.com/winsiderss/systeminformer/files/10087634/processhacker-3.0.4953-final.zip)
