### ISSUE TITLE
Migration from ProcessHacker to SystemInformer without loosing my settings

### ISSUE THREAD

**Issue by MagicAndre1981** [winsiderss/systeminformer#1261]
### Description of the feature, modification, idea or suggestion

Please add an automatic migration from ProcessHacker to SystemInformer without loosing my settings in .exe.xml and usernotes.xml as there are a lot of ProcessHacker.XYZ settings in the xml

**Comment by dmex** [comment]
You should make backups of those files... There could be some initial teething issues with migration.
