### ISSUE TITLE
Update 

### ISSUE THREAD

**Issue by omertazzz** [winsiderss/systeminformer#1263]
### Description of the feature, modification, idea or suggestion

I think you should update it to where people that like windows 11 and want to use process hacker can use it.

**Comment by Biswa96** [comment]
It may take some time https://twitter.com/aionescu/status/1536494552105766912

**Comment by jxy-s** [comment]
The ask here is not clear to me. The project already supports Windows 11. Or are you asking for something different?

**Comment by jxy-s** [comment]
This was moved to another location. Open the process information (double click a process in the tree). On the `Modules` tab for the process then `Options` > `Load module...`.
