### ISSUE TITLE
[Minor option] On start: Scroll to bottom of tree view [option]

### ISSUE THREAD

**Issue by AltF5** [winsiderss/systeminformer#1268]
### Description of the feature, modification, idea or suggestion

Use: When having many collapsed processes (or not), it is useful to see the bottom-most processes first (usually the most recently executed ones by explorer.exe in that case). This seems relatively simple or possibly could automated by sending the [End] key to SystemInformer's Process Tree view.

**Comment by jxy-s** [comment]
I want to make sure I fully understand what you're asking. By "collapsed processes" you mean processes' tab and the parent-child tree view?

If I'm understanding you correctly you want to order the tree view child items in some meaningful way. I don't think the work involved in this change is worth the value proposition, honestly.

**Comment by AltF5** [comment]
> I want to make sure I fully understand what you're asking. By "collapsed processes" you mean processes' tab and the parent-child tree view?
> 
> If I'm understanding you correctly you want to customize the order of the child items in the tree view. I don't think the work involved in this change is worth the value proposition, honestly.

I probably made this sound far too complicated. Mainly just a small enhancement to "Scroll to bottom on start", that is to have the TreeView send some window message to scroll all the way to the bottom (whereby its usefulness would be if we have customized many parent processes to be collapsed for organizational sake, then instead of the treenview starting from top-most with System Idle Process, it instead would include more recently run processes from explorer.exe)

**Comment by jxy-s** [comment]
Please just sort the table by how you want to view the processes. If you want to view them "bottom-up" you can do that using the columns in whichever way you define "bottom" or "up".

**Comment by fade2gray** [comment]
> We are in the middle of migrations and ask for patience while we're carrying that out.
> 
> All these feature requests and PRs are coming at a really bad time. I'd ask that you please hold off on further requests until after we complete the migration.
> 
> We have considered locking the repo until we complete migrations. I don't want to have to do this. But if it does get unmanagable we will.

Suggestion: couldn't that be pinned at the top of issues?

**Comment by jxy-s** [comment]
Done, thanks for the suggestion @fade2gray .
