### ISSUE TITLE
Log max size (entries [n] count)

### ISSUE THREAD

**Issue by AltF5** [winsiderss/systeminformer#1269]
### Description of the feature, modification, idea or suggestion

Use: would allow Help > Log to still operate, but be more of a "live running total" for the last [n] configured events.

I noticed there is Options > Advanced > LogEntries = 200, but that doesn't seem to be respected, at least in the Help > Log window.

### Proposed implementation details (optional)

Oldest entries are popped off the "stack", while new entries are pushed on (into the log)

**Comment by dmex** [comment]
> LogEntries = 200

0x200 = max 512 entries.

> that doesn't seem to be respected, at least in the Help > Log window.

It works fine. Changing the setting requires a restart. 

> Oldest entries are popped off the "stack", while new entries are pushed on (into the log)

This is what the LogEntries setting already does.

**Comment by AltF5** [comment]
Oh man its in Hex. Thank you!
