### ISSUE TITLE
Rotate log after [n] entires

### ISSUE THREAD

**Issue by AltF5** [winsiderss/systeminformer#1271]
### Description of the feature, modification, idea or suggestion

Use: Still have Help > Log work but don't grow the file beyond set limits.

I see there is a setting in System > Options > Advanced > LogEntries = 200, but it appears to not be respected.

**Comment by dmex** [comment]
Why did you create a new issue? https://github.com/winsiderss/systeminformer/issues/1269

**Comment by AltF5** [comment]
oops!
