### ISSUE TITLE
The kernel driver not found 

### ISSUE THREAD

**Issue by Avtroman** [winsiderss/systeminformer#1274]
https://drive.google.com/file/d/1Ld7ecq87DTCA4L0g-Nppb6Va1uWzv30-/view?usp=drivesdk

**Comment by dmex** [comment]
What is this?

**Comment by Avtroman** [comment]
> What is this?

After start, writed driver not found, after message "normal dump, mini dump, restart, exit". If press restart, this error again

**Comment by AltF5** [comment]
> > What is this?
> 
> After start, writed driver not found, after message "normal dump, mini dump, restart, exit". If press restart, this error again

It's challenging to understand what you are saying. Please provide screenshots to be able to better assist

**Comment by fade2gray** [comment]
@Avtroman the Google Drive link you provided appears to be private, and no-one except yourself can view it.

You can simply drag-and-and drop an image directly into the comment.


![dnd](https://user-images.githubusercontent.com/1332009/174190072-438bf932-3f2a-4e38-8bc0-f76a961cb57a.PNG)

**Comment by Avtroman** [comment]
> @Avtroman the Google Drive link you provided appears to be private, and no-one except yourself can view it.
> 
> You can simply drag-and-and drop an image directly into the comment.
> 
> ![dnd](https://user-images.githubusercontent.com/1332009/174190072-438bf932-3f2a-4e38-8bc0-f76a961cb57a.PNG)

![Снимок экрана (4)](https://user-images.githubusercontent.com/42459158/174237619-462d67a3-27c7-4337-b681-752ce0aa0b09.png)
![Снимок экрана (5)](https://user-images.githubusercontent.com/42459158/174237640-7afbf4e6-cda6-4968-8478-63b4aceebf67.png)
![Снимок экрана (6)](https://user-images.githubusercontent.com/42459158/174237655-a0b3431d-b128-4e77-9a16-6fa0f9b7b38c.png)

**Comment by dmex** [comment]
You probably have old plugin dlls or something that need to be deleted?


There hasn't been a release yet and there are no debug symbols. So until there's an actual release, you compiled that code so you need to debug where/how that's crashing.

**Comment by Avtroman** [comment]
> You probably have old plugin dlls or something that need to be deleted?
> 
> There hasn't been a release yet and there are no debug symbols. So until there's an actual release, you compiled that code so you need to debug where/how that's crashing.

When dekete plugins directory, only first time error message "driver not found". But after run ok. Where is processhacker2.exe?
How to install normal system Informer with new driver?

**Comment by AltF5** [comment]
The new driver is not ready yet for System Informer.

You can turn off warnings about it in Options, of go in and comment out the code lines where you get error messages.
Uncheck: 'Enable Kernel Mode driver'
Uncheck: 'Enable Warnings'

If you are unsure where the .exe is then download just the portable files via Binaries -- https://processhacker.sourceforge.io/nightly.php

The settings are in Win + R --> %APPDATA%\Process Hacker   if you are asking about that.

It's challenging to understand the language barrier here, but hopefully that helps.

**Comment by dmex** [comment]
> Where is processhacker2.exe?

Deprecated.

> How to install normal system Informer with new driver?

There is no compatible driver.
