### ISSUE TITLE
Bug: [Report 2] Standard Context Menu lag when launched as admin (Menu bar or Tray icon)

### ISSUE THREAD

**Issue by AltF5** [winsiderss/systeminformer#1281]
### Brief description of your issue

https://github.com/winsiderss/systeminformer/issues/1278 -- Re-open -- Was closed without a chance to respond 😢

Video demo of bug:
**https://www.youtube.com/watch?v=NkShxsJwrQA**

@dmex You mentioned (https://github.com/winsiderss/systeminformer/issues/1278) this is because of Security Software and bcd.dll and registry BCD keys ... I'm afraid I have no idea what this has to do with it. Can you clarify?
- What does BCD and bcd.cpp in the code have to do with the standard context menu generation (unless it is involved and I'm not familiar) ?
- Windows Defender is entirely disabled from the driver & kernel perspective on one of the PCs.
- This can be repro-ed on multiple PCs, VMs, etc when running as an admin regardless of "security software

### Steps to reproduce

I'll attach this Debug64 build (unzip, rename .txt to .exe, verify im not trying to pwn you ... which I wouldn't based on how long i've been around here).
[SystemInformer.zip](https://github.com/winsiderss/systeminformer/files/8929020/SystemInformer.zip)

> Run elevated
> Click on the '**System**' menubar item (not View | Tools | Users | or Help which are Unaffected)
> Also impacted: Tray icon right clicking.

Does the lag occur to you with this build, or is it truly all my Win10 Machines & VMs when launched elevated ? (I don't have a Win11 VM at the moment to confirm). I don't quite understand how this would not be reproducible for you. This is occuring with the code downloaded as-is compiled in Debug | x64 as-is, with no settings, with no modifications, and attempted both in VS2022 and VS2022 Preview (both which compile fine, but experience this Menu bug).
**Can you try backing up and deleting your settings in %AppData%\Process Hacker just to be sure you don't have some setting that is preventing this?**

Can others confirm whether or not they are experiencing this when running their builds elevated and trying to left-click 'System' or right click the tray icons? ( @jxy-s   @diversenok    @ionescu007 )

### Actual behavior
https://www.youtube.com/watch?v=NkShxsJwrQA

### Expected behavior
Function as intended. Not like that ^

### Environment

Win10 21H2.
Latest Windows SDK from VS2022 (did not ask for an upgrade, so nothing was changed)

**Comment by jxy-s** [comment]
@AltF5 - **_do not_** open a new issue just because a previous one was was closed. We consider that spamming. Consider this a warning.

What is stopping you from continuing your discussion on a closed issue? We can always re-open the previously closed one.

**Comment by AltF5** [comment]
> @AltF5 - **_do not_** open a new issue just because a previous one was was closed. We consider that spamming. Consider this a warning.
> 
> What is stopping you from continuing your discussion on a closed issue? We can always re-open the previously closed one.

I didn't know Closed issues could be re-opened and Closed are still considered / viewed.
