### ISSUE TITLE
"Unable to query the current affinity" on newer nightly versions

### ISSUE THREAD

**Issue by therealFramexdd** [winsiderss/systeminformer#1299]
### Brief description of your issue

The latest nightly versions have a bug specific to Windows 7 SP1 which prevents me from setting any affinity
![bug](https://user-images.githubusercontent.com/108267012/175906614-54f582b6-1287-44c2-b9aa-3988dfb24417.jpg)

I wish i could download older version of nightly builds (because only the nightly version allows you to save affintieis), too bad appveyor doesn't allow you to download files older than a month

Iirc this bug didn't happen on nightly version older than 3-4 months

### Environment (optional)

```shell
Windows 7 SP1
```

**Comment by dmex** [comment]
> I wish i could download older version of nightly builds

https://github.com/ProcessHackerRepoTool/nightly-builds-mirror/releases

**Comment by Framexdd** [comment]
> > I wish i could download older version of nightly builds
> 
> https://github.com/ProcessHackerRepoTool/nightly-builds-mirror/releases

too bad appveyor doesn't allow you to download files older than a month

**Comment by dmex** [comment]
Fixed 👍

**Comment by Framexdd** [comment]
> Fixed 👍

Hey sorry for the late reply, was on vacation.

The issue is solved when i try to normally set an affinity but it's still there if i try to "Save affinity for process/command line"
