### ISSUE TITLE
Wrong process termination on filtered process list with toolbar

### ISSUE THREAD

**Issue by pascalcaron** [winsiderss/systeminformer#1300]
Hello,

When you filter the list of the processes, if you click the X icon on the toolbar for terminating the process, application terminates wrong process, mostly explorer.exe

If you try to terminate process by right click menu, it terminates the correct process

**Comment by dmex** [comment]
The X button is used for terminating the window under the mouse pointer. You click the X and drag the mouse cursor to the window to kill/close and release the mouse. It works exactly the same as the feature included with Microsoft's Process Explorer 👍
