### ISSUE TITLE
CLA for pull requests

### ISSUE THREAD

**Issue by dmex** [winsiderss/systeminformer#1303]
Contributor License Agreement (CLA) for pull requests are mandatory going forward.

If contributors don't agree to the CLA then the PR must be rejected.

**Comment by OrbbQ3** [comment]
How i can agree to the CLA? Is a comment from me in the PR sufficent or will be there a agreement on the mainpage of the github project as form, that we must sign?

**Comment by jxy-s** [comment]
We are implementing a CLA process for tracking contributors. I will provide more information when that is complete.

**Comment by OrbbQ3** [comment]
Ok, thanks for your quick response :)

**Comment by jxy-s** [comment]
Update here, we have a process defined. Waiting on some administrative things to get done before we implement it.

**Comment by jxy-s** [comment]
CLA workflow is implemented:
https://github.com/winsiderss/systeminformer/pull/1308
https://github.com/winsiderss/systeminformer/pull/1309
