### ISSUE TITLE
Compiling systeminformer

### ISSUE THREAD

**Issue by ProphetLamb** [winsiderss/systeminformer#1305]
# Synopsis
In this issue I describe my journey compiling systeminformer. Before anything else I must say, it only took me half an hour until I could start debugging a working PH2. This is over 10x quicker than your average C/XX project. Absolutely amazing.

# CustomBuildTool
Let's start with `CustomBuildTool`, Windows SDKs is installed on `J:\Windows Kits` for me, so
 https://github.com/winsiderss/systeminformer/blob/527f0d4b2170e2b1918929a70178c4bb5a14fac4/tools/CustomBuildTool/Utils.cs#L491-L497
has no chance to find it. Which would've been fine, if I was prompted to specify the path, but 
https://github.com/winsiderss/systeminformer/blob/527f0d4b2170e2b1918929a70178c4bb5a14fac4/tools/CustomBuildTool/Build.cs#L904-L913
simply receives the literal `""`. So my first proposal is to return `null` from `VisualStudio.GetWindowsSdkPath()` and `VisualStudio.GetWindowsSdkIncludePath()` and prompt the user with a `Console.ReadLine()` via the null coalescing operator:

```csharp
string windowsSdkPath = VisualStudio.GetWindowsSdkPath() ?? ReadLine.PrompValidPath("Windows SDK binary path `[root]/Windows Kits/10/bin/[version]/[cpu]`");
string windowsSdkIncludePath = VisualStudio.GetWindowsSdkIncludePath() ??  ?? ReadLine.PrompValidPath("Windows SDK include path `[root]/Windows Kits/10/include/[version]/um`");;
```
- `ReadLine.PromptValidPath`: Prints the message, reads user input, ensures that the path exists.

# `ntzwapi.h`
For the next issues my Windows SDK versions may be relevant.
| Windows SDK | 
| --------------- |
|  10.0.19041.0  |
|  10.0.18362.0  |

Once the Windows SDK build 19041 was included in `phlib`, I started the compilation with the expected amount of undefined error.
These could be fixed by IntelliSense, which added the following headers to [ntzwapi.h](https://github.com/winsiderss/systeminformer/blob/f87b479949931013007386d30877a8f08cdb0559/phnt/include/ntzwapi.h).

```c++
#include "processthreadsapi.h"
#include "phnt_ntdef.h"
#include "ntlpcapi.h"
#include "ntseapi.h"
#include "ntexapi.h"
#include "psapi.h"
#include "ntpsapi.h"
```
Since `ntzwapi.h` is autogenerated, it is sensible not to statically include headers, so where should the includes above be defined?

## Windows 11?

The next error relates to `QUEUE_USER_APC_FLAGS` which is required by 
https://github.com/winsiderss/systeminformer/blob/f87b479949931013007386d30877a8f08cdb0559/phnt/include/ntzwapi.h#L3352-L3360
but not defined for `PHNT_VERSION < PHNT_WIN11` ,

https://github.com/winsiderss/systeminformer/blob/527f0d4b2170e2b1918929a70178c4bb5a14fac4/phnt/include/ntpsapi.h#L1614-L1637

hence I modified 
https://github.com/winsiderss/systeminformer/blob/527f0d4b2170e2b1918929a70178c4bb5a14fac4/SystemInformer/sdk/phdk.h#L6
for Debug
and 
https://github.com/winsiderss/systeminformer/blob/527f0d4b2170e2b1918929a70178c4bb5a14fac4/phnt/include/phnt.h#L60
for Release to 
```c++
#define PHNT_VERSION PHNT_WIN11
```
since `PHNT_WIN10` which is my OS would not compile, and compiled. The error seems resolved, still one error to go.

# `winnt.h` control flow guard policy (xfg)

Namely, my Windows SDK versions' `winnt.h` defines [PROCESS_MITIGATION_CONTROL_FLOW_GUARD_POLICY ](https://docs.microsoft.com/en-us/windows/win32/api/winnt/ns-winnt-process_mitigation_control_flow_guard_policy) as
```c++
typedef struct _PROCESS_MITIGATION_CONTROL_FLOW_GUARD_POLICY {
    union {
        DWORD Flags;
        struct {
            DWORD EnableControlFlowGuard : 1;
            DWORD EnableExportSuppression : 1;
            DWORD StrictMode : 1;
            DWORD ReservedFlags : 29;
        } DUMMYSTRUCTNAME;
    } DUMMYUNIONNAME;
} PROCESS_MITIGATION_CONTROL_FLOW_GUARD_POLICY, *PPROCESS_MITIGATION_CONTROL_FLOW_GUARD_POLICY;
```
, comparing against Microsoft docs, one can see, that 

- `EnableXfg`, and 
- `EnableXfgAuditMode` 

are missing. As a solution I `#if false`d in `procmtgn.h` and compiled.
https://github.com/winsiderss/systeminformer/blob/527f0d4b2170e2b1918929a70178c4bb5a14fac4/SystemInformer/procmtgn.c#L321-L332
Likely, this is a product of compiling for Win11 with a Win10 SDK (which I am forced to do, because of my solutions to the previous issues).

Success, and systeminformer even works, Eureka!

**Comment by ProphetLamb** [comment]
I would like to ask for verification whether the missing includes and the bogus version (the later two issues) are related to my system or reproducible on other systems?

**Comment by ProphetLamb** [comment]
Quite often I have the same issue, where the project compiles and works with my system. But a junior dev/fresh installation cannot successfully launch the app on their first few tries. So I documented what exactly I had to do, to compile systeminformer. I hope this helps, cheers!

**Comment by dmex** [comment]
> Windows SDKs is installed on J:\Windows Kits

How did you install the SDK into a custom location?

> Windows SDK build 1904

The minimum supported SDK is version 20348.

> Since ntzwapi.h is autogenerated, it is sensible not to statically include headers, so where should the includes above be defined?

ntzwapi is for kernel drivers and it shouldn't have includes.

> related to my system or reproducible on other systems?

The issues you've mentioned above are caused by the custom SDK location and outdated SDK version. The newer SDKs also don't allow changing the installation directory?

**Comment by CrendKing** [comment]
> How did you install the SDK into a custom location?

The installer from https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/ prompts install path:

![Clipboard 1](https://user-images.githubusercontent.com/975235/178261104-d68d1d74-b907-40e6-a8b9-b5ec959c42f8.jpg)

**Comment by dmex** [comment]
Fixed 👍
