### ISSUE TITLE
Undefined symbol PhDoesFileExistsWin32 and PhDoesFileExists

### ISSUE THREAD

**Issue by Avtroman** [winsiderss/systeminformer#1321]
### Brief description of your issue

2>memlist.c
2>cl : командная строка  warning D9025: переопределение "/sdl" на "/GS-"
2>memlists.c
1>phlib.lib(guisup.obj) : error LNK2001: неразрешенный внешний символ PhDoesFileExistsWin32.
1>phlib.lib(guisup.obj) : error LNK2001: неразрешенный внешний символ PhDoesFileExists.
1>D:\systeminformer-master\bin\Release64\peview.exe : fatal error LNK1120: неразрешенных внешних элементов: 2
2>memrslt.c
2>memsrch.c
![Снимок экрана (6)](https://user-images.githubusercontent.com/42459158/181236668-87911f0a-820b-411d-9e93-23a4bcac5152.png)

**Comment by ge0rdi** [comment]
@dmex 
I'm getting the same on latest master.
Maybe you forgot to push the fix?
