### ISSUE TITLE
What does the boost option do in context menu of process name? How to have all selected processes always boosted?

### ISSUE THREAD

**Issue by StacktraceException** [winsiderss/systeminformer#1327]
Hi, I could not find any documentation. I tried to ask in the Process Hacker forum, but for some reason it says that it does not allow registrations anymore.

All google search results were irrelevant. Can anyone tell me what this boost option is? It is located above process priority etc  in context menu.

Kind regards.

**Comment by jxy-s** [comment]
This is essentially setting or disabling the following:

https://docs.microsoft.com/en-us/windows/win32/procthread/priority-boosts
https://docs.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-setprocesspriorityboost

> Disables or enables the ability of the system to temporarily boost the priority of the threads of the specified process.

>When a thread is running in one of the dynamic priority classes, the system temporarily boosts the thread's priority when it is taken out of a wait state. If SetProcessPriorityBoost is called with the DisablePriorityBoost parameter set to TRUE, its threads' priorities are not boosted. This setting affects all existing threads and any threads subsequently created by the process. To restore normal behavior, call SetProcessPriorityBoost with DisablePriorityBoost set to FALSE.

This is the relevant code: https://github.com/winsiderss/systeminformer/blob/574ed7214f653fda5f17312c48f316af070c64ac/phlib/include/phnativeinl.h#L441-L458

**Comment by dmex** [comment]
> Can anyone tell me what this boost option is?

You use the option with the `Base priority` processes column to know when priority boosting is supported by the process: 
> The system does not boost the priority of threads with a base priority level between 16 and 31. Only threads with a base priority between 0 and 15
