### ISSUE TITLE
plugins build error

### ISSUE THREAD

**Issue by myshzzx** [winsiderss/systeminformer#1330]
### Brief description of your issue

[00:00] Building SystemInformer (x32)...
[04:53] Building SystemInformer (x64)...
[09:26] Building Plugins (x32)...
[ERROR] (1) C:\projects\systeminformer\plugins\ExtendedTools\gpudetails.c(162,40): error C2065: 'KMT_DRIVERVERSION_WDDM_3_1': undeclared identifier [C:\projects\systeminformer\plugins\ExtendedTools\ExtendedTools.vcxproj]C:\projects\systeminformer\plugins\ExtendedTools\gpudetails.c(162,1): error C2051: case expression not constant [C:\projects\systeminformer\plugins\ExtendedTools\ExtendedTools.vcxproj]

**Comment by MagicAndre1981** [comment]
make sure you use [WIn11 22H2 SDK/WDK Build 22621](https://docs.microsoft.com/en-us/windows-hardware/drivers/download-the-wdk#download-and-install-the-windows-11-version-22h2-wdk), here the d3dkmthk.h includes the definition:

![image](https://user-images.githubusercontent.com/8274816/183910976-da59f17d-93e8-489f-ae9a-4bbba8899f5d.png)
