### ISSUE TITLE
updating Process Hacker should mention name change to System Informer

### ISSUE THREAD

**Issue by as-muncher** [winsiderss/systeminformer#1344]
### Description of the feature, modification, idea or suggestion

Could you please update process hacker so that it will look to the systeminformer repository and update, with a notification that the name will be changed etc. etc.  If I open up Process Hacker 3.0.4953 and "check for updates", it's finding none.

**Comment by jxy-s** [comment]
That's because we haven't released a build yet. There is already code in place to notify people who update the name has been changed once a new build is made available.
