### ISSUE TITLE
Unable to load the kernel driver service

### ISSUE THREAD

**Issue by 0x4E69676874466F78** [winsiderss/systeminformer#1345]
### Brief description of your issue

![изображение](https://user-images.githubusercontent.com/4449851/185600615-f3c21b13-f08f-463f-9f05-494e5c16be10.png)
(Object with specified name not found)
![изображение](https://user-images.githubusercontent.com/4449851/185601084-d9914588-e8ea-462f-b70d-02e54898c7e1.png)
![изображение](https://user-images.githubusercontent.com/4449851/185601267-953e784c-f764-47e3-b108-3e2f961dadb7.png)
(kernel driver not work, start adress incorrected)

### Steps to reproduce (optional)

Enable kernel-mode driver and restart.

### Environment (optional)

```shell
Latest master version.
Windows 10 21H1.
Сompiled by 2019 visual studio and latest SDK (everything works fine except the driver).
```

**Comment by jxy-s** [comment]
The legacy driver will not function with the current builds. We are currently migrating the project: https://github.com/winsiderss/systeminformer/issues/1286

In the meantime, if you want to build the driver yourself, please see documentation here: https://github.com/winsiderss/systeminformer/tree/master/KSystemInformer
