### ISSUE TITLE
CPU sets

### ISSUE THREAD

**Issue by Aspector1** [winsiderss/systeminformer#1346]
### Description of the feature, modification, idea or suggestion

Hello! Can you add CPU Sets in addition to CPU Affinity?

UPD: https://docs.microsoft.com/en-us/windows/win32/procthread/cpu-sets

**Comment by dmex** [comment]
What benefit is there using cpu sets over affinity masks? The docs say they're ignored when the process/thread has a different affinity to the cpu set:

> If a thread or process has a restrictive affinity mask set, the affinity mask is respected above any conflicting CPU Set assignment

**Comment by Aspector1** [comment]
> What benefit is there using cpu sets over affinity masks? The docs say they're ignored when the process/thread has a different affinity to the cpu set:
> 
> > If a thread or process has a restrictive affinity mask set, the affinity mask is respected above any conflicting CPU Set assignment

So

> CPU Sets are a ‘softer’ form of CPU Affinities. Instead of a hard contract, they are a suggestion of preferred CPU cores. The OS will try to abide by a CPU Set, but has discretion to schedule outside the Set. This may be necessary when the thread load exceeds the number of cores in the Set, or for power management reasons. CPU Sets are natively supported by Windows.
> 
> CPU Sets give the OS thread scheduler more flexibility than CPU Affinities do. If a process with a CPU Sets rule needs more CPU(s) to handle its thread load, the OS can schedule onto CPUs outside the assigned Sets. In contrast, a CPU Affinity can not be violated, so the process’s compute would be limited. Therefore, for performance tuning, CPU Sets are usually preferred. For hard limits on CPU consumption, traditional CPU Affinities should be used.
> 
> Some apps and games are sensitive to CPU Affinity changes. In these cases, CPU Sets are a viable alternative since they are less likely to cause complications.

**Comment by dmex** [comment]
@Aspector1 

Process Lasso has support for CPU sets:
https://bitsum.com/product-update/process-lasso-10-4-cpu-sets-and-adler-lake/

**Comment by AloisKraus** [comment]
Is this implemented now? It would be interesting to see. I miss also Thread Priority for the threads. Why is this not present. Process Explorer is this also no showing.
