### ISSUE TITLE
kphlib compile error when compile tzwapi.h by visual studio 2022 Debug x64

### ISSUE THREAD

**Issue by cgsgood** [winsiderss/systeminformer#1349]
### Brief description of your issue

1>E:\openSource\systeminformer\phnt\include\ntzwapi.h(3355,31): error C2146: syntax error: missing ')' before identifier 'ApcFlags' (compiling source file kphmsgdyn.c)

——————content of ntzwapi.h——————
NTSYSCALLAPI
NTSTATUS
NTAPI
ZwQueueApcThreadEx2(
    _In_ HANDLE ThreadHandle,
    _In_opt_ HANDLE ReserveHandle, // NtAllocateReserveObject
    _In_ QUEUE_USER_APC_FLAGS ApcFlags,   // line 3355
    _In_ PPS_APC_ROUTINE ApcRoutine,
    _In_opt_ PVOID ApcArgument1,
    _In_opt_ PVOID ApcArgument2,
    _In_opt_ PVOID ApcArgument3
    );

**Comment by dmex** [comment]
You need to install the latest SDK/WDK
