### ISSUE TITLE
.NET Assemblies crash

### ISSUE THREAD

**Issue by Tharn** [winsiderss/systeminformer#1351]
### Brief description of your issue

Going into powershell.exe (64-bit) properties and selecting .NET Assemblies results in a repeatable crash. The .dmp file is attached
[ProcessHacker_SRWGONTFXTRVNJN_DumpFile.zip](https://github.com/winsiderss/systeminformer/files/9436293/ProcessHacker_SRWGONTFXTRVNJN_DumpFile.zip)
.

### Environment (optional)

```shell
Process Hacker nightly 3.0.4923.
Windows 10 Pro x64.
```

**Comment by dmex** [comment]
> 3.0.4923

You need to update to the latest version (4953):
https://processhacker.sourceforge.io/nightly.php

**Comment by Tharn** [comment]
Yep, works now!
