### ISSUE TITLE
[BUG] Minor issue in that double-click on column header separator does not include width of new total CPU, IO total rate text

### ISSUE THREAD

**Issue by Clouds123** [winsiderss/systeminformer#1353]
PH x64 3.0.4953 beta
Win 10 x64 latest

The old version worked perfectly in calculating maximum column width when column header separator was clicked, to avoid any of it being clipped, with ... ellipses added.

Now that the new version 3 beta also includes the Total amounts (in bigger font size above column name ) for some column's (eg. CPU, IO total rate, etc.), the max column width calculation logic also needs to include the width of this "Total" text width - ie. to calculate maximum column width when separator clicked, it should pick the max value between these three values:
  - width of column name text in column header
  - width of "Total" value text in column header
  - iterate through all data values for column, identifying max text width.

I can post screenshot if my description isn't clear.

**Comment by Clouds123** [comment]
Also, can you make the display update dynamically, as the column width is increased/decreased. I think it used to do that with older v2.x versions.

**Comment by dmex** [comment]
> dynamic updating has come back, so it was likely a Windows issue

There is a performance issue of sorts here. PhTickProcessNodes excludes the headers from painting so the paint handler invalidates the header:

https://github.com/winsiderss/systeminformer/blob/e50ec06ff0a7211fd25cb2d437a38074ed1ce81c/phlib/treenew.c#L5511-L5512

> max column width calculation logic also needs to include the width of this "Total" text width

This has been fixed 👍
