### ISSUE TITLE
Stable version Process Hacker 3.0

### ISSUE THREAD

**Issue by Alex-S1** [winsiderss/systeminformer#1357]
Hello 👋🏼
When will the stable version of Process Hacker 3.0 be released?

**Comment by jxy-s** [comment]
When it's ready. We are close 🤞.

Please in the future take some time to investigate existing discussions or other open issues to answer your question before creating new ones:
https://github.com/winsiderss/systeminformer/discussions?discussions_q=release
https://github.com/winsiderss/systeminformer/issues/1286
