### ISSUE TITLE
Project Downloads and Project site are broken

### ISSUE THREAD

**Issue by paulkermann** [winsiderss/systeminformer#1367]
### Description of the feature, modification, idea or suggestion

Hey
I wanted to download the latest nightly build for this project, however since the transfer to this new git repository I could not find the latest version to download.

### Proposed implementation details (optional)

I think updating the links should suffice.
The latest build available in the old git repository is from June.

**Comment by dmex** [comment]
https://processhacker.sourceforge.io/nightly.php

**Comment by paulkermann** [comment]
The last build available in the linked page is from 3 months ago (not the "nightly" build).

**Comment by dmex** [comment]
@paulkermann 

Nightly builds are suspended until after the migration is completed.

**Comment by paulkermann** [comment]
@dmex thanks, didn't know that
