### ISSUE TITLE
Plugin documentation missing

### ISSUE THREAD

**Issue by Airick73** [winsiderss/systeminformer#1373]
Hello I am attempting to develop a plugin for Process Hacker so that it can integrated with a service, similar to how there is a plugin for VirusTotal, but I am unable to find documentation on how to develop a plugin. If someone could please provide the documentation or have suggestions on where to start I would greatly appreciate it! 

P.S. I was unable to post on the source forge forms as there is no sign up page. 

Kindest Regards,
Eric Kemmer

**Comment by dmex** [comment]
> I was unable to post on the  forms as there is no sign up page.

The forums are deprecated and are basically going into read-only.

There's some documentation here but it's probably outdated:
https://wj32.org/processhacker/forums/viewtopic.php?t=41

> have suggestions on where to start

The easiest method is just copying one of the existing plugins and renaming everything. For example:
https://github.com/winsiderss/systeminformer/tree/master/plugins
or
https://github.com/processhacker/plugins-extra
