### ISSUE TITLE
Keeping row position after quick-filtering

### ISSUE THREAD

**Issue by Coldblackice** [winsiderss/systeminformer#1376]
### Description of the feature, modification, idea or suggestion

I frequently use the CTRL-K for quick-filtering to hone in on particular processes/PIDs. However, sometimes it's not the process I'm interested in, but rather, wanting to locate it to find its child or sibling process, and/or its relative position in the tree. When clearing the quick-filter to show the tree, however, the main pane's row selector is also cleared.

Not a huge deal, as an alternative it necessitates keyboard letter-selecting to it (multiple hits necessary or having to bring up the full CTRL-F searh and lock-on to a process that way.

But if it'd be possible to add an option to "Keep row position upon quick-filter clear", it would be most useful and much appreciated!

**Comment by dmex** [comment]
Added to latest nightly. Enable by changing `RestoreSelectionAfterSearch` to 1
