### ISSUE TITLE
Build error C1083 metahost.h

### ISSUE THREAD

**Issue by cgreenland** [winsiderss/systeminformer#1378]
### Brief description of your issue

Hello. I'm trying to build System Informer from source on Windows 10. I've installed Visual Studio 2022 with the Desktop Development for C++ workload and the latest Windows SDK.

Upon running the build_release.cmd, I get the below error output. I've resolved other errors by searching the posts here and installing VS 2022 components like the SDK. Is there a complete list somewhere of VS components I should install before building? Sorry for my ignorance, not experienced in Windows development. Thanks in advance.

```
Windows: 10.0.19041.1826 (WinBuild.160101.0800)
WindowsSDK: 10.0.22621.0 (17.3.32720.241)
VisualStudio: VisualStudio/17.3.4+32901.215

Building... 1.0.0.0

[00:00] Building SystemInformer (x32)...
[ERROR] (1) C:\Users\<username>\Documents\GitHub\systeminformer\tools\peview\clrtableimportprp.c(13,1): fatal  error C1083: Cannot open include file: 'metahost.h': No such file or directory [C:\Users\<username>\Documents\GitHub\systeminformer\tools\peview\peview.vcxproj]C:\Users\<username>\Documents\GitHub\systeminformer\tools\peview\clrprp.c(14,1): fatal  error C1083: Cannot open include file: 'metahost.h': No such file or directory [C:\Users\<username>\Documents\GitHub\systeminformer\tools\peview\peview.vcxproj]
```

**Comment by dmex** [comment]
You need to install the .NET workload or just one of the .NET SDKs from the VS installer?

![image](https://user-images.githubusercontent.com/1306177/190744775-841cf2c1-cc2a-48a5-afa2-6f6134879a9c.png)

**Comment by cgreenland** [comment]
Sorry to reopen, but I wanted to report back that installing the .NET workload solved that particular error. However, I now get another. Do I need something else?

>fatal  error C1083: Cannot open include file: 'd3dkmddi.h': No such file or directory (compiling source file disknotify.c) [C:\Users\<user>\Documents\GitHub\systeminformer\plugins\HardwareDevices\HardwareDevices.vcxproj]C:\Users\<user>\Documents\GitHub\systeminformer\plugins\HardwareDevices\devices.h(46,1):

**Comment by dmex** [comment]
@cgreenland

That's a separate issue on our end. Checkout the latest sources and it should be fixed 👍

**Comment by cgreenland** [comment]
Thank you @dmex, that worked! Perhaps the C++ and .NET workloads could be listed as requirements in the "Build the project" section of the README.md?

Also, what is the difference between the files created in /build/output and /bin?

**Comment by dmex** [comment]
> Perhaps the C++ and .NET workloads could be listed as requirements

The internet is littered with bug reports about C1083 and metahost.h so it's something Microsoft has broken.

> what is the difference between the files created in /build/output and /bin?

/bin contains the usual msvc debugging/compiler output and other junk while /bin/output contains the final release binaries (identical what you would download from the website).

**Comment by dmex** [comment]
> erhaps the C++ and .NET workloads could be listed as requirements

I've removed those dependencies in the latest commits 👍 

> what is the difference between the files created in /build/output and /bin?

/bin contains the usual msvc debugging/compiler output and other junk while /bin/output contains the final release binaries (identical what you would download from the website).
