### ISSUE TITLE
Exiting Process Hacker spins up all disks

### ISSUE THREAD

**Issue by galmok** [winsiderss/systeminformer#1380]
### Brief description of your issue

When I exit Process Hacker, all my disks are spun up. 

### Steps to reproduce (optional)

1. Start Process Hacker.
2. Have disks that are spun down.
3. Exit Process Hacker
4. Disks are spun up.

### Expected behavior (optional)

Disks should remain spun down.

### Actual behavior (optional)

Disks get spun up.

### Environment (optional)

```shell
Latest version of Process Hacker on Windows 10 64 bit.
```

**Comment by dmex** [comment]
Save the jokes for April 1st.

**Comment by galmok** [comment]
What joke? Process Hacker does spin  up disks when being excited. Is that really intended behavior?

**Comment by dmex** [comment]
> What joke?

Application termination is handled by the operating system. Your hardware spinning up is also handled by the operating system. 

You click X or select Exit and we call ExitProcess - everything past this point is the operating system.

> When I exit Process Hacker, all my disks are spun up.

Are you saving your settings files to those disks or are you running programs from those disks? 

If you're running Programs/Steam/Epic/Games that record process activity. For example:

![image](https://user-images.githubusercontent.com/1306177/191097467-081bff8a-8c8a-4683-a5a8-c3b05f641628.png)

Exiting a program will trigger those process events for programs starting/exiting (e.g. spinning up disk -> reading their executable into memory from disk-> invoke their event callbacks so they can log the process termination).

> Is that really intended behavior?

We have no control over your hard disks spinning up - especially during termination. I could understand if it was when you were starting the application but this program doesn't do anything during termination.

**Comment by Masamune3210** [comment]
Windows loves to do this on my box no matter what program I close sometimes, so I think its just Windows being Windows and nothing with the specific program really
