### ISSUE TITLE
'Unable to load the kernel driver service' on Windows 11 22h2

### ISSUE THREAD

**Issue by rampageX** [winsiderss/systeminformer#1383]
### Brief description of your issue

`The certificate has been directly revoked by the issuer`
![PH_WIN11](https://user-images.githubusercontent.com/994081/191659894-12064265-95c6-421f-bb52-7a21ec1e5155.png)

### Environment (optional)

```shell
Microsoft Windows [Version 10.0.22621.382]
```

**Comment by hwti** [comment]
See https://github.com/winsiderss/systeminformer/issues/1142#issuecomment-1148635917
