### ISSUE TITLE
Got access violation when using -ras command line option

### ISSUE THREAD

**Issue by wqreytuk** [winsiderss/systeminformer#1385]
### Brief description of your issue

I downloaded the latest code from https://github.com/winsiderss/systeminformer, and then using VS2022 attach the service process and debug, here is what I got
![image](https://user-images.githubusercontent.com/48377190/191911625-7072789c-e128-466c-935e-deff317d7de9.png)

the error is happend in https://github.com/winsiderss/systeminformer/blob/master/SystemInformer/runas.c#L1973

according to the Microsoft doc: https://learn.microsoft.com/en-us/windows/win32/api/winsvc/nf-winsvc-startservicectrldispatchera

the parameter of StartServiceCtrlDispatcherA should be an array and terminated with NULL values

here is a piece of code from https://learn.microsoft.com/en-us/windows/win32/services/writing-a-service-program-s-main-function:
```
SERVICE_TABLE_ENTRY DispatchTable[] = 
{ 
	{ SVCNAME, (LPSERVICE_MAIN_FUNCTION) SvcMain }, 
	{ NULL, NULL } 
}; 

// This call returns when the service has stopped. 
// The process should simply terminate when the call returns.

if (!StartServiceCtrlDispatcher( DispatchTable )) 
{ 
	SvcReportEvent(TEXT("StartServiceCtrlDispatcher")); 
} 
```
and I modified runas.c like this:
```
SERVICE_TABLE_ENTRY DispatchTable[] =
{
	{ ServiceName->Buffer, (LPSERVICE_MAIN_FUNCTION)RunAsServiceMain },
	{ NULL, NULL }
};
StartServiceCtrlDispatcher(DispatchTable);
```

the issus was solved, and the service for systeminformer.exe running successfully

**Comment by dmex** [comment]
Good catch, fixed 👍
