### ISSUE TITLE
Service notification doesn't work

### ISSUE THREAD

**Issue by bash-c** [winsiderss/systeminformer#1393]
### Brief description of your issue

Hi, 

I'm using `Process Hacker (Version: 3.0.4953 (37e0466))`, though I have toggled `View->Tray icons->Notifications->New/Started/Stopped/Deleted/Modified Services`, 
![image](https://user-images.githubusercontent.com/24247697/192685810-0287f2a3-dc72-416b-b3ae-1a37cc8835b1.png)
I didn't get the expected popup like below when services got changed.
![](https://899029.smushcdn.com/2131410/wp-content/uploads/labs/2021/05/process-hacker.jpg?lossy=0&strip=1&webp=0)

My options for `Notifications -Services` is like:
![image](https://user-images.githubusercontent.com/24247697/192686367-a420a34b-c82c-4d79-95dc-790d4e7b04e6.png)

I don't know if this is only me or generic. It really confuses me a lot.

If you need any further information or know how to resolve it, please tell me.

**Comment by dmex** [comment]
Is the CPU usage icon visible in the system tray?

![image](https://user-images.githubusercontent.com/1306177/192783434-a9cbab8a-cb8f-46ff-a362-610ccb30e003.png)

**Comment by bash-c** [comment]
> Is the CPU usage icon visible in the system tray?
> 
> ![image](https://user-images.githubusercontent.com/1306177/192783434-a9cbab8a-cb8f-46ff-a362-610ccb30e003.png)

hi @dmex, it's not visible, though I have enabled it in `View->Tray Icons->CPU Usage`
![image](https://user-images.githubusercontent.com/24247697/193178004-47acbc58-606a-488c-9998-3923e471b5f4.png)
![image](https://user-images.githubusercontent.com/24247697/193178028-da0a0b7f-0857-48bf-ade0-e76342f98e96.png)

**Comment by dmex** [comment]
You need to delete the 'IconGuids' setting.

I'm going to disable the tray icon persistence guids in the next version so this isn't an issue going forward but you'll need to delete the setting manually.

**Comment by bash-c** [comment]
Hi @dmex ,

It's true that if I deleted the 'IconGuids' setting in `settings.xml`, the expected popup would show up. But when I exit Process Hacker(System Informer), the 'IconGuids' setting is written back to `settings.xml` again. Is it possible to keep the setting unchanged?
