### ISSUE TITLE
FPS monitoring lags the system

### ISSUE THREAD

**Issue by ThebestkillerTBK** [winsiderss/systeminformer#1404]
### Brief description of your issue

If you turn on fps monitoring the system starts to lag

Only happens when I updated my system to Win11, Win10 works fine for me

### Steps to reproduce (optional)

Turn on ExtendedTools->FPS monitoring(By default)

### Expected behavior (optional)

System shouldnt be laggy

### Actual behavior (optional)

You feel your system lags down

### Environment (optional)

```shell
ProcessHacker 3.0.4953
Microsoft Windows [Version 10.0.22623.730]
```

**Comment by dmex** [comment]
Do you have the same issue with PresentMon?
https://github.com/GameTechDev/PresentMon/releases/tag/v1.8.0

**Comment by ThebestkillerTBK** [comment]
It lags the whole system not the program

**Comment by dmex** [comment]
@ThebestkillerTBK 

We're using PresentMon for capturing FPS information so if the same issue happens with their official release then it's an upstream issue with their library.
