### ISSUE TITLE
My download of process hacker 2 is missing search bar

### ISSUE THREAD

**Issue by ZeusSwerveBoi** [winsiderss/systeminformer#1406]
![PH2 ISSUE](https://user-images.githubusercontent.com/115348555/194702852-2e5b79a2-16df-4633-af2f-b51544df1a65.JPG)
My download of PH2 is missing the search bar
and here is what it should look like 
![Screenshot 2022-10-08 032438](https://user-images.githubusercontent.com/115348555/194702919-4eab1463-9ae8-4bd7-b4d5-6d43ac849478.png)

**Comment by ThebestkillerTBK** [comment]
view > toolbar > search box

**Comment by ZeusSwerveBoi** [comment]
> 

i dont see toolbar

**Comment by Biswa96** [comment]
Please try the nightly version from here https://processhacker.sourceforge.io/nightly.php

**Comment by ZeusSwerveBoi** [comment]
> Please try the nightly version from here https://processhacker.sourceforge.io/nightly.php

this works better i can finally see the search bar thank you

**Comment by tech-too-far** [comment]
Fix for that:
in `AppData\Roaming\Process Hacker\settings.xml`
find two setting strings and replace values:
```
<setting name="ProcessHacker.ToolStatus.Config">1f</setting>
<setting name="ProcessHacker.ToolStatus.SearchBoxDisplayMode">0</setting>
```
