### ISSUE TITLE
process hacker missing inject option

### ISSUE THREAD

**Issue by ZeusSwerveBoi** [winsiderss/systeminformer#1420]
### Brief description of your issue

so i got the nightly version of process hacker since the original one didnt show the search bar but now i dont see a option to inject dll on programs like black ops 3. this was the main use i got it for the 1st time.

### Steps to reproduce (optional)

click miscellaneous on any porgram then inject dll or inject should pop up but it's not

**Comment by jxy-s** [comment]
Open the process window > Modules > Options > Load module...

**Comment by dmex** [comment]
> programs like black ops 3

The 'inject' option is deliberately designed to trigger loader notifications in the target process. So don't be surprised if you're banned by anticheats.

**Comment by ZeusSwerveBoi** [comment]
> > programs like black ops 3
> 
> The 'inject' option is deliberately designed to trigger loader notifications in the target process. So don't be surprised if you're banned by anticheats.

my bad for the late reply but i only been using it on bo3 so far as other games i have not tried anything. bo3 seems safe to me

**Comment by ZeusSwerveBoi** [comment]
> Open the process window > Modules > Options > Load module...

i don't see  modules, sorry for my late reply i been busy

**Comment by jxy-s** [comment]
![image](https://user-images.githubusercontent.com/11687482/195998695-9ce89af8-cd0a-4304-8b86-801d06e5e95b.png)

**Comment by ZeusSwerveBoi** [comment]
![process hacker](https://user-images.githubusercontent.com/115348555/197744216-d212f71d-94f3-4f03-a0a6-3a45a83e2c11.png)
dont see it

**Comment by Vasilich** [comment]
1. in the other thread https://github.com/winsiderss/systeminformer/issues/1425 you were asked to remain within one thread, and not crosspost same issue in several threads.
2. Here you got exact instructions on how to load modules - in two ways, textual and with screenshots explaining how to load module. You have ignored textual answer and posted your screenshot that has nothing to do with load menu explained earlier. 

You should read answers given to you carefully and thoroughly.

**Comment by ZeusSwerveBoi** [comment]
in the other post i put "Because the old one shows as closed" when you asked me why im not going in the old one. so i HAD to make a new one. and in this thread i replied with the picture saying"dont see it" and it shows a screenshot of mine next to the one with the arrows on it. there is no modules tab.

**Comment by ZeusSwerveBoi** [comment]
> 1. in the other thread [cant find modules #1425](https://github.com/winsiderss/systeminformer/issues/1425) you were asked to remain within one thread, and not crosspost same issue in several threads.
> 2. Here you got exact instructions on how to load modules - in two ways, textual and with screenshots explaining how to load module. You have ignored textual answer and posted your screenshot that has nothing to do with load menu explained earlier.
> 
> You should read answers given to you carefully and thoroughly.

in the other post i put "Because the old one shows as closed" when you asked me why im not going in the old one. so i HAD to make a new one. and in this thread i replied with the picture saying"dont see it" and it shows a screenshot of mine next to the one with the arrows on it. there is no modules tab.

**Comment by Vasilich** [comment]
You have posted screenshot of your process menu, and not of menu explained above. See that https://github.com/winsiderss/systeminformer/issues/1420#issuecomment-1278483575 and https://github.com/winsiderss/systeminformer/issues/1420#issuecomment-1279783061 both point to **process** window, not to systeminformer's **main** window. That is why I asked to read answers thoroughly.

**Comment by ZeusSwerveBoi** [comment]
> 

i did open process menu and modules is not there

**Comment by Vasilich** [comment]
because you were not asked to open process menu, but process window. See the difference between "menu" and "window"? These words share only one letter....

**Comment by Biswa96** [comment]
Double click on the process, you'll see the window like jxy-s shown.

**Comment by ZeusSwerveBoi** [comment]
> because you were not asked to open process menu, but process window. See the difference between "menu" and "window"? These words share only one letter....



> because you were not asked to open process menu, but process window. See the difference between "menu" and "window"? These words share only one letter....

i wasnt told how to do this until now

**Comment by bvodntmiss** [comment]
what module do i use
