### ISSUE TITLE
Unable to load kernel driver service

### ISSUE THREAD

**Issue by pasha-zzz** [winsiderss/systeminformer#1421]
### Brief description of your issue

When kernel driver enabled - error on start:
"Unable to load kernel driver service
The request is not supported."

And driver not loads.

### Steps to reproduce (optional)

Enable kernel mode driver and restart

### Environment (optional)

```shell
System Informer 3.0.5346
Windows 10 22H2 10.0.19045.2006 x64
```

**Comment by jxy-s** [comment]
The build you installed (3.0.5346) is not supported yet. We're still migrating. Windows 10 22H2 10.0.19045.2006 x64 offsets are not updated yet, that's why you're getting "not supported".
