### ISSUE TITLE
cant find modules

### ISSUE THREAD

**Issue by ZeusSwerveBoi** [winsiderss/systeminformer#1425]
### Brief description of your issue

so in my other post it got closed but jxy-s said "Open the process window > Modules > Options > Load module..."
but i replied i don't see modules, sorry for my late reply i been busy

### Steps to reproduce (optional)

went to a process window and did not find modules

**Comment by jxy-s** [comment]
Why open a new issue and reply to the old one? Please engage with us in the other thread. Thanks.

**Comment by ZeusSwerveBoi** [comment]
Because the old one shows as closed

**Comment by ZeusSwerveBoi** [comment]
hello?

**Comment by jxy-s** [comment]
Duplicate: https://github.com/winsiderss/systeminformer/issues/1420
