### ISSUE TITLE
Warning after update Operating System.

### ISSUE THREAD

**Issue by rqueizan** [winsiderss/systeminformer#1452]
### Brief description of your issue

After upgrading Windows 11 Enterprise 21H2  to Build 22000.1165, when starting the Process Hacker the Operating System gives me this warning:
![PH vs Windows update](https://user-images.githubusercontent.com/18214796/198099035-93a4707e-f583-42b8-a97f-26ebc16a3ee8.png)

[A driver can't load on this device](https://support.microsoft.com/en-us/windows/a-driver-can-t-load-on-this-device-8eea34e5-ff4b-16ec-870d-61a4a43b3dd5)

### Steps to reproduce (optional)

Update Windows 11 with "2022-10 Cumulative Update for Windows 11 for x64-based Systems (KB5018483)" and restart.

### Expected behavior (optional)

The program ran as usual without any problem.

### Actual behavior (optional)

The program runs, but the operating system issues a warning.
It is not clear to me if Process Hacker is running correctly or with some limitation.

### Environment (optional)

```shell
Process Hacker 3.0.4953 (37e0466)
Windows 11 Enterprise 21H2 Build 22000.1165
```

**Comment by Bec-de-Xorbin** [comment]
They most likely backported some stuff from 22H2. See https://github.com/winsiderss/systeminformer/issues/1411

**Comment by rqueizan** [comment]
A driver can't load on this device
Security Windows 10
You are receiving this message because the Memory integrity setting in Windows Security is preventing a driver from loading on your device. Here are a few options you can try if you want to be able to use this driver:

See if an updated and compatible driver is available through Windows Update or from the driver manufacturer.

If that doesn’t work, try turning off the Memory integrity setting in Windows Security.

Warning: If you choose to continue using your device without addressing the driver problem, you might discover that the functionality the driver supports does not work any longer, which could have consequences ranging from negligible to severe.

To turn off the memory integrity setting
Go to the Core isolation page in Windows Security.

Turn the Memory integrity setting Off if it isn’t already. You'll need to restart your computer for the changes to take effect.

Notes: 

You can also open the Core isolation page by selecting Start  > Settings  > Update & Security  > Windows Security  > Device Security and then under Core isolation, selecting Core isolation details.

Though the driver has a minor vulnerability that’s preventing it from loading, it’s most likely not malicious in any way.

The driver name and company name that appear in the notification are the only reliable pieces of information that we have been able to gather about the driver.

If an updated driver is unavailable from the driver manufacturer, it might be a good idea to contact them and inquire whether a fix is coming soon.

**Comment by Masamune3210** [comment]
What is the point of posting the text of the error, you were already told how to remedy the issue lol

**Comment by jxy-s** [comment]
@rqueizan the issue you're experiencing has been answered in other closed issued (mentioned by @Bec-de-Xorbin above).
