### ISSUE TITLE
Time Started and Time Elapsed Columns

### ISSUE THREAD

**Issue by dragokas** [winsiderss/systeminformer#1455]
### Description of the feature, modification, idea or suggestion

Please, add "Time Started" and "Time Elapsed" as columns.

### Proposed implementation details (optional)

Very useful for debugging processes which are about to shutdown due to timeout.

**Comment by dmex** [comment]
There's 3 existing columns 👍 

* Timeline
The timeline column shows a graph relative to the system boot time useful for determining newer vs older (services, network, modules and other objects and tabs also have timeline columns).

* Start time
The start time column shows the "Time Started".

* Relative start time
The relative start time column shows the "Time Elapsed".

![image](https://user-images.githubusercontent.com/1306177/199377171-df5e31ec-d1c9-4b52-b58d-9dd77555b105.png)
