### ISSUE TITLE
Lacking cpu time

### ISSUE THREAD

**Issue by g-k-m** [winsiderss/systeminformer#1460]
I love process hacker but one thing that it doesn't have that i commonly use in task manager is "cpu time"

![image](https://user-images.githubusercontent.com/37273303/199285487-0a783b90-76a8-4b62-af0d-0df8cdd8a17a.png)

as u can see here this lets me know exactly how much cpu time each process has eaten (i just started my pc that's why they're so low)

process hacker has "cpu history" which is a % based usage rather than time and just isn't the same thing, plus the history is like what last 60 sec, 120 sec? it also has something called "cycles"

![image](https://user-images.githubusercontent.com/37273303/199285799-253075a7-f590-4637-ace9-a1b95e34fc07.png)

which shows the exact same processes as you can see but in a very different way, the ratios don't match and it doesn't show them in real time units like seconds or minutes but just in some big unitless numbers that make no sense to me, and like i took pics of both cpu time and cycles in task manager and process hacker, so the top process was 464 mil and the 2nd one was 380 mil, 464/380 = 1.221 that's the ratio, but in task manager they showed respectively 2:09 and 1:48 cpu cycles, that's in minutes so if we convert it in seconds 129/108 = 1.194 as you can see the ratios are not the same and in other calculations i've seen a difference as big as 0.1

when i see task manager showing cpu time of 2 minutes and 10 seconds, it tells me this process ate that much cpu time, but when i see process hacker showing me 480 mil, it tells me nothing
edit: 480 billion not million, same thing

**Comment by dmex** [comment]
> one thing that it doesn't have that i commonly use in task manager is "cpu time"

Have you tried adding the `Total CPU Time` column?

![image](https://user-images.githubusercontent.com/1306177/199301651-6eaaac3b-28fa-401c-be43-fea79508d80b.png)

There's also `Kernel CPU time` and `User CPU time` 😉
