### ISSUE TITLE
Unable to find Visual Studio.

### ISSUE THREAD

**Issue by henrypp** [winsiderss/systeminformer#1467]
### Brief description of your issue

Unable to find Visual Studio.

### Expected behavior (optional)

Run build\build_release.cmd

**Comment by dmex** [comment]
> Unable to find Visual Studio.

It's right here. Glad I could help :)
https://visualstudio.microsoft.com/

We're going to need more information. 

Are you using a preview version? 
What script/file/solution where you running?
Did you start an update/component installation then pause the installation (this breaks vswhere and the API detection)?

**Comment by henrypp** [comment]
I am runnning 17.3.6 with Windows 22621 sdk

**Comment by dmex** [comment]
Fixed in latest revisions 👍

**Comment by henrypp** [comment]
Looks like

**Comment by henrypp** [comment]
There is a new error:
```
Unable to find the resource compiler.
[WARN] Visual Studio Professional 2022 does not have required the packages:
Windows SDK
```

i have installed windows sdk 22621.755

**Comment by henrypp** [comment]
> There is a new error:

But build is successfull. Only these warnings.

**Comment by henrypp** [comment]
Now it have warning "Unable to find the resource compiler". But build is OK.

**Comment by skipik** [comment]
I have this error:

> Имя сбойного приложения: CustomBuildTool.exe, версия: 1.0.0.0, метка времени: 0x64cca5a3
> Имя сбойного модуля: Microsoft.VisualStudio.Setup.Configuration.Native.dll, версия: 3.4.1128.26111, метка времени: 0x62fab12a
> Код исключения: 0xc0000005
> Смещение ошибки: 0x0000000000005948
> Идентификатор сбойного процесса: 0x0x165C
> Время запуска сбойного приложения: 0x0x1D907B694C31809
> Путь сбойного приложения: D:\Dev\systeminformer\tools\CustomBuildTool\bin\Release\CustomBuildTool.exe
> Путь сбойного модуля: C:\ProgramData\Microsoft\VisualStudio\Setup\x64\Microsoft.VisualStudio.Setup.Configuration.Native.dll
> Идентификатор отчета: 53b6529c-0492-418d-a8fc-f432af3de0ce
> Полное имя сбойного пакета: 
> Код приложения, связанного со сбойным пакетом: 

for ~ 2 weeks already ...
could you please tell me how to fix it?

**Comment by dmex** [comment]
@skipik @henrypp 

Both of you should reset your VS installation by running:
`"C:\Program Files (x86)\Microsoft Visual Studio\Installer\InstallCleanup.exe"`

https://learn.microsoft.com/en-us/visualstudio/install/uninstall-visual-studio?view=vs-2022#remove-all-with-installcleanupexe

> "Unable to find the resource compiler"

The registry keys for locating the Windows SDK are missing from your machine. All of these errors you've been getting are errors locating the Windows SDK so your VS is corrupted or something.

> could you please tell me how to fix it?

It's crashing inside `Microsoft.VisualStudio.Setup.Configuration.Native` which is owned by Microsoft so there isn't much we do to workaround it. You need to reset your installation or contact Visual Studio support.

**Comment by skipik** [comment]
@dmex hey, thanks for your reply!
I've just fixed it :D I have fresh installation of VS, but both versions - 2019 and 2022. That was the reason. Just tried to rename the 2019 folder to "C:\Program Files (x86)\Microsoft Visual Studio\**_2019**" and it worked lol 
Just wanted to inform you.

**Comment by henrypp** [comment]
InstallCleanup.exe is just uninstall current Visual Studio. So it is not a solution.

**Comment by dmex** [comment]
> just uninstall current Visual Studio. So it is not a solution.

You need to reset the installation (uninstall & reinstall)?
