### ISSUE TITLE
error C2118: negative subscript (ntexapi.h)

### ISSUE THREAD

**Issue by LDzik** [winsiderss/systeminformer#1468]
### Brief description of your issue

After running "build_debug.cmd" I get these errors:

`ERROR] (1) D:\Process Hacker 2\systeminformer-master\phnt\include\ntexapi.h(6494,1): error C2118: negative subscript (compiling source file kphmsgdyn.c) [D:\Process Hacker 2\systeminformer-master\kphlib\kphlib_um.vcxproj]
D:\Process Hacker 2\systeminformer-master\phnt\include\ntexapi.h(6494,1): error C2118: negative subscript (compiling source file kphmsg.c) [D:\Process Hacker 2\systeminformer-master\kphlib\kphlib_um.vcxproj]
D:\Process Hacker 2\systeminformer-master\phnt\include\ntexapi.h(6495,1): error C2118: negative subscript (compiling source file kphmsgdyn.c) [D:\Process Hacker 2\systeminformer-master\kphlib\kphlib_um.vcxproj]
D:\Process Hacker 2\systeminformer-master\phnt\include\ntexapi.h(6495,1): error C2118: negative subscript (compiling source file kphmsg.c) [D:\Process Hacker 2\systeminformer-master\kphlib\kphlib_um.vcxproj]
D:\Process Hacker 2\systeminformer-master\phnt\include\ntexapi.h(6497,1): error C2118: negative subscript (compiling source file kphmsgdyn.c) [D:\Process Hacker 2\systeminformer-master\kphlib\kphlib_um.vcxproj]
D:\Process Hacker 2\systeminformer-master\phnt\include\ntexapi.h(6497,1): error C2118: negative subscript (compiling source file kphmsg.c) [D:\Process Hacker 2\systeminformer-master\kphlib\kphlib_um.vcxproj]
D:\Process Hacker 2\systeminformer-master\phnt\include\ntexapi.h(6494,1): error C2118: negative subscript (compiling source file kphdyn.c) [D:\Process Hacker 2\systeminformer-master\kphlib\kphlib_um.vcxproj]
D:\Process Hacker 2\systeminformer-master\phnt\include\ntexapi.h(6495,1): error C2118: negative subscript (compiling source file kphdyn.c) [D:\Process Hacker 2\systeminformer-master\kphlib\kphlib_um.vcxproj]
D:\Process Hacker 2\systeminformer-master\phnt\include\ntexapi.h(6497,1): error C2118: negative subscript (compiling source file kphdyn.c) [D:\Process Hacker 2\systeminformer-master\kphlib\kphlib_um.vcxproj]
`

**Comment by dmex** [comment]
Are you compiling with VS2022?

> error C2118: negative subscript

Your VS is failing this check for some reason:
`C_ASSERT(sizeof(KUSER_SHARED_DATA) == 0x738);`

**Comment by LDzik** [comment]
Running .cmd file it says this about vs:
VisualStudio: VisualStudio/17.1.1+32228.430

Yes I have VS2022 (I also have VS Build Tools 2017) installed and trying to compile it manually it gives me the same error but x  (prob for every file)

**Comment by LDzik** [comment]
Updated Visual Studio 2022 to 17.3.6+32929.385 still having this issue

**Comment by dmex** [comment]
> still having this issue

CI is passing without this issue and none of us can reproduce the error:
https://github.com/winsiderss/systeminformer/actions/workflows/msbuild.yml

> trying to compile it manually it gives me the same error

It's very likely your Windows SDK installation is corrupted and generating invalid binaries with invalid structures. You should uninstall the Windows SDK and then uninstall Visual Studio to reset the installation (repair install won't reset the Windows SDK) then reinstall.
