### ISSUE TITLE
Process hacker 2 its virus?

### ISSUE THREAD

**Issue by KolplayOne** [winsiderss/systeminformer#1471]
![875a8375f91de049494d6073098e8a2f_c623b0f96d648536815b5f6433ea9e56](https://user-images.githubusercontent.com/110826549/199947431-fcf9c282-8037-435c-8e01-df8bbc1cac82.png)
Virustotal show 19 virus
why do they write that process hacker 2 is a virus?

**Comment by Masamune3210** [comment]
Because False Positives are a thing. Use the search box next time please, a issue for this exact question has been asked 3 times in the last two months

**Comment by KolplayOne** [comment]
> Because False Positives are a thing. Use the search box next time please, a issue for this exact question has been asked 3 times in the last two months

is it safe without viruses?
are these false positives?

**Comment by jxy-s** [comment]
> is it safe without viruses?

The code is completely open source and available for review and scrutiny by the community. There is _**zero**_ malicious intent by the project.

> are these false positives?

The classifications provided on VT or by vendors are (in most cases) not false positives, rather, the industry recognizes "Process Hacker" as a "hacking tool". Which may or may not be desirable for certain users, environments, or applications.

The project, now "System Informer", has gone through a lot of changes to harden and minimize the abuse. Both in the term "hacking" (which is misdefined/understood by many) and abuse by a bad actor with malicious intent to do harm. The project does enable broader inspection into the system, which may be misconstrued as "malicious", but it is far from that. The project, in the right hands, enables users to identify misbehaving or malicious software in their environment. And take action against it. From the perspective of a bad actor leveraging System Informer to do legitimate harm - we have spent a lot of effort to coexist with the internals of the operating system to discourage and prevent bad actors from doing harm.
