### ISSUE TITLE
Build error WINHTTP_OPTION_DISABLE_GLOBAL_POOLING

### ISSUE THREAD

**Issue by gui28347** [winsiderss/systeminformer#1472]
### Brief description of your issue

Problem to build solution: 
[ERROR] (1) C:\processhacker\phlib\http.c(105,54): error C2065: 'WINHTTP_OPTION_DISABLE_GLOBAL_POOLING': undeclared identifier [C:\source\processhacker\phlib\phlib.vcxproj]C:\processhacker\phlib\http.c(950,62): error C2065: 'WINHTTP_OPTION_DISABLE_GLOBAL_POOLING': undeclared identifier [C:\processhacker\phlib\phlib.vcxproj]

### Steps to reproduce (optional)

download latest code from master and execute build script.

**Comment by dmex** [comment]
Install the latest Windows SDK
