### ISSUE TITLE
Change "Process Hacker" name

### ISSUE THREAD

**Issue by rogergithubbing** [winsiderss/systeminformer#1475]
Hello,

I know it would sound stupid, but I also know that I'm not the first one to ask it (see https://github.com/winsiderss/systeminformer/issues/978)

My peers at work continuously tell me about that 'name'... That the customers are gonna say something about it, etc.

It's not that stupid because a lot of people complains about it. Is there a way to change it ?

Thanks in advance,

Roger

**Comment by Masamune3210** [comment]
Its already been changed in the betas, just waiting on the first release

**Comment by rogergithubbing** [comment]
> Its already been changed in the betas, just waiting on the first release

Thanks for your answer; I'm sorry to ask this trivial question, but those 'betas' are downloadable right now or should we wait ? If that is the case, where is the link ?

**Comment by jxy-s** [comment]
There are a few other posts that explain:
https://github.com/winsiderss/systeminformer/discussions/1260
https://twitter.com/aionescu/status/1536494552105766912
https://github.com/winsiderss/systeminformer/issues/1286
