### ISSUE TITLE
what is the difference between version 2.39 and 3.0

### ISSUE THREAD

**Issue by KolplayOne** [winsiderss/systeminformer#1476]
There may have been a similar question already, but I couldn't find it.

**Comment by gettysburg** [comment]
I couldn't find either such a code branch or download branch, please link what you are referring to.

**Comment by dmex** [comment]
> what is the difference between version 2.39 and 3.0

3.0 has some new icons?

**Comment by KolplayOne** [comment]
> I couldn't find either such a code branch or download branch, please link what you are referring to.

what new features appeared in process hacker 3?

**Comment by jxy-s** [comment]
There are a lot, sorry to be _that guy_ who posts a diff.. but looking over the commits here is about the the most comprehensive thing I can provide at this time: https://github.com/winsiderss/systeminformer/compare/v2.39...master

So much work has been done, I won't be able to list everything. We might have a more comprehensive list of release notes when do we an official 3.x release. In the meantime, here are some highlights that are at the top of my mind (this list is going to be far from comprehensive):
- theme support (dark mode, modern icons)
- better GPU and FPS monitoring
- pool, object, firmware, named pipe, NTFS inspection (some extra plugins were promoted)
- many improvements and additions to PE viewer (searchable exports and imports, section and directory info, ...)
- more details handle details, searching, and inspection
- ALPC port client, server, and connection details
- extended computer boot options (System > Computer)
- monospace font options
- cleaner, better, and more tray icons
- firewall monitoring and management
- CPU group awareness
- many miscellaneous fixes and performance improvements
