### ISSUE TITLE
Provide a working link to downloads page

### ISSUE THREAD

**Issue by Speravir** [winsiderss/systeminformer#1479]
The link to the downloads page you present in README.MD – https://systeminformer.sourceforge.io/downloads.php – is dead. Please, either add there some content with downloadable binaries or change in the readme to another working link, where compiled binaries are available.

This said there is also [ProcessHackerRepoTool/nightly-builds-mirror](https://github.com/ProcessHackerRepoTool/nightly-builds-mirror) which you could migrate, as well, if possible, or otherwise this should be set into archived state.

**Comment by jxy-s** [comment]
We're working on the migration, please read the pinned issue, thanks: https://github.com/winsiderss/systeminformer/issues/1286
