### ISSUE TITLE
process hacker 3 release date

### ISSUE THREAD

**Issue by KolplayOne** [winsiderss/systeminformer#1486]
when will process hacker 3 be released?

**Comment by Biswa96** [comment]
The new SystemInformer nightly build has been released here https://systeminformer.sourceforge.io/nightly.php. Remember the project is still in development.

**Comment by KolplayOne** [comment]
> The new SystemInformer nightly build has been released here https://systeminformer.sourceforge.io/nightly.php. Remember the project is still in development.

This is process hacker 3?

**Comment by tsunamistate** [comment]
Process Hacker was renamed to System Informer

**Comment by KolplayOne** [comment]
> Process Hacker was renamed to System Informer

System informer = process hacker 3?

**Comment by Biswa96** [comment]
> System informer = process hacker 3?

Yes. See this tweet https://twitter.com/yarden_shafir/status/1592571932611846144

**Comment by KolplayOne** [comment]
> 

Thanks
