### ISSUE TITLE
Purpose new option: [View] - Scroll to next END process

### ISSUE THREAD

**Issue by nico92GitHub** [winsiderss/systeminformer#1487]
Hello Dev

I switch from Process Hacker Nightly to System Informer with pleasure.
Will the ProcessHacker_2.39_R124 project also be renamed to System Informer? In any case, these are utilities that I cannot do without :)

I would like to propose an option that would facilitate real-time monitoring of a program that stops a subroutine and launches a new one, for example. So as said in the topic "[View] - Scroll to next END process". It seems to me that it is as important to know what starts as what stops.

Awaiting your return,
regards,
Nico

**Comment by dmex** [comment]
> Scroll to next END process

Isn't this the same as the current option in the View menu > Scroll to new processes?

**Comment by nico92GitHub** [comment]
thank you for your return.

Unfortunately not, the "Scroll to new processes" option only goes to a starting process, not a terminating process.

Nico



> Scroll to next END process

Isn't this the same as the current option in the View menu > Scroll to new processes?

**Comment by SeaHOH** [comment]
Keep showing terminated processes for more seconds? or this is no sense.

**Comment by SeaHOH** [comment]
> I probably wasn't explicit enough... Is it clearer for you?

Yes, I got it now. I did not notice this setting before. The feature you requested maybe a good idea.

**Comment by nico92GitHub** [comment]
Ok, j'espère que vous l'implémenterez prochainement :)

**Comment by nico92GitHub** [comment]
oops! Ok, hope you implement it soon :)

**Comment by dmex** [comment]
`ScrollToRemovedProcesses` to 1

**Comment by nico92GitHub** [comment]
Excuse me, I'm not comfortable in the github environment.
_"Yes, I got it now. I did not notice this setting before. The feature you requested maybe a good idea."_
((>Can I hope that my "good idea" will be integrated in the next version Nightly Build ?
