### ISSUE TITLE
Add contrast border or background color in tray icons

### ISSUE THREAD

**Issue by Biswa96** [winsiderss/systeminformer#1490]
### Description of the feature, modification, idea or suggestion

In dark mode, the tray icons in taskbar are not easily distinguishable. For example, see the following screenshots

* SystemInformer

![1](https://user-images.githubusercontent.com/31443074/202133115-945e31b2-70a7-49b8-b538-9225a7c6d098.png)

* Process Explorer

![2](https://user-images.githubusercontent.com/31443074/202133290-f6a8e72b-8c1f-4f62-a557-c6e8d2316cb9.png)

See the difference in the tray icons.

**Comment by dmex** [comment]
Setting `IconTransparencyEnabled` to 0 reverts to the non-transparent background

**Comment by d-faure** [comment]
> Setting `IconTransparencyEnabled` to 0 reverts to the non-transparent background

Good! That was exactly the parameter I wanted.

> The colors are not so distinct. Also editing XML file is not so user convenient 🤓

In fact, this is rather easily done through the advanced options tab.

**Comment by Vasilich** [comment]
2 tray icons get transparent color after first redrawing (after start bg for all icons is black): 

-  "SystemInformer icon (static)" is transparent and empty
- "Disk history" icon has transparent background.

All this with `IconTransparencyEnabled`  set to 0, on Windows 10 22H2 and SI 3.0.5527.

**Comment by dmex** [comment]
I've changed the settings so the transparent icons won't be enabled by default.

> 2 tray icons get transparent color

Fixed 👍
