### ISSUE TITLE
Constant Crashes from the Latest Nightly

### ISSUE THREAD

**Issue by Still34** [winsiderss/systeminformer#1495]
### Brief description of your issue

Every few hours or so, I'd get a `System Informer has crashed` message with the error code `0xC0000005 (Invalid access to memory location.)`. I'm unable to reproduce this reliably, so I have no idea what part of it is failing. I've attached a dump here 
[SystemInformer_AZXKXHTEVHIYWPK_DumpFile.zip](https://github.com/winsiderss/systeminformer/files/10045677/SystemInformer_AZXKXHTEVHIYWPK_DumpFile.zip).

### Environment (optional)

```shell
Nightly b4c6ea5
Microsoft Windows 10.0.25236 (Windows 11)
```

**Comment by KAMKillJoy** [comment]
I have the same problem on win10 x64. But its more often for me.
![image](https://user-images.githubusercontent.com/8235528/202834445-83f189da-72fe-4f0b-8502-b1424f604da3.png)

**Comment by ge0rdi** [comment]
Guys, you are using build 5520.
Latest nightly is 5527 and it fixes those crashes.

Just go to `Help` -> `Check for updates` and update.

**Comment by KAMKillJoy** [comment]
Yeah, thanks.
