### ISSUE TITLE
Tray icons order is not saved. Resets positions every time.

### ISSUE THREAD

**Issue by Milincho** [winsiderss/systeminformer#1496]
The tray icons order is not saved. Resets positions every time. 

And the color for "Physical" is too dark for dark themes. It blends with the background and can't be seen. Can the tray icon colors be changed?

These problems were not present in Process Hacker.

**Comment by Masamune3210** [comment]
Trey icon order is handled by Windows, not by the app unless there is some function to call that I don't remember off the top of my head

**Comment by dmex** [comment]
> The tray icons order is not saved. Resets positions every time.

You have to enable this feature by setting `IconTrayPersistGuidEnabled` to 1

There's been too many bug reports over the last few years where tray icons have disappeared and stop working entirely until you delete the IconGuids setting and regenerate guids for all the icons. So to workaround those bugs in Windows the guid functionality for persistence won't be enabled by default.

> And the color for "Physical" is too dark for dark themes

The colors haven't changed and are whatever colors you've selected in the Options > Graphs > colors window.

**Comment by Milincho** [comment]
> > The tray icons order is not saved. Resets positions every time.
> 
> You have to enable this feature by setting `IconTrayPersistGuidEnabled` to 1
> 
> There's been too many bug reports over the last few years where tray icons have disappeared and stop working entirely until you delete the IconGuids setting and regenerate guids for all the icons. So to workaround those bugs in Windows the guid functionality for persistence won't be enabled by default.
> 
> > And the color for "Physical" is too dark for dark themes
> 
> The colors haven't changed and are whatever colors you've selected in the Options > Graphs > colors window.

I see, thanks for the clarifications. 

Is there a way to set black backgrounds for the tray icons like they have in Process Hacker?

**Comment by Vasilich** [comment]
> Is there a way to set black backgrounds for the tray icons like they have in Process Hacker?

check this issue https://github.com/winsiderss/systeminformer/issues/1490
