### ISSUE TITLE
Cannot start windows task manager

### ISSUE THREAD

**Issue by vsub** [winsiderss/systeminformer#1497]
### Brief description of your issue

With the old version(Process Hacker)this was possible but not anymore with System Informer
If System Informer is set as the default task manager,when you attempt to start the windows task manager from withing System Informer(Tools=>Start Task Manager),the program just tries to run another instance of System Informer

**Comment by dmex** [comment]
Try setting `EnableShellExecuteSkipIfeoDebugger` to 0

**Comment by vsub** [comment]
Yes that fixed it
