### ISSUE TITLE
DLL injection fails if kernel driver is loaded

### ISSUE THREAD

**Issue by 0xGREG** [winsiderss/systeminformer#1500]
### Brief description of your issue

When the kernel-mode driver is enabled in the settings and it is successfully loaded, trying to inject a DLL into any process fails: it gives an "Access Denied" error. Disabling the kernel-mode driver solves the issue.

### Steps to reproduce (optional)

- Enable kernel driver in Options,
- Try injecting a dll, it will fail.
- Disable kernel driver in Options,
- Injecting any dll into any process will be successful.

### Expected behavior (optional)

- The DLL should inject successfully regardless of the driver's status.

### Actual behavior (optional)

The DLL doesn't get injected.

### Environment (optional)

```shell
Windows 10 21H2 (build 19044.2251)
Secure Boot disabled, HVCI disabled
```

**Comment by jxy-s** [comment]
fixed with https://github.com/winsiderss/systeminformer/commit/b6bc2b44035cca813c67bdddb010b1a9fc4580a8
