### ISSUE TITLE
Services - Filename column not filled

### ISSUE THREAD

**Issue by Vasilich** [winsiderss/systeminformer#1501]
When enabling the "Filename" column in Services tab, it is always empty for all services. 
Checked with last ProcessHacker - there it has shown full path to file.
Checked with SI 3.0.5553.

**Comment by dmex** [comment]
You need to enable the `Check services for digital signatures` option in the settings window.

* Querying the filename for services requires at minimum +700 registry handles and (minimum) 1,462 registry string lookups.
* The service filenames have to be copied into application memory and remain in memory until exiting the application. 

The service filenames are rarely used by anyone so opening all these handles+queries+copying strings during application startup isn't the best for processor time and system memory... So to improve application performance we don't query/copy/show service filenames unless you enable the `Check services for digital signatures` option in settings 👍
