### ISSUE TITLE
Threat found on version 3.0.5553

### ISSUE THREAD

**Issue by Liano** [winsiderss/systeminformer#1504]
### Brief description of your issue

I downloaded nightly version 3.0.5553 today, but Kaspersky detected thread when extracted from the archive.
To confirm that Kaspersky is not reporting false alert, I searched using archive sha2 value in TotalVirus, similar issue was reported.
48C869FF4CCEA0EA0D4E9A23E5BFBBA640B5F092BD69E779F320262BCCE0A491
I didn't test the setup file.
Is something wrong here, or Kaspersky and TotalVirus reporting false alert?

### Environment (optional)

```shell
Nightly version 3.0.5553
Windows 10, Kaspersky Total security 21
```

**Comment by dmex** [comment]
False positives.
