### ISSUE TITLE
Unable to save the live kernel dump.

### ISSUE THREAD

**Issue by kouzhudong** [winsiderss/systeminformer#1507]
### Brief description of your issue

![1669170843024](https://user-images.githubusercontent.com/18212165/203459084-d4142ab1-c0e2-4be5-a82e-478dd1ff952e.png)

**Comment by dmex** [comment]
You probably have a rootkit?

I tested all versions of Windows and creating live kernel dumps worked fine 🤷‍♂️

![image](https://user-images.githubusercontent.com/1306177/203471975-92156647-f1be-432d-a9cb-f776af58cc66.png)
![image](https://user-images.githubusercontent.com/1306177/203472017-e170d87c-c3f5-4882-824e-743574f62299.png)
![image](https://user-images.githubusercontent.com/1306177/203472298-e7296121-736c-41e2-9e08-26ca72823076.png)
