### ISSUE TITLE
"Find Window" functionality broken in nightly build

### ISSUE THREAD

**Issue by yossizahn** [winsiderss/systeminformer#1516]
### Brief description of your issue

The "Find Window" functionality seems to be broken in the latest nightly.
The button in the toolbar is not draggable anymore.

### Environment (optional)

Latest nightly (3.0.5578)

**Comment by Biswa96** [comment]
I can not reproduce the issue in my system. The find window button in toolbar works fine.

When some random GUI problem happens, I move SystemInformer.exe.settings.xml file to another folder. Then SystemInformer would create a fresh one. If the issue is fixed I diff those files.

**Comment by yossizahn** [comment]
Thanks, @Biswa96, you were right
My mistake, it is working, but it doesn't give any visual indication that it is draggable, i.e a "ghost" icon should come with the pointer, or something similar.

**Comment by dmex** [comment]
> it doesn't give any visual indication that it is draggable, i.e a "ghost" icon should come with the pointer, or something similar.

The cursor changes to a large cross when find window is active.

**Comment by yossizahn** [comment]
Indeed, I see that this works on my win10 machine. For some reason my win11 machine is not showing the cross. Can any one corroborate this?

**Comment by dmex** [comment]
> For some reason my win11 machine is not showing the cross. Can any one corroborate this?

Was your Win11 installation fresh or upgraded from Win10? The functions for changing the cursor haven't changed since 1995 so it's likely an upgrade install corrupted the system images for cursors?

**Comment by ge0rdi** [comment]
For me it works well on Win11 22H2 (and latest Insider too).
Once I'll click to `Find windows` button, cursor changes to cross and I'm able to pick some window.

**Comment by yossizahn** [comment]
@dmex it is a fresh win11 install on macOS using Parallels. 
I'm not sure what else could be causing this.
Maybe the hidpi screen?
