### ISSUE TITLE
Process Hacker prevents shutdown

### ISSUE THREAD

**Issue by skeetor** [winsiderss/systeminformer#1520]
### Brief description of your issue

I foound that ticket here https://github.com/winsiderss/systeminformer/issues/1193 which has been closed, which exactly describes my problem. I'm a bit surprised that it was closed due to inactivity,because the problem exists and the proposed solution is just a workaround that can be used, but doesn't solve the actual problem.

I'm using 2.39.124, which was the latest version I found here: https://processhacker.sourceforge.io/downloads.php

### Steps to reproduce (optional)

Normal shutdown, either via menu or on commandline doesn't work. The system can't shutdown and the winlogon process has to be terminated manually to trigger it.
Which is not easily done, because Process Hacker itself becomes unresponsive at this stage.

### Expected behavior (optional)

Normal shutdown

**Comment by jxy-s** [comment]
We've had infrequent reports of this over the years. We did implement a patch in System Informer that we believe may be the cause of the hang. But haven't been able to reproduce ourselves, nor have we had anyone active enough to help us verify the potential fix.

@skeetor please try reproducing the problem using the System Informer nightly build: https://system-informer.com/nightly.php

**Comment by skeetor** [comment]
With the nightly version it appears to work. Retried it now 2 times and I could shutdown. I noticed that Windows freezes for a second or so, where I though that it crashed (mousealso didn't move in that time) but then it shuts down. Didn't notice any bad effects because of the freezing, so I figure it might be ok.

**Comment by jxy-s** [comment]
Thanks for verifying the fixes for us 👍.
