### ISSUE TITLE
"Find Window" outline persists on Window when tabbing back to System Informer

### ISSUE THREAD

**Issue by leumasme** [winsiderss/systeminformer#1533]
### Brief description of your issue

When using the "Find Window" Drag and Drop Tool and tabbing back to System Informer while the tool is still active, the selection outline may remain visible on a Window even after the tool is exited and the Window unselected

### Steps to reproduce (optional)

- Open SystemInformer and another Window of Choice (Tested with explorer folder view)
- Click and Hold the Find Window tool, drag it over the Window of Choice, then alt-tab back to System Informer (which was automatically moved into the background)
- Move the Mouse to System Informer and release the button

### Expected behavior (optional)

The Selection Outline should not remain on a window after the tool has ended.

### Actual behavior (optional)

The Selection Outline remains on the window even after the tool has finished.
Video:

https://user-images.githubusercontent.com/29953391/206912578-bdac7fac-8244-47ed-8ce5-6640fc723d50.mp4

### Environment (optional)

```shell
OS: Windows 10
Version: System Informer 3.0.5578 (ccc890a)
```

**Comment by leumasme** [comment]
I see, but why does this then only happen when exiting the find window tool in this specific way?
If the find window tool ends on Explorer normally by just releasing the mouse while it's over it, this same thing does not happen.

**Comment by dmex** [comment]
> why does this then only happen when exiting the find window tool in this specific way?

I think it's the immersive new alt-tab window included with recent Win10/11 dropping some window messages because the border resets when using the old dialog and doesn't trigger the issue.

> If the find window tool ends on Explorer normally

I've added a workaround to reset the state when capture changes that should reset the border when alt-tabbing.
