### ISSUE TITLE
Unable to build the project using Visual Studio 2022.

### ISSUE THREAD

**Issue by umeshiscreative** [winsiderss/systeminformer#1535]
I followed the build instructions from the repo but was unable to build this project using Visual Studio 2022. 

<img width="312" alt="sysinforErr" src="https://user-images.githubusercontent.com/36879900/207081347-1a4c994b-1499-47c4-96bf-8d0e4606b22f.PNG">

If I ignore the warning I am unable to see the process's CPU usage and its memory usage.

<img width="592" alt="sysinforErr2" src="https://user-images.githubusercontent.com/36879900/207081942-81542f23-6733-4991-9d89-74a20e6f506c.PNG">

Any help will be appreciated. :)
Thanks,

**Comment by dmex** [comment]
> I followed the build instructions from the repo but was unable to build

Assertion failure prompts are a runtime error not build errors. The project built successfully but something at runtime failed.

> If I ignore the warning I am unable to see

This assert is for allocating 0 bytes. You need to click Retry and copy/paste the stacktrace so we can see what failed.

**Comment by dmex** [comment]
Feel free to re-open this issue if you still need help 👍
