### ISSUE TITLE
Feature Request:   Hide System Idle and remove Idle Percentage from other graphs

### ISSUE THREAD

**Issue by donxr** [winsiderss/systeminformer#1538]
Thank you for developing this wonderful tool.
There are so many things i love about this process manager which the others do not do.

I have a request for an additional improvement.

the CPU History graph shows very little information for most processes, partly because the System Idle Process is usually where most of the CPU usage is found.

Can we make an option to hide the System Idle Process?

Further to that idea, can we make the CPU History for the other processes exclude the System Idle Process CPU usage values from the other CPU History graphs for other processes?
![kj - system informer Idle Process dominates cpu history graph](https://user-images.githubusercontent.com/19331297/207943881-c7f060c2-0480-4d91-b0c5-1d63938ba565.PNG)

**Comment by dmex** [comment]
> make the CPU History for the other processes exclude the System Idle Process CPU usage values

The graphs are drawn independently of other graphs/processes. The idle process does not affect the values or display of processes or graphs and excluding it doesn't make a difference.

> the CPU History graph shows very little information for most processes

There's a setting for scaling graphs in the options window:

![image](https://user-images.githubusercontent.com/1306177/207965116-21958269-e1ef-4882-8238-bcf110347a1c.png)

I'll extend the setting to include the CPU History graph on the processes list.

**Comment by donxr** [comment]
Thank you for clarifying how the graphs work,  my erroneous assumption, and most of all, responding so quickly!
My apologies for missing that setting in the options,  I will give it a try!

**Comment by dmex** [comment]
The latest nightly will now scale the CPU history graphs when that option is enabled 👍 

![image](https://user-images.githubusercontent.com/1306177/209901176-5d77a54c-3ac5-4a8d-9ef2-d55571c58745.png)
