### ISSUE TITLE
Unloaded Modules Viewer Logic Bug

### ISSUE THREAD

**Issue by TorseqTech** [winsiderss/systeminformer#1539]
### Brief description of your issue

If the last call to ReadProcessMemory fails cleanup is called but memory is allocated before this and never freed. Inside the cleanup area you should check that result !=0 (failed) and if (memoryBuffer != NULL) phFree(memoryBuffer) because the caller otherwise does not see a successful result to free the memory themselves and it will leak.

**Comment by dmex** [comment]
Fixed with 0543e720cc4d2878ce9e638a27479dfe30bac53d 👍
