### ISSUE TITLE
Fail to build code from master branch

### ISSUE THREAD

**Issue by gui28347** [winsiderss/systeminformer#1542]
### Brief description of your issue

Fail to build after syncing latest code from master branch.

### Steps to reproduce (optional)

1 Clone this repo
2 Pull the latest code
3 Run .\build\build_release.cmd

![image](https://user-images.githubusercontent.com/8279438/208763678-bb730600-debd-4e63-bcc9-edce2e7e4247.png)

[ERROR] (1) C:\source\systeminformer\SystemInformer\main.c(1093,10): error C2220: the following warning is treated as an error [C:\source\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\source\systeminformer\SystemInformer\main.c(1093,10): warning C4013: 'CoInitializeEx' undefined; assuming extern returning int [C:\source\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\source\systeminformer\SystemInformer\main.c(1093,10): error C2065: 'COINIT_APARTMENTTHREADED': undeclared identifier [C:\source\systeminformer\SystemInformer\SystemInformer.vcxproj]C:\source\systeminformer\SystemInformer\main.c(1093,10): error C2065: 'COINIT_DISABLE_OLE1DDE': undeclared identifier [C:\source\systeminformer\SystemInformer\SystemInformer.vcxproj]

### Expected behavior (optional)

Build with no errors.

### Actual behavior (optional)

Build error: C2220

**Comment by ge0rdi** [comment]
I guess there is no need to report build errors that are already reported by CI pipeline:
![image](https://user-images.githubusercontent.com/2453094/208765848-8f83b5ae-5544-46c2-b8b2-44f5d0523e08.png)
You can find details by clicking on the build status icon.

I'm sure @dmex will fix it soon.
