### ISSUE TITLE
No Way To Close To Tray

### ISSUE THREAD

**Issue by CityguyUSA** [winsiderss/systeminformer#1543]
You can start System Hacker 2 in the tray with Windows at startup but once you open the window/restore the window there's no way to put it back too the tray.  Clicking the X will shut it down entirely requiring you to restart it.

**Comment by jxy-s** [comment]
`Options > Hide when closed` should keep the program active and the tray icon active when you close the program.

**Comment by CityguyUSA** [comment]
Sorry. I didn't see it when I went through setup options.  Working good now.
