### ISSUE TITLE
Top bar missing since upgrade to System Informer

### ISSUE THREAD

**Issue by ghGhost-cs** [winsiderss/systeminformer#1548]
### Brief description of your issue

After updaing to System Informer from Process Hacker (nightly) top bar gone missing with no ability to recover it.
With that bar you could open defult process manager, start process as some user and so. If was so useful for me.
It was present from upgrading to System Informer and thought that it would get fixxed in next update.
Screenshot of both programs open:
![image](https://user-images.githubusercontent.com/61838935/209475601-12fdee71-ceb4-431d-96e3-5a89411d30f8.png)

### Environment (optional)

```shell
System Informer (nightly), last update check 20.12.2022
Process Hacker (nightly) 3.0.4953 (37e0466)
Win10x64 Pro 21H2 19044.2364
```

**Comment by Popsoywhip** [comment]
Fix

**Comment by Biswa96** [comment]
It may be set as auto-hide. Press Alt and View > Toolbar > Main menu (auto-hide)

**Comment by ghGhost-cs** [comment]
Thanks! No need to press ALT because the context menu will continue to disappear.

**Comment by dmex** [comment]
@ghGhost-cs 

You should reset settings to defaults
