### ISSUE TITLE
PH2 warns every day a new Service MpKslxxxxxxx is created! Any helps to track it?

### ISSUE THREAD

**Issue by the-insulter** [winsiderss/systeminformer#1549]
Hello,

as told every day a new service with mpksl is created, and I don't see it any where only with PH giving a waringin in info center AND then there is also no logs in PH?

Can you please help me and put that log in Process HAcker too?`

Thanks and best regards.

**Comment by Biswa96** [comment]
Duplicate of https://github.com/winsiderss/systeminformer/issues/561

Also ProcessHacker project has been changed into SystemInformer. Please use the latest program from here https://systeminformer.sourceforge.io/nightly.php

**Comment by the-insulter** [comment]
Thanks for describing and making me smarter :)

**Comment by dmex** [comment]
Duplicate of #561
