### ISSUE TITLE
Updater asks for admin rigths

### ISSUE THREAD

**Issue by Nojevah** [winsiderss/systeminformer#1550]
### Brief description of your issue

I use option "Check for updates automatically" with SI and I'm in "portable" mode. The 2 or 3 last updates have forced me to be admin (via UAC) to install update.
It wasn't the case with PH3 of for the first SI update (if I remember correctly).

### Environment (optional)

```shell
SI 3.0.5727
Windows 11
```

**Comment by dmex** [comment]
Fixed in the next nightly 👍
