### ISSUE TITLE
can't change csrss priority on latest system informer builds

### ISSUE THREAD

**Issue by BK8000L** [winsiderss/systeminformer#1553]
### Brief description of your issue

With process hacker 3.0.4953 and enabled kernel-mode driver i can change csrss priority, but system informer says "Access denied".

### Steps to reproduce (optional)

Case 1:
1. Install Process Hacker 3.0.4953 (https://disk.yandex.com/d/I932kx8-bmhXUA)
2. Enable "Kernel-mode driver"
3. Change priority of csrss.exe to Real time

Case 2:
1. Install latest nightly
2. Enable "Kernel-mode driver"
3. Change priority of csrss.exe to Real time

### Expected behavior (optional)

Priority changes in both cases

### Actual behavior (optional)

Case 1:
Priority changes
![image](https://user-images.githubusercontent.com/82240117/210044842-c7cfc498-6a9e-46c0-9d5d-f8d367cfee1d.png)

Case 2:
![image](https://user-images.githubusercontent.com/82240117/210044944-45c6cf08-f171-4575-a8ed-beebc279154e.png)

### Environment (optional)

```shell
Windows 10 22H2
```

**Comment by TheEragon** [comment]
This is due to changes in driver so it would comply with MS rules and they'd sign it. So it's not a bug.

Why would you need to change priority of csrss in the first place?

**Comment by Biswa96** [comment]
> This is due to changes in driver so it would comply with MS rules and they'd sign it. 

Can you provide which code was changed for that?

**Comment by BK8000L** [comment]
> So it's not a bug.

Can you please provide the latest version that can do this?

**Comment by TheEragon** [comment]
> Can you provide which code was changed for that?

I believe it "fails" here https://github.com/winsiderss/systeminformer/blob/master/KSystemInformer/verify.c#L398-L412 because csrss runs with WinTcb protection.

**Comment by BK8000L** [comment]
This https://github.com/katlogic/WindowsD can remove protection and then even a kernel-level driver is not required

**Comment by jxy-s** [comment]
This is by design. We respect the PPL security boundaries enforced by the operating system.
