### ISSUE TITLE
Error updating System Informer

### ISSUE THREAD

**Issue by PJAlley** [winsiderss/systeminformer#1554]
### Brief description of your issue

Cannot update System Informer to new version.

### Steps to reproduce (optional)

Go to Help and click on Check for updates.

App states that update is available.

Updated version downloads and asks to install.

![2022-12-30 21_15_14-System Informer - Updater](https://user-images.githubusercontent.com/40871127/210122209-112b0dd6-79b8-43b0-bb96-5b40b4a6ec52.png)

I click on Install and I receive this error:
![2022-12-30 21_22_21-System Informer - Setup](https://user-images.githubusercontent.com/40871127/210122233-d573fba9-47f8-40bb-a82c-42585fa87260.png)

Retrying doesn't work. I have to close out the application.

### Expected behavior (optional)

The update installs.

### Actual behavior (optional)

In an install loop - Cannot create the file when that file already exists

### Environment (optional)

```shell
System Informer version 3.0.5578
Windows 11
```

**Comment by PJAlley** [comment]
To add: The only way to update is to uninstall and reinstall the app, which isn't user-friendly. 

Getting the installation file, I attempt to use it and receive this warning:
![2022-12-30 21_33_24-System Informer - Setup](https://user-images.githubusercontent.com/40871127/210122497-1739b8ae-d940-4373-8e20-72faf4b5d175.png)

When I click 'Yes', I get this error message:
![2022-12-30 21_34_33-System Informer - Setup](https://user-images.githubusercontent.com/40871127/210122515-5c0cdf13-dda4-407f-b5e7-322d6e3520bc.png)

**Comment by as-muncher** [comment]
I was able to update Process Hacker 3 nightly to System Informer, automatically, when prompted, but then when I got System Informer, it could not update.  The files download, but then maybe Kapsersky deletes the files quickly?  system informer 3.0.5553.  update available, wants to update to 3.0.5727.  Download works okay.  Clicking Install to continue, Kaspersky Free's protection is paused until application restart.  Updating... files extracted.  hmm... worked.  Okay, my bad.  I just had to pause Kaspersky protection.

**Comment by PJAlley** [comment]
Hmmm...I have Avast. Do you believe it's the antivirus that's causing the upload to fail? Do you receive an alert from Kaspersky? With Avast, there's no alert when downloading or attempts to update.

**Comment by as-muncher** [comment]
@PJAlley no need to ask all that.  :)  Just let me know whether disabling the antivirus worked or not.  I did not receive an alert from Kapersky.

**Comment by Thunder33345** [comment]
Can repro on win10
```
OS Version		Win10 10.0.19044 Build 19044
Sys informer 	3.0.55789(ccc890a)
AV used 			Windows defender
```
Seems like this also happens if i tried to use [nightly builds ](https://systeminformer.sourceforge.io/downloads.php)to manually update it

**Comment by as-muncher** [comment]
@PJAlley Did you get it to update?
@Thunder33345 Does updating work if you disable Windows Defender temporarily?

**Comment by Thunder33345** [comment]
@as-muncher, nope, that error still occurs

> Cannot create a file when that file already exists.

I don't believe the error has anything to do with AV though. It is what it says on the tin in this case, I believe installer was not meant to handle upgrading, it did not expect files already exist in the install directory, and have no logic to handle that(asking users if they want to overwrite everything, running the uninstaller first, etc)

**Comment by Vasilich** [comment]
@Thunder33345 i have no problem to update SI, did it several times on different PCs without issues, so your assumption about installer, that can't handle upgrade, is wrong.
All of my PCs have no AV though, so your AV can have issues. 
> It is what it says on the tin in this case,
Yes, because some process can lock file that need to be upgraded. Are you sure that your AV haven't locked it during uprgade?

**Comment by PJAlley** [comment]
> @PJAlley Did you get it to update? @Thunder33345 Does updating work if you disable Windows Defender temporarily?

I ended up uninstalling and re-installing System Informer.

**Comment by Thunder33345** [comment]
> All of my PCs have no AV though, so your AV can have issues.

Interesting, sadly I only have one device to test, but good to know it works, and this is a special edge case...

> Are you sure that your AV haven't locked it during upgrade?

I would assume it's unlocked since I disabled by AV, but I cannot tell for certain(did not attempt to reboot)

> I ended up uninstalling and re-installing System Informer.

Does setting still preserve when done this way? I might just do this... But I can't tell if doing that is just going to be a temporary solution that I will need to apply for every new update.

**Comment by PJAlley** [comment]
> > I ended up uninstalling and re-installing System Informer.
> 
> Does setting still preserve when done this way? I might just do this... But I can't tell if doing that is just going to be a temporary solution that I will need to apply for every new update.

You have the option to keep or delete your settings. I kept mine and they are preserved.

It doesn't seem to be a specific AV issue. The only scenario I can think to try is to download the update, close the application, then attempt the upgrade (see if the error exists when the application is in use).

**Comment by dmex** [comment]
> I believe installer was not meant to handle upgrading, it did not expect files already exist in the install directory, and have no logic to handle that

The setup has always handled the upgrade since 2015 and hasn't had this problem until last week.

> Are you sure that your AV haven't locked it during upgrade?

I've seen a few machines where Explorer.exe and PcaSvc (Program Compatibility Assistant Service) appear to be leaking handles and preventing the updater from upgrading files?

If the updater fails with `Cannot create the file when that file already exists` then open System Informer and select the `Find handles or Dlls` window and try search for `systeminformer.exe`, `updater.dll`, `networktools.dll` and `setup.exe` and it'll show the process locking the files as in-use and blocking the updater.

> Does setting still preserve when done this way? I might just do this...

Settings are not removed on uninstall unless you select the option to remove settings.

**Comment by as-muncher** [comment]
@dmex, This problem of updating Process Hacker / System Informer has been happening for longer than 3 weeks.  I'm glad that, so far, I can update by disabling antivirus.

**Comment by dmex** [comment]
@as-muncher 

You need to report the problem to your anti-virus vendor. Their product is causing the issue not our setup.

**Comment by PJAlley** [comment]
With this new update, I disabled my anti-virus and still received the error 
![2023-01-26 19_25_55-System Informer - Setup](https://user-images.githubusercontent.com/40871127/214980158-22bd9d79-4409-4f0f-b51b-0b3c6759fcdb.png)

And attempting to upgrade using the cached version, I get this warning:
![2023-01-26 19_29_21-System Informer - Setup](https://user-images.githubusercontent.com/40871127/214980492-0e6891ca-035e-4e39-8b1e-19047d8a6d31.png)

I click on Continue and immediately get this error:
![2023-01-26 19_29_21-System Informer - Setup](https://user-images.githubusercontent.com/40871127/214980550-fa99374c-a5ee-448f-ab03-3f01feeda39e.png)

So this issue is _not_ resolved at all, even without an antivirus. The _only_ way to upgrade is to uninstall and reinstall, and that is **not** user-friendly at all.

**Comment by PJAlley** [comment]
> > I believe installer was not meant to handle upgrading, it did not expect files already exist in the install directory, and have no logic to handle that
> 
> The setup has always handled the upgrade since 2015 and hasn't had this problem until last week.
> 
> > Are you sure that your AV haven't locked it during upgrade?
> 
> I've seen a few machines where Explorer.exe and PcaSvc (Program Compatibility Assistant Service) appear to be leaking handles and preventing the updater from upgrading files?
> 
> If the updater fails with `Cannot create the file when that file already exists` then open System Informer and select the `Find handles or Dlls` window and try search for `systeminformer.exe`, `updater.dll`, `networktools.dll` and `setup.exe` and it'll show the process locking the files as in-use and blocking the updater.
> 
> > Does setting still preserve when done this way? I might just do this...
> 
> Settings are not removed on uninstall unless you select the option to remove settings.

Pre-System Informer (Process Hacker 2 and Process Hacker 3 Beta), there was no issues with upgrading the system, either in Windows 10 or Windows 11. This issue only started when it was rebranded as System Informer.

**Comment by trparky** [comment]
I have the same issue, I compiled my copy from source on my own system. I get to this part of the installer...
![image](https://user-images.githubusercontent.com/32105035/217391293-1066dd75-46e4-49b4-8c58-c1e5c9d8ecbf.png)
And it dies.

Fault bucket 2288574126000581603, type 1
Event Name: APPCRASH
Response: Not available
Cab Id: 0

Problem signature:
P1: systeminformer-build-setup.exe
P2: 3.0.10512.5985
P3: c9a9188b
P4: systeminformer-build-setup.exe
P5: 3.0.10512.5985
P6: c9a9188b
P7: c0000005
P8: 000049d0
P9: 
P10: 

Attached files:
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.eac01dc4-7e2b-4e5c-a06c-b8a14694147d.tmp.dmp
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.95e1f56e-5f2b-4101-82b6-66410b05965e.tmp.WERInternalMetadata.xml
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.4cac85ce-55b7-4978-a7fc-ec167650119a.tmp.csv
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.c1b1f11d-184a-4252-9e4d-a88403a374e5.tmp.txt
\\?\C:\ProgramData\Microsoft\Windows\WER\Temp\WER.665f13c1-dd4e-4d5d-8b78-380ed0dfab76.tmp.xml

These files may be available here:
\\?\C:\ProgramData\Microsoft\Windows\WER\ReportArchive\AppCrash_systeminformer-b_ffe79fee81e4766895705596bead2558a38caadf_d702a380_f50e7805-3043-44dc-a02d-179431243aa8

Analysis symbol: 
Rechecking for solution: 0
Report Id: 3a82f26a-e5ad-499e-a6db-cf28b9ceb414
Report Status: 268435456
Hashed bucket: 894d3188e7489dce3fc2a60ace6a2be3
Cab Guid: 0

Faulting application name: systeminformer-build-setup.exe, version: 3.0.10512.5985, time stamp: 0xc9a9188b
Faulting module name: systeminformer-build-setup.exe, version: 3.0.10512.5985, time stamp: 0xc9a9188b
Exception code: 0xc0000005
Fault offset: 0x000049d0
Faulting process id: 0x0x2788
Faulting application start time: 0x0x1D93B4CE9EF53C5
Faulting application path: C:\Users\trpar\source\repos\systeminformer\build\output\systeminformer-build-setup.exe
Faulting module path: C:\Users\trpar\source\repos\systeminformer\build\output\systeminformer-build-setup.exe
Report Id: 3a82f26a-e5ad-499e-a6db-cf28b9ceb414
Faulting package full name: 
Faulting package-relative application ID:

**Comment by trparky** [comment]
Compiled the program and setup on a completely different system to rule out possible hardware issues during compile, same exact issue; the setup died at the same spot.

**Comment by trparky** [comment]
OK, I did some investigation and it seems something happened in commit d84d49443 that caused things to break.

**Comment by trparky** [comment]
Got it!!! Commit cd886e0a399e70212da71fe433fb276e4e172d97 is the commit that broke things.

**Comment by PJAlley** [comment]
New update didn't solve the original issue.

I basically have to change the folder name in order to get an update to install.

**Comment by olavinto** [comment]
This might be related so I won't post a new issue about it at this time. For me, the update process downloads and seemingly installs just fine but when the app is restarted afterwards it informs of the same update again. Sometimes closing the app and manually restarting it fixes this - sometimes it doesn't. There seems to be some kind of problem where the installer doesn't close the older running app or doesn't close it fast enough and the update is installed only partly or not at all. Manually downloading and installing has always worked fine. This happened with many ProcessHacker 3 versions but disappeared prior to the rebranding but now it has appeared again with perhaps two or three updates. In between updates worked just fine.

**Comment by dmex** [comment]
@PJAlley @olavinto 

It might help to upload a trace using procmon:
https://learn.microsoft.com/en-us/sysinternals/downloads/procmon

Exclude everything except systeminformer.exe and systeminformer-setup.exe then either attach the trace here or email to 
dmex04 at gmail.com

**Comment by PJAlley** [comment]
Hi @dmex , here's the trace in CSV format:
[Logfile.CSV](https://github.com/winsiderss/systeminformer/files/10738327/Logfile.CSV)

I also have the PML format if need be.

**Comment by PJAlley** [comment]
There was also another avenue to install the upgrade which involved going to `AppData\Roaming\SystemInformer\cache` folders.

There. it spells a warning that the file already exists, then errors out immediately after clicking on 'Continue'.

Procmon Log here:
[Logfile2.CSV](https://github.com/winsiderss/systeminformer/files/10738345/Logfile2.CSV)

**Comment by dmex** [comment]
> PML format

If you can upload the PML file it would be easier

**Comment by PJAlley** [comment]
I'll have to email you directly. Github doesn't support PML.

**Comment by PJAlley** [comment]
Using an older setup file that I saved, I installed it. The update came up and the update installed successfully.

**Comment by PJAlley** [comment]
New update also installed without any errors. 

Thank you @dmex for this fix! :)

**Comment by PJAlley** [comment]
Resolved as fixed.

**Comment by MagicAndre1981** [comment]
from time to time I get this error:

![_systeminformer_updater_error](https://user-images.githubusercontent.com/8274816/221977453-a8ef42c9-f84f-4f58-b373-aff28ce9cd31.png)

and clicking retry solves it. Mabye handle  `ERROR_SERVICE_MARKED_FOR_DELETE` and retry internally @dmex
