### ISSUE TITLE
How to know which network interface is used ?

### ISSUE THREAD

**Issue by Glubzor** [winsiderss/systeminformer#1562]
Hi,
To be able to access my ISP newsgroups with a NNTP newsreader, I have to use the Windows VPN to reach from anywhere a modem connected to this ISP network.
I found a way to force Gravity (the newsreader) to work with the VPN network interface by using ForceBindIP.
This seems to work... (is there a simpler way ?)
To be certain, could SI show me if the gravity process truly uses the proper  IP address, (those dedicated to the VPN)?
Thanks

**Comment by dmex** [comment]
> This seems to work... (is there a simpler way ?)

You need to configure the interface metric (aka priority) for each adapter:

![image](https://user-images.githubusercontent.com/1306177/211174007-385dbdde-8eb8-461b-bf1e-0ab02d91d8da.png)

Set the metric for the VPN adapter to 1 and all other adapters a higher number (2,3,4,5 etc...) and the VPN adapter (lower number) becomes high priority (the default outgoing connection). You need configure the metric for all the adapters making sure the VPN has the lower number for this configuration to work: https://www.google.com/search?q=interface+metric+windows+10+11


> could SI show me if the gravity process truly uses the proper IP address, (those dedicated to the VPN)?

Yes. The application will have local addresses matching the IP address of the VPN. If the network tab shows any application with the local address identical to the VPN connection then the program is using the VPN connection:

![image](https://user-images.githubusercontent.com/1306177/211173951-89cde49b-e74d-4bf0-9389-9b8e01fb0a42.png)
