### ISSUE TITLE
Run as Trusted Installer on system startup

### ISSUE THREAD

**Issue by MadProbe** [winsiderss/systeminformer#1563]
### Description of the feature, modification, idea or suggestion

I would be happy if System Informer could start up automatically as trusted installer on user log on.
This could co-exist with current Enable Run As Admin flag in settings.

**Comment by dmex** [comment]
The TrustedInstaller service is created in session 0 while the current user is session +1 and creating cross-session processes requires modifying the window station and desktop security granting Everyone access. System Informer currently requires user interaction before making changes to the desktop security descriptor making it incompatible to launch as TrustedInstaller after startup.

If you need to start applications with TI at startup then dedicated software like NSudo/NanaRun is better at creating systeminformer.exe with TrustedInstaller (they change the security descriptors automatically without user interaction) 👍 
https://github.com/M2TeamArchived/NSudo/
https://github.com/M2Team/NanaRun

**Comment by MadProbe** [comment]
Thank you very much!
