### ISSUE TITLE
Position recovery

### ISSUE THREAD

**Issue by alabotski** [winsiderss/systeminformer#1568]
### Brief description of your issue

Incorrectly restores the position when using the function Snap
https://support.microsoft.com/en-us/windows/snap-your-windows-885a9b1e-a983-a3b1-16cd-c531795e6241

### Steps to reproduce (optional)

1. Open SI
2. Snap it to left side
3. Close SI
4. Open SI
5. It restores not the last position, but the penultimate one

### Expected behavior (optional)

Memorized the position

### Environment (optional)

```shell
SI 3.0.5727
Win 10 19045.2486
```

**Comment by dmex** [comment]
Every application for Windows has this exact same problem because Windows doesn't allow applications to query the snap location of the window.
