### ISSUE TITLE
Error build one plug-in: HardwareDevices

### ISSUE THREAD

**Issue by Avtroman** [winsiderss/systeminformer#1569]
### Brief description of your issue

Error: not found definitions: DEVPKEY_Device_FirmwareVendor

**Comment by Biswa96** [comment]
DEVPKEY_Device_FirmwareVendor is defined in devpkey.h header file. Please use the latest official Windows SDK from here https://developer.microsoft.com/en-US/windows/downloads/windows-sdk/


```
$ grep -ir DEVPKEY_Device_FirmwareVendor
10.0.22621.0/shared/devpkey.h:DEFINE_DEVPROPKEY(DEVPKEY_Device_FirmwareVendor,           0x540b947e, 0x8b40, 0x45bc, 0xa8, 0xa2, 0x6a, 0x0b, 0x89, 0x4c, 0xbd, 0xa2, 26);   // DEVPROP_TYPE_STRING
```
