### ISSUE TITLE
Process Hacker 2 driver issue

### ISSUE THREAD

**Issue by skepticologist** [winsiderss/systeminformer#1575]
I downloaded and installed Process Hacker 2 from sourceforge.net earlier this afternoon. It started as expected and appears to be fully functional, but I received the attached error message regarding the driver kprocesshacker.sys. I have checked Windows Defender and Malwarebytes and can find no indication that either of them is blocking the driver. Please let me know how to resolve this issue. Thanks.

![230124 Driver Error Message](https://user-images.githubusercontent.com/35746296/214433379-780ad7c1-9d18-4fcc-b4eb-c8d7d84a1cec.png)

**Comment by Biswa96** [comment]
Please download the latest systeminformer (previously processhacker) from this page https://systeminformer.sourceforge.io/nightly.php

**Comment by jxy-s** [comment]
Duplicate: https://github.com/winsiderss/systeminformer/issues/997
