### ISSUE TITLE
Unhandled `STATUS_NOT_FOUND` exception occurs upon right-clicking a column header in PE Viewer

### ISSUE THREAD

**Issue by integerbang** [winsiderss/systeminformer#1576]
### Brief description of your issue

A setting named `EnableThemeAcrylicSupport` was added to System Informer [last week](https://github.com/winsiderss/systeminformer/commit/cfdc49ebcb73ba039d4e35ca1c3a84f486a329b9). The changes made within the relevant commit appeared later in the latest nightly build (based on [`c665ab86`](https://github.com/winsiderss/systeminformer/commit/c665ab86fc176029309a9da15fb6dca64e19aa57)), where PE Viewer now stops working upon right-clicking a column header.

This issue is presumably due to `phlib` assuming the setting to be present when [`PhEMenuToHMenu` attempts to retrieve it](https://github.com/winsiderss/systeminformer/blob/cfdc49ebcb73ba039d4e35ca1c3a84f486a329b9/phlib/emenu.c#L459), which doesn't appear to be the case in PE Viewer.

### Steps to reproduce (optional)

1. Open PE Viewer and select an executable file.
2. Go to any page with a tree view in it.
3. Right-click any of the column headers in the tree view.

### Expected behavior (optional)

A context menu should be shown.

### Actual behavior (optional)

An unhandled `STATUS_NOT_FOUND` exception gets raised by `PhGetIntegerStringRefSetting`.

### Environment (optional)

```
System Informer 3.0.5847
Windows 10 November 2021 Update (OS Build 19044.2486)
```

**Comment by Biswa96** [comment]
Agree. I can reproduce the issue in my system.

![image](https://user-images.githubusercontent.com/31443074/214497757-46e66b5a-59ec-4a72-bd5c-74315cd9df9d.png)
