### ISSUE TITLE
[Solved] <CTRL+SHIFT+ESC> to show main window (like ProcessHacker)?

### ISSUE THREAD

**Issue by SanderBouwhuis** [winsiderss/systeminformer#1579]
### Description of the feature, modification, idea or suggestion

I switched from ProcessHacker to SystemInformer, but I'm dearly missing the ability to press <CTRL+SHIFT+ESC> to show the window.
Also, it used to replace TaskManager.

Is there a setting I should set to activate this, or is this a missing feature?

**Comment by TheEragon** [comment]
![image](https://user-images.githubusercontent.com/5801389/215039806-c985fbca-cc49-4827-b67b-f2a686dfd3d5.png)

**Comment by SanderBouwhuis** [comment]
@TheEragon 
Ooooooooh... I'm an idiot (although there are admittedly many options).
Thanks a bunch for the help!
