### ISSUE TITLE
Color Highlighting for Jobs not working

### ISSUE THREAD

**Issue by GanbaruTobi** [winsiderss/systeminformer#1582]
### Brief description of your issue

When activating the color for jobs, nothing gets marked with color.

Here, compare Process Explorer and System Informer:

![grafik](https://user-images.githubusercontent.com/15239745/215354042-92b090c0-b184-458d-a0c4-59e7b5515dff.png)

### Steps to reproduce (optional)

System -> Options -> Highlighting -> Tick Jobs. View Process

### Environment (optional)

```shell
3.0.5872 (9e70b20)
```

**Comment by Biswa96** [comment]
Job highlighting is working fine in my system. Here is a screenshot

![image](https://user-images.githubusercontent.com/31443074/215354357-4bc3898e-5b9a-4981-9923-b653a8341e7c.png)

**Comment by dmex** [comment]
> When activating the color for jobs, nothing gets marked with color.

Job highlighting requires a kernel driver. You'll see a `+` symbol in the window title when the driver is enabled but your screenshot shows it's currently disabled.

You either need to enable the kernel driver or alternatively add the "Job Object Id" column to the processes list.
