### ISSUE TITLE
"Insecure Location" warning appears when restoring default task manager

### ISSUE THREAD

**Issue by leumasme** [winsiderss/systeminformer#1594]
### Brief description of your issue

Insecure Location warning appears when restoring the default task manager.

Seems to have been introduced 7 days ago by https://github.com/winsiderss/systeminformer/commit/7d19095d9c0eda2c922909b515f42a8534dc3fed

### Steps to reproduce (optional)

- Set System Informer as Default Task Manager
- Restore Default Task Manager from within System Explorer
- Observe warning when you're trying to _restore the default_ task manager

### Expected behavior (optional)

Warning should appear when overwriting Task Manager (_i guess_), but not when restoring it

### Actual behavior (optional)

Warning appears when restoring default Task Manager

### Environment (optional)

```shell
System Informer nightly 3.0.5974
```

**Comment by dmex** [comment]
Thanks, fixed 👍
