### ISSUE TITLE
Status Bar: Process, Handles, Threads sometimes shows 0 for all three

### ISSUE THREAD

**Issue by Almighty188** [winsiderss/systeminformer#1595]
### Brief description of your issue

The Status Bar: Process, Handles, and Threads sometimes will show 0 for all three at the same time and then revert back to the actual count.  

### Steps to reproduce (optional)

Have System Informer main window opened with Customized Status bar showing the items:
Number of processes, Number of threads, Number of Handles shown

### Expected behavior (optional)

It is supposed to show the correct count

### Actual behavior (optional)

It shows the correct count for all three but once in awhile, all three will show 0 at the same time.  

System Informer nightly v3.0.5974
Windows 11 Profession Edition x64 22H2 Build 22623.1250

### Environment (optional)

```shell
System Informer nightly v3.0.5974 and earlier nightly builds
Windows 11 Profession Edition x64 22H2 Build 22623.1250
```

**Comment by dmex** [comment]
Does the System Information > CPU window also show 0?

![image](https://user-images.githubusercontent.com/1306177/218827284-54f8ba49-03bd-4895-b6fb-90b6a4459201.png)

**Comment by Almighty188** [comment]
> 

How do I actually get that window to show up?

**Comment by dmex** [comment]
Click one of those graphs to show the advanced details

**Comment by Almighty188** [comment]
Thanks, this is what it shows currently:
![image](https://user-images.githubusercontent.com/78993393/218928258-23e1c96e-f853-4046-939a-21aa9f638bbf.png)

**Comment by dmex** [comment]
Is this an official build downloaded from here or did you download from somewhere else?

**Comment by Almighty188** [comment]
All official builds as it happened with all the nightly builds https://systeminformer.sourceforge.io/nightly.php where I got the v3.0.5988 when this was initially reported, the screenshot in the last post is actually from v3.0.6043 from https://github.com/winsiderss/si-builds/releases

**Comment by dmex** [comment]
I can't reproduce this and it isn't possible for these counters to be zero.


Your screenshot shows missing borders for these windows:

![image](https://user-images.githubusercontent.com/1306177/221498896-e6ec6182-c3a9-413e-b7a3-66d952c92789.png)

There should be borders like these:

![image](https://user-images.githubusercontent.com/1306177/221498993-6ec029a0-f4d1-42a3-a5b4-a26007c29116.png)

The problem is either:
1) You've installed some some third party software which is corrupting the UI.
2) Your windows installation is corrupted.
3) You have a rootkit.

**Comment by Almighty188** [comment]
You are right that it isn't possible for these counters to be zero because Windows Task Manager does show actual numbers in the same screenshot.  It seems like the last screenshot is missing the borders as you had mentioned unless Snagit messed with the screenshot but the earlier comment https://github.com/winsiderss/systeminformer/issues/1595#issuecomment-1430734497 does have the borders.  Could the problem also be related to the system having a large number count for those counters that after the number exceeds a certain number, it will just display 0?   As of now under System Informer v3.0.6226:

![image](https://user-images.githubusercontent.com/78993393/223314222-9afed1c5-6595-4fc2-92b7-35f152cdc47f.png)

I also do have gadgets running which does gather the same info via WMI so not sure if it's related or not as it would be related to problem #1.  

![image](https://user-images.githubusercontent.com/78993393/223314542-c3681919-ce01-4de7-b189-441084c84b67.png)

**Comment by dmex** [comment]
>  Could the problem also be related to the system having a large number count for those counters that after the number exceeds a certain number, it will just display 0?

No the processor resets any values that are too large then continues incrementing the value. The current maximum is about 4 billion and if you added 1500 then it'll show 500.

> last screenshot is missing the borders as you had mentioned

Are you able to create a dump file and upload it here or email it? Right-click systeminformer.exe on the process list and select Create Dump File while these values are zero and we can check why they're not getting updated.

**Comment by Almighty188** [comment]
Actually, I added the Handles column and after 3 days of uptime - I sorted the Handles by largest to smallest, don't have screenshots for both now but I was at 2,000,000+ (2 Million) handles, there were two offending processes:
msmoney.exe which is Microsoft Money Sunset Edition with 700,000 handles
DellFanManagement.exe which is a utility to manage the Dell laptop fan speed with 224,000 handles.  
![image](https://user-images.githubusercontent.com/78993393/224653540-79d4f164-3ab6-4d73-8748-38febf07c069.png)
![image](https://user-images.githubusercontent.com/78993393/224653661-445ab0c4-f91d-44aa-acfa-fcb3023da7c5.png)

I manually closed msmoney.exe since it backs up the data which takes a minute and then started it again 
while I clicked on restart on the DellFanManagement.exe and basically the total handles systemwide went back to 200,000 and then the counters for Processes, Threads, and Handles  in SystemInformer works again.  

The next time it happens which should be within a few days, I will create the dump file and submit it.

**Comment by Almighty188** [comment]
I just updated to System Informer v3.0.6303 nighty build a few minutes ago, current system uptime is 23 hours and 15 minutes.
![image](https://user-images.githubusercontent.com/78993393/224929353-4af832de-eb64-4900-a414-9206b31c5f97.png)

When I tried to create the dump file, it prompts to Save as and then it tries to create minidump and then did the following:
![image](https://user-images.githubusercontent.com/78993393/224929190-1b85cb06-a76b-4167-b215-2595a9d2d9d1.png)

After closing and manually starting msmoney.exe and restarting DellFanManagement.exe -  Processes, Threads, Handles will show 0 for a few minutes and then show the correct count and alternate between the correct counter without changing and 0 and then a few more minutes will return back to normal where it shows the counter:
![image](https://user-images.githubusercontent.com/78993393/224931912-f177e35d-7164-4b84-9acc-badce2428abd.png)

**Comment by dmex** [comment]
> Microsoft Money Sunset Edition with 700,000 handles
> Dell laptop fan speed with 224,000 handles.

Yep those programs are responsible for your handle leaks. You should report the handle leaks for the Dell tool on their github.

> When I tried to create the dump file, it prompts to Save as and then it tries to create minidump and then did the following:

Try creating the dump for systeminformer.exe using Windows Task Manager?

**Comment by Almighty188** [comment]
I already reported the problem on their forum thread at https://notebooktalk.net/topic/20-dell-fan-management-%E2%80%94-software-for-controlling-the-dell-laptop-fan-speed/page/4/ over4 days ago which is newer as the github one does not have the GUI interface and only runs on the command line.  

When it happens again, I'll try creating the dump for systeminformer.exe using Windows Task Manager.  I thought the dump if it had worked from System Informer might have been more detailed.

**Comment by Almighty188** [comment]
It's showing all zeroes now, Creating a dump on SystemInformer.exe from System Informer didn't work as just like last time, it said Invalid Function.  Successfully created the dump file on SystemInformer.exe in Windows Task Manaager which is available for download here:
https://krakenfiles.com/view/TGAcoDfqd8/file.html

**Comment by Almighty188** [comment]
Here is a dump file created by System Informer v3.0.6433 while it's showing all zeros which can be downloaded at:
https://krakenfiles.com/view/LwJ6F0kYOd/file.html

![image](https://user-images.githubusercontent.com/78993393/229328139-6b66e7ce-2a71-4532-8024-49768afa1a79.png)

**Comment by Almighty188** [comment]
Seems to be related to the number of handles on the system since once I kill the processes when then handles are high on those two processes, the problem is fixed.

**Comment by dmex** [comment]
Fixed
