### ISSUE TITLE
silent installation mode not working

### ISSUE THREAD

**Issue by bibimagic** [winsiderss/systeminformer#1597]
### Brief description of your issue

Hi,
I was able to install System Informer in silent mode until v3.0.5727 by running:
`systemformer-3.0.5727-setup.exe -silent`.
Since v3.0.5847, this does not work anymore.

How else can I install the application in silent mode?
Or, is this option expected to be replaced in future versions of System Informer?

Thank you.

### Environment

```shell
System Informer nightly builds
Windows 10 / 11
cmd / pwsh
```

**Comment by dmex** [comment]
> Since v3.0.5847, this does not work anymore.

The setup has never supported -silent mode?

See #759
