### ISSUE TITLE
Network addresses aren't resolved

### ISSUE THREAD

**Issue by gittest6** [winsiderss/systeminformer#1598]
Despite checked option "Resolve network addresses", I always see IP addresses in "Remote address" column of "Network" tab. I know that at least many of them are in fact resolvable.
I'm using System Informer version 3.0.5988 on Windows 10 and 11, but in all previous versions of System Informer I observed the same behavior.
What can be the cause?

**Comment by dmex** [comment]
>  I always see IP addresses in "Remote address" column of "Network" tab. I know that at least many of them are in fact resolvable.

The remote address column only shows addresses. Hostnames are shown in the `Remove hostname` column?

**Comment by gittest6** [comment]
Indeed, thank you. Process Hacker shows both IP addresses and host names in "Remote address" column, it got me confused.
