### ISSUE TITLE
Unable to commit detours transaction.

### ISSUE THREAD

**Issue by Upgrad3** [winsiderss/systeminformer#1599]
I get this error when using the dark theme every single time i start System Informer. clicking close allows you to use normally but the error pops up upon each launch of the application. This only happens when the dark theme support is enabled.
Happened with the past few nightlys of System Informer.

My OS is windows 11 22H2 (x64)

Probably nothing to do with it but i notice there is a x86 folder inside the x64 program files folder, is this necessary on a x64 system could it be causing an issue?

![image](https://user-images.githubusercontent.com/16259892/218081913-5c069816-c08a-4e0b-87a8-378a45d0f736.png)

**Comment by ge0rdi** [comment]
See #1572.
Should be _fixed_ in latest nightly (I have 3.0.5988).

**Comment by ge0rdi** [comment]
Interesting. It works for me without a problem on the same system.

Could you check if you have `HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SystemInformer` registry key present? And eventually what's inside it?

**Comment by Upgrad3** [comment]
It is present:
![image](https://user-images.githubusercontent.com/16259892/218228352-d8870b85-dda8-42c4-b24e-9117ac4b4dfb.png)

**Comment by ge0rdi** [comment]
> Deleting the mitigation options qword works. I am no longer seeing the issue.

Cool.

@dmex 
Maybe installer should remove `MitigationOptions` value?
Now that you removed setting that controlled it.

OTOH it will prevent custom mitigation settings to persist across `SystemInformer` upgrades (not sure if wanted).

**Comment by Upgrad3** [comment]
Is it necessary to include the x86 exe with the x64 version ? Just curious as to why its included in the x86 folder within the x64 it it ever used on a x64 system ?

**Comment by ge0rdi** [comment]
> Is it necessary to include the x86 exe with the x64 version ?

Yes.
x86 executable is used for certain tasks related to 32bit processes (like get heap info, etc) that are impossible (or quite hard) to do from 64bit process.

**Comment by Upgrad3** [comment]
Thank you, that makes sense now

**Comment by dmex** [comment]
@ge0rdi 

> Maybe installer should remove MitigationOptions value?

It was originally removing the values... but you asked in the other issue:

> Could you at least keep the mitigation option (even disabled by default and in advanced options), so that it can be enabled by those who want it?

So the deletion part was removed so you could keep using the option when enabled using powershell and other tools.

**Comment by StacktraceException** [comment]
The problem is not solved. still exists on newest versions.
