### ISSUE TITLE
Add back the `-settings` CLI flag

### ISSUE THREAD

**Issue by MatejKafka** [winsiderss/systeminformer#1602]
### Description of the feature, modification, idea or suggestion

ProcessHacker used to have a `-settings` flag to set a custom path to the settings file, but it was [removed](https://github.com/winsiderss/systeminformer/commit/96708310258729d7aedaf5ca534e286ab9788cea) 5 months ago. I've been using the option in the previous versions. Why was it removed? Could you add it back?

**Comment by dmex** [comment]
Latest canary build
