### ISSUE TITLE
hide processes signed by microsoft

### ISSUE THREAD

**Issue by wincmd64** [winsiderss/systeminformer#1604]
### Description of the feature, modification, idea or suggestion

pls add to View -> hide processes signed by microsoft

**Comment by dmex** [comment]
View > Hide System Processes in latest nightly 👍

**Comment by enervated** [comment]
I just installed 3.0.6210, but View > "Hide system processes" doesn't hide most of my system processes. It does hide cmd.exe and maybe some others, but it leaves most system processes showing, such as csrss.exe, svchost.exe, SecurityHealthService.exe, SgrmBroker.exe, wininit.exe, etc.

I'm on Win10 22H2.

**Comment by dmex** [comment]
>  doesn't hide most of my system processes

The filter wasn't processing at startup. I've updated the nightly build with a fix.

**Comment by enervated** [comment]
The option is to hide system processes, not to blanket-trust processes. And then you have lsass.exe, SecurityHealthService.exe, services.exe, SgrmBroker.exe, csrss.exe, wininit.exe, smss.exe, etc. which are also still not hidden.

**Comment by dmex** [comment]
@enervated Works for me?

![image](https://user-images.githubusercontent.com/1306177/221735135-ef0ef08b-f715-453b-b28f-d80b63800b30.png)

If you have disabled signature checking (Options > Check images for digital signatures) then it can't properly exclude system processes and instead tries to exclude based on file version information and the version filter only supports English.

**Comment by enervated** [comment]
Thanks, but I have always had "Check images for digital signatures" and "Check services for digital signatures" enabled.

**Comment by dmex** [comment]
> the version filter only supports English

^ this would be the issue? @enervated

**Comment by enervated** [comment]
I only have "English (United States)" installed in Windows 10 and have never used any other language.

**Comment by wincmd64** [comment]
![2023-06-08 12_24_40-System Informer  KRASNOVA_admin](https://github.com/winsiderss/systeminformer/assets/104612222/0f9dd2ce-d6c5-4db1-a828-439ef2888111)

v3.0.6550 (win11)

still tons of svchost.exe

**Comment by myshzzx** [comment]
still tons of svchost.exe
3.0.7310
win11 22H2

**Comment by sequencerr** [comment]
I there option to manually specify filter? I don't want to hide system process, but, for example only "svhost.exe"

**Comment by enervated** [comment]
hurr durr unsubscribe
