### ISSUE TITLE
The CPU graph in the toolbar shows only green.

### ISSUE THREAD

**Issue by Alex-S1** [winsiderss/systeminformer#1605]
### Brief description of your issue

![green_CPU_graph-fs8](https://user-images.githubusercontent.com/61148267/219348702-be56c465-1401-426f-a70a-d4f1fe708ce9.png)

### Environment (optional)

```shell
System Informer 3.0.6058 (e373c10) 64-Bit
Windows 10.0.19044.1288 Pro 64-Bit
```

**Comment by Alex-S1** [comment]
And correct the year in the window About.

**Comment by dmex** [comment]
Thanks fixed 👍
