### ISSUE TITLE
w32.org

### ISSUE THREAD

**Issue by bringrainfire** [winsiderss/systeminformer#1610]
A quick search about w32.org has lead me here today to let you know that the server seems to be down. No one's able to access the website at all on any browser. I'm not sure if this is your domain or if you have the contacts to let them know about this but that would be great if you could!

**Comment by MagicAndre1981** [comment]
this is the new website for the project:

https://system-informer.com/

**Comment by bringrainfire** [comment]
amazing thank you!
if there a link to the clear standby memory program or is this now defunct.

**Comment by MagicAndre1981** [comment]
ok, I've [uploaded the only version I have to my OneDrive as 7z file](https://1drv.ms/u/s!AtziW2MYxY8SmZoX5UHz7vzWz_CpZQ?e=KlEOih). THe Systeminformer UI also has an option to clear the list, but not via commandline.

**Comment by bringrainfire** [comment]
ok cool, I've got a newer version from 1/12/2022 backed up here -> https://ufile.io/2pqpl28c

**Comment by bringrainfire** [comment]
I was basically just running it from the task scheduler to clear the standby space. I was having issues with the c and c++ compiler where it wouldn't count the standby memory as useable free memory and would fail/crash when compiling large code files. I'll be checking out your tools for sure though!

**Comment by MagicAndre1981** [comment]
they are both the same.

**Comment by jxy-s** [comment]
I recognize this isn't an automated option but you can do this in System Informer here:
![image](https://user-images.githubusercontent.com/11687482/222062626-f7e0f212-3fab-4fe9-a18a-bd702bd2aba6.png)

Sounds like ya'll are sorted either way. Going to close this.
