### ISSUE TITLE
Little request

### ISSUE THREAD

**Issue by rxznve** [winsiderss/systeminformer#1611]
### Description of the feature, modification, idea or suggestion

Please add a check for child processes and if there are none, remove the "Terminate Tree" and "Suspend Tree" options from the context menu ;)

**Comment by Biswa96** [comment]
You can already see if a process has child process, click on the 'Name' column header to or three times.

**Comment by Vasilich** [comment]
@Biswa96 topicstarter haven't said that it is impossible to see whether process has children or not. He asked about hiding unneeded/not working menu items automatically.

**Comment by dmex** [comment]
Added with #1612
