### ISSUE TITLE
WinGet support

### ISSUE THREAD

**Issue by coconutbird** [winsiderss/systeminformer#1613]
### Description of the feature, modification, idea or suggestion

While setting up my system I always install process hacker/system informer and I was wondering if it was planned to add to WinGet so it's easy for people to install via scripting or searching on https://winstall.app/

**Comment by Kamilkampfwagen-II** [comment]
Chocolatey support would also be nice.

**Comment by Masamune3210** [comment]
As long as there are issues with AV detecting SI as malicious, specifically Defender, winget will never happen. One of the requirements to be added is to pass a malware scan.

**Comment by sitiom** [comment]
> As long as there are issues with AV detecting SI as malicious, specifically Defender, winget will never happen.

I just tried scanning the latest nightly build, and Defender doesn't seem to flag it. So that doesn't seem to be a problem:
![image](https://github.com/winsiderss/systeminformer/assets/56180050/caf2cec6-bc20-494b-855c-f24a6df08db5)

However, Winget support is still blocked with https://github.com/winsiderss/systeminformer/issues/759

**Comment by jxy-s** [comment]
We're now on winget 🎉 
```
winget search WinsiderSS
Name                     Id                               Version     Source
-----------------------------------------------------------------------------
System Informer          WinsiderSS.SystemInformer        3.1.24283.0 winget
System Informer (Canary) WinsiderSS.SystemInformer.Canary 3.1.24283.0 winget
```

**Comment by coconutbird** [comment]
> We're now on winget 🎉
> 
> ```
> winget search WinsiderSS
> Name                     Id                               Version     Source
> -----------------------------------------------------------------------------
> System Informer          WinsiderSS.SystemInformer        3.1.24283.0 winget
> System Informer (Canary) WinsiderSS.SystemInformer.Canary 3.1.24283.0 winget
> ```

the final step is to add this to the website - https://systeminformer.sourceforge.io/downloads
