### ISSUE TITLE
Access violation in PhpFlushProcessPropSheetWaitContextData

### ISSUE THREAD

**Issue by EggsyCRO** [winsiderss/systeminformer#1614]
### Brief description of your issue

An access violation can occur inside of PhpFlushProcessPropSheetWaitContextData, specifically, when accessing `data->ProcessItem->QueryHandle` (ProcessItem an invalid pointer).

Disassembly:
`lea     r8, [rsp+140h+ProcessInformation] ; ProcessInformation`
`mov     r9d, 30h ; '0'  ; ProcessInformationLength`
`mov     [rsp+140h+ReturnLength], r13 ; ReturnLength`
`xor     edx, edx        ; ProcessInformationClass`
`mov     rcx, [rax+48h]  ; ProcessHandle` <- Access violation happens here
`call    cs:NtQueryInformationProcess`
`test    eax, eax`

Pseudocode:
![image](https://user-images.githubusercontent.com/39103865/221390835-51a5108d-4b13-44a0-9b87-dc652427cba6.png)

Line of code:
https://github.com/winsiderss/systeminformer/blob/fd372c4d8902ed25136376df595d20381e746d84/SystemInformer/procprp.c#L575

Registers and stack dump:
https://pastebin.com/raw/kCJpTpp3

### Environment (optional)

```shell
System Informer 3.0.6170 (5a6fad1)
Windows 11 22H2
```

**Comment by dmex** [comment]
> An access violation can occur

Are you just suggesting one might occur here or did you actually crash here?

**Comment by EggsyCRO** [comment]
> Are you just suggesting one might occur here or did you actually crash here?

I crashed here, hence the register and stack dump.

**Comment by dmex** [comment]
> I crashed here

What security software do you have installed?

> hence the register and stack dump.

Are you able to upload a crash dump?

**Comment by EggsyCRO** [comment]
> What security software do you have installed?

None.

> Are you able to upload a crash dump?

I've emailed you the crash dump.

**Comment by dmex** [comment]
Fixed in latest nightly
