### ISSUE TITLE
Process elevation is not being detected

### ISSUE THREAD

**Issue by Cheatoid** [winsiderss/systeminformer#1615]
### Brief description of your issue

Recently I have upgraded from Process Hacker to System Informer.
In Process Hacker, elevated process is detected correctly and says `Process is elevated` in the tooltip; in System Informer that is not the case (it seems it doesn't detect elevation at all), moreover the Elevation column always says `N/A`. I have also run System Informer as administrator and enabled use of kernel-mode driver, and still it doesn't detect elevation.
I suspect ec0935ebe852bad2cb116b86eccbf6d761571582 to be the cause.

### Steps to reproduce (optional)

1. Run command line as administrator (<kbd>WIN + X</kbd>, `Command Prompt (Admin)`).
2. Observe that elevation is not being detected for any process in System Informer, even if you run System Informer as administrator.

### Expected behavior (optional)

A tooltip (or Elevated column) for (fully) elevated process should say that a process is elevated.

### Actual behavior (optional)

Tooltip doesn't say anything about elevation for (fully) elevated process. Elevated column always say `N/A`.

### Environment (optional)

```shell
System Informer 3.0.6170
Windows 10 x64 22H2 (19045.2486)
```

**Comment by Biswa96** [comment]
Do you mean something like this?

![image](https://user-images.githubusercontent.com/31443074/221402852-57652c28-001c-4a21-96c5-3e2a463eed90.png)

Did you check if systeminformer is running as admin and kernel mode driver is enabled?

**Comment by Cheatoid** [comment]
> Do you mean something like this?

Yes. That doesn't appear for me.

> Did you check if systeminformer is running as admin and kernel mode driver is enabled?

Guess you didn't read:
> I have also run System Informer as administrator and enabled use of kernel-mode driver, and still it doesn't detect elevation.

**Comment by OrbbQ3** [comment]
1. Have you disabled the UAC? If yes, the commit ae89d87387f5086fbaa91981be4bfabf1835b201 have changed the tooltip behavioue.
2. To the column info in the process list: Yes, there have you right with N/A. I have not made changes here.

I will provide a PR soon.

**Comment by Cheatoid** [comment]
> Have you disabled the UAC?

Confirmative.

**Comment by dmex** [comment]
> System Informer that is not the case (it seems it doesn't detect elevation at all)

There's no elevation when UAC is disabled.

> Elevated column always say N/A

N/A is correct because elevation doesn't exist when UAC is disabled.

**Comment by jxy-s** [comment]
Fixed with https://github.com/winsiderss/systeminformer/commit/6ae653cb95dee3cc68ab0373e787bce489a5ee16

Will be in next nightly.
