### ISSUE TITLE
Services untrusted but mandatory

### ISSUE THREAD

**Issue by git6578** [winsiderss/systeminformer#1617]
### Brief description of your issue

Yesterday I deleted some untrusted Service after System Informer got my attention there, it din't show any hint of being official. Turns out it was a mandatory w10 service, I was not able to recover in any way. Since it is just a handful of services that are untrusted on a vanilla Windows, could you remove this untrusted status for these? Services like MsRPC, Ntfs, exfat. This is highly misleading.

### Steps to reproduce (optional)

delete untrusted services

**Comment by jxy-s** [comment]
To confirm, @git6578, are you talking about the "Verification status" column?:
![image](https://user-images.githubusercontent.com/11687482/221626222-5bf5a946-2683-4257-9f90-12bd2d1e5b55.png)

**Comment by git6578** [comment]
in combination with the red highlighting of the entire row (indicating moderate security concerns), yes
![image](https://user-images.githubusercontent.com/32224997/221628999-67fe43f9-b9db-4af5-9634-d8b825687493.png)

**Comment by Masamune3210** [comment]
This is a wonderful example of why you should never muck around with things that can hose a system without a functional backup....

**Comment by git6578** [comment]
> This is a wonderful example of why you should never muck around with things that can hose a system without a functional backup....

Sure true, while doing it on the fly and not as a system revision, it's the thinking-fast-and-slow problem, it didn't hit my questioning radar as I trust this tool and its call-outs for many years now. of course it's a user error in the end, (as a comparison, how can you blame a user if a scam mail is forged very well?). You can try to mitigate issues on the root, which is why I am posting here, I don't think this should be flagged as Not trusted, let alone why this doesn't have a verified signature.

The fallout is quite heavier, fresh Windows did overwrite the old user folder of >100GB, I am now sitting with KaliOS and Autopsy.

when it rains it pours

**Comment by jxy-s** [comment]
I removed some assumptions in the signature verification code where we would assume there is "no signature" if we fail to access the file. We will now also show an appropriate string for the "Verification status" in the UI. The consequence, however, is if something is blocking us from accessing the file we will show a "blank" status and will not highlight "untrusted" modules. No information is probably safer than bad information in this scenario.

Changes are here: https://github.com/winsiderss/systeminformer/commit/e3c48d2248f169ece9af1212862a9d227edc39a8

Will be picked up by the next nightly.
