### ISSUE TITLE
Restart to firmware application - desktop shortcut or command?

### ISSUE THREAD

**Issue by Falcordog** [winsiderss/systeminformer#1618]
Is there a way to generate a shortcut (or via cmd) to a specific boot entry without having to execute that from the GUI 'System' menu?

**Comment by dmex** [comment]
These menus configure the [one-time boot sequence](https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/bcdedit--bootsequence). You can execute the restart from command by copying the boot identifier for the application from bcdedit then executing the /bootsequence command:

```
bcdedit /bootsequence {ID_HERE} /addfirst
shutdown /r
```

When you reboot the firmware application {ID} will be executed first and only once before the default boot order is restored.
