### ISSUE TITLE
/hidden

### ISSUE THREAD

**Issue by wincmd64** [winsiderss/systeminformer#1619]
### Description of the feature, modification, idea or suggestion

I know about option "start hidden", but I need also command line parameter "/hiden"

**Comment by dmex** [comment]
Why?

**Comment by wincmd64** [comment]
for example, using with .lnk
and btw where can i read about all command switches?

**Comment by dmex** [comment]
Oh right sounded like you were requesting something else.

> using with .lnk

`-hide` to start minimized

> where can i read about all command switches

`-help` to view the options. This was also posted on the forum which is currently offline.

**Comment by Biswa96** [comment]
> ...the forum which is currently offline.

Is it possible to use gitter or Matrix for this kind of general q&a?

**Comment by dmex** [comment]
@Biswa96 

This is why we have discord: https://discord.com/invite/k2MQd2DzC2
and discussions: https://github.com/winsiderss/systeminformer/discussions
