### ISSUE TITLE
DESCRIPT.ION

### ISSUE THREAD

**Issue by wincmd64** [winsiderss/systeminformer#1620]
### Description of the feature, modification, idea or suggestion

Pls, add DESCRIPT.ION file with a description of all files in the distribution
For example, ksi.dll - is it needed?
For what etwguids.txt?
etc

**Comment by dmex** [comment]
> description of all files in the distribution

The descriptions are already provided with the source?

> what etwguids.txt

Required for translating token and handle guids to names.

> ksi.dll - is it needed

Yes. This is part of the kernel driver. We don't include unnecessary files and any files included with the distribution are required.
