### ISSUE TITLE
collapsed processes

### ISSUE THREAD

**Issue by wincmd64** [winsiderss/systeminformer#1622]
### Description of the feature, modification, idea or suggestion

![Window](https://user-images.githubusercontent.com/104612222/221842486-3ccfd914-73cc-4d24-8c66-84d3b42ab552.png)

1) for collapsed processes should show the total number in brackets
2) for collapsed processes should show total memory
3) also show total memory must me in status bar (selected processes)

**Comment by dmex** [comment]
1) Add the `Subprocesses` column
2) Enable `Include usage of collapsed processes` in options 
3) Add `Selected process private bytes` by right-clicking the statusbar

👍

**Comment by wincmd64** [comment]
3. nothing changed

**Comment by dmex** [comment]
You need to select the values to change the total?

**Comment by wincmd64** [comment]
![2023-03-01 11_22_25-Window](https://user-images.githubusercontent.com/104612222/222097213-f03eea09-59dd-4f88-aa37-e0214b5fae6b.png)

**Comment by Lumbago1337** [comment]
Any plans to just add a new Column, like it is in Process Explorer? (named Tree CPU Usage)
![procexp64_2023-04-06_17-00-44](https://user-images.githubusercontent.com/59123498/230421144-dd180dfc-f91f-4f9e-a4b7-9d8ff50c2d6d.png)
That way you don't have to collapse anything and still see the Subprocesses. Could also be done with GPU, Memory and Network.

**Comment by dmex** [comment]
@Lumbago1337 

Reopening an old topic to discuss something unrelated is considered bad form. 

> Any plans to just add a new Column

Please create a new issue or new discussion so other users have the opportunity to contribute to the discussion. If I don't add the feature then someone else can submit a pull request and implement it but how will they know unless someone creates an issue or discussion? 😉
