### ISSUE TITLE
No unsupported system alert

### ISSUE THREAD

**Issue by Soda5601** [winsiderss/systeminformer#1626]
### Brief description of your issue

There is no unsupported system alert.

### Steps to reproduce (optional)

Turn on kernel mode in the latest version of Windows 11

### Expected behavior (optional)

An alert appears tells your system is not supported

### Actual behavior (optional)

Nothing happens

### Environment (optional)

SI 3.0.6226, Windows 11 Latest

**Comment by Biswa96** [comment]
Would you like to share a screenshot of that system alert?

**Comment by Soda5601** [comment]
I think there is a popup that shows your system is not supported, and it is not showing up rn.

**Comment by dmex** [comment]
> Code do check whether the system is supported

32-bit XP and Vista are not supported. 

> An alert appears tells your system is not supported

You probably executed the 32bit binaries which is not supported.

> There is no unsupported system alert ... Windows 11 Latest

Windows 11 is supported and there are no alerts.

**Comment by Soda5601** [comment]
I mean the kernel mode unsupported notification, not the software

**Comment by dmex** [comment]
> If you click "kernel mode" in windows 11 and restart, driver not loaded and no warnings.

There's no prompt because the driver supports Windows 11 but doesn't support insider builds and insider builds are Windows 11.
