### ISSUE TITLE
Don't readd desktop icon on upgrade

### ISSUE THREAD

**Issue by mmozeiko** [winsiderss/systeminformer#1629]
### Description of the feature, modification, idea or suggestion

When System Informer asks to upgrade to newer installation it always adds desktop icon, even if I don't want it.

I prefer not to have desktop icon for it, so I have deleted it. But on every upgrade the icon comes back. Please consider installer to differentiate if this is upgrade or new installation, and do not add desktop icon on upgrades.

It is reasonable to add desktop icon for new installation, but is gets super annoying to deal with it on every upgrade.

**Comment by MagicAndre1981** [comment]
yes, this also confused me all time

**Comment by dmex** [comment]
> differentiate if this is upgrade or new installation

It already differentiates installations and upgrades but the function responsible for updating was copy/pasted/based on the same code used for installing and the line of code to create shortcuts when installing wasn't removed for updates.

> But on every upgrade the icon comes back

Fixed in latest nightly👍

**Comment by MagicAndre1981** [comment]
> Fixed in latest nightly👍

nope, I still got the new shortcut on desktop when updating from 3.0.6295 to 3.0.6303
