### ISSUE TITLE
.net color

### ISSUE THREAD

**Issue by wincmd64** [winsiderss/systeminformer#1633]
### Brief description of your issue

![2023-03-08 15_38_31-Свойства_ Greenshot exe (1764)](https://user-images.githubusercontent.com/104612222/223727602-4cefd245-81cc-4660-8ac1-444ac3df870c.png)
process is .net but color doesn't changed

### Environment (optional)

```shell
3.0.10791.6264
win7
```

**Comment by wincmd64** [comment]
OK

**Comment by dmex** [comment]
Fixed in latest nightly build 👍
