### ISSUE TITLE
selected COLLAPSED processes in status bar

### ISSUE THREAD

**Issue by wincmd64** [winsiderss/systeminformer#1634]
### Brief description of your issue

click on selected COLLAPSED processes in status bar show only first one
![2023-03-08 15_38_55-System Informer  KRASNOVA_admin  (Administrator)](https://user-images.githubusercontent.com/104612222/223728909-269e1559-9cf6-41e6-bcf2-88755bd56e7a.png)

### Environment (optional)

```shell
3.0.10791.6264
win7
```

**Comment by dmex** [comment]
Added with latest nightly build 👍

**Comment by wincmd64** [comment]
nothing changed
tested in win7 and win10

**Comment by dmex** [comment]
Fixed
