### ISSUE TITLE
-hide on win7 doesn't work

### ISSUE THREAD

**Issue by wincmd64** [winsiderss/systeminformer#1639]
### Brief description of your issue

doesn't work on win7
v3.0.10822.6295

**Comment by dmex** [comment]
-hide requires tray icons enabled 

> doesn't work on win7

I checked win7 and it works so you've probably disabled the tray icons?

**Comment by wincmd64** [comment]
**SystemInformer.exe -hide**
tray icon is enabled

It work on win10, but doesn't work on win7 (x32)

**Comment by dmex** [comment]
I tested win7 and it works?

**Comment by wincmd64** [comment]
![Запись_2023_03_12_09_34_42_997](https://user-images.githubusercontent.com/104612222/224530954-f49ce49d-3aca-4f8c-8cf0-ebd42953f2a7.gif)

**Comment by wincmd64** [comment]
I figured out - happened when "start as admin" option enabled

**Comment by dmex** [comment]
Start as admin uses Task Scheduler and doesn't support command line parameters. So instead you have to use the Options > General > Start hidden checkbox.
