### ISSUE TITLE
Process termination doesn't work in some circumstances and is usually too slow even when it works

### ISSUE THREAD

**Issue by KOLANICH** [winsiderss/systeminformer#1642]
### Brief description of your issue

<details>

<summary>Some offtop</summary>

I was testing OneCoreAPI on Windows XP (a compatibility layer allow run some Windows Vista to 10 software on it). It turned out `Process Explorer` (the one for XP) started crashing on it, so I have started looking for alternatives. One of the "alternatives" was ProcessHacker. After the testing (the results were unsatisfying) I reverted the system back.

</details>

It turns out its `Terminate` feature doesn't work like the one of Sysinternals Process Explorer. 

### Steps to reproduce (optional)

Try to terminate a process and feel the delay.

### Expected behavior (optional)

When I use Process Explorer, when I terminate a process, it is just killed within a short amount of time.

### Actual behavior (optional)

When I use Process Hacker to kill a hung process, nothing happens and I have to use OS task manager to kill it. When I use it to kill a non-hung process, it kills it after quite some time.

### Environment (optional)

* Windows XP SP3 (both with OneCoreAPI and vanilla, but terminating hung processes was only tested on OneCoreAPI (the hung process is any WinPython 3.6 run under Depencency Walker instrumentation, in that case both DependencyWalker and python.exe hung))
* ProcessHacker 2.38
* Pentium 4 CPU (32 bit one) with hyper-threading

**Comment by dmex** [comment]
> It turns out its Terminate feature doesn't work like the one of Sysinternals Process Explorer.

There is no difference. They both call [TerminateProcess](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-terminateprocess) with the same exit code (1). 

> When I use Process Hacker to kill a hung process, nothing happens and I have to use OS task manager 

Task Manager and Process Hacker are both using [TerminateProcess](https://learn.microsoft.com/en-us/windows/win32/api/processthreadsapi/nf-processthreadsapi-terminateprocess)... If it's not working then you've corrupted the OS.

> Windows XP SP3 

We don't support XP and v2.38 has the terminator feature so maybe use that instead:

![image](https://user-images.githubusercontent.com/1306177/224523909-ebe20b26-85c2-490f-9f64-92b47a5de164.png)
