### ISSUE TITLE
Can't update to newest nightly because of error: „Unable to commit detours transaction”. Kernel driver error too.

### ISSUE THREAD

**Issue by StacktraceException** [winsiderss/systeminformer#1646]
The error message goes on to say that there were too strict virtual memory and/or page file constraints. I have checked these settings in Windows, and the settings are all default. I also tried to run the standalone setup file (with System Informer fully closed) and it seems to finish but do nothing. 

I am not sure whether this is maybe somehow related (?) but there is a can't load Kernel driver error too. (Which says that the certificate has been rejected by its issuer). 

The build I currently have is 3.0.4953. I could try removing the program and reinstalling, but I don't want to lose all the settings.
How do I backup all the settings?

Regards :).

**Comment by dmex** [comment]
The mitigation checkbox in settings was removed and you need to delete the registry key from
`HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows NT\CurrentVersion\Image File Execution Options\SystemInformer.exe`

Right-click and delete:
![image](https://user-images.githubusercontent.com/1306177/225960656-1fa6d4ab-ef49-450a-86d9-dbdcc3d2b816.png)

**Comment by StacktraceException** [comment]
Can someone please explain why is this recommended as a solution to this problem? This did not  work. However, this time I have had an error of window class already exists or smth instead after update.

**Comment by dmex** [comment]
> Can someone please explain why is this recommended as a solution to this problem?

Because this option was removed:

![image](https://user-images.githubusercontent.com/1306177/228134287-c36e3a35-cda2-48df-9fd0-efc33c18ce82.png)

It configured those registry keys causing the detours errors hence removing the key fixes the failures.

**Comment by StacktraceException** [comment]
But in the version that I have, this option still exxists, although it showed an error when was deselected.
