### ISSUE TITLE
3.0.6328  Unable to load the driver

### ISSUE THREAD

**Issue by wnstngs** [winsiderss/systeminformer#1647]
Windows Defender has quarantined SystemInformer.exe with the reason "Trojan:Win32/Wacatac.H!ml". I canceled this action, however, the driver stopped loading. I reinstalled SystemInformer and now get the message "KSystemInformer could not be loaded. KSystemInformer does not support your operating system or could not be loaded. Make sure System Informer is running with administrative privileges." running as admin.

System Informer
Version: 3.0.6328 (8903fe9)

**Comment by Vasilich** [comment]
@wnstngs 
check https://github.com/winsiderss/systeminformer/issues/1630 and https://github.com/winsiderss/systeminformer/issues/1631

**Comment by wnstngs** [comment]
I'm sure it's a false positive. The problem is that I can't install the driver anymore.

**Comment by dmex** [comment]
> I can't install the driver

@wnstngs This specific error is when files are missing. Check defender isn't quarantining the files.

**Comment by wnstngs** [comment]
> > I can't install the driver
> 
> @wnstngs This specific error is when files are missing. Check defender isn't quarantining the files.

I followed this guide https://learn.microsoft.com/en-us/microsoft-365/security/defender-endpoint/restore-quarantined-files-microsoft-defender-antivirus?view=o365-worldwide and came to the conclusion that none of the files associated with System Informer are in quarantine.

**Comment by wnstngs** [comment]
> Defender doesn't generally restore files and will keep deleting them until you view the protection history and manually allow the file or whitelist the install directory.
The defender no longer swears at the file and Protection History is empty.

> The files are missing or something is blocking the files. If you've tried reinstalling and it's still happening then something is still deleting the files or blocking file access.
I tried both the version with the installer and the portable version where you can see that all the files are present, including the driver. Still "KSystemInformer could not be loaded." and "Unable to open the thread. Access is denied." I'm sure that I run System Informer as admin.

> Run Process Monitor (https://learn.microsoft.com/en-us/sysinternals/downloads/procmon)
I tried using ProcMon to inspect events, but I couldn't find anything related to the error / driver.

**Comment by dmex** [comment]
@wnstngs 

Is `EnableKphWarnings` set to 1?

> I tried using ProcMon to inspect events, but I couldn't find anything related to the error 

You might need to reboot and/or delete everything from the Filter menu > Filter window since the defaults exclude System

**Comment by dmex** [comment]
@wnstngs 

Looks like I was wrong about this error message and `This specific error is when files are missing.` was not correct. There were a bunch of changes last year and this exact same error is shown for multiple reasons.

We've added extra diagnostics and error messages for these other cases. Update to the latest nightly (3.0.6370) and it should display the correct error message.

**Comment by wnstngs** [comment]
> @wnstngs
> 
> Looks like I was wrong about this error message and `This specific error is when files are missing.` was not correct. There were a bunch of changes last year and this exact same error is shown for multiple reasons.
> 
> We've added extra diagnostics and error messages for these other cases. Update to the latest nightly (3.0.6370) and it should display the correct error message.

Thanks for the update

The error message:
```
The kernel driver is not supported on preview builds. If this is not a preview build, request support by 
submitting a GitHub issue with the Windows Kernel version.
Kernel version: 10.0.25314.1010
State mask: 0x00000000
```

It turns out that the driver will not work as long as I use Canary Build. Why is it not possible to load the driver in the case of the Preview version?

**Comment by Masamune3210** [comment]
Insider changes too quickly and regularly has things changed that do not make it to retail. It simply just isnt worth the time to try to keep up with a moving non-guaranteed target.
