### ISSUE TITLE
Unable to commit detours transaction

### ISSUE THREAD

**Issue by devinaws** [winsiderss/systeminformer#1648]
A few days ago I'm upgrade my process hacker to version 3.0.6328 (8903fe9). And then this error keep showing every time I restart my windows. 
![Unable to commit detours transaction](https://user-images.githubusercontent.com/99480814/226106640-ecfc7eff-3335-48f4-8934-6a4b3dd71356.png)

If you need some log, I've created one here:
[System Informer Log.txt](https://github.com/winsiderss/systeminformer/files/11008534/System.Informer.Log.txt)

By the way I'm using windows 11 Pro 22H2 OS build 22621.1413 and Windows Feature Experience Pack 1000.22639.1000.0

**Comment by dmex** [comment]
https://github.com/winsiderss/systeminformer/issues/1646#issuecomment-1474079745

**Comment by devinaws** [comment]
> [#1646 (comment)](https://github.com/winsiderss/systeminformer/issues/1646#issuecomment-1474079745)

Many thank @dmex . Now I can close this issues
