### ISSUE TITLE
Latest update 3.0.6328 (8903fe9)  causes the program to just close...

### ISSUE THREAD

**Issue by lilking420** [winsiderss/systeminformer#1650]
Not sure exactly if I'm submitting this correctly, but here' the "normal" dump file from the crash.  Hope this helps.[SystemInformer_DEKIGZYTRAPIXIQ_DumpFile.zip](https://github.com/winsiderss/systeminformer/files/11024210/SystemInformer_DEKIGZYTRAPIXIQ_DumpFile.zip)

**Comment by lilking420** [comment]
Downloaded new update 3.0.6370 (d9c1262) and this issue seems to be resolved.  Much obliged for the prompt fix!!!

**Comment by dmex** [comment]
> this issue seems to be resolved. Much obliged for the prompt fix

We didn't fix anything related to this crash?

Something sent a button message and this was handled by Windows:
```
	ntdll.dll!RtlDeactivateActivationContextUnsafeFast()
 	user32.dll!UserCallWinProcCheckWow()
 	user32.dll!SendMessageWorker()
 	user32.dll!SendMessageW()
 	comctl32.dll!Button_ReleaseCapture()
 	comctl32.dll!Button_WndProc()
 	user32.dll!UserCallWinProcCheckWow()
 	user32.dll!DispatchMessageWorker()
 	user32.dll!IsDialogMessageW()
```

Our code wasn't executing and this was entirely handled by Windows without us. This is some sort of weird Windows bug: 0xC0150014: The activation context activation stack for the running thread of execution is corrupt.

Your version of Windows (15063) also expired 6 years ago and you should probably update.

**Comment by lilking420** [comment]
That explains a lot.  DERP!  Thank you for your reply @dmex.  I'm stuck on 15063 cuz I'm on an even older AIO which refuses to update beyond where it is, something to do with the graphics and drivers causing issue and this PC not being supported doesn't help.  This machine has about had it, I reported the issue as it was the first time System Informer had ever just closed like it did and I thought I was being helpful.  Thanks again!

**Comment by dmex** [comment]
> I reported the issue as it was the first time System Informer had ever just closed like it did and I thought I was being helpful. Thanks again!

No problem. It's always good to report these issues 👍
