### ISSUE TITLE
SystemInformer (3.0.6328 8903fe9) crashes and exits, generating dump file

### ISSUE THREAD

**Issue by ShenHongFei** [winsiderss/systeminformer#1651]
### Brief description of your issue

It crashes when switching to the Disk panel.
This doesn't happen every time.
[SystemInformer_RFOULTGSXGWMPXV_DumpFile.zip](https://github.com/winsiderss/systeminformer/files/11024631/SystemInformer_RFOULTGSXGWMPXV_DumpFile.zip)

### Environment (optional)

```shell
Windows 22H2 22621.1413
```

**Comment by dmex** [comment]
Fixed in latest nightly 👍
