### ISSUE TITLE
"The kernel driver is temporarily disabled on this Windows version" | Kernel 6.1.7601.25792

### ISSUE THREAD

**Issue by tordenflesk** [winsiderss/systeminformer#1656]
### Brief description of your issue

https://i.imgur.com/UdxareH.png

Dropping W7 support, or?
What would i be missing by not using the kernel driver?

### Environment (optional)

```shell
systeminformer-nightly installed from Scoop/Versions
W7 X64 6.1.7601.25792
```

**Comment by jxy-s** [comment]
The driver isn't supported on W7. We should reorder the checks to convey this more appropriately. See here:
https://github.com/winsiderss/systeminformer/blob/master/SystemInformer/ksisup.c#L541

You won't be missing out on much, some broader inspection capability and a small set of features require the driver.

**Comment by jxy-s** [comment]
I've reordered the error messages. Will be in next nightly. https://github.com/winsiderss/systeminformer/commit/024ff12399bb8ff9a8815e543a18ea1712108333
