### ISSUE TITLE
"Enable theme support" makes dwm.exe crash

### ISSUE THREAD

**Issue by Puncia** [winsiderss/systeminformer#1657]
### Brief description of your issue

When opening *any* new window from System Informer (Log, System Information, System->Run, works on anything) the cursor completely freezes, the system hangs and makes the dwm.exe process crash.

From the Log window:
![image](https://user-images.githubusercontent.com/4633311/226910199-8202edb4-34e2-43c5-b0e2-4dbd2ee9ebe0.png)
the exit status is consistent between crashes.

I made a short recording of my desktop when opening new windows within SI
![UFbyHENwaK](https://user-images.githubusercontent.com/4633311/226909277-c0a32fcd-e214-4fef-9ada-5378b273e70d.gif)

### Steps to reproduce (optional)

1. Enable the option "Enable theme support (experimental)" from the Options window
2. Restart SI
3. Open any new window
4. Observe dwm.exe explode

### Environment (optional)

```shell
System Informer
Version: 3.0.6390 (59376c3)

Windows 11 22H2 (OS Build 22621.1413)
dwm.exe: 10.0.22621.608 (WinBuild.160101.0800) SHA256: 14C2317D6CA82ACE2AC252B2ED64B61C735F14279DF543F7B69EC2DF09D6AC5B
```

**Comment by MagicAndre1981** [comment]
Collect a [dump from DWM](https://learn.microsoft.com/en-us/windows/win32/wer/collecting-user-mode-dumps) and run **!analyze -v** in [windbg](https://learn.microsoft.com/en-us/windows-hardware/drivers/debugger/using-the--analyze-extension). 

Which GPU do you use? Is driver up to date? In my 22621 VM I don't get any crashes related to theme.

**Comment by Puncia** [comment]
Yeah.. despite ProcDump being set correctly, I still don't see any generated dumps whenever dwm.exe crashes.

**Comment by MagicAndre1981** [comment]
Try [DebugDiag](https://www.microsoft.com/en-us/download/details.aspx?id=103453) to [generate a dump](https://www.youtube.com/watch?v=5MqFlcACSzI), this is my last way that I know of.

After you generated the rule, try to repro the crash and look if you now get a dump.

**Comment by Puncia** [comment]
Thanks, I was able to generate the file. In fact, it generated 21 of them, including some logs and process lists. I also run the analysis in windbg but I don't know what to look for since there's a lot of data. The whole folder is over 3GB.
What do you want me to do? I am a bit reluctant to share publicly to be honest.
Below is a listing of all the files:

<details>
<summary>File listing</summary>

"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__44932__Date__03_22_2023__Time_07_39_34PM__237__First chance exception 0X000006BA.dmp"
"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__44932__Date__03_22_2023__Time_07_39_34PM__237__ProcessList.txt"
"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__44932__Date__03_22_2023__Time_07_39_32PM__405__ProcessList.txt"
"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__44932__Date__03_22_2023__Time_07_39_32PM__405__First chance exception 0X000006BA.dmp"
"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__44932__Date__03_22_2023__Time_07_39_31PM__487__First chance exception 0X000006BA.dmp"
"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__44932__Date__03_22_2023__Time_07_39_31PM__487__ProcessList.txt"
"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__44932__Date__03_22_2023__Time_07_39_30PM__828__First chance exception 0X000006BA.dmp"
"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__44932__Date__03_22_2023__Time_07_39_30PM__828__ProcessList.txt"
"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__42208__Date__03_22_2023__Time_07_38_47PM__496__Log.txt"
"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__42208__Date__03_22_2023__Time_07_39_26PM__590__ProcessList.txt"
"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__42208__Date__03_22_2023__Time_07_39_24PM__643__Second_Chance_Exception_C0000409.dmp"
"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__42208__Date__03_22_2023__Time_07_39_26PM__590__First chance exception 0XC0000409.dmp"
"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__44932__Date__03_22_2023__Time_07_39_28PM__263__Log.txt"
"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__44932__Date__03_22_2023__Time_07_39_40PM__382__ProcessList.txt"
"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__44932__Date__03_22_2023__Time_07_39_40PM__382__First chance exception 0X000006BA.dmp"
"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__44932__Date__03_22_2023__Time_07_39_39PM__119__First chance exception 0X406D1388.dmp"
"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__44932__Date__03_22_2023__Time_07_39_39PM__119__ProcessList.txt"
"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__44932__Date__03_22_2023__Time_07_39_37PM__526__ProcessList.txt"
"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__44932__Date__03_22_2023__Time_07_39_37PM__526__First chance exception 0X000006BA.dmp"
"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__44932__Date__03_22_2023__Time_07_39_35PM__445__First chance exception 0X000006BA.dmp"
"C:\Program Files\DebugDiag\Logs\Crash rule for all instances of dwm.exe\dwm__PID__44932__Date__03_22_2023__Time_07_39_35PM__445__ProcessList.txt"
</details>

**Comment by MagicAndre1981** [comment]
let [DebugDiag analyzer](https://www.youtube.com/watch?v=rPjt10B1muA) analyze the dmp files or load them in Windbg, load debug symbols and run **!analyze -v**

**Comment by Puncia** [comment]
Ok. this is the report for all the dmp files.
[archive.zip](https://github.com/winsiderss/systeminformer/files/11044065/archive.zip)

**Comment by dmex** [comment]
> dwm.exe process crash

This is a bug in the OS and was reported last year but no response from Microsoft.

> When opening any new window from System Informer

I added checks to workaround the issue for normal windows but didn't add checks for dialog windows. I've updated the nightly build with extra checks for the dialogs and prevents dwm crashing👍
