### ISSUE TITLE
Can't restart a process.

### ISSUE THREAD

**Issue by disc0nct** [winsiderss/systeminformer#1661]
### Brief description of your issue

When I run the program normally then I can restart any process running by user but in the system informer with admin rights in can't restart them.

### Steps to reproduce (optional)

run the system informer and try to restart a user process.

### Expected behavior (optional)

To restart the process even, I'm using system informer with admin rights.

### Actual behavior (optional)

show's this message error : “Unable to restart *process name* (PID)”
“a required privilege is not held by client”

### Environment (optional)

```shell
Nightly : 3.0.6390
Windows 10 : 10.0.19045 build 19045
```

**Comment by dmex** [comment]
Duplicate of #1621
