### ISSUE TITLE
SysTray not disappear when close main window

### ISSUE THREAD

**Issue by lollita** [winsiderss/systeminformer#1662]
### Brief description of your issue

When I close SystemInformer windows the SysTrayicon not disappear.
I have to go hover with mouse to disappear.

**Comment by dmex** [comment]
What version of System Informer do you have installed?

I've checked all 16 icons and they disappear when exiting:
![image](https://user-images.githubusercontent.com/1306177/228657044-dc54f411-e2af-48a2-bec0-4f89a4505af1.png)

**Comment by dmex** [comment]
Fixed in the latest nightly update 👍

**Comment by lollita** [comment]
I confirm: it work now. ty.
