### ISSUE TITLE
make default not working

### ISSUE THREAD

**Issue by lollita** [winsiderss/systeminformer#1663]
### Brief description of your issue

I make default task manager portable but nothing start with taskmgr or from task bar.

**Comment by dmex** [comment]
Cannot reproduce. Check your AV product.

**Comment by lollita** [comment]
AV disabled.

**Comment by lollita** [comment]
If I disable Start as administrator
Make as default
Enable Start as administrator
as default continue to work.

**Comment by lollita** [comment]
I not know because but now it work every.
