### ISSUE TITLE
Can't update nor uninstall System Informer (process hacker) program. 

### ISSUE THREAD

**Issue by StacktraceException** [winsiderss/systeminformer#1664]
### Brief description of your issue

This is a continuation of the too quickly closed previous issue: https://github.com/winsiderss/systeminformer/issues/1646 .
The proposed solution therein does not work.  Uninstalling just like installing seems to work (the setup program shows a success message), BUT nothing gets changed. Except that there is no option to remove it anymore from Add or Remove programs (even after rerunning the installer later).

### Environment (optional)

```shell
System Informer version 3.0.4953.
Windows 11.
```

**Comment by dmex** [comment]
> The proposed solution therein does not work

That solution is only for users who enabled legacy mitigations from the settings window. If you didn't enable the option then you have some other issue.

> there is no option to remove it anymore from Add or Remove programs (even after rerunning the installer later).

I just tested this and the ARP entry was always created? Your security software is probably blocking the installer.

**Comment by StacktraceException** [comment]
I don't have such security software. This must be something more complex.

**Comment by dmex** [comment]
@StacktraceException 

1) Run Process Monitor: https://learn.microsoft.com/en-us/sysinternals/downloads/procmon
2) Run the setup.
3) Right-click the setup in process monitor and select "include":
![image](https://user-images.githubusercontent.com/1306177/228767782-f2d1529a-b563-4bed-b1f1-846b81acc37c.png)
4) Screenshot or copy/paste any failures here if you're unsure whats causing them. For example you can search for Uninstall and check if the uninstall entries are created successfully:
![image](https://user-images.githubusercontent.com/1306177/228768184-2309165d-d6c5-4318-a83e-880b5556f1e2.png)

**Comment by dmex** [comment]
Closing as non-reproducible / inactive. I'll reopen the issue if you can post screenshots 👍
