### ISSUE TITLE
Crash in Windows view

### ISSUE THREAD

**Issue by MarekKnapek** [winsiderss/systeminformer#1673]
### Brief description of your issue

System Informer crashes.

### Steps to reproduce (optional)

 - Main menu.
 - View.
 - Windows.
 - Click on list view's "Modules" header.
 - Crash.

### Expected behavior (optional)

No crash.

### Environment (optional)

```shell
System Informer latest nightly.
```

**Comment by dmex** [comment]
Duplicate of #1674
