### ISSUE TITLE
csrss on windows 11

### ISSUE THREAD

**Issue by ShowMyPots** [winsiderss/systeminformer#1682]
is csrss on windows 11 locked? how to unlock it?

**Comment by dmex** [comment]
![image](https://user-images.githubusercontent.com/1306177/230644161-130adf37-793e-448f-a0ef-6f818ce4c431.png)

Enable debug mode:
```
Bcdedit.exe -set DEBUG ON 
Bcdedit.exe -set TESTSIGNING ON
```

**Comment by ShowMyPots** [comment]
> ![image](https://user-images.githubusercontent.com/1306177/230644161-130adf37-793e-448f-a0ef-6f818ce4c431.png)
> 
> Enable debug mode:
> 
> ```
> Bcdedit.exe -set DEBUG ON 
> Bcdedit.exe -set TESTSIGNING ON
> ```

how to enable it?

**Comment by Masamune3210** [comment]
by running those two commands in a administrator shell

**Comment by ShowMyPots** [comment]
windwo

> by running those two commands in a administrator shell

windows powershell?

**Comment by Masamune3210** [comment]
If you are having this much difficulty already, it might not be the best idea to go fiddling with critical windows processes.....

**Comment by ShowMyPots** [comment]
> If you are having this much difficulty already, it might not be the best idea to go fiddling with critical windows processes.....

i need it, i'm on cmd, i do the commands but i've errors: 
Error setting item data.
The value is protected by Secure Boot policies and cannot be changed or deleted.

**Comment by ShowMyPots** [comment]
i'm on w11

**Comment by Masamune3210** [comment]
As a exercise, I will leave this one for you to figure out. The message tells you what the issue is exactly. I repeat, if you are having this much of a issue, you might not want to go around messing with things that can hose your system

**Comment by ShowMyPots** [comment]
> As a exercise, I will leave this one for you to figure out. The message tells you what the issue is exactly. I repeat, if you are having this much of a issue, you might not want to go around messing with things that can hose your system

i understand it's for secure boot and i've to disable it maybe.. I need it for minecraft ScreenShare

**Comment by ShowMyPots** [comment]
on w10 csrss is accessible, on w11 not, i need just this help .-.

**Comment by Masamune3210** [comment]
....you do not have to touch csrss to share a screen

**Comment by ShowMyPots** [comment]
> ....you do not have to touch csrss to share a screen

i'm talking about minecraft Hack Controls.

**Comment by ShowMyPots** [comment]
if i need to see excecuted files i need csrss, but in w11 it's locked, i'm just asking how to unlock it, it's difficult to answer?

**Comment by Masamune3210** [comment]
Yes. Its explained to you very clearly in the error message. If you cant figure it out from there I am not sure what to tell you lol

**Comment by ShowMyPots** [comment]
> Yes. Its explained to you very clearly in the error message. If you cant figure it out from there I am not sure what to tell you lol

i've to turn off secure boot?
