### ISSUE TITLE
Win11 - Process Hacker Portable (via PortableApps): Show icon in Tray area?

### ISSUE THREAD

**Issue by UglyStuff** [winsiderss/systeminformer#1683]
Hi everyone, 

After Windows Defender banned System Informer from my Win11 Pro PC, I decided to try my luck with Process Hacker Portable from PortableApps. 

So far, so good: The program runs alright, starts minimized when I log on, etc... However, I can't bring Windows to show the icon in the Tray area. 

By this I mean that the icon is there, but it's hidden, and I'd like it to show permanently. Problem is, since my copy of PH is portable, Windows won't offer that possibility. 

Is there a way to work around that? It's a minor inconvenience, but still...

**Comment by dmex** [comment]
View > Tray icons > Settings > Enable persistent layout?

**Comment by UglyStuff** [comment]
Hi, 

I don't have that option, at least not in the portable version I use. I can choose different views, I can even choose to display several icons (CPU history AND CPU usage, for example), but that's it. 

The PH version I have is 2.39.124 (portable via PortableApps).

**Comment by dmex** [comment]
The latest version is 3.0.6505

**Comment by UglyStuff** [comment]
I tried to update, but it tells me I'm running the latest version of PH (PortableApps, I remind you). 

Is there a portable version of System Informer I can download? If so, can you post the link here?

**Comment by dmex** [comment]
bin.zip 

https://systeminformer.sourceforge.io/nightly.php
