### ISSUE TITLE
Sign nightly releases

### ISSUE THREAD

**Issue by PerikiyoXD** [winsiderss/systeminformer#1688]
Just as the title says.

**Comment by PerikiyoXD** [comment]
Any plans on this matter?

**Comment by SirWobbyTheFirst** [comment]
> It's on our radar. We're looking into it.

A better option will be to produce a stable build, even if some of the features have to be cut out until the next version. That way you don't spend excess money trying to code sign every single new build and don't get flagged as malware.

**Comment by jxy-s** [comment]
As of `3.0.7256` nightly builds are signed 👍
