### ISSUE TITLE
Using System Informer with Avast Antivirus

### ISSUE THREAD

**Issue by Baantjer** [winsiderss/systeminformer#1698]
Just a heads up in case it proves an issue to other users of SI.
Avast is wanting to quarantine several plug-ins. Below is a screenshot of one request.
It will soon not be an issue because I will find  a different anti-virus software.

![screenshot](https://user-images.githubusercontent.com/114300941/232683538-1c42bf87-5627-4667-aeef-0b6622a14819.jpg)

**Comment by dmex** [comment]
Duplicate of #1668
