### ISSUE TITLE
Tray Icon - Add GPU Dedicated Memory

### ISSUE THREAD

**Issue by TFWol** [winsiderss/systeminformer#1699]
### Description of the feature, modification, idea or suggestion

I absolutely love the graphs we can place as Tray Icons. They're out of the way and provide convenient information, especially when interacted with.

The only thing I'm really missing is an icon to monitor the GPU's Dedicated Memory. 
Would you consider adding this as an option?

### Proposed implementation details (optional)

It could be setup like how RAM is displayed and the toggle could be under the current GPU menu entry.
![image](https://user-images.githubusercontent.com/9045213/232951328-3a75dbe2-c264-4631-ae57-d37f15da0fa8.png)

**Comment by jxy-s** [comment]
Will be in next nightly: https://github.com/winsiderss/systeminformer/commit/8c516d5a4a6c8768904b40b53727eee4da90fcb0

**Comment by TFWol** [comment]
Awesome!

**Comment by TFWol** [comment]
Got it, thanks.
@jxy-s Is the current repo safe for me to build from or is it best to wait for the nightly?

**Comment by jxy-s** [comment]
Should be fine to build from.

**Comment by TFWol** [comment]
Nice. I'm definitely going to check it out.
