### ISSUE TITLE
System information displays invalid memory

### ISSUE THREAD

**Issue by henrypp** [winsiderss/systeminformer#1710]
Subj displays 64 memory percentage, but valid value is 48 (same as aida64), i think it's enough!

![sshot-002](https://user-images.githubusercontent.com/3902025/235405007-239b3c75-d87e-4578-a3e9-10fd9947c401.png)

**Comment by dmex** [comment]
It's showing commit memory not physical memory which is correct? 

Options > Graphs > Uncheck `Show commit charge instead of physical memory`:

![image](https://user-images.githubusercontent.com/1306177/235434954-32a1b5ea-d54c-4aa5-a770-0ade7a1d193b.png)

**Comment by henrypp** [comment]
Ah,ok. But by default need to be not enabled this option.
