### ISSUE TITLE
SystemInformer cannot be opened in a mounted folder

### ISSUE THREAD

**Issue by f32by** [winsiderss/systeminformer#1712]
### Brief description of your issue

I have a NTFS partition mounted to C:\Soft. If SystemInformer is in this folder (e.g C:\Soft\SystemInformer\) it can not open. If I put it elsewhere everything works fine. I uploaded a SysInternal Process Monitor log and maybe it provides something useful :)

[log.zip](https://github.com/winsiderss/systeminformer/files/11374182/log.zip)

### Environment (optional)

```shell
SystemInformer version: 3.0.6550
```

**Comment by dmex** [comment]
Thanks for the report, I've fixed the issue 👍 

Nightly builds are on hold for the moment. I'll let you know when they resume.

**Comment by dmex** [comment]
Fixed in latest nightly build 🥳
