### ISSUE TITLE
Export Process from Command Line

### ISSUE THREAD

**Issue by MUWASEC** [winsiderss/systeminformer#1723]
i can't find any documentation or tutorial on how to export/save current process into txt from commandline, is this feature even exist or is there any alternative for process monitoring and save it into file like process hacker but via commandline ?

**Comment by dmex** [comment]
System Informer doesn't support command line parameters. 

You can save the commandline for running programs by either adding the commandline column and selecting System > Save or opening the properties window and copy/pasting the commandline into a text file.

**Comment by MUWASEC** [comment]
> You can save the commandline for running programs by either adding the commandline column and selecting System > Save or opening the properties window and copy/pasting the commandline into a text file.

i am not quite understand about this one, why should i save the commandline into text file ? 

the point of my question is the feature exist (this ofc not exist based on your answer) and if not then do you have any alternative for process monitor which the output similar to System Informer "Save to File" and support command line parameters for Windows OS ?

**Comment by dmex** [comment]
> why should i save the commandline into text file

I wasn't sure if you were asking to save command lines or if there were command line parameters.

> do you have any alternative for process monitor which the output 

Powershell? Install the [NtObjectManager extension](https://www.powershellgallery.com/packages/NtObjectManager/1.1.33) using these commands:

```
Install-Module "NtObjectManager" -Scope CurrentUser
Import-Module NtObjectManager
```

Then execute: 

```
(Get-NtProcess -Name svchost.exe).CommandLine
```
or
```
(Get-NtProcess -pid 1234).CommandLine
```
or
```
$processes = Get-NtProcess
$processes.CommandLine
```

The NtObjectManager library can access and enumerate more information than System Informer does.
