### ISSUE TITLE
crash if I close the laptop lid shortly after System Informer starts, external monitor attached through HDMI

### ISSUE THREAD

**Issue by as-muncher** [winsiderss/systeminformer#1726]
As it is now, 3.0.6550, as soon as System Informer starts, as it does automatically when Windows boots, if I close the lid, while the TV is connected through HDMI, mirrored displays, System Informer will crash, give a beep or some sound like that, and not give any options to create any kind of dump file.

I had to do this a few times just to be able to get the options, waiting for 1 second, 2, 3, 5, 10 seconds until I could get the options.

How to reproduce:
Let System Informer start up with Windows, TV connected through HDMI, mirrored displays.  As soon as you see System Informer start up, close the laptop lid, and it will crash.
[SystemInformer_ZLNOXBPJQQUBZPC_DumpFile.zip](https://github.com/winsiderss/systeminformer/files/11468121/SystemInformer_ZLNOXBPJQQUBZPC_DumpFile.zip)

**Comment by Masamune3210** [comment]
The beep makes me think the GPU driver is crashing, as a system beep is the way that Windows let's you know a TDR event occured

**Comment by as-muncher** [comment]
> The beep makes me think the GPU driver is crashing, as a system beep is the way that Windows let's you know a TDR event occured

It's not a hardware beep, more a Windows "ding"-like sound.

**Comment by dmex** [comment]
Fixed in the latest update 👍

**Comment by as-muncher** [comment]
Thank you.
