### ISSUE TITLE
Errors in displaying drivers "Verified Signer" and "Timestamp" fields

### ISSUE THREAD

**Issue by GanbaruTobi** [winsiderss/systeminformer#1729]
I run with driver enabled and as admin:
![grafik](https://github.com/winsiderss/systeminformer/assets/15239745/c9b8f1f3-c77c-4739-bb89-42320e86f54a)

**Comment by dmex** [comment]
> "Timestamp" fields

All of those images are compiled with [deterministic](https://en.wikipedia.org/wiki/Reproducible_builds) and the "Timestamp" isn't a timestamp it's an MD5 hash of the image. There isn't a reliable way of determining if the timestamp is a hash so it just shows the hashes as timestamps.

Right-click the file > Properties > General tab shows the partial hash after the timestamp with (deterministic):

![image](https://github.com/winsiderss/systeminformer/assets/1306177/c84f056c-13f1-4c84-8df2-9ce0678816d8)

The reproducible hash is the PDB hash + Image hash + Timestamp:

![image](https://github.com/winsiderss/systeminformer/assets/1306177/1cb821ce-a9e9-4664-9762-4e789fc37b04)

The timestamp (f6-38-65-a7) is the last 4 bytes of the hash (a7-65-38-f6) they're just swapped. 

> drivers "Verified Signer"

This is a bug... Thanks, I'll fix this in the next build 👍

**Comment by dmex** [comment]
Nightly builds have finally resumed...  Fixed in latest nightly build 👍
