### ISSUE TITLE
Sort by column doesn't work in Wait Chain Traversal window

### ISSUE THREAD

**Issue by MarekKnapek** [winsiderss/systeminformer#1736]
Sort by column doesn't work in Wait Chain Traversal window.

Steps to reproduce:
 - Open System Informer (latest version of 3.0.6550).
 - Right-click on some process to open its context menu.
 - Miscellaneous -> Wait Chain Traversal.
 - Click some list view header in order to sort rows by this column.
 - Rows are not sorted. First column gets indented.

See attached video.

https://github.com/winsiderss/systeminformer/assets/13893067/643f8a1c-848d-4496-a52a-5b8333f41bcf

**Comment by dmex** [comment]
Fixed in the next nightly build 👍
