### ISSUE TITLE
Compile Error: fatal error C1047

### ISSUE THREAD

**Issue by trparky** [winsiderss/systeminformer#1737]
### Brief description of your issue

[ERROR] (1) LINK : fatal error C1047: The object or library file 'C:\Users\trpar\source\repos\systeminformer\phlib\bin\Release32\phlib.lib' was created by a different version of the compiler than other objects like 'C:\Users\trpar\source\repos\systeminformer\SystemInformer\obj\Release32\about.obj'; rebuild all objects and libraries with the same compiler [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]LINK : fatal error LNK1257: code generation failed [C:\Users\trpar\source\repos\systeminformer\SystemInformer\SystemInformer.vcxproj]LINK : fatal error C1047: The object or library file 'C:\Users\trpar\source\repos\systeminformer\phlib\bin\Release32\phlib.lib' was created by a different version of the compiler than other objects like 'C:\Users\trpar\source\repos\systeminformer\tools\peview\obj\Release32\cfgprp.obj'; rebuild all objects and libraries with the same compiler [C:\Users\trpar\source\repos\systeminformer\tools\peview\peview.vcxproj]LINK : fatal error LNK1257: code generation failed [C:\Users\trpar\source\repos\systeminformer\tools\peview\peview.vcxproj]

I have done a full clean by executing build_clean.cmd but still have the same issue.

**Comment by dmex** [comment]
Run `build_thirdparty.cmd`

**Comment by trparky** [comment]
OK, that fixed it. It's been awhile since I had to do that.
