### ISSUE TITLE
Why was windows 7 support removed?

### ISSUE THREAD

**Issue by lavinkabul** [winsiderss/systeminformer#1739]
I understand that windows 10 and 11 are the most fashionable right now. But why was the adequate windows 7 operating system removed?
Version 3.0.6550

**Comment by dmex** [comment]
Visual Studio 2022 dropped support for Windows 7 and Windows 8... We're unable to compile drivers for those platforms and code signing for those platforms has been deprecated so we're unable to sign drivers for Windows 7 and Windows 8.

System Informer does run on Windows 7 and 8 (without driver support):

![image](https://github.com/winsiderss/systeminformer/assets/1306177/98a3bc65-6bf0-4675-a887-7ddc3f808ca7)

Visual Studio will likely remove the remaining client support at some point so we only support Windows 10 and Windows 11 even though the client works (for now).

If you're running Windows 7 or Windows 8 then I'd suggest to keep using Process Hacker v2.39 which was built for those versions of Windows and has driver support: https://sourceforge.net/projects/processhacker/files/processhacker2/

**Comment by lavinkabul** [comment]
Thank you for the detailed answer. It looks like I'll have to take a week and start switching to windows 10/ As more and more programs stop supporting windows 7.

**Comment by pegleGrot** [comment]
Maybe VS + the Clang/LLVM toolset is an option:
https://building.enlyze.com/posts/targeting-25-years-of-windows-with-visual-studio-2019/

**Comment by tamr** [comment]
Noticed I have the Process Hacker driver installed previously and it seems works just fine with System Informer (even the recent builds). At least it doesn't complain and asks to install a new one and feels pretty snappy on win7. Not sure if it's capable to expose the extended information, but it seems everything's there.

![125833](https://github.com/winsiderss/systeminformer/assets/209513/47a29241-c4ef-4804-b2ee-fe56557977bd)
