### ISSUE TITLE
Linux Version? 

### ISSUE THREAD

**Issue by TasfiqSami** [winsiderss/systeminformer#1742]
I'm a Linux User and i want i'm looking forward to it.

**Comment by djkato** [comment]
Just use [btop](https://github.com/aristocratos/btop) instead :)

**Comment by gggirlgeek** [comment]
I would die for this. It's probably the main reason I'm not a fulltime Linux user (and not laziness, I promise!) :-P But, as I understand it, there really is no way to report the information in Linux the same way as Windows. btop is like many similar apps for Linux that are confusing, and not really consistent with total process usage and memory -- not to mention they are terminal-based UI's. What I really miss though are simple tray icons that let me see my memory, CPU, and network usage in numbers at a glance. Whenever I'm on another computer without System Informer I feel downright blind. System Informer, for me, is like having Star Trek sound affects, letting me know the computer is processing my request, and if there are delays, telling me why. (Browser page is loading slow? Look down at the memory icon. Sure enough! 78% memory is being hogged by Firefox. Time to unload 326 open tabs.) :-)

**Comment by djkato** [comment]
> What I really miss though are simple tray icons that let me see my memory, CPU, and network usage in numbers at a glance.

@gggirlgeek That is totally possible!
Check out [Polybar](https://github.com/polybar/polybar)
![image](https://github.com/winsiderss/systeminformer/assets/25299243/325af5d5-217e-4881-b315-cf62c364cdfe)
[Image config source](https://www.reddit.com/r/Polybar/comments/i4t5bg/dwm_with_polybar_my_simple_rice/)

Thing about linux is that it can do everything if you know how.. The learning curve can feel steep, but once yo uget the hang of it you'll never want to move to windows again ^^
Check out [https://www.reddit.com/r/unixporn/](https://www.reddit.com/r/unixporn/) for some amazing setups people have made, many share their config files etc and they're a great starting point

**Comment by dmex** [comment]
https://missioncenter.io/ for Linux

![0001-cpu-multi](https://github.com/winsiderss/systeminformer/assets/1306177/a275db79-77f1-4718-b999-bfbc920cfbaa)

**Comment by mausalimi** [comment]
first finish the windows 3 version, which probably needs another 5 years....

**Comment by MagicAndre1981** [comment]
Here is a taskmgr replica for Linux: 

https://github.com/KrispyCamel4u/SysMonTask

![image](https://github.com/winsiderss/systeminformer/assets/8274816/40322643-7723-459d-9b06-10e27a122689)
