### ISSUE TITLE
process hacker 2 auto shutdown for security reason (what i dont know)

### ISSUE THREAD

**Issue by nightmare3007** [winsiderss/systeminformer#1744]
### Brief description of your issue

i just installed process hacker but it will shutdown for security reason immediately after starting (in .00005 seconds)
![image](https://github.com/winsiderss/systeminformer/assets/68788826/9f3fa5a8-1715-4d56-a46d-14af1e0f1b23)

tried restart the pc but the problem remains.
tried noninstall ver but same problem.
tried using it as administrator.
tried using it as win 7 compatible.

### Steps to reproduce (optional)

install the programe processhacker-2.39-setup

### Environment (optional)

```shell
Device name	DESKTOP-M43QNCV
Processor	Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz   4.00 GHz
Installed RAM	32.0 GB
System type	64-bit operating system, x64-based processor
Pen and touch	No pen or touch input is available for this display
Edition	Windows 10 Pro
Version	22H2
Installed on	‎11/‎30/‎2022
OS build	19045.2965
Experience	Windows Feature Experience Pack 1000.19041.1000.0
```

**Comment by dmex** [comment]
You're likely infected with malware. Process Hacker doesn't have dialogs like that one and any security software would show a proper message identifying themselves as the source.

Should be easy enough to locate the program responsible.

1) Download System Informer: 
https://systeminformer.sourceforge.io/nightly.php

2) Run System Informer then run Process Hacker.
3) These icons on the toolbar will locate the owner of that dialog:
![image](https://github.com/winsiderss/systeminformer/assets/1306177/cd6cb9c9-a31e-47c4-a0f6-9d8aff8c4648)

Left click+hold and drag those icons over that message window and when you release the mouse it'll select the program showing that dialog and if it's selecting something like explorer.exe or svchost.exe then it's very likely malware responsible. 

You could right-click whichever process is selected, open the properties window, select the Threads tab and inspect each thread. One of the threads will be calling `user32.dll MessageBox` waiting for you to click OK and the stack will show the name of the DLL calling MessageBox and you can select the Modules tab to inspect the DLL.

If you can post the name of the program or the name of the DLL then we can look into what they're doing 👍

**Comment by nightmare3007** [comment]
not a virus or malware.
it was a finance protective program name fasoo drm.
it kill Process Hacker the moment it become active windows and leve it be if it is minimal or in task bar.

**Comment by jxy-s** [comment]
You'll have to ask the authors of that program. Happy to hear it's resolved. Also, as a reminder Process Hacker has been sunset, please use System Informer instead.
