### ISSUE TITLE
Process Hacker

### ISSUE THREAD

**Issue by deltaromeo44** [winsiderss/systeminformer#1749]
When i try to open the properties of a process, a dialog box open and says "you are not authorized to display parameters..."

I am administrator so i don't know what to do...any idear ?

**Comment by dmex** [comment]
Upload a screenshot?

**Comment by iraizo** [comment]
just a reminder: next time shortly describe your issue in the title of the issue

**Comment by dmex** [comment]
Feel free to re-open if you still have the issue
