### ISSUE TITLE
Nightly builds are broken

### ISSUE THREAD

**Issue by KarenArzumanyan** [winsiderss/systeminformer#1750]
### Brief description of your issue

Night builds are broken

### Steps to reproduce (optional)

If go to the page of nightly builds, then there is the latest build from April 26, 2023.

https://github.com/winsiderss/si-builds/releases
or
https://systeminformer.sourceforge.io/nightly.php

### Expected behavior (optional)

Please fix running builds.

**Comment by dmex** [comment]
> builds are broken

Nightly builds were intentionally disabled as a precaution while we investigated malware reports by security vendors (see #1668).

> Please fix running builds.

We've spoken with 15 vendors over the last month and these reports were apparently false positives... we're just waiting to hear from Symantec but either way nightly builds are resuming this weekend 👍

**Comment by KarenArzumanyan** [comment]
Broke again.
