### ISSUE TITLE
"Access Denied" when trying to update to newest build.

### ISSUE THREAD

**Issue by Dajova** [winsiderss/systeminformer#1757]
### Brief description of your issue

Trying to update SI to the latest build and as soon as i hit "install", it shows this:
![image](https://i.imgur.com/0GDq51j.png)
... and then it just force-closes itself. This is even with admin permission enabled.

### Environment (optional)

```shell
Build 3.0.6550, commit cd8e90b (current)
Build 3.0.6772, commit a7cce79 (new)
Windows 11 Pro, 22H2
```

**Comment by dmex** [comment]
Can you check Process Monitor and find the last file/folder returning access denied?

https://learn.microsoft.com/en-us/sysinternals/downloads/procmon

**Comment by Dajova** [comment]
Alright, took me some time to understand how to filter out the events, but here's what i got:

> Date:	12/06/2023 18:26:06.5879151
Thread:	5448
Class:	File System
Operation:	CreateFile
Result:	ACCESS DENIED
Path:	D:\Program\System Informer\systeminformer-setup.exe
Duration:	0.0000241
Desired Access:	Generic Write
Disposition:	OverwriteIf
Options:	Sequential Access, Synchronous IO Non-Alert, Non-Directory File
Attributes:	N
ShareMode:	Read
AllocationSize:	13,955,072
