### ISSUE TITLE
Process Haker on Windows 11.

### ISSUE THREAD

**Issue by GYRAGA558** [winsiderss/systeminformer#1758]
Is it possible to download it on windows 11, if so, then you can link

**Comment by dmex** [comment]
You can download Process Hacker from the website: 
https://processhacker.sourceforge.io/downloads.php

Process Hacker doesn't support Windows 11 or Windows 10 and you'll have various issues. I'd recommend using System Informer instead which is is the successor to Process Hacker: https://systeminformer.sourceforge.io/

**Comment by GYRAGA558** [comment]
Thank you very much for the detailed answer, can you please describe this program in detail

**Comment by dmex** [comment]
> can you please describe this program

System Informer is a task manager application for monitoring system resources and the overall performance of the system while including information about the processes, services, devices, network connections and firewall activity.

>  in detail

There's a lot of functionality provided for all sorts of diagnostics and development related reasons. Is there something specific you're unsure about or some feature that doesn't make sense? System Informer can show upwards of 1000 different data points and each feature covers multiple topics for diagnostics and development utility so you'll need to be more specific about what you need details about.

Alternatively... The owners of System Informer (this project) are also the co-authors of the Windows Internals books 1-7 and these they publish highly detailed information about functionality provided the Operating System... Everything System Informer does is information provided directly from the Operating System, so by leaning about system functionality you'll understand why System Informer shows that information and necessary for monitoring system resources and the overall performance of the system.

For example System Informer has dozens of columns showing things like working sets, context switches, cycles, page faults etc... information provided by the Operating System to System Informer for monitoring system resources. The Windows Internals books detail everything about the Operating System, so if you want to understand the information displayed by System Informer then you should read the Windows Internals books: https://learn.microsoft.com/en-us/sysinternals/resources/windows-internals

**Comment by sulman45** [comment]
I am unable to download system informer on windows 11 pro, version 24H2, OS build 26100.2605. i am trying to download from this link https://systeminformer.sourceforge.io/ but in my windows 11 pro it does no download.I had tried in both Chrome and Firefox browser.
