### ISSUE TITLE
System informer hangs (crash dump included)

### ISSUE THREAD

**Issue by SanderBouwhuis** [winsiderss/systeminformer#1760]
### Brief description of your issue

I suspended two instances of the same applications and then System informer hung.

### Steps to reproduce (optional)

Suspend two instances of the same application

### Expected behavior (optional)

It should not hang

### Actual behavior (optional)

It hangs.

Here is the crash dump:
[SystemInformer.exe_2023-06-14_13-29-07.7z.001.txt](https://github.com/winsiderss/systeminformer/files/11745205/SystemInformer.exe_2023-06-14_13-29-07.7z.001.txt)
[SystemInformer.exe_2023-06-14_13-29-07.7z.002.txt](https://github.com/winsiderss/systeminformer/files/11745209/SystemInformer.exe_2023-06-14_13-29-07.7z.002.txt)

### Environment (optional)

```shell
System Informer v3.0.6433
Windows 10 x64
```

**Comment by dmex** [comment]
Does the crash always happen or was it only once?

**Comment by SanderBouwhuis** [comment]
It happened once, but I tried it once. It was a situation where an application was started twice, and I tried to pause/stop them.
I can't reproduce it, but maybe the dump file shows you a hidden bug which got triggered.

**Comment by dmex** [comment]
> I can't reproduce it, but maybe the dump file shows you a hidden bug which got triggered.

The exception was generated in the kernel:

```
ExceptionAddress: 0000000000000000
ExceptionCode: 80000003 (Break instruction exception) STATUS_BREAKPOINT
```

![image](https://github.com/winsiderss/systeminformer/assets/1306177/807984a6-bbef-43c5-8fbd-6eebf4ab1b73)

I can't find anything that would explain the crash. Best guess is some kernel driver modified the handle while we were using it 🤷‍♂️
