### ISSUE TITLE
GPU activity not detected for GTX 1060

### ISSUE THREAD

**Issue by Black-Platypus** [winsiderss/systeminformer#1764]
GPU activity is always reported as 0.0%. Other things like RAM usage and fan speed work fine.
[ PCI Express 2.0 x16: nVIDIA GeForce GTX 1060 6GB ]

    Graphics Processor Properties:
      Video Adapter                                     nVIDIA GeForce GTX 1060 6GB
      BIOS Version                                      86.06.0E.00.99
      BIOS Date                                         2016-07-28
      GPU Code Name                                     GP106-400
      PCI Device                                        10DE-1C03 / 0000-0000  (Rev A1)
      Transistors                                       4400 million
      Process Technology                                16 nm
      Die Size                                          200 mm2
      Bus Type                                          PCI Express 2.0 x16 @ 2.0 x16
      Memory Size                                       6 GB
      GPU Clock                                         1556 MHz
      RAMDAC Clock                                      400 MHz
      Pixel Pipelines                                   48
      Texture Mapping Units                             80
      Unified Shaders                                   1280  (v5.0)
      DirectX Hardware Support                          DirectX v12
      WDDM Version                                      Unknown (ID = 2700)

    Memory Bus Properties:
      Bus Type                                          GDDR5 (Samsung)
      Bus Width                                         192-bit
      Real Clock                                        2003 MHz (QDR)
      Effective Clock                                   8012 MHz
      Bandwidth                                         187.8 GB/s

![image](https://github.com/winsiderss/systeminformer/assets/13470026/1c577b5b-19cc-4524-be20-91cdeb1d5090)

Edit: I can't get "GPU 0", which is the only GPU in my system, to replace the default "GPU". The _GPU_ column in the _Processes_ view never displays any activity

**Comment by Black-Platypus** [comment]
After going to Settings -> Advanced and setting `ProcessHacker.ExtendedTools.EnableGpuPerformanceCounters` to `1`, I had to restart System Informer, then it showed 😅
Don't know why it was disabled.

Sorry, wish I could delete this issue. I guess this might be useful for others, so up it stays 🤷‍♂️

**Comment by WAZAAAAA0** [comment]
> I guess this might be useful for others

can confirm
