### ISSUE TITLE
Possible to try to close Mapped file handle

### ISSUE THREAD

**Issue by TETYYS** [winsiderss/systeminformer#1765]
### Brief description of your issue

It is possible to try to close `Mapped file` handle in `Find Handles or DLLs` window by `Del` hotkey, while `Close` context menu item is grayed out

### Steps to reproduce (optional)

Search for `Mapped file`, press `Del`

### Expected behavior (optional)

Nothing happens

### Actual behavior (optional)

A dialog pops up asking for confirmation. After pressing yes nothing happens

### Environment (optional)

```shell
System Informer 3.0.6772
Windows 10 22H2 19045.2965
```

**Comment by dmex** [comment]
Fixed in latest nightly 👍
