### ISSUE TITLE
W11 efficiency mode

### ISSUE THREAD

**Issue by nikczemnydev** [winsiderss/systeminformer#1771]
can I make the efficiency mode setting stick to the processes I chose? on vanilla w11 the setting only sticks until reboot. thanks

**Comment by not-holar** [comment]
yes, it would be great to have the same "Save for x" checkmark for efficiency mode as we do with priorities etc

**Comment by nikczemnydev** [comment]
Oh so I take it's not possible with Process Hacker at the moment. Pity, I was looking for a program that can do that and it looks like there isn't one that has that function as of now.  : <

**Comment by dmex** [comment]
The latest update has a new menu `right-click > Efficiency > Save for...` where you can save efficiency preferences 👍

**Comment by nikczemnydev** [comment]
Yay! Thank you very much.

**Comment by chrcoluk** [comment]
What does this mode even do?  Does it work on windows 10?

**Comment by rpodric** [comment]
Shouldn't there be a columnar choice for it (a la Task Manager) so it's easy to see which processes actually have it on? There might be, but if there is the word "Efficiency" isn't in the name.

**Comment by lollita** [comment]
> The latest update has a new menu `right-click > Efficiency > Save for...` where you can save efficiency preferences 👍

I not see it.
