### ISSUE TITLE
Collumn for GPU Memory, GPU CUDA usage from processes

### ISSUE THREAD

**Issue by djkato** [winsiderss/systeminformer#1772]
### Description of the feature, modification, idea or suggestion

Currently I only found GPU % in general and some shared / dedicated bytes. It would be helpful for me if I could monitor the GPU Memory usage and GPU CUDA usage per app. The regular task manager also has:
- *"Video encode/decode"* (For HVENC I assume)
- *"3D"* (Which I think is Raster or the generic % SystemInformer has) 
- *"CUDA"* (Can't see it on my 1070gtx even though it has CUDA cores, but I've seen it elsewhere) 

and a few more I don't see use in personally.
![image](https://github.com/winsiderss/systeminformer/assets/25299243/26503d5c-d80d-48a4-9fea-7ccd45d369aa)

**Comment by Vasilich** [comment]
Is there anything that you miss?
As i have built-in Vega, there is no CUDA cores indication. But i don't know what you want to see more?
![image](https://github.com/winsiderss/systeminformer/assets/1168434/a6e5c3b7-17fb-49eb-892a-33d8b82f3f16)
Post a screenshot of your SI System information + GPU Nodes, so that we can see what information you are missing comparing to TaskManager.

**Comment by djkato** [comment]
Sorry I should've done more testing and research. About the whole CUDA thing, I went on all my life thinking Nvidias GPU has two different cores, something something 3D raster for games and CUDA for professional work and I was just humbled researching into what CUDA actually is.

What I meant originally though is the ability to sort by GPU Memory on processes. eg:
![image](https://github.com/winsiderss/systeminformer/assets/25299243/59fce929-514e-4afe-b565-1b2fda360014)

**Comment by dmex** [comment]
> thinking Nvidias GPU has two different cores, something something 3D raster for games and CUDA for professional work

They do have different cores. These are divided into nodes and are visible from the System Information window -> GPU section -> click the `Nodes` button. 

> What I meant originally though is the ability to sort by GPU Memory on processes. eg:

You can already sort by GPU memory? The columns for GPU memory are called `GPU dedicated bytes` and `GPU shared bytes` ? 

![image](https://github.com/winsiderss/systeminformer/assets/1306177/981d8a66-e1cd-4a6f-95e9-1107d97948a6)

`GPU dedicated bytes` is memory from the graphics card.
`GPU shared bytes` is memory from RAM.

**Comment by djkato** [comment]
> They do have different cores. These are divided into nodes and are visible from the System Information window -> GPU section -> click the Nodes button.

Well, not quite from my research.

>CUDA is simply Nvidias API that gives developers access to the cores on the GPU. While I have heard the term "CUDA core", in graphics a CUDA core is analogous to a stream processor which is the type of processing core that the graphics cards use. CUDA runs programs on the graphics cores, the programs can be shaders or they can be compute tasks to do highly parallel tasks such as video encoding.
[src](https://superuser.com/a/856434)

Regardless though, I've seen screenshots with CUDA in the default task manager, but I don't have them neither in regular task manager nor sysinformer.


![image](https://github.com/winsiderss/systeminformer/assets/25299243/00e50e4f-e073-4076-be7d-8b411b88ac10)
I don't see CUDA here though? Or do I need a quatro card?

**Comment by djkato** [comment]
Thanks for the extensive details! I'll just rely on the generic 3D node. I did mention uptop that 3D has both CUDA and regular workloads underneath it, now I learned why ^^.
