### ISSUE TITLE
Add option to show changelog/commits when using self compiled version

### ISSUE THREAD

**Issue by MagicAndre1981** [winsiderss/systeminformer#1777]
When I use a self compiled version and check for updates, I get a message that I use a [pre-release version](https://github.com/winsiderss/systeminformer/blob/43b85946257582880aba5df5b1652cb4ce9c5dc5/plugins/Updater/page5.c#L190). Here I would also like to have a link to the changelog to see which commits are added after my compiled build

**Comment by dmex** [comment]
> I would also like to have a link to the changelog to see which commits are added after my compiled build

You'll see a changelog when syncing your local branch?

**Comment by MagicAndre1981** [comment]
yes, but when I run a self compiled version on a system without git and VS2022 I want to see if there are new commits so that I can pull the new commits on the dev system and compile it.

**Comment by MagicAndre1981** [comment]
thanks 👍
