### ISSUE TITLE
services tab in process hacker?

### ISSUE THREAD

**Issue by mikeezlove169** [winsiderss/systeminformer#1789]
i got the process hacker and i found the services tab but im dealing with something disableing services without my knowledge and i hate trying to chase it one by one to turn those back on we need an ability to shift select multiple items and activate their status settings and locks to save the setting the same issue with the services that dont allow multiple selections and only going one by one takes to many hours to chase and then so many that are seemingly locked without the ability to turn them on for wrong peramitors bs and i like to have mostly anything that makes my system fuly done processed not sitting dead silent  on crap being shut down without my haveing set it to shut down to disabled or any other setting so is there anything faster to set and keep those on or fast select multiple services ive tried and it just blinks back to one by one .....

**Comment by jxy-s** [comment]
> i got the process hacker 

Process Hacker is no longer supported or maintained, please consider downloading and use the System Informer nightly here: https://system-informer.com/nightly.php

> shift select multiple items and activate their status settings 

I apologize, but I don't fully understand what you're asking for. I'll try to answer. First, in System Informer you can select multiple services and issue start/stop/etc. commands to them. With respect to manipulating their "status settings". I think you asking for a "bulk edit" of their underlying properties. This isn't possible through System Informer. However you could achieve this in Windows itself using some scripting, registry editing, or using a system restore point.

> locks to save the setting 

Locking a service configuration down is tricky business. This is far outside the scope of System Informer.

> im dealing with something disableing services without my knowledge

I suggest tracking this down and removing it from your system before continuing with restoring any service configurations it might be modifying.

**Comment by mikeezlove169** [comment]
thank you looks about the same as but with more ...the service cuts are probly the optimizers of wise care and advanced system care or even ccleaner  i think they shut down some of the services but it seems to hit some i prefure...since i like my com fully ready to go and not missing out on preprocessed steps and thats why but yes looking for a batch process to services when theres just too many things to be chaseing one by one steps as ya know most things can be shift selected else where...it just needs a dialog thats similar but effects all selected because its not like they got varient feilds ...all pretty well the same ...i like the cleaners for other purposes but need the faster step for turning those back to auto start  instead of demand start and one by one is just too slow when there a hundreds to be turned back ...but thanks

**Comment by Masamune3210** [comment]
There is a simple solution if you don't like your services being disabled. Stop using those gross cleaning programs. Or if you insist on using them, only use them to clean up files, stay out of the "optimizers" and especially their stupid useless registry cleaners that cause untold amounts of issues because they don't know what they are doing and fundamentally do not need to exist. The registry does not need to be "cleaned"
