### ISSUE TITLE
Incorrectly reported I/O usage

### ISSUE THREAD

**Issue by arukateru** [winsiderss/systeminformer#1790]
### Brief description of your issue

Sometimes, while using SoftEther VPN, the write speed shown in Process Hacker goes all the way up to even 200MB/s. However, with using the default Windows task manager, no such disk activity is reported. Also, using CrystalDiskInfo, the written value doesn't increase even after using it for a little while, which especially leads me to believe it is a bug with Process Hacker.

![image](https://github.com/winsiderss/systeminformer/assets/84914212/fb0155c8-9fa3-41f7-9063-1a8fa703473f)

### Steps to reproduce (optional)

Install and connect to a VPN in SoftEther VPN

### Expected behavior (optional)

The actual I/O usage should be shown

### Actual behavior (optional)

An absurd amount of I/O usage is shown which is not picked up on by other applications

### Environment (optional)

```shell
Windows 10 LTSC 2019
```

**Comment by arukateru** [comment]
Update: I tried to install newer version: System Informer. And, look at that! My only disk attatched is the C: drive. So how can it be? Also, for clarification purposes, this is Windows 10 themed to look like Windows 7

![image](https://github.com/winsiderss/systeminformer/assets/84914212/8b2c90c8-0f83-4beb-a254-926eedde9260)

**Comment by dmex** [comment]
You're comparing apples with oranges... The I/O total column doesn't just include the disk but also kernel, user, page, pipes, mapped, unix socket etc... data copied across various boundaries (physical and virtual).

> using the default Windows task manager, no such disk activity is reported.

Task Manager doesn't support these values at all and the only other software that does is Process Explorer.

> The actual I/O usage should be shown

You need to add the Disk IO columns to compare disk usage.

> An absurd amount of I/O usage is shown which is not picked up on by other applications

These values are correct and you'll need Process Explorer to compare.
