### ISSUE TITLE
Process Hacker, Help me please, what did my son do to my machines?

### ISSUE THREAD

**Issue by kevincaines** [winsiderss/systeminformer#1791]
What did my son put on my Computer ?  Process Hacker...  What is it and or how do I get rid of it??? Its on both of my machines. Please help, the program info sent me here.

**Comment by kevincaines** [comment]
![Screenshot 2023-07-17 094025](https://github.com/winsiderss/systeminformer/assets/76895135/fa983bc4-f7bf-4e5d-afb7-7d882d74e8ea)

**Comment by kevincaines** [comment]
Can someone Email me or something? Thank you. Still trying to figure it out.

**Comment by jxy-s** [comment]
Process Hacker is an open source replacement for Task Manager. System Informer is the successor to Process Hacker. You can remove Process Hacker through "Add and remove programs".

**Comment by kevincaines** [comment]
Thank you I will try that.

**Comment by jxy-s** [comment]
I would also advise, since your son may have installed it, they may be helpful in removing it too.

**Comment by jxy-s** [comment]
To get to "Add and remove programs" to uninstall, follow these instructions:
1. Hold the Windows Key and press `r`
2. In the "Run" dialog, type `appwiz.cpl` and click `OK`
3. In the "Programs and Features" window look for "Process Hacker"
4. Double click it
5. Follow the prompts to uninstall the program

Alternatively you could try:
1. Hold the Windows Key and press `R`
2. In the "Run" dialog type `"C:\Program Files\Process Hacker 2\unins000.exe"` (with quotes) and click `OK`
3. Follow the prompts to uninstall the program

**Comment by kevincaines** [comment]
Thank you, No such luck.. This is what I got. 
![Screenshot 2023-07-17 161741](https://github.com/winsiderss/systeminformer/assets/76895135/d57bf614-f8dc-4abc-a303-0c1f9da9fe7b)
![Screenshot 2023-07-17 162016](https://github.com/winsiderss/systeminformer/assets/76895135/b4f8bad3-8186-4929-b0f5-94583b70f69a)
[Process Hacker Log.txt](https://github.com/winsiderss/systeminformer/files/12073958/Process.Hacker.Log.txt)

**Comment by kevincaines** [comment]
![Screenshot 2023-07-17 163139](https://github.com/winsiderss/systeminformer/assets/76895135/923d324f-bdf4-44d4-bd76-fb517d429423)

**Comment by kevincaines** [comment]
![image](https://github.com/winsiderss/systeminformer/assets/76895135/ff3b6ca5-a37c-4b56-8ff2-f9545a5d35af)

**Comment by kevincaines** [comment]
# @[https://github.com/winsiderss/systeminformer/issues/1791#issue-1807937134](url)

**Comment by kevincaines** [comment]
Sorry if I caused a problem, didn't mean to. I am just looking for a little help here.

**Comment by jxy-s** [comment]
Thanks for providing the screenshots.

> Sorry if I caused a problem, didn't mean to. I am just looking for a little help here.

Not a problem, I know this can be frustrating. I'll try to provide assistance.

> It won't let me Chang any settings back or remove anything. I'm still admin and the only account on here, but it is useless. Its on my wives new Lenovo and it's getting the blue screen every other booty. I could really use some Help..

Based on this description and the behavior your experiencing interacting with the operating system. Something has damaged the operating system and/or your user account. It's a likely some other unwanted software has caused damage to your system. It's also possible your machines have been compromised/infected. You could try some of these recovery options and instructions from Microsoft: https://support.microsoft.com/en-us/windows/recovery-options-in-windows-31ce2444-7de3-818c-d626-e3b5a3024da5

I would recommend the actions listed under "Your PC isn't working well and you recently installed an app." or "You suspect your device has been infected.".

We are really approaching topics and troubleshooting that are outside the scope of this forum - my best advise would be to seek a local support tech.

**Comment by jxy-s** [comment]
I will add, don't trust phone-in or online support tech services- they're full of scammers. The best option would be a local store (like BestBuy or similar).

**Comment by kevincaines** [comment]
Thank you all so much.  And your correct, wife somehow erased, damaged or corrupted sys.32 files in the library somehow.  getting it taken care of. Again, Thank you. Kevin MS Insider 5 years.
