### ISSUE TITLE
appveyor daily build has been broken for over a month.

### ISSUE THREAD

**Issue by sonyps5201314** [winsiderss/systeminformer#1793]
### Brief description of your issue

`
Build started
git clone -q --branch=master https://github.com/winsiderss/systeminformer.git C:\projects\systeminformer
git checkout -qf b0c0096[2](https://ci.appveyor.com/project/winsiderss/systeminformer#L2)fdf59[3](https://ci.appveyor.com/project/winsiderss/systeminformer#L3)58d1fb7f2[4](https://ci.appveyor.com/project/winsiderss/systeminformer#L4)a81323ea1df2b392
tools\CustomBuildTool\bin\Release\CustomBuildTool.exe -appveyor
Windows: 10.0.17763.4010 (WinBuild.160101.0800)
WindowsSDK: 10.0.22621.0
VisualStudio: VisualStudio/17.[5](https://ci.appveyor.com/project/winsiderss/systeminformer#L5).4+33530.505
Building... 3.0.1129[6](https://ci.appveyor.com/project/winsiderss/systeminformer#L6).6[7](https://ci.appveyor.com/project/winsiderss/systeminformer#L7)6[9](https://ci.appveyor.com/project/winsiderss/systeminformer#L9) (b0c0096) [HEAD]
[00:00] Building SystemInformer (x32)...
[ERROR] (1) LIB : fatal error C1900: Il mismatch between 'P1' version '2022[12](https://ci.appveyor.com/project/winsiderss/systeminformer#L12)15' and 'P2' version '20220715' [C:\projects\systeminformer\phlib\phlib.vcxproj]LINK : fatal error LNK1257: code generation failed [C:\projects\systeminformer\phlib\phlib.vcxproj]
Command exited with code 1
`

**Comment by dmex** [comment]
It's not broken just outdated, we're running builds locally.

**Comment by sonyps5201314** [comment]
So how do users download the latest daily automatic build version?

**Comment by dmex** [comment]
> So how do users download the latest daily automatic build version?

The exact same way as before? We just haven't updated the build.
