### ISSUE TITLE
Building error

### ISSUE THREAD

**Issue by henrypp** [winsiderss/systeminformer#1795]
when i run `build\build_release.cmd` it recieve this error:

`[ERROR] (1) LIB : fatal error C1900: Il mismatch between 'P1' version '20221215' and 'P2' version '20220715' [..\systeminformer\phlib\phlib.vcxproj]LINK : fatal error LNK1257: code generation failed [D:\projects\!repos\systeminformer\phlib\phlib.vcxproj]`

only debug build was success.

do not understand,where is the problem?

**Comment by MagicAndre1981** [comment]
have you called `build_thirdparty.cmd` before `build_release.cmd`?

**Comment by henrypp** [comment]
@MagicAndre1981 if debug was sucessful,then no requirement for build_thirdparty.cmd
