### ISSUE TITLE
show "SeLockMemoryPrivilege" on process token tab

### ISSUE THREAD

**Issue by luciouskami** [winsiderss/systeminformer#1797]
I noticed that the "token" tab in the "process" property page in systeminformer is missing the display of the "SeLockMemoryPrivilege" privilege property.

![pic](https://github.com/winsiderss/systeminformer/assets/10268785/0b3cfa18-f572-4d51-a776-c0711a36f7b8)

One use case for this privilege attribute is the following link:

[Address Windowing Extensions](https://learn.microsoft.com/en-us/windows/win32/memory/address-windowing-extensions)

My attempt to enable the privilege property using Systeminformer also failed, but it worked using the windows api, as shown here:

```cpp
      	bool SetSeLockMemoryPrivilege()
        {
            bool v_ret_val{false};
#if 0

#else
            HANDLE hToken;
            LUID luid;
            TOKEN_PRIVILEGES tkp = {};
#endif


            for(;;)
            {
#if 1
                const auto status = PhAdjustPrivilege(const_cast<PWSTR>(L"SeLockMemoryPrivilege"),0,TRUE);

                if (!NT_SUCCESS(status))
                {
                    break;
                }
#else
                if (!OpenProcessToken(GetCurrentProcess(), TOKEN_ADJUST_PRIVILEGES | TOKEN_QUERY, &hToken))
                {
		            break;
	            }
                	LookupPrivilegeValue(nullptr, SE_LOCK_MEMORY_NAME, &tkp.Privileges[0].Luid);
	            	tkp.PrivilegeCount = 1;  // one privilege to set
	            	tkp.Privileges[0].Attributes = SE_PRIVILEGE_ENABLED;
	 
                if (FALSE == AdjustTokenPrivileges(hToken, FALSE, &tkp, 0,nullptr, nullptr))
                {
                     break;
                }
#endif
                v_ret_val = true;
                break;
            }
#if 0
            CloseHandle(hToken);
#endif
            return v_ret_val;
        }
```

**Comment by dmex** [comment]
> I noticed that the "token" tab in the "process" property page in systeminformer is missing the display of the "SeLockMemoryPrivilege" privilege property

System Informer will only show privileges currently present in the token you're viewing. The SeLockMemoryPrivilege privilege is missing because the token you're viewing doesn't have the privilege. 

If the privilege has been removed from the token then it won't be visible. Windows doesn't record deleted privileges and showing a non-existent privilege would be misleading since the token would appear to have privileges that don't exist and cannot be deleted.

> My attempt to enable the privilege property using Systeminformer also failed

You won't be able to enable it because:
* Windows prohibits applications from enabling a privilege unless they're present in the token.
* Windows prohibits applications from adding a privileges after the program has started executing.
* Windows doesn't allow creation of tokens with privileges unless the current user has rights to the privilege (generally configured via group policy).

You need to edit group policy, add your username to the policy and restart:
https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/lock-pages-in-memory#location

>  it worked using the windows api, as shown here:

You code returns an unassigned error code? PrivilegeCheck also failed:

```
BOOLEAN privilegeEnabled = FALSE;
PRIVILEGE_SET requiredPrivileges;

requiredPrivileges.PrivilegeCount = 1;
requiredPrivileges.Control = PRIVILEGE_SET_ALL_NECESSARY;
requiredPrivileges.Privilege[0].Luid.LowPart = SE_LOCK_MEMORY_PRIVILEGE;
requiredPrivileges.Privilege[0].Attributes = SE_PRIVILEGE_ENABLED;
PrivilegeCheck(GetCurrentProcessToken(), &requiredPrivileges, &privilegeEnabled);

if (privilegeEnabled)
{
    printf("PRIVILEGE_ENABLED\n");
}
```

**Comment by luciouskami** [comment]
> > I noticed that the "token" tab in the "process" property page in systeminformer is missing the display of the "SeLockMemoryPrivilege" privilege property
> 
> System Informer will only show privileges currently present in the token you're viewing. The SeLockMemoryPrivilege privilege is missing because the token you're viewing doesn't have the privilege.
> 
> If the privilege has been removed from the token then it won't be visible. Windows doesn't record deleted privileges and showing a non-existent privilege would be misleading since the token would appear to have privileges that don't exist and cannot be deleted.
> 
> > My attempt to enable the privilege property using Systeminformer also failed
> 
> You won't be able to enable it because:
> 
> * Windows prohibits applications from enabling a privilege unless they're present in the token.
> * Windows prohibits applications from adding a privileges after the program has started executing.
> * Windows doesn't allow creation of tokens with privileges unless the current user has rights to the privilege (generally configured via group policy).
> 
> You need to edit group policy, add your username to the policy and restart: https://learn.microsoft.com/en-us/windows/security/threat-protection/security-policy-settings/lock-pages-in-memory#location
> 
> > it worked using the windows api, as shown here:
> 
> You code returns an unassigned error code? PrivilegeCheck also failed:
> 
> ```
> BOOLEAN privilegeEnabled = FALSE;
> PRIVILEGE_SET requiredPrivileges;
> 
> requiredPrivileges.PrivilegeCount = 1;
> requiredPrivileges.Control = PRIVILEGE_SET_ALL_NECESSARY;
> requiredPrivileges.Privilege[0].Luid.LowPart = SE_LOCK_MEMORY_PRIVILEGE;
> requiredPrivileges.Privilege[0].Attributes = SE_PRIVILEGE_ENABLED;
> PrivilegeCheck(GetCurrentProcessToken(), &requiredPrivileges, &privilegeEnabled);
> 
> if (privilegeEnabled)
> {
>     printf("PRIVILEGE_ENABLED\n");
> }
> ```
Thank you.
