### ISSUE TITLE
Not working Nightly Builds

### ISSUE THREAD

**Issue by f9-w** [winsiderss/systeminformer#1800]
### Brief description of your issue

Latest Nightly Build from Wednesday, 21st of June, 2023
https://systeminformer.sourceforge.io/nightly.php
Where the new nightly builds?

**Comment by dmex** [comment]
Waiting for Appveyor build image update to 17.6.5

**Comment by wmjordan** [comment]
I've just downloaded the nightly build and it keeps crashing on my computer.
Where can I download a working version?
