### ISSUE TITLE
where is windows 10?

### ISSUE THREAD

**Issue by metemrc61** [winsiderss/systeminformer#1804]
![image](https://github.com/winsiderss/systeminformer/assets/137706464/d971c52d-51ea-4ff9-be3c-70cc65c5abcd)

**Comment by jxy-s** [comment]
Process Hacker is no longer supported. Nightly builds for System Informer are here:

https://system-informer.com/nightly.php

**Comment by metemrc61** [comment]
What is the difference between system informer and process hacker?

**Comment by metemrc61** [comment]
thank you bro
