### ISSUE TITLE
Unable to edit memory: An attempt was made to access an exiting procces

### ISSUE THREAD

**Issue by imjusthereforprocesshacker** [winsiderss/systeminformer#1808]
I'm just so confused on what this means, I'm trying to overwrite this string but it just keeps doing this over and over again

**Comment by dmex** [comment]
The program was terminated and any memory was deleted.

**Comment by imjusthereforprocesshacker** [comment]
Oh okay but do you know why when I try to write strings the program just
crashes?

**Comment by dmex** [comment]
No clue, there could be hundreds of reasons. You need to debug that program and check the assembly and stack trace to know what's casuing the problem.

1) It's common for some types of programs to hash strings for table lookup, modifying the string would generate a hash that doesn't exist in the table and crash the program.
2) It's also common for programs to change the memory after you've opened the memory editor, you could also be overwriting the memory with stale/outdated/unexpected contents so make sure the process is suspended before doing anything.

**Comment by imjusthereforprocesshacker** [comment]
Ohhhhh that’s so smart thanks bro, I’ll try number 2 and get back to you.

**Comment by imjusthereforprocesshacker** [comment]
so i tried number 2 because i didnt completely understand number 1, so
first i suspended the program then i tried to overwrite the string, but the
second i resumed the process it crashed, it said it couldnt make changes to
a exiting process

**Comment by imjusthereforprocesshacker** [comment]
[image: image.png]

**Comment by imjusthereforprocesshacker** [comment]
actually, void all of that imagine as if i never sent it. Do you know how
to make other programs say this? [image:
e47230fb-9520-4b58-bb1e-62aa82d175dd.png]

**Comment by dmex** [comment]
Github doesn't show any attachments you've sent via email. You need to attach them from the issue on the website: https://github.com/winsiderss/systeminformer/issues/1808

**Comment by imjusthereforprocesshacker** [comment]
Oh okay, these were the screenshots I was talking about ![image](https://github.com/winsiderss/systeminformer/assets/141767935/a467d65b-baf7-40fa-8346-2b0e0e045d04) like if you could make the other program say that, that would fix all of my problems

**Comment by imjusthereforprocesshacker** [comment]
Do you know how I can use this, I'm new and I don't want to mess anything up on my pc 😭😭.

**Comment by imjusthereforprocesshacker** [comment]
Like what is control and driver?

**Comment by imjusthereforprocesshacker** [comment]
![image](https://github.com/winsiderss/systeminformer/assets/141767935/3ba34caf-4d21-4267-a886-3941711415cd)
so i did some reading but then i got this

**Comment by imjusthereforprocesshacker** [comment]
did i do something wrong?

**Comment by dmex** [comment]
Microsoft doesn't provide a working sample by default. you need to enable test singing mode, compile the driver and sign it.

> Do you know how I can use this, I'm new and I don't want to mess anything up on my pc

Those samples won't be much use without knowing how to compile and debug.

> if you could make the other program say that, that would fix all of my problems

Are you trying to block memory access or something else?

**Comment by imjusthereforprocesshacker** [comment]
like I want to block memory access for another app, like Roblox, or for example, just hide the strings from showing.

**Comment by imjusthereforprocesshacker** [comment]
![image](https://github.com/winsiderss/systeminformer/assets/141767935/bbb51470-c5a8-437e-bd1a-0c31acb17bc2)
so basically, i have some people who are going to be looking on my pc for stuff, and i want to hide it becuase i dont want them to see the stuff i have on my pc

**Comment by imjusthereforprocesshacker** [comment]
but idk how to hide the stuff (the picture above is the stuff im trying to hide btw)

**Comment by imjusthereforprocesshacker** [comment]
> Those samples won't be much use without knowing how to compile and debug.

how did u even learn bro it's like a different language when I try to read it

**Comment by imjusthereforprocesshacker** [comment]
> ![image](https://user-images.githubusercontent.com/141767935/260139975-bbb51470-c5a8-437e-bd1a-0c31acb17bc2.png) so basically, i have some people who are going to be looking on my pc for stuff, and i want to hide it becuase i dont want them to see the stuff i have on my pc

hello bro

**Comment by dmex** [comment]
>  so basically, i have some people who are going to be looking on my pc for stuff, and i want to hide it becuase i dont want them to see the stuff i have on my pc

You should just create a local user from Windows settings:
https://support.microsoft.com/en-us/windows/create-a-local-user-or-administrator-account-in-windows-20de74e0-ac7f-3502-a866-32915af2a34d

Login as the current user --> Press CTRL+ALT+DEL --> Click `Switch User` --> Login with the new account.

The switch user option lets you run programs from both accounts simultaneously, the other account cannot access files, processes and memory etc... so run whatever program with your current admin account then switch to the standard user before letting anyone use your machine and they won't be able to access anything. 

If they open an 'Administrator' prompt it'll ask for your password, tell them that's your parents account and close it. If you do accidentally give them admin, flip the power switch and blame the weather 😜

If they try viewing memory it'll just show access denied:
![image](https://github.com/winsiderss/systeminformer/assets/1306177/a5015b5f-f2fd-4278-9b1e-7ffe02075f5f)

**Comment by imjusthereforprocesshacker** [comment]
He’s the goat I’m going to try this thanks man

**Comment by imjusthereforprocesshacker** [comment]
sadly this didn't work i don't think I did it right
