### ISSUE TITLE
Find Misses ?:\$Extend\$RmMetadata\$Txf...

### ISSUE THREAD

**Issue by TheSQLGuru** [winsiderss/systeminformer#1811]
In seeking to find out why external drive is failing to disconnect, I searched for t:\ with SI. It showed nothing open with that prefix. Using Process Explorer, the usual 4 files that have the prefix shown in the title of this post were found. Images attached. 

I feel it is a bug to not find/show such files. 

SI version 3.0.6806, Win 11 x64 patched up.

![System Informer Not Find Drive](https://github.com/winsiderss/systeminformer/assets/2779491/d938d63e-a431-411c-85c5-ca67fccda1f2)
![Process Explorer Drive Search Results](https://github.com/winsiderss/systeminformer/assets/2779491/1a537e41-fa07-4c89-adcd-899d78bd80d1)

**Comment by dmex** [comment]
Does System Informer have administrative privileges and have you selected the  `Enable kernel-mode driver` option in the `General` settings? The main window contains a `+` symbol when the driver and user have admin.

The system process (PID 4) is protected and without both of those being true it cannot enumerate those processes. Also the System Informer kernel driver is disabled by default while the Process Explorer kernel driver is enabled by default.

**Comment by MagicAndre1981** [comment]
if you have Taskmgr running, close it before trying to eject the drive.

**Comment by TheSQLGuru** [comment]
I apologize for ghosting my submission. I was in Admin mode, but I did not have the kernel-mode driver selected. Enabling that caused the expected behavior to materialize. 

Thanks for the comment, and kudos for releasing such an AMAZING utility!!
