### ISSUE TITLE
Filter altitude allocation request

### ISSUE THREAD

**Issue by DavidXanatos** [winsiderss/systeminformer#1816]
In https://github.com/winsiderss/systeminformer/blob/fc8f1e12ff0e2649b93c3cf05996d62bcd225fc3/SystemInformer/settings.c#L335C8-L335C8
i see that SI is using altitude 385400 which according to https://learn.microsoft.com/en-us/windows-hardware/drivers/ifs/allocated-altitudes is allocated to AppVMon.sys Microsoft.
Why not request your own?
May this be one of the reasons for problems?

**Comment by jxy-s** [comment]
> Why not request your own?

Haven't gotten around to it. I'll put in a request soon. I honestly forgot to go back and make a request after the initial changes went in. Thanks for bringing this up to remind me 😄.

> May this be one of the reasons for problems?

I wouldn't think so, there's plenty of filters out there that exist without formal registration. Obviously there is the possibility of a collision with the default today. It's configurable option so the user can easily rectify it if it does collide.

When we were choosing one, I did reference this list to choose one close to procmon, however it seems I just overlooked there is already one at that altitude.

**Comment by jxy-s** [comment]
> The Microsoft File System Filter team has allocated the altitude 385210.5 for your : SystemInformer.sys minifilter.

Their website hasn't been updated yet. But we've been assigned the altitude and I've updated it here: https://github.com/winsiderss/systeminformer/commit/46fff2e2bcc95b03976e50c47cabe167e6f7725c
