### ISSUE TITLE
Network Total Rate is not displayed

### ISSUE THREAD

**Issue by rqueizan** [winsiderss/systeminformer#1822]
### Brief description of your issue

Network Total Rate is not displayed

### Steps to reproduce (optional)

Show tab Network.
Sort by Total Rate.
![image](https://github.com/winsiderss/systeminformer/assets/18214796/2c740f78-2144-4c48-88ba-c7e6b8f7a53b)

### Expected behavior (optional)

Total, Send and Receive Rate should be displayed.

### Actual behavior (optional)

Neither of Total, Send and Receive Rate is displayed.

### Environment (optional)

```shell
System Informer 3.0.7029 (f647fb0)
Windows 11 Enterprise 22H2 Build 22621.2134
AMD Ryzen 5 4600H with Radeon Graphics
```

**Comment by rqueizan** [comment]
In tab Process is working well:
![image](https://github.com/winsiderss/systeminformer/assets/18214796/9060516e-4341-4223-9b10-e6d0ccc8d42a)
But in tab Network still not working:
![image](https://github.com/winsiderss/systeminformer/assets/18214796/350feef4-358b-4882-8663-a732ecb693d3)

**Comment by dmex** [comment]
> But in tab Network still not working:

@rqueizan The next update fixes the issue👍
