### ISSUE TITLE
CrowdStrike and several vendors detect this as malware.

### ISSUE THREAD

**Issue by Retoxx2** [winsiderss/systeminformer#1824]
### Brief description of your issue

This install is blocked by CrowdStrike as malicious activity, and all files are quarantined. 

### Steps to reproduce (optional)

Simply try to install on a system running CrowdStrike, Symantec, Acronis, Trellix, etc.. or just throw the exe at virustotal.com.

### Expected behavior (optional)

I would expect the program to not attempt malicious activities that would cause CrowdStrike or any other AV solution to raise alarms.

### Actual behavior (optional)

"CrowdStrike has detected malicious activity and as a result has quarantined the file 'systeminformer-setup.exe'."

### Environment (optional)

```shell
Happens with latest nightly build.

Copyright	
Copyright (c) Winsider Seminars & Solutions, Inc. All rights reserved.

Product	
System Informer

Description	
System Informer - Setup

Original Name	
systeminformer-setup.exe

Internal Name	
systeminformer-setup.exe

File Version	
3.0.11556.7029

https://www.virustotal.com/gui/file/908ec453dd818ec97b01718fb29c5a1c4825ad1405902843bebfa5881b05d6a1/details
```

**Comment by DavidOsipov** [comment]
Standard trouble up until the software gets digitally signed. Because of the open source nature of the software, malicious actors use parts of the code in their malware, which in turn leads the software being detected by AV companies. Long time users know about that and we are used to this.

**Comment by Retoxx2** [comment]
Ok... was hoping to test at work, but that's going to be a no-go for ISC.  Bummer.
