### ISSUE TITLE
Collapse by default doesn't work with some processes

### ISSUE THREAD

**Issue by p-yukusai** [winsiderss/systeminformer#1825]
### Brief description of your issue

The option to collapse child processes by default does not work for some executables, for example Brave.
If I got an option wrong or it is some other issue on my end please let me know.

### Steps to reproduce (optional)

[collapse bug.webm](https://github.com/winsiderss/systeminformer/assets/85849071/6ae61a99-bdbb-4b0e-90be-95edab74daeb)

### Expected behavior (optional)

For the child processes to collapse on process launch as expected. 

### Environment (optional)

```shell
System Informer 3.0.7029
Windows 11 Pro 22H2
```

**Comment by dmex** [comment]
I wasn't able to reproduce your video and Brave always collapses when the option is selected on my machine?

1) Did you install System Informer using some package manager, install from setup.exe or are you running the bin.zip portable version?
2) Does the Options > UserNotes window have an entry for Brave?
![image](https://github.com/winsiderss/systeminformer/assets/1306177/9aa1cb26-66ac-4d85-8e23-93c0df2ad8a7)

3) Does the option work if you reset settings?

* Exit System Informer
* Rename the `%AppData%\SystemInformer\`  directory to `SystemInformer_BAK`
* Try setting brave to collapse and check the UserNotes options.

**Comment by p-yukusai** [comment]
Hello!
1.- I use the official installer and update from inside the application.
2.- Yes 
![image](https://github.com/winsiderss/systeminformer/assets/85849071/b34e3b31-d8fe-4744-b712-10ffa08c97ef)
3.- Resetting the settings makes it work as intended now, it would seem the settings interfered with the processes' collapse by default check in some way or another.
![image](https://github.com/winsiderss/systeminformer/assets/85849071/c53439f1-1814-4c37-a18d-e38fac8d81fc)

**Comment by dmex** [comment]
> Here's the settings file

Thanks, the problem was related to the `Hide System Processes` option. The next update will fix the issue 👍
