### ISSUE TITLE
[Feature Request]Added "Create Full Dump" context menu

### ISSUE THREAD

**Issue by pedoc** [winsiderss/systeminformer#1840]
### Description of the feature, modification, idea or suggestion

Hello, thank you for your great work

Currently, only a "mini dump" of the process can be created, but sometimes we want a "full dump" for program debugging

So I want to be able to have a context menu in the process list for creating a "full dump",
Thanks

Current:
![image](https://github.com/winsiderss/systeminformer/assets/6604230/8690068a-47cf-4771-b160-19bda8f62ea0)

**Comment by jxy-s** [comment]
The "minidump" is already mostly full dump, the same you would get with task manager. I am adding options that would give you more control on what you would get in the dump. Would something like this meet your expectations?

![image](https://github.com/winsiderss/systeminformer/assets/11687482/788c0486-4e27-46a2-a00d-3a5f0c9dc2d5)

```cpp
    switch (DumpType)
    {
    case PhProcessDumpTypeMinimal:
        context->DumpType =
            MiniDumpWithDataSegs |
            MiniDumpWithUnloadedModules |
            MiniDumpWithThreadInfo |
            MiniDumpIgnoreInaccessibleMemory;
        break;
    case PhProcessDumpTypeLimited:
        context->DumpType =
            MiniDumpWithFullMemory |
            MiniDumpWithUnloadedModules |
            MiniDumpWithFullMemoryInfo |
            MiniDumpWithThreadInfo |
            MiniDumpIgnoreInaccessibleMemory;
    default: case PhProcessDumpTypeNormal:
        // task manager uses these flags (wj32)
        context->DumpType =
            MiniDumpWithFullMemory |
            MiniDumpWithHandleData |
            MiniDumpWithUnloadedModules |
            MiniDumpWithFullMemoryInfo |
            MiniDumpWithThreadInfo |
            MiniDumpIgnoreInaccessibleMemory |
            MiniDumpWithIptTrace;
        break;
    case PhProcessDumpTypeFull:
        context->DumpType =
            MiniDumpWithDataSegs |
            MiniDumpWithFullMemory |
            MiniDumpWithHandleData |
            MiniDumpWithUnloadedModules |
            MiniDumpWithIndirectlyReferencedMemory |
            MiniDumpWithProcessThreadData |
            MiniDumpWithPrivateReadWriteMemory |
            MiniDumpWithFullMemoryInfo |
            MiniDumpWithCodeSegs |
            MiniDumpWithFullAuxiliaryState |
            MiniDumpWithPrivateWriteCopyMemory |
            MiniDumpIgnoreInaccessibleMemory |
            MiniDumpWithTokenInformation |
            MiniDumpWithModuleHeaders |
            MiniDumpWithAvxXStateContext |
            MiniDumpWithIptTrace;
        break;
    }
```

I am also adding an option specific for "System" that assists in generation of live kernel dumps:
![image](https://github.com/winsiderss/systeminformer/assets/11687482/92051f99-3e0d-4337-94da-f5b30df2e3ef)

**Comment by jxy-s** [comment]
Added: https://github.com/winsiderss/systeminformer/commit/cf92171764d3653fccc68a944226cc8d2cf62957

**Comment by pedoc** [comment]
nice,thank you
