### ISSUE TITLE
Sign nightly bits

### ISSUE THREAD

**Issue by manastalukdar** [winsiderss/systeminformer#185]
Please consider digitally signing the bits provided in the nightly builds.

**Comment by ge0rdi** [comment]
+1

Though it seems certificate used to sign _release_ Process Hacker binaries expired about a year ago.
Not sure there is new one ...

**Comment by manastalukdar** [comment]
Happy to make a contribution if a crowdfunding effort to buy a new certificate is set up.

**Comment by Bodup** [comment]
Would also like this since I can't run the nightly versions due to a enforced code integrity policy

**Comment by dmex** [comment]
The nightly builds are compiled by Appveyor/Github whom don't support Windows code signing certificates. The updater checks for a ECDSA sha256 signature for nightly builds but otherwise you should use stable builds which have Windows code signing.
