### ISSUE TITLE
wrong strings in resource files

### ISSUE THREAD

**Issue by jxzhxch** [winsiderss/systeminformer#1850]
### Brief description of your issue

![图片](https://github.com/winsiderss/systeminformer/assets/5178662/33d67fb5-160e-4f34-9781-c1206529e694)

**Comment by dmex** [comment]
Those strings are intentionally incorrect. We're planning to implement localization support in the near future and these strings are what's called pseudolocalization and are  required to identify bugs and other problems before implementing localization. 

Pseudotranslation is documented by Microsoft here and explains the process:
https://learn.microsoft.com/en-us/globalization/methodology/pseudolocalization

The strings will be replaced with their original english text once any localization issues are resolved and implemented 👍
