### ISSUE TITLE
System tray always shows cpu usage regardless of configuration.

### ISSUE THREAD

**Issue by chrcoluk** [winsiderss/systeminformer#1852]
### Brief description of your issue

Go to options.

ToolStatus

Is taskbar configuration, set this to commit charge history (or anything else that isnt cpu usage), and the graphs stays as cpu usage, even after restarting system informer.

### Environment (optional)

```shell
Nightly 3.0.7309
Windows 10 21H2 64bit.
```

**Comment by dmex** [comment]
>  options > ToolStatus

 These options do not change the tray icons and will only change the taskbar application icon. 

> set this to commit charge history (or anything else that isnt cpu usage), and the graphs stays as cpu usage

Tray icons can only be changed using the `Main Window > View menu > Tray Icons` menu. You need to use this menu to change the tray icons.

**Comment by chrcoluk** [comment]
Thanks, confirmed its working as expected.
