### ISSUE TITLE
Newest windows 11 update from 26.09.2023 needs support, kernel version 10.0.22621.2361

### ISSUE THREAD

**Issue by DavidXanatos** [winsiderss/systeminformer#1855]
After installing the latest windows 11 update which enable some 23H2 functions (not insider or preview) the SI driver says it needs an update.
reported kernel version: 10.0.22621.2361

PS: on some of my machines this happens on its own on others the enablement update kb5027397 causes it, seams the Rollout is done in stages.

**Comment by jxy-s** [comment]
Support was added already here: https://github.com/winsiderss/systeminformer/commit/d1a6baf440e357f1c1806554ad97df4a5972c3de

It's on the train for the next build 👍
