### ISSUE TITLE
Suggest adding the PhExecuteRunAsCommand3 function to the output API list in the SystemInformer.def file

### ISSUE THREAD

**Issue by sqlnew** [winsiderss/systeminformer#1860]
### Description of the feature, modification, idea or suggestion

I used the SystemInformer project as a DLL to call functions inside, which is very useful. Thank you for this great project!
Suggest adding the PhExecuteRunAsCommand3 function to the output API list in the SystemInformer.def file!
In order to conveniently call this function to specify the user to run the program.

**Comment by dmex** [comment]
We only use the definition file for library exports and when they're required for plugin support. This function probably won't be exported because it's not used by plugins but feel free to compile your own builds with changes to the exports 👍
