### ISSUE TITLE
Unable to start the firewall event tracing session: Access is denied. (5)

### ISSUE THREAD

**Issue by Cyber5imon** [winsiderss/systeminformer#1862]
The Firewall tab shows: **_Unable to start the firewall event tracing session: Access is denied. (5)_**

What would cause this and how can I troubleshoot this?

**Comment by dmex** [comment]
1) Are you running the program as Administrator?
2) Have you installed third party software for modifying firewall rules (e.g. simplewall)?

**Comment by dmex** [comment]
Closing as inactive/unreproducible
