### ISSUE TITLE
Ping graph

### ISSUE THREAD

**Issue by rqueizan** [winsiderss/systeminformer#1869]
### Description of the feature, modification, idea or suggestion

It would be interesting if the failed pings were displayed on the graph, with a red dot, or a red bar.
To have information on connection problems at a glance, including the trend of errors.

### Proposed implementation details (optional)

![image](https://github.com/winsiderss/systeminformer/assets/18214796/ac3638cc-4044-4bac-b7c2-93a9915a3d23)

**Comment by dmex** [comment]
Tracking the response time for failed pings is a good idea (and show the maximum value) with something like:

![image](https://github.com/winsiderss/systeminformer/assets/1306177/137c9d8b-ecb0-43c4-8237-a19babf5656d)

The response time for failed pings would also indicate the source or hop. For example if there's 10 servers and 100ms latency:
< 10ms = local network fault
< 50ms = server 5 or 6 fault
< 70ms = frontend fault
< 90ms = server fault

**Comment by rqueizan** [comment]
> Tracking the response time for failed pings is a good idea (and show the maximum value) with something like:
> 
> ![image](https://user-images.githubusercontent.com/1306177/277060724-24284603-78e0-4e38-a791-32c11d33aa9c.png)
> 
> The response time for failed pings would also indicate the source or hop. For example if there's 10 servers and 100ms latency: < 10ms = local network fault < 50ms = server 5 or 6 fault < 70ms = frontend fault < 90ms = server fault

I really like your idea. It's very interesting.
