### ISSUE TITLE
New Windows 10 kernel, "Unable to load kernel driver"

### ISSUE THREAD

**Issue by token0** [winsiderss/systeminformer#1870]
[Window Title]
System Informer

[Main Instruction]
Unable to load kernel driver

[Content]
The kernel driver is not yet supported on this kernel version. Request support by submitting a GitHub issue with the Windows Kernel version.

Windows 10 22H2 10.0.19045
Windows Kernel 10.0.19041.3570
System Informer 3.0.7256 (121e1d2)

![image](https://github.com/winsiderss/systeminformer/assets/4627595/3365de7a-d323-411e-a6c1-4189204cc5bb)

**Comment by jxy-s** [comment]
Duplicate: https://github.com/winsiderss/systeminformer/issues/1823

Help > Check for updates
