### ISSUE TITLE
Add source index to PDBs

### ISSUE THREAD

**Issue by ge0rdi** [winsiderss/systeminformer#1871]
### Description of the feature, modification, idea or suggestion

It seems that you are finally providing PDBs for `SystemInformer` builds (at least looking at release assets in `si-builds` repo). Which is cool and I hope it is intentional 😄 

It will be great to have also _source index_ in those PDBs so that debuggers will be able to automatically fetch proper version of source files from github. This makes analysis of crash dumps a lot easier as there is no need to look for proper revision of given file manually.

Here is nice guide that explains how the source index works and how to add it to PDBs:
https://gist.github.com/baldurk/c6feb31b0305125c6d1a#source-indexing

I have some experience with that as I did similar thing (based on that guide) for [project](https://github.com/Open-Shell/Open-Shell-Menu/blob/master/Src/Setup/CreateSourceIndex.bat) I'm maintaining.
So I'd like to help with the implementation in `SystemInformer` if you are interested in it.

**Comment by MagicAndre1981** [comment]
new way is to use [sourcelink](https://github.com/dotnet/sourcelink#using-source-link-in-c-projects), which adds a json to the PDB which includes url to the source and debugger can use this url to fetch source files.

**Comment by ge0rdi** [comment]
@MagicAndre1981 
Thank you for pointing this out.

Unfortunately, `SystemInformer` uses _deterministic builds_ where relative source paths are stored in PDB (such as `SystemInformer\main.c`).
`Source Link` seems to not support that. It always generates _json_ file with absolute source paths. At least I wasn't able to convince it to do otherwise.
This issue should be related [Epic: Deterministic build support](https://github.com/dotnet/sourcelink/issues/601).

Though I think we don't even need to use `Source Link` toolset.
We can just generate simple _json_ file like this at the beginning of build:
```
{"documents":{"*":https://raw.githubusercontent.com/winsiderss/systeminformer/155715a8ae3f3499f0a3480aa8c6de1c4be85de4/*"}}
```
And then include it in PDBs using `/sourcelink:sourcelink.json` linker switch.

This will basically map all local paths (relative to repo root) to actual remote repo paths.
It seems to work nicely (at least in WinDbg).

**Comment by MagicAndre1981** [comment]
sourcelink works with deterministic builds as it is done with [this package for .net libs](https://github.com/dotnet/reproducible-builds#dotnetreproduciblebuilds-nuget-package).

And source link generates this json on its own

**Comment by ge0rdi** [comment]
It still generates _json_ with absolute local paths. But it seems it doesn't matter.
I haven't tested it originally as I thought it cannot match the path if there is absolute path to repo root in json and relative repo paths in PDB. But now I tried and it somehow works 😅 

Even with original [Using Source Link in C++ projects](https://github.com/dotnet/sourcelink#using-source-link-in-c-projects) instructions.

So it should be really just about adding few _nuget_ packages to the projects.
Which is cool.
Thanks again.

**Comment by MagicAndre1981** [comment]
> But now I tried and it somehow works 😅

MS added source link support in VS2017 times to VS and windbg and VS is using source link in "go to definition" to get the source with the help of source link.

> So it should be really just about adding few _nuget_ packages to the projects. Which is cool. Thanks again.

yes, great idea and improved debugging of 3rd party libs a lot.

**Comment by dmex** [comment]
@ge0rdi 

https://www.kenmuse.com/blog/an-intro-to-sourcelink/

**Comment by MagicAndre1981** [comment]
looks like Sourcelink is missing from driver PDB @dmex I checked the dmp from #2887 and found that source info are missing from the kernel driver PDB

**Comment by ge0rdi** [comment]
> looks like Sourcelink is missing from driver PDB

Yup, it can be easily verified by running:
`"C:\Program Files (x86)\Windows Kits\10\Debuggers\x64\srcsrv\pdbstr.exe" -r -p:systeminformer.pdb -s:sourcelink$1 -i:sourcelink`

It doesn't produce any output for driver PDB.
It saves SourceLink stream for user-mode PDB (which works nicely in Windbg).
