### ISSUE TITLE
After update KB5031455 the dyn data is again outdated

### ISSUE THREAD

**Issue by DavidXanatos** [winsiderss/systeminformer#1889]
Windows 11 build 2009 (22631)

I wonder if we could not have some smart mechanism to figure out if a given dyndata version is still valid for a newer build of windows.

**Comment by MagicAndre1981** [comment]
update the latest SI version 3.0.7310 that already [has the fixed ](https://github.com/winsiderss/systeminformer/commit/bc98048099421785ea4a37670d7b57bfb924cda5)data

**Comment by DavidXanatos** [comment]
thanks
