### ISSUE TITLE
hide when minimized option not working

### ISSUE THREAD

**Issue by eadmaster** [winsiderss/systeminformer#1891]
### Brief description of your issue

hide when minimized option is not working when enabled

### Steps to reproduce (optional)

1. set "Start Hidden" and "hide when minimized" in the options.
2. Close the program and start it again
3. restore the main window from the systray
4. minimize the main window, it shoud disappear from the taskbar

### Expected behavior (optional)

SI shoud disappear from the taskbar

### Actual behavior (optional)

SI stays in the taskbar

### Environment (optional)

```shell
Sistem Informer 3.0.7310  https://github.com/winsiderss/systeminformer/commit/bc98048
Windows 10
```

**Comment by dmex** [comment]
I've tested multiple machines and can't reproduce. Either you've disabled tray icons or need to reset settings.
