### ISSUE TITLE
RAPL Devices Unknown Devices - Please report on Github Intel i9-10980XE

### ISSUE THREAD

**Issue by Nodens-** [winsiderss/systeminformer#1892]
### Brief description of your issue

Under RAPL Devices, direction to report the device on github.

### Steps to reproduce (optional)

Options-> RAPL Devices

### Environment (optional)

```shell
Nightly 3.0.7310 https://github.com/winsiderss/systeminformer/commit/bc98048
Windows 22621.2506
```

**Comment by UhuruNUru** [comment]
Getting same with all 8 Cores of my
**AMD Ryzen 7 7800X3D 8-Core Processor**
Only other difference to above report is OS
**Windows 11 Pro v23H2 Build 22631.2428**

**Comment by dmex** [comment]
Duplicate of #1558
