### ISSUE TITLE
System Informer reads VBoxSDS.exe every time it refreshes

### ISSUE THREAD

**Issue by ponjadito23** [winsiderss/systeminformer#1893]
### Brief description of your issue

System Informer reads "C:\Program Files\Oracle\VirtualBox\VBoxSDS.exe" from the disk every time it refreshes after version 3.0.7147.

I was able to find this issue because I have a software that adds and extra layer of cache to my drives and I noticed and unusual amount of cache hits on the system drive, which seems that Windows is not caching this particular read. I found out that it's reading "C:\Program Files\Oracle\VirtualBox\VBoxSDS.exe" after disabling my cache.

System informer version 3.0.7039 and below do not present this issue.

### Steps to reproduce (optional)

Observe disk activity after a refresh using the Disk tab or disk activity LED while having VirtualBox installed.

### Environment (optional)

```shell
System Informer >=3.0.7147
Oracle VirtualBox 7.0.6
Windows 10 21H2
```

**Comment by dmex** [comment]
VirtualBox has a custom security component named "hardening" it's verifying the process against the disk image.

**Comment by ponjadito23** [comment]
Ok but the service isn't even running. I don't think System Informer should be verifying the image and waking up the drive every time it refreshes.

**Comment by dmex** [comment]
> Ok but the service isn't even running. 

🤷‍♂️ The software you're using as a "caching layer" is likely blocking queries for the NTFS journal. Every file has a USN (update sequence number) and the number determines when Windows flushes caches including any caching for signatures (ci.dll).

> I don't think System Informer should be verifying the image and waking up the drive every time it refreshes.

Options > Check images for digital sigantues -> Disable
