### ISSUE TITLE
ExtendedTools: crash and memory leak in Object Manager tool

### ISSUE THREAD

**Issue by hg421** [winsiderss/systeminformer#1895]
### Environment
System Informer 3.0.7310 (bc98048)
Windows 10 x64 22H2

### Description

The following steps lead to a System Informer crash:

1. Open Tools -> System -> Object Manager
2. Select any object in the right pane and click "Security" in the context menu
3. Close the security editor/message box
4. Select "Security" again on the same object
5. System Informer crashes (0xC0000005 / STATUS_ACCESS_VIOLATION) at https://github.com/winsiderss/systeminformer/blob/5d97d6b3f99bd7c651b448ae414f39150cf9af2f/plugins/ExtendedTools/objmgr.c#L534

I believe this happens because [`EtObjectManagerHandleCloseCallback`](https://github.com/winsiderss/systeminformer/blob/5d97d6b3f99bd7c651b448ae414f39150cf9af2f/plugins/ExtendedTools/objmgr.c#L749-L750) wrongly deletes the `entry->Name` and `entry->TypeName` strings after showing the security dialog, but they are still needed e.g. when clicking on "Security" again.

Additionally it seems that the `Name` and `TypeName` strings for the current shown objects are not freed when navigating to another directory on the left pane, leading to a memory leak of string objects. This can be seen by rapidly switching between directories and watching the memory usage and object counts. There is a cleanup function [`EtCleanupTreeViewItemParams`](https://github.com/winsiderss/systeminformer/blob/5d97d6b3f99bd7c651b448ae414f39150cf9af2f/plugins/ExtendedTools/objmgr.c#L182C6-L182C33), but it's only called when the Object Manager tool is closed and not when we change between directories. (And shouldn't `EtCleanupTreeViewItemParams` also cleanup `item->TypeName` in addition to `item->Name`?)

**Comment by dmex** [comment]
Thanks, fixed 👍
