### ISSUE TITLE
Windows 10 - Un-Supported Kernel Version

### ISSUE THREAD

**Issue by AuthoritiveProtocol** [winsiderss/systeminformer#1900]
### Brief description of your issue

![SystemInformer_KernelError](https://github.com/winsiderss/systeminformer/assets/104904397/487b3e7b-345c-4edb-95e0-6869fe89b06f)

Just Reporting This Because It Recommended to Do So. I'm Not Looking for Additional Support, I'm Just Informing Developers.

**Comment by MagicAndre1981** [comment]
duplicated by https://github.com/winsiderss/systeminformer/issues/1823

**Comment by jxy-s** [comment]
Waiting on symbols 👍
