### ISSUE TITLE
Not possible to properly restart explorer.exe

### ISSUE THREAD

**Issue by TETYYS** [winsiderss/systeminformer#1904]
### Description of the feature, modification, idea or suggestion

If you have System Informer as your default task manager it is practically impossible to restart explorer.exe properly due to [System Informer having `Junction redirection protection` mitigation policy enabled](https://github.com/winsiderss/systeminformer/blob/64891545c02c8d329f358ced5a652e6d3d2a48f6/SystemInformer/main.c#L937) and processes started by SI having this mitigation as well. This prevents explorer opening files which have their application in a junction.

For example, if you have mpv installed through scoop, assigned application for a wav file is in `~\scoop\apps\mpv\current\mpv.exe` where `current` is a junction.

One of the workarounds is to deliberately crash explorer.exe and let winlogon.exe restart it.

### Proposed implementation details (optional)

• Not sure if possible, but there could be an option to remove this policy for a process in run dialog.
• Option to use some [exit code](https://github.com/winsiderss/systeminformer/blob/64891545c02c8d329f358ced5a652e6d3d2a48f6/SystemInformer/actions.c#L1640) other than 1 to allow winlogon to restart explorer properly, or prompt user with an option if he tries to terminate explorer.exe

**Comment by dmex** [comment]
Thanks, fixed 👍
