### ISSUE TITLE
Cannot open systeminformer from junction point.

### ISSUE THREAD

**Issue by cesaryuan** [winsiderss/systeminformer#1905]
### Brief description of your issue

Opening `systeminformer.exe` from a junction directory will cause all UI text invisible. Junction is used by Scoop, so this bug makes it impossible to install and open SystemInformer through Scoop.

![image](https://github.com/winsiderss/systeminformer/assets/35998162/25632223-31f2-4b23-9378-8b2d3ed0df71)

### Steps to reproduce (optional)

1. Download SystemInformer from [Nightly - System Informer](https://systeminformer.sourceforge.io/nightly.php)
2. Unzip it to some path. (for example: `~\systeminformer`)
3. Create a junction point `~\junction_point` link to `~\systeminformer`.
4. Go to `~\junction_point\amd64` and double click `SystemInformer.exe` to open it.
5. As you can see, all text is invisble.
6. Then go to `~\systeminformer\amd64` and double click `SystemInformer.exe` to open it.
7. As you can see, the UI is normal.

Or you can reproduce it by following pwsh commands:
```pwsh
> Invoke-WebRequest https://github.com/winsiderss/si-builds/releases/download/3.0.7313/systeminformer-3.0.7313-bin.zip -OutFile systeminformer-bin.zip
> Expand-Archive .\systeminformer-bin.zip -DestinationPath systeminformer
> New-Item -Type Junction -Path junction_point -Target .\systeminformer\
> cd .\junction_point\amd64\
> .\SystemInformer.exe
```

### Expected behavior (optional)

The UI should be normal when launch SystemInformer from a junction point.

### Actual behavior (optional)

All UI text is invisble.

### Environment (optional)

```shell
SystemInformer: 3.0.7313
Windows: Windows 10 22H2
```

**Comment by MagicAndre1981** [comment]
works fine for me under Windows 10 177763.x and 19045.x

**Comment by dmex** [comment]
https://github.com/ScoopInstaller/Scoop/issues/5238
+
https://github.com/ScoopInstaller/Scoop/issues/5234
