### ISSUE TITLE
Bring Window to Front Request

### ISSUE THREAD

**Issue by TheSQLGuru** [winsiderss/systeminformer#1906]
### Description of the feature, modification, idea or suggestion

I feel that brining an application window to the foreground is a pretty common need. As such, I ask that you add that to the main Processes tab as a right-click option. Thanks for your consideration, and also for an amazingly-useful utility!!

**Comment by dmex** [comment]
Have you tried the Bring to front menu option?

**Comment by dmex** [comment]
Right click -> Window -> Bring To Front
