### ISSUE TITLE
I can't open the native process strings, permission error

### ISSUE THREAD

**Issue by Unescopi** [winsiderss/systeminformer#1911]
### Brief description of your issue

I can't open the native process memory strings, permission error
![image](https://github.com/winsiderss/systeminformer/assets/152059211/458ad96b-d7c6-4e2d-a0c3-167ca097a70a)

### Steps to reproduce (optional)

SgrmBroker
MsMpEng
I need to access these two processes to see some records, they both don't open

### Expected behavior (optional)

open the string search tab

### Environment (optional)

```shell
System Informer 3.0.7333
Windows 11 10.0.22631 / 22631
```

**Comment by dmex** [comment]
These processes have PPL and Microsoft enforces limited access.

**Comment by Unescopi** [comment]
Is there nothing I can do to gain access?
