### ISSUE TITLE
AMD Ryzen Threadripper PRO 3995WX 64-Cores [UNKNOWN DEVICE - PLEASE REPORT ON GITHUB]

### ISSUE THREAD

**Issue by StanleyChristmas** [winsiderss/systeminformer#1912]
Reporting unknown devices. :)

![image](https://github.com/winsiderss/systeminformer/assets/11148061/5bceb38f-0d99-40e8-907b-83180ca682cc)

**Comment by dmex** [comment]
Duplicate of #1558
