### ISSUE TITLE
The inline function in phnt ntrtl.h conflicts on x86.

### ISSUE THREAD

**Issue by kanren3** [winsiderss/systeminformer#1926]
### Brief description of your issue

![image](https://github.com/winsiderss/systeminformer/assets/32032670/a48a83af-1137-4c8c-b2a0-b6d44896acf9)
![image](https://github.com/winsiderss/systeminformer/assets/32032670/39205e62-338c-4afc-9e65-7650a81c0b08)
It appears that the conflict is caused by the absence of a calling convention in the inline function. Is this as expected?
(In the absence of defining PHNT_INLINE_FREE_FORWARDERS.)

**Comment by dmex** [comment]
> inline function in phnt ntrtl.h conflicts on x86

I don't see any failures building on x86 and none of the build logs are showing those errors?
https://github.com/winsiderss/systeminformer/actions/workflows/msbuild.yml

> the conflict is caused by the absence of a calling convention in the inline function

Inline functions don't have calling conventions because the function doesn't exist once they're inlined.

**Comment by kanren3** [comment]
> I can confirm there are compilation errors on x32, and that they are solely due to missing calling convention at function definition.
> 
> Although there are **no errors** when default calling convention matches the declared calling convention. That is: even if calling convention is not specified, there still is the default one; and the default one depends on the project settings, and even on the individual cpp units compilation settings. When the declared and the default conventions happen to match, all's good (such as on x64, where cdecl/stdcall/fastcall is one and the same). When they don't match, compiler complains.
> 
> Since headers can be included in files where default calling convention can be different, **the best way to solve the problem** is simple: just always _explicitly specify calling convention for non-static functions_, even if function is inline. It won't affect the optimizer in any way.
> 
> Note compiler strives for consistency of calling conventions even if function is defined inline because it might not actually be inlined (such as when max inline depht reached, or when inlinining disabled globally, or when it's disabled at particular code fragment via #pragma).

Yes, I agree with that. This issue can be addressed either by modifying the default invocation convention or by explicitly adding invocation conventions.
