### ISSUE TITLE
Tab Navigation from the search box to the process list. 

### ISSUE THREAD

**Issue by Glitchy-Sheep** [winsiderss/systeminformer#1930]
### Description of the feature, modification, idea or suggestion

**I had a great experience with `ProcessHacker`, and it's even better with `SystemInformer`, it's an essential** software on my PC so far, and at the first place I want to tell you and the community a big thanks.

But I have some struggle with keyboard navigation.

**In the process hacker when I open it and search for a specific process (more often to terminate), I always hit tab**, so I navigate to a *first process list entry* and then `del + enter` do the trick. I did almost all the work with only my keyboard, it's superfast.

But for some reason, `SystemInformer` does nothing when I'm trying to navigate somewhere via tab.

![image](https://github.com/winsiderss/systeminformer/assets/93445878/419d8fa1-0152-41cc-b9c7-8992742a3b45)

### Proposed implementation details (optional)

Add tab navigation between `search field` and `process/services/etc.` entries. 🙏

**Comment by jxy-s** [comment]
`Ctrl+K` will navigate to _and_ from the search box.

`Ctrl+K` is the shortcut for navigating to the search box, it was that way in Process Hacker too:

![image](https://github.com/winsiderss/systeminformer/assets/11687482/21cb38cf-82a5-4ff9-894c-8681aafe71d3)

In Process Hacker `Tab` would return you to tree. In System Informer `Ctrl+K` returns you to the tree.

**Comment by Glitchy-Sheep** [comment]
> In Process Hacker `Tab` would return you to tree. In System Informer `Ctrl+K` returns you to the tree.

Oh, I get it now, thanks! 
But is there any way to bind the `Tab` key to the toggle?
That would be a more natural way to navigate in this case, maybe some kind of option.

Or is it about the implementation of context change?

**Comment by jxy-s** [comment]
Fixed: https://github.com/winsiderss/systeminformer/commit/7ccb384d40d29cb3ebc1707944f209a270af2300
