### ISSUE TITLE
Search doesn't always work for processes collapsed by default

### ISSUE THREAD

**Issue by ge0rdi** [winsiderss/systeminformer#1931]
### Brief description of your issue

Process search doesn't always work for collapsed by default processes.
It works correctly when search box is selected using mouse, but doesn't work when `Ctrl+K` is pressed.
In such case collapsed processes are not searched (don't appear in filtered results).

It used to work before. I think it got broken in recent search changes that added support for regex/case sensitivity.

### Steps to reproduce (optional)

Mark `services.exe` to be collapsed by default (right-click -> Miscellaneous  -> Collapse by default).
Restart SI to make sure the process is collapsed automatically.

Press `Ctrl+K` and type few characters of process name that is child of `services.exe` (`calc` in my case).
Filtered list won't contain the process.

Now you can repeat the same but instead of pressing `Ctrl+K` click on search box using mouse.
Filtered processes will contain matching process.

### Expected behavior (optional)

Process filtering works for collapsed processes no matter how search box was selected.

### Environment (optional)

```shell
System Informer 3.0.7407
Windows 10 22H2
```

**Comment by jxy-s** [comment]
Should be fixed with: https://github.com/winsiderss/systeminformer/commit/de143da46ab3fa47a38d2c228752c0aa14db55ae

**Comment by jxy-s** [comment]
`3.0.7412` -> `Help > Check for updates` 👍

**Comment by ge0rdi** [comment]
I can confirm it is fixed now.
Thank you very much.
