### ISSUE TITLE
Unable to load kernel driver, 10.0.22621.2861

### ISSUE THREAD

**Issue by Ryloth** [winsiderss/systeminformer#1932]
### Brief description of your issue

System Informer displays an error that the kernel driver is not yet supported.

### Steps to reproduce (optional)

Open System Informer after installing KB5033375.

### Environment (optional)

```shell
System Informer 3.0.7353
Windows Kernel 10.0.22621.2861
```

**Comment by dmex** [comment]
> System Informer 3.0.7353

Help menu > Check for updates > 7407 👍
