### ISSUE TITLE
VirusTotal Scanning Broken

### ISSUE THREAD

**Issue by bruh1273** [winsiderss/systeminformer#1938]
### Brief description of your issue

Duplicate of #1783.
Still hasn't been patched, atleast for me, running the latest build.

### Steps to reproduce (optional)

Enable VirusTotal checks in the options, and in columns. Restart app.

### Expected behavior (optional)

Shows processes VirusTotal flags ie. 0/74

### Actual behavior (optional)

Absolutely nothing displays.

### Environment (optional)

```shell
System Informer: 3.0.7412
Windows 10 Pro: Version	10.0.19045 Build 19045
```

**Comment by sperglord8008s** [comment]
Why is every issue about Virus Total Closed?
This Is Not Fixed, Its not completed, It's not allocated.
