### ISSUE TITLE
Crash on opening memory tab of wow64 process

### ISSUE THREAD

**Issue by rtldg** [winsiderss/systeminformer#1945]
### Brief description of your issue

The latest version release (`3.0.7420`) crashes due to `0xC0000005 (Invalid access to memory location.)` when opening the memory tab from a wow64 process's properties. This does not happen on the previous release (`3.0.7412`)

**Comment by dmex** [comment]
Regression from PR #1935 @diversenok

**Comment by diversenok** [comment]
Yeah, definitely my bad. I think your fix should be sufficient.
