### ISSUE TITLE
Locks pdb file.

### ISSUE THREAD

**Issue by gnilsson2** [winsiderss/systeminformer#1946]
When having properties window open for a executable, that has a pdb file, Visual Studio can't build that executable.
Closing the properties window, enables building.
(A bit annoying,)

**Comment by jxy-s** [comment]
This is a common problem with `dbghelp.dll` which is not really in our control. The same problem happens with any process using the symbols for a binary (through `dbghelp.dll`) when trying to rebuild. I myself run into this most frequently when kernel debugging using `windbg`.

**Comment by gnilsson2** [comment]
Is this so, even when the process has ended ?
In theory, the properties window could detect, and release dbghelp.dll

**Comment by jxy-s** [comment]
This might be possible.

**Comment by jxy-s** [comment]
This commit (https://github.com/winsiderss/systeminformer/commit/e82f41ddc8e035378a887b8791ae630b40d420ee) _should_ workaround this issue, as you suggested. There is still a race condition, but there isn't much we can do about that. It might at least make it less annoying for most cases. Will be in next build 👍
