### ISSUE TITLE
GPU usage not showing (Windows 10 Pro)

### ISSUE THREAD

**Issue by dmex** [winsiderss/systeminformer#1949]
> Few years later, this tool still isn't showing (Windows 10 Pro, running as an admin) GPU usage, at all. Any logs I can provide to track this issue further?

_Originally posted by @scotrod in https://github.com/winsiderss/systeminformer/issues/514#issuecomment-1872362852_

**Comment by MagicAndre1981** [comment]
@scotrod In option click on "Graphic devices" and look if you see a GPU there and if you see one, select it. This newer Graph shows me GPU usage even for old WDDM 1.x drivers like in VMware or old Intel iGPUs

**Comment by MagicAndre1981** [comment]
Don't show the system information window, on main program, click on System->Options and here go to Graphic Devices:

![image](https://github.com/winsiderss/systeminformer/assets/8274816/c03033b3-cdb4-4558-b8a5-3bdd9f5ff561)

**Comment by Biswa96** [comment]
You are using the older Process Hacker. The project name has changed to System Informer. Please use the new installer.

**Comment by MagicAndre1981** [comment]
yes, [use the new version](https://systeminformer.sourceforge.io/nightly.php), process hacker was renamed to [System Informer in 2022](https://github.com/winsiderss/systeminformer/issues/1253)

**Comment by scotrod** [comment]
Thanks a lot! I take it that Process Hacker is not maintained anymore and System Informer is its successor?

**Comment by scotrod** [comment]
Thanks a lot! I really didn't know that Process Hacker was rebranded to System Informer...

**Comment by MagicAndre1981** [comment]
does it work now with Systeminformer?
