### ISSUE TITLE
Empty All caches

### ISSUE THREAD

**Issue by OkobaPatino** [winsiderss/systeminformer#1951]
### Description of the feature, modification, idea or suggestion

Can you add Empty All to the System Information Empty Button?
It helps a lot to not go each one by one and helpful mostly while benchmarking as only clearing StandbyList wont help.
It can be a good replacement for old EmptyStandbyList program.

**Comment by jxy-s** [comment]
Added: https://github.com/winsiderss/systeminformer/commit/18e478cc6294d340f1dd2517aa798854f9ea76e9
