### ISSUE TITLE
Possible Memory Information Error

### ISSUE THREAD

**Issue by rqueizan** [winsiderss/systeminformer#1955]
### Brief description of your issue

It apparently had more than half of the RAM in use, about 18GB out of a total of 32GB.
On Standby there was about 14 GB.
I hit it on Empty Standby List and the consumption remained pretty much the same, even though it almost completely freed up the total memory on Standby.
I raised the Resource Monitor to query and see that the values differ.

![PH vs RAM](https://github.com/winsiderss/systeminformer/assets/18214796/6874feff-bbea-4875-ab6a-d00eb6d96a28)

### Steps to reproduce (optional)

It's been four days since I rebooted the laptop, I don't know if it makes an impact.
It had very high RAM consumption, I freed up the memory in Standby and the consumption remained practically the same.
I compared the information with the Resourse Monitor and see discrepancies between one and the other.

### Expected behavior (optional)

I thought it would free up around 14GB of RAM.

### Actual behavior (optional)

RAM consumption remained pretty much the same, although almost all of the memory was freed up in Stanby.

### Environment (optional)

```shell
System Informer 3.0.11949.7422 (9fe0874) nigthly
Windows11 22H2 22621.2861
```

**Comment by dmex** [comment]
Options > Graphs > Uncheck the "Show commit chage instead of physical memory" option and restart the application.
