### ISSUE TITLE
Unable to terminate csrss.exe

### ISSUE THREAD

**Issue by TK50P** [winsiderss/systeminformer#1959]
### Brief description of your issue

In process hacker, it was possible to terminate the system process csrss.exe, but in systeminformer, it is unknown but cannot be terminated.
it shows access denied (404).

### Steps to reproduce (optional)

None

### Expected behavior (optional)

Maybe if it was driver problem, it should be fixed

### Actual behavior (optional)

when I tried to terminate csrss.exe it doesn't show BSOD and it shows error (Access denied 404)

### Environment (optional)

```shell
System Informer (Nightly version)
Windows 8.1
```

**Comment by jxy-s** [comment]
This is by design. CSRSS is a protected process.
