### ISSUE TITLE
Unable to load kernel driver at Windows 11 22H2 10.0.22621 for laste version

### ISSUE THREAD

**Issue by yanite** [winsiderss/systeminformer#1960]
### Brief description of your issue

Unable to load kernel driver at Windows 11 22H2 10.0.22621 for laste version

![屏幕截图 2024-01-10 091517](https://github.com/winsiderss/systeminformer/assets/5064763/4bdc66cc-c9d6-43b9-9c83-9d21be33e0f3)

### Steps to reproduce (optional)

at startup 

### Actual behavior (optional)

dno't load kerenel

**Comment by jxy-s** [comment]
duplicate: https://github.com/winsiderss/systeminformer/issues/1823
