### ISSUE TITLE
Unable to load kernel driver

### ISSUE THREAD

**Issue by AbdelrahmanMohamedDesoky** [winsiderss/systeminformer#1961]
### Brief description of your issue

![screenshot](https://github.com/winsiderss/systeminformer/assets/12201594/d15b3d43-53d9-491e-9204-fddbec6191a2)

System Informer

Unable to load kernel driver

The kernel driver is not yet supported on this kernel version. Request support by submitting a GitHub issue with the Windows Kernel version.

Windows 11 23H2 10.0.22631
Windows Kernel 10.0.22621.3007
System Informer 3.0.7422 (9fe0874)

it was running fine a few days ago, maybe Microsoft decided to update something ?

### Steps to reproduce (optional)

Open System Informer with Kernel driver

### Expected behavior (optional)

To Start and not give error

### Actual behavior (optional)

Gives error because it's unable to load kernel driver.

### Environment (optional)

```shell
Nightly System Informer V3.0.77422 (9fe0874)
Windows 11 23H2 Build 22631.3007 

Let me know if you need anything else
```

**Comment by jxy-s** [comment]
https://github.com/winsiderss/systeminformer/issues/1823
