### ISSUE TITLE
Support for Windows Kernel v10.0.22621.3007

### ISSUE THREAD

**Issue by N08I40K** [winsiderss/systeminformer#1962]
### Description of the feature, modification, idea or suggestion

![image](https://github.com/winsiderss/systeminformer/assets/55545594/5ba2c778-226a-40b6-bd7c-606d59636352)

**Comment by MagicAndre1981** [comment]
duplicated by https://github.com/winsiderss/systeminformer/issues/1823 and already fixed in https://github.com/winsiderss/systeminformer/commit/e93bcbaa4670b01e535f0a48b39c944afe273f8b

**Comment by MagicAndre1981** [comment]
new version Rev7429 is out, search for update and install it
