### ISSUE TITLE
New release builds?

### ISSUE THREAD

**Issue by Neustradamus** [winsiderss/systeminformer#1966]
### Brief description of your issue

Dear @winsiderss team,

Currently the latest version is very old: 2.39 (2016-03-29)
- https://github.com/winsiderss/systeminformer/releases

Can you create a new release build with all improvements?

**Comment by jxy-s** [comment]
We plan to do a formal release build when it is ready. In the meantime please use the nightly build. https://system-informer.com/nightly.php
