### ISSUE TITLE
Can't Inject DLLs even though I loaded a module

### ISSUE THREAD

**Issue by haha183** [winsiderss/systeminformer#1969]
### Brief description of your issue

I can't Inject DLL's even though I loaded a module. This also happens in Process Hacker 2.

### Steps to reproduce (optional)

Idk ._.

### Expected behavior (optional)

I expected that it injected the DLL's because Process Hacker 2 couldn't, but it didn't.

### Actual behavior (optional)

 Ever since I turned my PC into Windows 11, it doesn't let me Inject DLL's anymore, same for Process Hacker 2. I went to Proccess's Properties > Modules > Options and Loaded a module but didn't Inject in TF2 or L4D2.

### Environment (optional)

```shell
SystemInformer 3.0.7432
Edition	Windows 11 Pro
Version	21H2
Installed on	‎1/‎25/‎2024
OS build	22000.2538
Experience	Windows Feature Experience Pack 1000.22001.1000.0
```

**Comment by dmex** [comment]
> Windows 11, it doesn't let me Inject DLL's anymore, same for Process Hacker 2.

The OS doesn't allow injecting 64bit binaries into 32bit processes.

> Loaded a module but didn't Inject in TF2 or L4D2.

LoadLibrary generates loader notifications and those applications block loading of foreign images using those same notifications. The image failing to load is the expected behavior in this case.
