### ISSUE TITLE
Feature request: automatic collapse of the list of processes (similar to services.exe)

### ISSUE THREAD

**Issue by Andrysky** [winsiderss/systeminformer#1976]
### Description of the feature, modification, idea or suggestion

Please add the ability to add your processes to this list - so that they collapse themselves both when systeminformer is launched and when a new process appears.
![image](https://github.com/winsiderss/systeminformer/assets/5894390/45ca31ca-ccdb-4fa8-9f7d-c11a459470a7)

**Comment by dmex** [comment]
Right click any process > Miscellaneous > Collapse by default ✔️
