### ISSUE TITLE
Unable to load kernel driver 

### ISSUE THREAD

**Issue by jonnieplayz** [winsiderss/systeminformer#1977]
### Brief description of your issue

Whenever i open system informer this pops up 

![Screenshot_1](https://github.com/winsiderss/systeminformer/assets/159253764/fbf07232-d53b-447f-93f1-26a5ca078d24)

**Comment by jxy-s** [comment]
@jonnieplayz I incorrectly assumed this was an unsupported kernel version previously. Apologies for this oversight. "Unable to restart." with "Access is denied". But the "Process State" is `0x000001fe`. The kernel driver is actually loaded, title of the error message could do with some clarification in that case. For some reason `SystemInformer.exe` could not restart itself to meet one of the state requirements.

The only way this could be possible is if some third party is interfering with creation of processes on the system.

**Comment by DavidOsipov** [comment]
The access can be denied due to Avast (hardening mode on) or other AV
