### ISSUE TITLE
"Invalid Access to Memory Location" crash

### ISSUE THREAD

**Issue by dmex** [winsiderss/systeminformer#1983]
### Discussed in https://github.com/winsiderss/systeminformer/discussions/1943

<div type='discussions-op-text'>

<sup>Originally posted by **GY8VSdYYzvL8-K6T** December 25, 2023</sup>
When I navigate to Process>Properties>Memory for Ubisoft Connect (UPC.exe and UplayWebCore.exe), I get "Invalid Access to Memory Location" crash, even if I use Kernel-Mode driver. </div>

**Comment by GY8VSdYYzvL8-K6T** [comment]
Have there been updates regarding this issue? Does anyone know why it happens?
