### ISSUE TITLE
AMD Ryzen 7 3800X - Unknown Device

### ISSUE THREAD

**Issue by HenryBlackie** [winsiderss/systeminformer#1993]
### Brief description of your issue

In the RAPL Devices section of the Options menu my CPU was marked as an unknown device and it said to report this on GitHub.
![rapl](https://github.com/winsiderss/systeminformer/assets/5684989/9b5cf051-460e-4d66-86ca-2edc56f04f5f)

In a [similar bug report](https://github.com/winsiderss/systeminformer/issues/1558#issuecomment-1534102367) I saw a request to collect energy counters:
[counters.txt](https://github.com/winsiderss/systeminformer/files/14537803/counters.txt)

### Steps to reproduce (optional)

1. Open Options window
2. Navigate to RAPL Devices
3. Verify CPU is listed and marked as unknown

### Environment (optional)

```shell
AMD Ryzen 7 3800X 8-Core Processor
Windows 11 Pro | 22631.3235
System Informer Nightly | 3.0.7474
```

**Comment by dmex** [comment]
Thanks for the counter samples 👍 

Follow the other thread for updates: #1558
