### ISSUE TITLE
Enhancement of Ping Graph Scaling for Improved Data Visibility

### ISSUE THREAD

**Issue by FuhrerStein** [winsiderss/systeminformer#2003]
### Description of the feature, modification, idea or suggestion

Ping graph is really useful feature, but it has one drawback when using with fast targets. The graph’s default scale is quite large, capable of displaying up to 1000 ms or more. This causes all relevant data to be compacted at the bottom, making it difficult to analyze and interpret the ping data effectively. 

![screenshot 2177162764](https://github.com/winsiderss/systeminformer/assets/65869926/f9b00586-bb71-4e0b-9809-dccd1c497d5e)

### Proposed implementation details (optional)

Here are a few suggestions on how this could be improved:

Adaptive Scaling: Implement adaptive scaling where the y-axis adjusts dynamically based on the range of ping values recorded. This will ensure that data is spread across the graph for better visibility and analysis.

Customizable Scale: Allow users to manually adjust the scale of the y-axis. Providing options to set maximum and minimum values can help in focusing on specific data ranges.

**Comment by dmex** [comment]
Options > General > `Enable fixed graph scaling (experimental)` or alternatively configure `ProcessHacker.NetworkTools.PingMinScaling` with the maximum scaling as a hexadecimal value (e.g. `c8` == 200ms)

**Comment by FuhrerStein** [comment]
Thanks! Both methods offer so needed solution. I guess now what's needed is a way to bring these settings closer to a user rather then buried deep into options, but that's a topic for another issue.

Just out of curiosity: why does "Enable fixed graph scaling" option seems to do exactly opposite, namely it disables fixed graph scaling and enables adaptive graph scaling? Is it on purpose, or by accident?
