### ISSUE TITLE
Not found some #define values

### ISSUE THREAD

**Issue by HongThatCong** [winsiderss/systeminformer#2011]
File phnt/include/ntexapi.h:

I was unable to find the #define and value of the following 4 values:
- EVENT_TRACE_TYPE_CONFIG_OSVERSION
- EVENT_TRACE_TYPE_CONFIG_VISUALTHEME
- EVENT_TRACE_TYPE_CONFIG_SYSTEMRANGE
- EVENT_TRACE_TYPE_CONFIG_SYSDLLINFO
From: https://github.com/winsiderss/systeminformer/blob/e4df6204d94a4310006593d66093289931b0f3c3/phnt/include/ntexapi.h#L2337 to https://github.com/winsiderss/systeminformer/blob/e4df6204d94a4310006593d66093289931b0f3c3/phnt/include/ntexapi.h#L2340

I am using:
Windows Kit: 10.0.22621.0
Windows Driver Kit: 10.0.22621.382

Can you provide more of those values?
Thank you very much

**Comment by dmex** [comment]
> Can you provide more of those values?

These values don't exist in `\system32\EtwRundown.dll` and were probably from the checked build of Windows.

**Comment by diversenok** [comment]
The same problem exists in `ntwmi.h` that was distributed with early Windows 10 EWDKs. The header references constants that are nowhere to be found ¯\_(ツ)_/¯
