### ISSUE TITLE
Duplicate some #defines and structs, enums

### ISSUE THREAD

**Issue by HongThatCong** [winsiderss/systeminformer#2013]
### Description

Duplicate some #define and structs, enums in to file: ntmisc.h and ntwmi.h.
For struct/enum:
- ETW_REF_CLOCK struct
- TRACE_ENABLE_FLAG_EXTENSION struct
- TRACE_ENABLE_FLAG_EXT_HEADER struct
- TRACE_ENABLE_FLAG_EXT_ITEM struct
- ETW_STACK_CACHING_CONFIG struct
- PERFINFO_GROUPMASK struct
- ETW_UMGL_KEY struct
- ETW_KERNEL_HEADER_EXTENSION struct
- ETW_NOTIFICATION_TYPE enum
- ETW_NOTIFICATION_HEADER struct
- ETW_SESSION_NOTIFICATION_TYPE enum
- ETW_SESSION_NOTIFICATION_PACKET struct
- ETW_TRACE_PROVIDER_INSTANCE_INFO struct
- ETW_TRACE_GUID_INFO enum
- ETWTRACECONTROLCODE enum
- TELEMETRY_COVERAGE_POINT struct

For #define (macro):
- PERFINFO_OR_GROUP_WITH_GROUPMASK
- PERF_PFSECTION
- PERF_CLUSTER_OFF
- PERF_MEMORY_CONTROL

### Proposed implementation details

Can we delete duplicates defines/structs/enums in one of two files: ntmisc.h or ntwmi.h?
Or should we use #ifndef/#endif to still keep those duplicates defines/structs/enums in both files?

Best regards,

**Comment by dmex** [comment]
> Can we delete duplicates defines/structs/enums in one of two files: ntmisc.h or ntwmi.h?

ntwmi.h was just added yesterday. The duplicate definitions will be resolved once it's stable/linked with the build tools 👍
