### ISSUE TITLE
Missing some .h files in phnt.h

### ISSUE THREAD

**Issue by HongThatCong** [winsiderss/systeminformer#2014]
### Description

I am creating phnt amalgamate, a single phnt.h file.
A good work by Mr.Exodia:
https://github.com/mrexodia/phnt-single-header
I'm updating the phnt.h output, only 1 file, according to the master branch of your repo.
I discovered that there are some .h files in phnt\include that are not included in your phnt.h file. Including:
- ntgdi.h
- ntsmss.h
- ntwmi.h
- subprocesstag.h
- usermgr.h
- winsta.h

### Proposed implementation details

I want to ask: can I put those missing .h files into phnt.h, and can I put them into the block:
#if (PHNT_MODE != PHNT_MODE_KERNEL)
....
#endif
Is that Okay ?

Thank you for your good work.
Best regards,

**Comment by dmex** [comment]
```
ntwmi.h
```

This header was added yesterday and hasn't been included in the build.

```
ntgdi.h
ntsmss.h
winsta.h
subprocesstag.h
usermgr.h
```

These are not included because they're rarely used or essentially obsolete. 

> can I put those missing .h files into phnt.h

ntwmi.h will be added but the others just waste CI ($) minutes.
