### ISSUE TITLE
Multiple instances even when not allowed.

### ISSUE THREAD

**Issue by Milincho** [winsiderss/systeminformer#2016]
I have set 'Allow Only One Instance' to 1:

![image](https://github.com/winsiderss/systeminformer/assets/60118859/80bc580a-46d7-438c-b448-e7b8cf6f7839)

but even then multiple instances appear:
![image](https://github.com/winsiderss/systeminformer/assets/60118859/359adb6a-1063-49ef-b18f-70a9ae615ad0)
![image](https://github.com/winsiderss/systeminformer/assets/60118859/23c325b2-f591-4c5c-98c8-a5766a24a38a)

**Comment by jxy-s** [comment]
@Biswa96 also reported on Discord:
>  When I try to restart SI with the shield icon, UAC pops up as usual. If I click 'no' button in UAC window SI fully closes. Is that expected?
