### ISSUE TITLE
Private Bytes on performance tab on properties of a process not scaling correctly

### ISSUE THREAD

**Issue by Skyhikeeper** [winsiderss/systeminformer#2017]
The Private Bytes on performance tab on properties of a process not scaling correctly, it seems to scale up but not down when the bytes usage gets smaller, This ends up showing a very small line graph at the bottom of the graph.

Version : 3.0.7479

**Comment by dmex** [comment]
The scale is based on the maximum private bytes and Windows doesn't reset the value until after reboot.

**Comment by dmex** [comment]
Fixed
