### ISSUE TITLE
Requesting support for Windows Kernel version

### ISSUE THREAD

**Issue by Lagmaker** [winsiderss/systeminformer#2019]
### Brief description of your issue

[Window Title]
System Informer

[Main Instruction]
Unable to load kernel driver

[Content]
The kernel driver is not yet supported on this kernel version. Request support by submitting a GitHub issue with the Windows Kernel version.

Windows 10 22H2 10.0.19045
Windows Kernel 10.0.19041.4239
System Informer 3.0.7526 (863858c)

[ ] Don't show this message again  [OK]

### Steps to reproduce (optional)

1. Enable auto-startup for System Informer
2. Enable Kernel-Mode
3. Update Windows
4. See the error message

**Comment by jxy-s** [comment]
Duplicate: https://github.com/winsiderss/systeminformer/issues/1823
