### ISSUE TITLE
System Informer throws an exception in the Firewall tab

### ISSUE THREAD

**Issue by rqueizan** [winsiderss/systeminformer#2025]
### Brief description of your issue

When I access the firewall tab, an error occurs.

### Steps to reproduce (optional)

Show the main window, access the firewall tab.

### Expected behavior (optional)

It should show the firewall rules applied.

### Actual behavior (optional)

The app throws an error.

### Environment (optional)

```shell
System Informer 3.0.7546 (92cd97f)
Windows 11 Enterprise 22H2 Build 22621.2134
AMD Ryzen 5 4600H with Radeon Graphics
```

**Comment by rqueizan** [comment]
[Dump](https://mega.nz/file/zVQF0aqS#72cJ3vD7t2JwEg4JqwFFpO5vmpKpetgyHtwLH6hXg5I)

**Comment by jxy-s** [comment]
Duplicate: https://github.com/winsiderss/systeminformer/issues/2024
