### ISSUE TITLE
unreachable code inside `PhGenerateSyscallLists`

### ISSUE THREAD

**Issue by oberrich** [winsiderss/systeminformer#2027]
### Brief description of your issue

https://github.com/winsiderss/systeminformer/blob/342ef190cb717f43a4bcfd30eeb7095909106644/SystemInformer/ksyscall.c#L184-L214

is unreachable due to earlier check here

https://github.com/winsiderss/systeminformer/blob/342ef190cb717f43a4bcfd30eeb7095909106644/SystemInformer/ksyscall.c#L109

**Comment by dmex** [comment]
This is intentional. This branch of code is not used at all and is optimized away at compile time but will very likely be required again in the future and when it does, we can just flip the version check to start using it again when needed.
