### ISSUE TITLE
Error checking for update

### ISSUE THREAD

**Issue by rqueizan** [winsiderss/systeminformer#2030]
### Brief description of your issue

When I check for updates, an error occurs.

### Expected behavior (optional)

Check for updates.

### Actual behavior (optional)

It does not notify you whether or not an update is available, it only indicates that an error has occurred.
![image](https://github.com/winsiderss/systeminformer/assets/18214796/c6fed6b6-f5c8-47f0-a6e8-a7e21e201c9d)

### Environment (optional)

```shell
System Informer nightly 3.0.7566 999ab69
Windows 11 Enterprise 21H2 Build 22000.1165
```

**Comment by jxy-s** [comment]
We're working on ironing out a problem on the back end, expected for now.
