### ISSUE TITLE
One graph per CPU shows only single thread load

### ISSUE THREAD

**Issue by Vavun** [winsiderss/systeminformer#2033]
### Brief description of your issue

Window "System information => CPU" with "Show one graph per CPU" enabled displays loading of only one core/thread

### Steps to reproduce

Launch next to task manager and see

Screenshot
<details>

![Снимок экрана 2024-04-18 205954](https://github.com/winsiderss/systeminformer/assets/31875619/04c3c702-fc5f-4631-af51-16b5df54990c)

</details>

### Environment

```shell
System Informer Nightly 3.0.7566 (latest at the moment)
Windows 11 23H2 build 22631.3447
```
What additional information do I need to provide?

**Comment by dmex** [comment]
Works for me.

**Comment by Vavun** [comment]
1. Same behavior with Process Explorer.
2. No difference with **Enable cycle-based CPU usage** on or off

What information is needed?
What else can I do?

**Comment by dmex** [comment]
> Same behavior with Process Explorer.

You have malware or some rootkit preventing applications from calling the [GetSystemInfo](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsysteminfo) function. Applications require the function to query `dwNumberOfProcessors` and can only show 1 processor when prevented from querying the actual total.

**Comment by Vavun** [comment]
@dmex thanks for your answer.
I don’t think it’s some kind of virus (but I’ll check anyway) because I reinstalled Windows about a week ago and haven’t managed to install anything like that yet.

However, you gave me an idea: could I have just overtweaked my system setup? How to check it ?
I have a bunch of settings that I store as *.reg, *.cmd and *.ps1 files and apply as needed, so maybe I accidentally used something that I didn't intend to use.

**Comment by Vavun** [comment]
I figured out the reason.

The reason was disabled option in system configuration
`bcdedit /set disabledynamictick yes`
https://learn.microsoft.com/en-us/windows-hardware/drivers/devtest/bcdedit--set#additional-settings

Old habits on new hardware

In any case, the program behaves strangely
