### ISSUE TITLE
Signature check failure when downloading update

### ISSUE THREAD

**Issue by asampal** [winsiderss/systeminformer#2036]
### Brief description of your issue

After downloading the update, a signature check fails.

![image](https://github.com/winsiderss/systeminformer/assets/281639/dca189db-0463-4eca-85fd-d23eb96327c3)

**Comment by jxy-s** [comment]
We've been preparing for a full release and rotated the keys we use to validate the installer. If you're on a version older than 3.0.7566 this is expected.

You can run the installer on top of an existing install. You will get a warning but it should go through find and preserve your settings: https://system-informer.com/canary.php

**Comment by asampal** [comment]
I'll close this if the latest canary I installed on top of my previous install manages to download updates without failing. I was using a build older (74xx) than the one you mentioned, @jxy-s .

**Comment by tort32** [comment]
Can confirm manually downloaded Canary build is reinstalled in-place and working.

**Comment by asampal** [comment]
Same here. Closing
