### ISSUE TITLE
Unable to load kernel driver

### ISSUE THREAD

**Issue by IGod2020** [winsiderss/systeminformer#2044]
### Brief description of your issue

I try to use the kernel driver running S.I as Admin, but i came up with this error: 
![image](https://github.com/winsiderss/systeminformer/assets/49529276/956a5d7b-b34c-4415-8420-dc9f0f0e0b74)

### Environment (optional)

```shell
systeminformer-3.0.7578-release-bin.zip SHA256: 0E5AA4EF9C1AE3DB80FBB1D86A363F3EF435A499A88AC3941FC46BC71FD2A5D1

Windows version: Windows 11 23H2 10.0.22631

Windows Kernel: 10.0.22621.3527
```

**Comment by jxy-s** [comment]
Duplicate: https://github.com/winsiderss/systeminformer/issues/1823
