### ISSUE TITLE
Crash Upon Opening and Closing

### ISSUE THREAD

**Issue by TheSQLGuru** [winsiderss/systeminformer#2045]
### Brief description of your issue

I just upgraded to:

System Informer 3.0.7578 (ff4fc00)
OBJECT INFORMATION
PhObjectTypeObject: 21 objects
PhStringType: 4524 objects
PhBytesType: 0 objects
PhListType: 212 objects
PhPointerListType: 92 objects
PhHashtableType: 16 objects
PhFileStreamType: 1 objects
PhSymbolProviderType: 0 objects
PhProcessItemType: 179 objects
PhServiceItemType: 818 objects
PhNetworkItemType: 0 objects
PhModuleProviderType: 0 objects
PhModuleItemType: 0 objects
PhThreadProviderType: 0 objects
PhThreadItemType: 0 objects
PhHandleProviderType: 0 objects
PhHandleItemType: 0 objects
PhMemoryItemType: 0 objects
PhImageListItemType: 395 objects

Win 11 22H2 April 2024 CU applied
14th Gen i9 laptop

Each time I open SI, I get a popup message from windows that the application crashed. Immediately after I click the message, application starts and appears to run correctly. 

Each time I shutdown the application, I get the same crash message. 

STARTUP EVENT LOG MESSAGE:

[-](https://github.com/winsiderss/systeminformer/issues/new?assignees=&labels=bug%2Cneeds+investigation&projects=&template=bug_report.yml#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/winsiderss/systeminformer/issues/new?assignees=&labels=bug%2Cneeds+investigation&projects=&template=bug_report.yml#) <System>
  <Provider Name="Microsoft-Windows-ProcessExitMonitor" Guid="{fd771d53-8492-4057-8e35-8c02813af49b}" /> 
  <EventID>3000</EventID> 
  <Version>1</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2024-05-01T19:03:06.7287922Z" /> 
  <EventRecordID>58325</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="13484" ThreadID="7124" /> 
  <Channel>Application</Channel> 
  <Computer>LAPTOP8</Computer> 
  <Security UserID="S[-](https://github.com/winsiderss/systeminformer/issues/new?assignees=&labels=bug%2Cneeds+investigation&projects=&template=bug_report.yml#)1-5-21-153893299-2849885253-3918819830-1001" /> 
  </System>
- <EventData Name="EVENT_PROCESSTERMINATION_SELF">
  <Data Name="param1">D:\Program Files\Utilities\SystemInformer\SystemInformer.exe</Data> 
  <Data Name="param2">0</Data> 
  <Data Name="param3">01da9bfa3354b075</Data> 
  <Data Name="ExitingProcessId">4012</Data> 
  </EventData>
  </Event>

SHUTDOWN EVENT LOG MESSAGE:

[-](https://github.com/winsiderss/systeminformer/issues/new?assignees=&labels=bug%2Cneeds+investigation&projects=&template=bug_report.yml#) <Event xmlns="http://schemas.microsoft.com/win/2004/08/events/event">
[-](https://github.com/winsiderss/systeminformer/issues/new?assignees=&labels=bug%2Cneeds+investigation&projects=&template=bug_report.yml#) <System>
  <Provider Name="Microsoft-Windows-ProcessExitMonitor" Guid="{fd771d53-8492-4057-8e35-8c02813af49b}" /> 
  <EventID>3000</EventID> 
  <Version>1</Version> 
  <Level>4</Level> 
  <Task>0</Task> 
  <Opcode>0</Opcode> 
  <Keywords>0x8000000000000000</Keywords> 
  <TimeCreated SystemTime="2024-05-01T19:03:15.3892089Z" /> 
  <EventRecordID>58326</EventRecordID> 
  <Correlation /> 
  <Execution ProcessID="14228" ThreadID="2804" /> 
  <Channel>Application</Channel> 
  <Computer>LAPTOP8</Computer> 
  <Security UserID="S[-](https://github.com/winsiderss/systeminformer/issues/new?assignees=&labels=bug%2Cneeds+investigation&projects=&template=bug_report.yml#)1-5-21-153893299-2849885253-3918819830-1001" /> 
  </System>
- <EventData Name="EVENT_PROCESSTERMINATION_SELF">
  <Data Name="param1">D:\Program Files\Utilities\SystemInformer\SystemInformer.exe</Data> 
  <Data Name="param2">0</Data> 
  <Data Name="param3">01da9bfa335b8a88</Data> 
  <Data Name="ExitingProcessId">13976</Data> 
  </EventData>
  </Event>

**Comment by dmex** [comment]
1) Extract zip: [LocalDumps.zip](https://github.com/winsiderss/systeminformer/files/15182252/LocalDumps.zip)
2) Import the registry key.
3) Restart the application and get both the startup and shutdown crashes.
4) Compress / Zip any crash dumps found in the `C:\ProgramData\SystemInformer\CrashDumps` folder and send to `johnny.shaw@live.com` and `dmex04@gmail.com`

**Comment by dmex** [comment]
Closing as waiting-for-feedback
