### ISSUE TITLE
Upgrade error ("signature failed")

### ISSUE THREAD

**Issue by CComparon** [winsiderss/systeminformer#2046]
### Brief description of your issue

Trying to upgrade from within the app fails with error below.

Current version: 3.0.7479
![image](https://github.com/winsiderss/systeminformer/assets/12992190/506b1e6a-e6d7-4a9e-bfeb-e776f84de11a)
![image](https://github.com/winsiderss/systeminformer/assets/12992190/6a09a806-7302-406b-a6b7-80dada6ec21b)

Windows version:
![image](https://github.com/winsiderss/systeminformer/assets/12992190/f8877799-b652-4b0d-94ba-d7af1f0767b3)

**Comment by jxy-s** [comment]
This is a duplicate - @CComparon please see: https://github.com/winsiderss/systeminformer/issues/2046

**Comment by CComparon** [comment]
Thanks
