### ISSUE TITLE
Display "Build Time" in process properties window

### ISSUE THREAD

**Issue by SilmorSenedlen** [winsiderss/systeminformer#2057]
Good day

It would be great to see "Build Time" property under "Version" in General tab of process properties window, like in SystemInternals Process Explorer:
![ProcessExplorer_BuildTimeProperty](https://github.com/winsiderss/systeminformer/assets/6761903/f65f8dad-bcc4-4f25-ab16-773404c19423)

**Comment by dmex** [comment]
The "build time" or timestamp is shown on the image properties page (click the magnifying glass button to the right)

![image](https://github.com/winsiderss/systeminformer/assets/1306177/6201d69a-4031-454d-aa86-40e8b197941e)
