### ISSUE TITLE
Process tree mode

### ISSUE THREAD

**Issue by pedoc** [winsiderss/systeminformer#2059]
### Description of the feature, modification, idea or suggestion

Just like ``Process Explorer``, this can easily distinguish and identify the relationship between parent and child processes.

![image](https://github.com/winsiderss/systeminformer/assets/6604230/4e8162a4-3766-426a-85d7-0a7c9e65c14b)

I tried google and searched in the options, but I didn't find the relevant switch. If there is, please forgive me.

**Comment by jxy-s** [comment]
Click the "Name" column to change the sort order, one of which changes to tree view:
![image](https://github.com/winsiderss/systeminformer/assets/11687482/ef3292ce-d23f-4a9a-987b-fb7af1b3b036)

**Comment by pedoc** [comment]
Sorry I didn't find this 😄
