### ISSUE TITLE
Add kernal mode driver for windows 11 23H2

### ISSUE THREAD

**Issue by DateAGentleman** [winsiderss/systeminformer#2061]
### Description of the feature, modification, idea or suggestion

Per screenshot:
![image](https://github.com/winsiderss/systeminformer/assets/160681255/eec5e844-8da8-43e3-8931-32a8235fbe05)

### Proposed implementation details (optional)

You know what to do lads.

**Comment by jxy-s** [comment]
Duplicate: https://github.com/winsiderss/systeminformer/issues/1823

Switch to the Canary channel - `Help > Switch update channel`
