### ISSUE TITLE
Can't load the kernel driver on the latest Windows 11 23H2 build 22631.3593

### ISSUE THREAD

**Issue by ToddIndry37** [winsiderss/systeminformer#2067]
### Brief description of your issue

Kernel driver unable to load after _2024-05 Cumulative Update for Windows 11 Version 23H2 for x64-based Systems (KB5037771)_ installed on my PC.

### Steps to reproduce (optional)

Launch System Informer as usual (in administrator mode). Open Options > ☑️ Enable kernel-mode driver. Restart System Informer.

### Expected behavior (optional)

It should load the kernel driver normally after restart.

### Actual behavior (optional)

Got an error message that current System Informer's kernel-mode driver is not supported.

![image](https://github.com/winsiderss/systeminformer/assets/88038185/3961f354-bc12-4f90-9fbd-00faf379eedb)

### Environment (optional)

```shell
System Informer 3.07579 (fc042be) Canary
Windows 11 23H2 build 22631
Kernel version 10.0.22621.3593
```

**Comment by jxy-s** [comment]
Duplicate: https://github.com/winsiderss/systeminformer/issues/1823

**Comment by ToddIndry37** [comment]
> Duplicate: #1823

Oh, sorry. I'll forwarding on that anyways.
