### ISSUE TITLE
Boost disabled as soon as you save for the process

### ISSUE THREAD

**Issue by VorlonCD** [winsiderss/systeminformer#2071]
### Brief description of your issue

When you click save for boost on a process, it disables it.

This feature:  https://github.com/winsiderss/systeminformer/issues/1244

### Steps to reproduce (optional)

1) Right-click > Boost > Set boost, the 'Priority boost" column correctly says YES.
2) Right-click > Boost > SAVE, boost is now disabled and says NO in the boost column.

### Environment (optional)

```shell
Windows 10 and 11, latest builds
System Informer 3.0.7645 Canary and the last build before that.  Didnt check older.
```

**Comment by dmex** [comment]
Fixed in latest nightly

**Comment by VorlonCD** [comment]
Thanks!    Although I see SAVE FOR PROCESS.EXE checkbox doesnt 'stick' in the right click menu?

**Comment by Gameking1happy** [comment]
this is happening to me is this issue back?
