### ISSUE TITLE
Compilation error after installing Windows SDK (10.0.26100)

### ISSUE THREAD

**Issue by sonyps5201314** [winsiderss/systeminformer#2072]
### Brief description of your issue

`
2>M:\DISASSEMBLE_TOOLS\systeminformer\systeminformer\phnt\include\ntioapi.h(881,16): error C2011: '_FILE_STAT_INFORMATION': 'struct' type redefinition
2>M:\DISASSEMBLE_TOOLS\systeminformer\systeminformer\phnt\include\ntioapi.h(917,16): error C2011: '_FILE_STAT_LX_INFORMATION': 'struct' type redefinition
2>M:\DISASSEMBLE_TOOLS\systeminformer\systeminformer\phnt\include\ntioapi.h(944,16): error C2011: '_FILE_CASE_SENSITIVE_INFORMATION': 'struct' type redefinition
2>M:\DISASSEMBLE_TOOLS\systeminformer\systeminformer\phnt\include\ntioapi.h(881,16): error C2011: '_FILE_STAT_INFORMATION': 'struct' type redefinition
2>M:\DISASSEMBLE_TOOLS\systeminformer\systeminformer\phnt\include\ntioapi.h(917,16): error C2011: '_FILE_STAT_LX_INFORMATION': 'struct' type redefinition
2>M:\DISASSEMBLE_TOOLS\systeminformer\systeminformer\phnt\include\ntioapi.h(944,16): error C2011: '_FILE_CASE_SENSITIVE_INFORMATION': 'struct' type redefinition
2>M:\DISASSEMBLE_TOOLS\systeminformer\systeminformer\phnt\include\ntioapi.h(881,16): error C2011: '_FILE_STAT_INFORMATION': 'struct' type redefinition
2>M:\DISASSEMBLE_TOOLS\systeminformer\systeminformer\phnt\include\ntioapi.h(917,16): error C2011: '_FILE_STAT_LX_INFORMATION': 'struct' type redefinition
2>M:\DISASSEMBLE_TOOLS\systeminformer\systeminformer\phnt\include\ntioapi.h(944,16): error C2011: '_FILE_CASE_SENSITIVE_INFORMATION': 'struct' type redefinit
`

### Steps to reproduce (optional)

https://developer.microsoft.com/en-us/windows/downloads/windows-sdk/

### Expected behavior (optional)

everything is ok.

### Actual behavior (optional)

error

### Environment (optional)

```shell
vs2022 v17.10 win11
```

**Comment by jxy-s** [comment]
Fixed here 👍: https://github.com/winsiderss/systeminformer/commit/060790a298177dea9cdc99663821bfea17de9c5b
