### ISSUE TITLE
Unable to load Kernel Driver

### ISSUE THREAD

**Issue by NocDaTekDoc** [winsiderss/systeminformer#2075]
![image](https://github.com/winsiderss/systeminformer/assets/11171976/d0511cff-0d02-4cf9-aaf0-6f0b4b312ec1)

in case the Screenshot didnt upload properly

Windows 10 22H2 10.0.19045
Windows Kernel 10.0.19041.4412
System Informer 3.0.7578 (ff4fc00)

trying to use the option to show details for all processes in the system menu possibly with the system driver 

first report apologies for lacking the formatting or detailed information for proper reports im a newb that tries to fix it themselves and barely have a clue to figure out how to get all that fancy data, Sincere thanks regardless for your time

**Comment by MagicAndre1981** [comment]
switch to canary channel und search for update.

Duplicated by #1823

**Comment by NocDaTekDoc** [comment]
Thank you, will do, also looked at #1823 understood
