### ISSUE TITLE
Unable to Load Kernel driver

### ISSUE THREAD

**Issue by yanite** [winsiderss/systeminformer#2081]
### Brief description of your issue

Unable to Load Kernel driver

### Steps to reproduce (optional)

start program

### Expected behavior (optional)

load kernel

### Environment (optional)

```shell
Windows 11 23H2 10.0.22631
Windows Kernel 10.0.22621.3672
System Informer 3.0.7645 (2726cf5)
```

**Comment by dmex** [comment]
Duplicate of #1823
