### ISSUE TITLE
Build 3.1.7741 shows 3.0.7741 in Help--> About

### ISSUE THREAD

**Issue by Jillian999** [winsiderss/systeminformer#2087]
### Brief description of your issue

Build 3.1.7741 shows 3.0.7741 in Help--> About

**Comment by MagicAndre1981** [comment]
I have the same, so the update to 3.1.7741 is offered again and again.

**Comment by dmex** [comment]
@MagicAndre1981 

The updater can't offer an update more than once every 7 days?

**Comment by ToddIndry37** [comment]
I got the same bug here. I thought System Informer got upgraded to 3.1 but it's not lol.

![image](https://github.com/winsiderss/systeminformer/assets/88038185/bbdddb47-634e-4a4f-acb0-4c0b3e10e63b)

**Comment by Almighty188** [comment]
Same issue here:
![image](https://github.com/winsiderss/systeminformer/assets/78993393/9fc63027-e345-48d8-9cf1-a01b4dbac741)

Also should update the Copyright (c) to 2024 LOL

**Comment by Almighty188** [comment]
Anyone successfully able to update their GeoIP database in this version?

**Comment by ToddIndry37** [comment]
Oh yeah, it is! They forgot to change the copyright year on 3.1 huh. That also should gonna change too.

**Comment by Almighty188** [comment]
Not just in 3.1, they never updated the 2023 in all versions  that came out in 2024 but since the About screen was mentioned, might as well mention it.

> Oh yeah, it is! They forgot to change the copyright year on 3.1 huh. That also should gonna change too. Sent from my iPhone 6+ lol
> […](#)
> On 8 Jun 2024, at 08.05, Almighty188 ***@***.***> wrote: Same issue here: image.png (view on web) Also should update the Copyright (c) to 2024 LOL — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.

**Comment by Almighty188** [comment]
> @MagicAndre1981
> 
> The updater can't offer an update more than once every 7 days?

I don't think so, wouldn't the actual issue be 3.**1**.7741 is coded as 3.**0**.7741** so when the update checks, it will always see 3.**1**.7741 as a newer version than 3.**0**.7741 which is actually 3.**1**.7741?

**Comment by kotenok2000** [comment]
It reports 3.1.0.7741  for me.
Looks like someone tried to fix it but couldn't.
![image](https://github.com/winsiderss/systeminformer/assets/8822292/7497c9ed-7851-45c6-b55d-f4e6f769ab8c)

**Comment by Almighty188** [comment]
> It reports 3.1.0.7741 for me. Looks like someone tried to fix it but couldn't. ![image](https://private-user-images.githubusercontent.com/8822292/337967737-7497c9ed-7851-45c6-b55d-f4e6f769ab8c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc5OTIzNTcsIm5iZiI6MTcxNzk5MjA1NywicGF0aCI6Ii84ODIyMjkyLzMzNzk2NzczNy03NDk3YzllZC03ODUxLTQ1YzYtYjU1ZC1mNGU2Zjc2OWFiOGMucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTBUMDQwMDU3WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmY5YjFjZmNmMzY3NGE2NTUzNGQzMzY1ODhhNjc0MzdiMzMxZjMwMjAwOGQ1MzQ1ZmE4Njg5MGFiNGQyMDMyMiZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.H2XcUzMEGN4EpLZ76W3ILgs8rNiMc2dWbCp4tdq4eSc)

@kotenok2000 - Talking about two different things, place your mouse pointer over the SystemInformer.exe process while running v3.1.7741 and what does it show for the version number?  Your updater is interesting as it shows v3.1."0".7741 not v3.1.7741, there is a extra 0. before the 7741.

**Comment by dmex** [comment]
We're changing the build format and testing the changes before the next canary release.

**Comment by ToddIndry37** [comment]
Does this build probably fix this issue or something? Or maybe the same thing?

![image](https://github.com/winsiderss/systeminformer/assets/88038185/29b225d4-22e2-4620-af68-8ce790a82336)

**Comment by kotenok2000** [comment]
no

![image](https://github.com/winsiderss/systeminformer/assets/8822292/3804cbce-b841-4eeb-85b6-5438de6bd7e8)

**Comment by ToddIndry37** [comment]
Yep, I tried to update it, and it still stuck on current version. Nothing has changed.

![image](https://github.com/winsiderss/systeminformer/assets/88038185/5b48a0cd-f79c-4e3e-91b2-56efc96e06d6)

**Comment by Almighty188** [comment]
I never use the built-in Check for updates feature as I usually just download the -bin archive of the latest available build.  It seems Check for Updates for stable will show v3.0.7660 while canary will shows v3.1.12000.7441 when according to https://github.com/winsiderss/si-builds/releases/tag/3.1.7741, v3.1.7741 is supposed to be the latest stable and canary build.

**Comment by ToddIndry37** [comment]
> I never use the built-in Check for updates feature as I usually just download the -bin archive of the latest available build. It seems Check for Updates for stable will show v3.0.7660 while canary will shows v3.1.12000.7441 when according to https://github.com/winsiderss/si-builds/releases/tag/3.1.7741, v3.1.7741 is supposed to be the latest stable and canary build, the first and only v3.1 build. v3.0.7660 was supposedly the last v3.0 build.

Let me try that. If that still didn't in effect, could be they should update it soon on next build.

**Comment by Almighty188** [comment]
> > I never use the built-in Check for updates feature as I usually just download the -bin archive of the latest available build. It seems Check for Updates for stable will show v3.0.7660 while canary will shows v3.1.12000.7441 when according to https://github.com/winsiderss/si-builds/releases/tag/3.1.7741, v3.1.7741 is supposed to be the latest stable and canary build, the first and only v3.1 build. v3.0.7660 was supposedly the last v3.0 build.
> 
> Let me try that. If that still didn't in effect, could be they should update it soon on next build. **Update**: It doesn't do anything, even I install or overwrite it through the installer itself.

It is the same build because you can tell from the timestamp and that's what I am using  to post all the above screenshots in this thread so it's not the build even though 7741 which is listed as 3.1 seems to itself think it is a 3.0 version.

**Comment by ToddIndry37** [comment]
> > > I never use the built-in Check for updates feature as I usually just download the -bin archive of the latest available build. It seems Check for Updates for stable will show v3.0.7660 while canary will shows v3.1.12000.7441 when according to https://github.com/winsiderss/si-builds/releases/tag/3.1.7741, v3.1.7741 is supposed to be the latest stable and canary build, the first and only v3.1 build. v3.0.7660 was supposedly the last v3.0 build.
> > 
> > 
> > Let me try that. If that still didn't in effect, could be they should update it soon on next build. **Update**: It doesn't do anything, even I install or overwrite it through the installer itself.
> 
> It is the same build because you can tell from the timestamp and that's what I am using to post all the above screenshots in this thread so it's not the build even though 7741 which is listed as 3.1 seems to itself think it is a 3.0 version. So we will probably have to wait until the next build comes out to know for sure if the updater is reporting the correct results or not since one is already on the latest build.

Yeah, well... guess I'll wait for the next build, and also making the kernel driver compatible with Patch Tuesday builds on Windows 10 & 11.

**Comment by Almighty188** [comment]
> > > > I never use the built-in Check for updates feature as I usually just download the -bin archive of the latest available build. It seems Check for Updates for stable will show v3.0.7660 while canary will shows v3.1.12000.7441 when according to https://github.com/winsiderss/si-builds/releases/tag/3.1.7741, v3.1.7741 is supposed to be the latest stable and canary build, the first and only v3.1 build. v3.0.7660 was supposedly the last v3.0 build.
> > > 
> > > 
> > > Let me try that. If that still didn't in effect, could be they should update it soon on next build. **Update**: It doesn't do anything, even I install or overwrite it through the installer itself.
> > 
> > 
> > It is the same build because you can tell from the timestamp and that's what I am using to post all the above screenshots in this thread so it's not the build even though 7741 which is listed as 3.1 seems to itself think it is a 3.0 version. So we will probably have to wait until the next build comes out to know for sure if the updater is reporting the correct results or not since one is already on the latest build.
> 
> Yeah, well... guess I'll wait for the next build, and also making the kernel driver compatible with Patch Tuesday builds on Windows 10 & 11.

I can't use the kernel driver because it doesn't work with non-stable Windows 11 builds.  Are you using the kernel driver?

**Comment by ToddIndry37** [comment]
> > > > > I never use the built-in Check for updates feature as I usually just download the -bin archive of the latest available build. It seems Check for Updates for stable will show v3.0.7660 while canary will shows v3.1.12000.7441 when according to https://github.com/winsiderss/si-builds/releases/tag/3.1.7741, v3.1.7741 is supposed to be the latest stable and canary build, the first and only v3.1 build. v3.0.7660 was supposedly the last v3.0 build.
> > > > 
> > > > 
> > > > Let me try that. If that still didn't in effect, could be they should update it soon on next build. **Update**: It doesn't do anything, even I install or overwrite it through the installer itself.
> > > 
> > > 
> > > It is the same build because you can tell from the timestamp and that's what I am using to post all the above screenshots in this thread so it's not the build even though 7741 which is listed as 3.1 seems to itself think it is a 3.0 version. So we will probably have to wait until the next build comes out to know for sure if the updater is reporting the correct results or not since one is already on the latest build.
> > 
> > 
> > Yeah, well... guess I'll wait for the next build, and also making the kernel driver compatible with Patch Tuesday builds on Windows 10 & 11.
> 
> I can't use the kernel driver because it doesn't work with non-stable Windows 11 builds. Are you using the kernel driver?

Yes, since it supported my Windows 11 kernel though. I don't use beta builds on here.

**Comment by Almighty188** [comment]
> > > > > > I never use the built-in Check for updates feature as I usually just download the -bin archive of the latest available build. It seems Check for Updates for stable will show v3.0.7660 while canary will shows v3.1.12000.7441 when according to https://github.com/winsiderss/si-builds/releases/tag/3.1.7741, v3.1.7741 is supposed to be the latest stable and canary build, the first and only v3.1 build. v3.0.7660 was supposedly the last v3.0 build.
> > > > > 
> > > > > 
> > > > > Let me try that. If that still didn't in effect, could be they should update it soon on next build. **Update**: It doesn't do anything, even I install or overwrite it through the installer itself.
> > > > 
> > > > 
> > > > It is the same build because you can tell from the timestamp and that's what I am using to post all the above screenshots in this thread so it's not the build even though 7741 which is listed as 3.1 seems to itself think it is a 3.0 version. So we will probably have to wait until the next build comes out to know for sure if the updater is reporting the correct results or not since one is already on the latest build.
> > > 
> > > 
> > > Yeah, well... guess I'll wait for the next build, and also making the kernel driver compatible with Patch Tuesday builds on Windows 10 & 11.
> > 
> > 
> > I can't use the kernel driver because it doesn't work with non-stable Windows 11 builds. Are you using the kernel driver?
> 
> Yes, since it supported my Windows 11 kernel though. I don't use beta builds on here.

That could be the variable on the whois crash.

**Comment by MagicAndre1981** [comment]
looks like team removed that update to prevent users to run into the update showing again issue.

**Comment by Almighty188** [comment]
Looks like on https://github.com/winsiderss/si-builds/releases - v3.1.7741 got removed as v3.0.7660 is the latest version shown.

**Comment by MagicAndre1981** [comment]
works now with 3.1.24184.1 (3aab5576)

![image](https://github.com/winsiderss/systeminformer/assets/8274816/3c0a7c78-868d-4366-8f29-2725607f6cbc)


So this can be closed
