### ISSUE TITLE
Whois Address crashing System Informer

### ISSUE THREAD

**Issue by ToddIndry37** [winsiderss/systeminformer#2089]
### Brief description of your issue

When I check the _Whois address_ under network tools in System Informer, after I type the website address, System Informer immediately crashed due to "Invalid access to the memory location".

### Steps to reproduce (optional)

1. Open System Informer (either run normally or run as administrator)
2. Click Tools > Network Tools > Whois Address…
3. Type any website you want to check
4. Click OK or press Enter

### Expected behavior (optional)

It should be showing the whois details on the window

### Actual behavior (optional)

Crashed with error code `0xC0000005`, invalid access to the memory location

![image](https://github.com/winsiderss/systeminformer/assets/88038185/f201f56e-97c5-4215-8907-6bd612ca6b56)

And here is the dump for troubleshooting:
[SystemInformer_DumpFile_FNRQRVBXORZRKZH.dmp](https://github.com/user-attachments/files/15747360/SystemInformer_DumpFile_FNRQRVBXORZRKZH.dmp)

### Environment (optional)

```shell
System Informer 3.1.7741 (25e6b31) Canary
Windows 11 23H2 (build 22631.3593)
```

**Comment by dmex** [comment]
The dialog is being destroyed before it's created:

![image](https://github.com/winsiderss/systeminformer/assets/1306177/4529b049-d630-4381-abd2-27b772ef6f1f)

**Comment by Almighty188** [comment]
Works fine for me in System Informer v3.1.7741 Canary

![image](https://github.com/winsiderss/systeminformer/assets/78993393/324db652-aa47-447d-8c30-6974dcb1dd9c)

**Comment by ToddIndry37** [comment]
> Works fine for me in System Informer v3.1.7741 Canary
> 
> ![image](https://private-user-images.githubusercontent.com/78993393/338049339-324db652-aa47-447d-8c30-6974dcb1dd9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNjc0NzEsIm5iZiI6MTcxODA2NzE3MSwicGF0aCI6Ii83ODk5MzM5My8zMzgwNDkzMzktMzI0ZGI2NTItYWE0Ny00NDdkLThjMzAtNjk3NGRjYjFkZDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAwNTI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NGE0NDY3N2JjMDg5YjRiNmEyNGRmYjUxNjNmNmYxYTM1Zjc1MWEyN2IwNjlhNDJkNGFjODg4N2FhMzIxNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Df0eUdstUgco8buTaK1LEsSHU6mGLgwdC0kMnf23ZWQ)

Well, for me, it crashed because of what @dmex says previously. I don't know why your System Informer worked fine when doing the exact same thing, but me it's not.

**Comment by ToddIndry37** [comment]
> The dialog is being destroyed before it's created:
> 
> ![image](https://private-user-images.githubusercontent.com/1306177/337923354-4529b049-d630-4381-abd2-27b772ef6f1f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNjc0NzEsIm5iZiI6MTcxODA2NzE3MSwicGF0aCI6Ii8xMzA2MTc3LzMzNzkyMzM1NC00NTI5YjA0OS1kNjMwLTQzODEtYWJkMi0yN2I3NzJlZjZmMWYucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDYxMSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA2MTFUMDA1MjUxWiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9OTViZjc0MGIxODdiOGM1ZWNiMzFhNWVmYjVkM2NhZmVlY2Y5Y2QxZDU1NzBiYmEwNTUzYjhmMTA2ZDRlMDRjMyZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.ncZOH-6UGu7znynr33_RE_xOh5A2jBtZNq5n5NRKj_I)

Ah I see. Glad that crash dump helps you.

**Comment by Almighty188** [comment]
> > Works fine for me in System Informer v3.1.7741 Canary
> > ![image](https://private-user-images.githubusercontent.com/78993393/338049339-324db652-aa47-447d-8c30-6974dcb1dd9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNjc0NzEsIm5iZiI6MTcxODA2NzE3MSwicGF0aCI6Ii83ODk5MzM5My8zMzgwNDkzMzktMzI0ZGI2NTItYWE0Ny00NDdkLThjMzAtNjk3NGRjYjFkZDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAwNTI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NGE0NDY3N2JjMDg5YjRiNmEyNGRmYjUxNjNmNmYxYTM1Zjc1MWEyN2IwNjlhNDJkNGFjODg4N2FhMzIxNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Df0eUdstUgco8buTaK1LEsSHU6mGLgwdC0kMnf23ZWQ)
> 
> Well, for me, it crashed because of what @dmex says previously. I don't know why your System Informer worked fine when doing the exact same thing, but me it's not.

@ToddIndry37 - Yeah, I wonder why it works for me.  But I am glad atleast @dmex acknowledged it's a problem as it might crash maybe under certain conditions that I haven't tried as I only tried once so it could crash in other instances.

**Comment by ToddIndry37** [comment]
> > > Works fine for me in System Informer v3.1.7741 Canary
> > > ![image](https://private-user-images.githubusercontent.com/78993393/338049339-324db652-aa47-447d-8c30-6974dcb1dd9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNjc0NzEsIm5iZiI6MTcxODA2NzE3MSwicGF0aCI6Ii83ODk5MzM5My8zMzgwNDkzMzktMzI0ZGI2NTItYWE0Ny00NDdkLThjMzAtNjk3NGRjYjFkZDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAwNTI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NGE0NDY3N2JjMDg5YjRiNmEyNGRmYjUxNjNmNmYxYTM1Zjc1MWEyN2IwNjlhNDJkNGFjODg4N2FhMzIxNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Df0eUdstUgco8buTaK1LEsSHU6mGLgwdC0kMnf23ZWQ)
> > 
> > 
> > Well, for me, it crashed because of what @dmex says previously. I don't know why your System Informer worked fine when doing the exact same thing, but me it's not.
> 
> @ToddIndry37 - Yeah, I wonder why it works for me. But I am glad atleast @dmex acknowledged it's a problem as it might crash maybe under certain conditions that I haven't tried as I only tried once so it could crash in other instances. Probably your crash dump is what really help show what triggered the problem.

Yeah hehe, exactly. Glad I did send the crash dump though, so it's easy to identify what's the issue. Also, you use Windows 11, right? Or 10? Mine is Windows 11 23H2.

**Comment by Almighty188** [comment]
> > > > Works fine for me in System Informer v3.1.7741 Canary
> > > > ![image](https://private-user-images.githubusercontent.com/78993393/338049339-324db652-aa47-447d-8c30-6974dcb1dd9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNjc0NzEsIm5iZiI6MTcxODA2NzE3MSwicGF0aCI6Ii83ODk5MzM5My8zMzgwNDkzMzktMzI0ZGI2NTItYWE0Ny00NDdkLThjMzAtNjk3NGRjYjFkZDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAwNTI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NGE0NDY3N2JjMDg5YjRiNmEyNGRmYjUxNjNmNmYxYTM1Zjc1MWEyN2IwNjlhNDJkNGFjODg4N2FhMzIxNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Df0eUdstUgco8buTaK1LEsSHU6mGLgwdC0kMnf23ZWQ)
> > > 
> > > 
> > > Well, for me, it crashed because of what @dmex says previously. I don't know why your System Informer worked fine when doing the exact same thing, but me it's not.
> > 
> > 
> > @ToddIndry37 - Yeah, I wonder why it works for me. But I am glad atleast @dmex acknowledged it's a problem as it might crash maybe under certain conditions that I haven't tried as I only tried once so it could crash in other instances. Probably your crash dump is what really help show what triggered the problem.
> 
> Yeah hehe, exactly. Glad I did send the crash dump though, so it's easy to identify what's the issue. Also, you use Windows 11, right? Or 10? Mine is Windows 11 23H2.

Windows 11 23H2 22635.3720 Beta Insiders

**Comment by ToddIndry37** [comment]
> > > > > Works fine for me in System Informer v3.1.7741 Canary
> > > > > ![image](https://private-user-images.githubusercontent.com/78993393/338049339-324db652-aa47-447d-8c30-6974dcb1dd9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNjc0NzEsIm5iZiI6MTcxODA2NzE3MSwicGF0aCI6Ii83ODk5MzM5My8zMzgwNDkzMzktMzI0ZGI2NTItYWE0Ny00NDdkLThjMzAtNjk3NGRjYjFkZDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAwNTI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NGE0NDY3N2JjMDg5YjRiNmEyNGRmYjUxNjNmNmYxYTM1Zjc1MWEyN2IwNjlhNDJkNGFjODg4N2FhMzIxNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Df0eUdstUgco8buTaK1LEsSHU6mGLgwdC0kMnf23ZWQ)
> > > > 
> > > > 
> > > > Well, for me, it crashed because of what @dmex says previously. I don't know why your System Informer worked fine when doing the exact same thing, but me it's not.
> > > 
> > > 
> > > @ToddIndry37 - Yeah, I wonder why it works for me. But I am glad atleast @dmex acknowledged it's a problem as it might crash maybe under certain conditions that I haven't tried as I only tried once so it could crash in other instances. Probably your crash dump is what really help show what triggered the problem.
> > 
> > 
> > Yeah hehe, exactly. Glad I did send the crash dump though, so it's easy to identify what's the issue. Also, you use Windows 11, right? Or 10? Mine is Windows 11 23H2.
> 
> Windows 11 23H2 22635.3720 Beta Insiders

Ah, that is why it didn't crash on you.

**Comment by Almighty188** [comment]
> > > > > > Works fine for me in System Informer v3.1.7741 Canary
> > > > > > ![image](https://private-user-images.githubusercontent.com/78993393/338049339-324db652-aa47-447d-8c30-6974dcb1dd9c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwNjc0NzEsIm5iZiI6MTcxODA2NzE3MSwicGF0aCI6Ii83ODk5MzM5My8zMzgwNDkzMzktMzI0ZGI2NTItYWE0Ny00NDdkLThjMzAtNjk3NGRjYjFkZDljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjExVDAwNTI1MVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ2NGE0NDY3N2JjMDg5YjRiNmEyNGRmYjUxNjNmNmYxYTM1Zjc1MWEyN2IwNjlhNDJkNGFjODg4N2FhMzIxNTUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Df0eUdstUgco8buTaK1LEsSHU6mGLgwdC0kMnf23ZWQ)
> > > > > 
> > > > > 
> > > > > Well, for me, it crashed because of what @dmex says previously. I don't know why your System Informer worked fine when doing the exact same thing, but me it's not.
> > > > 
> > > > 
> > > > @ToddIndry37 - Yeah, I wonder why it works for me. But I am glad atleast @dmex acknowledged it's a problem as it might crash maybe under certain conditions that I haven't tried as I only tried once so it could crash in other instances. Probably your crash dump is what really help show what triggered the problem.
> > > 
> > > 
> > > Yeah hehe, exactly. Glad I did send the crash dump though, so it's easy to identify what's the issue. Also, you use Windows 11, right? Or 10? Mine is Windows 11 23H2.
> > 
> > 
> > Windows 11 23H2 22635.3720 Beta Insiders
> 
> Ah, that is why it didn't crash on you.

I have a higher chance of crashing as my CPU is hitting 100% due to CPU temperature throttling, will need to replace the thermal grease when I open the notebook to replace the keyboard in the next few weeks.

**Comment by dmex** [comment]
>  Yeah, I wonder why it works for me. But I am glad atleast @dmex acknowledged it's a problem as it might crash maybe under certain conditions

If the edit control failed to initialize or fail loading the DLL it would start destroying the window from the create handler. The destroy callback is where generally memory is deallocated and desoying objects from the create handler, before the're initialized isn't the normal window cleanup and so it crashed trying to destroy objects before they were initialized.

![image](https://github.com/user-attachments/assets/cf1145d2-3f04-46e4-8779-1166fe6ee600)

We preload the edit control before creating the dialog and skip the dialog entirely.
