### ISSUE TITLE
Geolite database downloader downloads GeoLite2-Country instead of GeoLite-City

### ISSUE THREAD

**Issue by kotenok2000** [winsiderss/systeminformer#2091]
### Brief description of your issue

When i set dropdown to GeoLite City (Large) SystemInformer still downloads GeoLite Country (Small)

### Actual behavior (optional)

![image](https://github.com/winsiderss/systeminformer/assets/8822292/1cbb09fb-23c4-4aea-b211-dee4fc8f01fb)

### Environment (optional)

```shell
3.0.7741
Microsoft Windows [Version 10.0.22631.3593]
```

**Comment by Almighty188** [comment]
Same thing here with v3.1.7741 Canary

<img width="477" alt="image" src="https://github.com/winsiderss/systeminformer/assets/78993393/b99bee7e-9f62-424a-bf2a-9d77be539f39">

**Comment by Almighty188** [comment]
Fixed in System Informer v3.1.24184.1 Canary

![image](https://github.com/winsiderss/systeminformer/assets/78993393/fa7bb817-2b7c-4b38-a0c2-5d67051334b0)
