### ISSUE TITLE
Update PresentMon to Version 2.1.0 to fix security issues

### ISSUE THREAD

**Issue by MagicAndre1981** [winsiderss/systeminformer#2097]
### Description of the feature, modification, idea or suggestion

https://github.com/GameTechDev/PresentMon/releases/tag/v2.1.0

> **Bug Fixes**
> 
Addressed various low impact security CVEs.

**Comment by dmex** [comment]
> Addressed various low impact security CVEs.

System Informer only includes the win32k present event trace from PresentMon. We don't use any of the PresentMon application related support like NPM:

`https://github.com/GameTechDev/PresentMon/commit/e5aa9c9068f9e850db45cdb7cd59580c85475b65`

**Comment by MagicAndre1981** [comment]
ok
