### ISSUE TITLE
Windows 11 kernel driver update

### ISSUE THREAD

**Issue by derudi** [winsiderss/systeminformer#2099]
### Description of the feature, modification, idea or suggestion

Hi, process hacker 3 told me to open a request for kernel support in my version of Windows 11:

Windows 11      23H2 10.0.22631
Windows Kernel  10.0.22621.3733
System Informer 3.0.7660 (08de40d) Canary

greetings from germany

**Comment by jxy-s** [comment]
Duplicate: https://github.com/winsiderss/systeminformer/issues/1823

**Comment by derudi** [comment]
hi there again,

i would also like to ask if there is a way to make SystemInformer auto-safe everything i set in for the processes as ex. priority,io,affinity etc. without manually checking it every single time for every process.
or is there a keybind/combo that i dont know that autosaves every for selected process or something similar?

greetings
thanks in advance

**Comment by dmex** [comment]
@derudi 

Try the save option right below each menu item.
