### ISSUE TITLE
Kernel Driver Support - Windows 11 Enterprise

### ISSUE THREAD

**Issue by FaMaSha** [winsiderss/systeminformer#2103]
### Brief description of your issue

Hi There,

I'd to kindly ask, if you can add the support for the Windows 11 Enterprise.

Windows 11 22H2 10.0.22621
Kernel 10.0.22621.3733
System Informer 3.0.7660 (08de40d)

Many Thanks and Greets from Germany

Cheers,
Freddy 

### Steps to reproduce (optional)

Admin rights didn't help ;)

### Expected behavior (optional)

No Kernel Information

### Actual behavior (optional)

Error on Startup

### Environment (optional)

```shell
Windows 11 22H2 10.0.22621
Kernel 10.0.22621.3733
System Informer 3.0.7660 (08de40d)
```

**Comment by jxy-s** [comment]
Duplicate: https://github.com/winsiderss/systeminformer/issues/1823

(When resolved you need to switch to the Canary channel)

**Comment by FaMaSha** [comment]
Many Thanks for the very quick response!
Cheers...
