### ISSUE TITLE
CustomBuildTool problem with compilation

### ISSUE THREAD

**Issue by henrypp** [winsiderss/systeminformer#2108]
### Brief description of your issue

1) Your CustomBuildTool was made SI with version 0.0 (it is not cool, because i need to refute every start SI because of updater), and i know that you changed this tool, but...

![sshot-003](https://github.com/winsiderss/systeminformer/assets/3902025/415d416b-4403-464f-9eb9-c1deccfe83a9)

2) Error:

![sshot-004](https://github.com/winsiderss/systeminformer/assets/3902025/137b46c9-2998-46cf-91cf-4d5438f0cec2)
25/06/2024 now it fixed!

**Comment by MagicAndre1981** [comment]
there is already the PR #2106 to fix it

**Comment by trparky** [comment]
My pull request, namely https://github.com/winsiderss/systeminformer/pull/2106, has been closed by me (the author). As I mentioned in the closing comments, something must have changed in another commit to fix this issue since now the code compiles without incident even without my changes.

**Comment by henrypp** [comment]
>  25/06/2024 now it fixed!

my comment above.

@trparky it is noting changed even in SI repo (or i did not find it), but compile is A-OK, all good, only 0.0 version was not changed by now

**Comment by trparky** [comment]
Excuse me. What?

**Comment by henrypp** [comment]
@trparky custombuild tool was create bibary with version 0.0, all in this issue

**Comment by trparky** [comment]
This? https://github.com/winsiderss/systeminformer/commit/456731b8f90f64a4a050b8d2ff9528c44f5ec3d6

**Comment by henrypp** [comment]
@trparky maybe, even recompile custombuildtool was generate binary with version 0.0

**Comment by trparky** [comment]
> @trparky maybe, even recompile custombuildtool was generate binary with version 0.0

Yeah, that's weird. I wonder what difference it makes.

**Comment by henrypp** [comment]
@trparky that is strange answer - updater will bring every start and tell me that new version available

**Comment by henrypp** [comment]
now, i think, problem are solved

![sshot-003](https://github.com/winsiderss/systeminformer/assets/3902025/138e8402-a484-40b2-9dff-9cd51bba660d)
