### ISSUE TITLE
Build breakage on Visual Studio 2022 17.10.3

### ISSUE THREAD

**Issue by robertroessler** [winsiderss/systeminformer#2113]
### Brief description of your issue

I do semi-regular "pulls" from github for System Informer.  Since (at least) June 23, and with a total of 3 pulls since then, VS 2022 has had *simple* compile failures:

...\systeminformer\SystemInformer\sysscmem.c line 1058 VS wants kernelFileName to be initialized, since it can't tell that it was presumably set in the call above to PhGetKernelFileNameEx()
C:\usr\Play\systeminformer\SystemInformer\thrdprv.c line 342 VS wants fileName to be initialized, since it can't tell that it was presumably set in the call above to PhGetKernelFileNameEx()

You might think this should only be a warning, but it will NOT go away if you say to not promote warnings into errors - aside from changing the source and initing these vars to nullprtr, I made the build complete by disabling the so-called "SDL" check.

EDIT: In case this wasn't clear, I mean to say that *either* the simple source edit(s) will work *or* changing the "SDL" VS project option to "false" will work - whichever approach you take, you will get clean builds.

### Environment (optional)

```shell
Local builds of System Informer based on "latest" github sources.
Windows 11 [Insiders] 24H2 prelease (really).
Visual Studio 2022 17.10.3
```

**Comment by trparky** [comment]
Do a pull of the new code, execute build_clean.cmd, and it should work. I had the same issue and it resolved itself in a recent commit.

**Comment by robertroessler** [comment]
Cool, thanks, you are certainly correct - but I don't understand _why_.

The source is the source (nothing had changed since my last pull), and the compiler hasn't changed - so why is it now unconcerned with those 2 lines in those 2 files after just removing all build artifacts and re-executing the same VS solution and project files?

In any case, thanks again.

**Comment by dmex** [comment]
@robertroessler This has been an issue with MSVC for a long time: https://stackoverflow.com/questions/17703004/visual-studio-displaying-errors-even-if-projects-build

> why is it now unconcerned with those 2 lines in those 2 files after just removing all build artifacts and re-executing the same VS solution and project files?

Disable the /INCREMENTAL option has NO otherwise MSVC doesn't always detect changes and compiles broken code. You need to disable it under Project properties > Linker:

![image](https://github.com/winsiderss/systeminformer/assets/1306177/7a46ca7a-c131-42f4-a18c-59d0ac948357)
