### ISSUE TITLE
System tray pop-up won't work on Windows 11

### ISSUE THREAD

**Issue by Core-2-Extreme** [winsiderss/systeminformer#2118]
### Brief description of your issue

System tray pop-up which will be shown when hovering system tray icon doesn't work after clicking system tray icon once on Windows 11.
It doesn't occur on windows 10 (I tested it on 22H2).
Restarting system informer will fix the problem, but will occur again if I click system tray icon once.

### Steps to reproduce (optional)

1. Close system informer if it's running.
2. Open system informer.
3. Hover on system tray icon to check if pop-up shows.
4. Pop-up shows here as expected.
5. Click on system tray icon to show/hide system informer **except right click** can be used to reproduce the problem.
6. Hover on system tray icon to check if pop-up shows.
7. **Pop-up won't be shown**.

### Expected behavior (optional)

(In step 3)

https://github.com/winsiderss/systeminformer/assets/45873899/aa4c91c0-306f-4881-914e-3a025add0b4c

### Actual behavior (optional)

(In step 6)

https://github.com/winsiderss/systeminformer/assets/45873899/93de20eb-4309-4e7c-9a58-ceb0bfc93a1d

### Environment (optional)

```shell
System informer : 3.0.7660 (08de40d)
Windows : Windows 11 Pro 10.0.22631 Build 22631 (23H2)
```

**Comment by enervated** [comment]
I'm seeing the exact same behavior and would've reported it had this issue not already existed.
Win11 23H2, System Informer 3.0.7660.

**Comment by SolarTheory** [comment]
Same. Exactly as described by OP. This has actually been happening for me for many many months. Maybe even into end of last year. I don't recall exactly when I began noticing it.  I have just dealt with it, hoping it will be fixed will each successive release. It is also only  my Windows 11 machine that has been exhibiting this issue (Windows 10 systems are fine).

**Comment by enervated** [comment]
> If you left-click on an empty section of the taskbar, then proceed to right-click the tray icon, does this sequence of actions fix the tray icon menu?
> 
> ![image](https://private-user-images.githubusercontent.com/1306177/350452804-6347c6fe-57f4-41d6-bc6f-2c50ac1f51b8.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE0MDM3ODYsIm5iZiI6MTcyMTQwMzQ4NiwicGF0aCI6Ii8xMzA2MTc3LzM1MDQ1MjgwNC02MzQ3YzZmZS01N2Y0LTQxZDYtYmM2Zi0yYzUwYWMxZjUxYjgucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcxOSUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MTlUMTUzODA2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDQ0MGIwMzRhMDgyMzU3MzI4ZTZmYmJlZjYzNTZkNjFhMWIwMTY4ZmVlMjIyYTAxYzdmNmY5YTNiYzBjYTZhZCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.o84fu2IK8Q98XTjuaIebVXRzCfkrMNjh3BtCfVlELS0)

For me, no, this does not fix the tray icon pop-up (which is what I assume you meant to refer to).

**Comment by Core-2-Extreme** [comment]
> If you left-click on an empty section of the taskbar, then proceed to right-click the tray icon, does this sequence of actions fix the tray icon menu?

It doesn't work for me either.

> This is what does temporarily fix it:
> 1. Right click a System Informer tray icon (causing the SI context menu to open).
> 2. Left click a System Informer tray icon (with the SI context menu still showing), opening the main SI window.
> 3. Close the System Informer main window (using either the ESC key or the "x" caption button).

It partially works for me.
In step 3, if I use ESC key to close SI, it works (pop-up shows) however if I use "X" button to close SI it doesn't work for me.

**Comment by Core-2-Extreme** [comment]
> Same. Exactly as described by OP. This has actually been happening for me for many many months. Maybe even into end of last year. I don't recall exactly when I began noticing it.

I noticed this issues since the windows 11 is called "new version of windows (likely windows 11) has been leaked" so I think this issue exists since first release of windows 11 (maybe 21H2?).

**Comment by CriDos** [comment]
Starting from this build, this issue appears - https://github.com/winsiderss/si-builds/releases/tag/3.0.6303
The build before it works normally - https://github.com/winsiderss/si-builds/releases/tag/3.0.6295

**Comment by enervated** [comment]
Awww, look, you've got your own version of reality going. Adorable. I don't care anymore. Don't fix it. DGAF. Done with this spam.

**Comment by CriDos** [comment]
The problem seems to be somewhere here: https://github.com/winsiderss/systeminformer/compare/5f3e7df...8f3d619

**Comment by Cleroth** [comment]
Still isn't working for me. Hovering on the tray icon does nothing.
