### ISSUE TITLE
Unable to load kernel driver (The referenced account is currently disabled and may not be logged on to)

### ISSUE THREAD

**Issue by poqdavid** [winsiderss/systeminformer#2123]
### Brief description of your issue

![SystemInformer_fNHCqrwySK](https://github.com/winsiderss/systeminformer/assets/9592210/d689c327-5e30-4b63-b7d2-6d77aac95ac4)
Just after the update this message poped up

### Steps to reproduce (optional)

- Update to version 3.1.24183.0 Canary.
- Run System Informer as admin.

### Environment (optional)

```shell
- System Informer version 3.1.24183.0 (24696944) x64.
- Windows 11 Pro x64, 23H2, 10.0.22631
- Windows Kernel 10.0.22621.3810
```

**Comment by jxy-s** [comment]
Known issue with the build tools run through the release pipeline, I know where the problem is - fixing now.

**Comment by jxy-s** [comment]
`3.1.24184.1` - `Help > Check for updates` - 👍
