### ISSUE TITLE
Kernel Driver Support - Windows 11 Enterprise LTSC

### ISSUE THREAD

**Issue by FaMaSha** [winsiderss/systeminformer#2126]
### Brief description of your issue

Hi There,

I'd to kindly ask, if you can add the support for the Windows 11 Enterprise LTSC.

Windows 11 24H2 10.0.26100
Kernel 10.0.26100.863
System Informer 3.0.7660 (08de40d)

I'd like to know if with solving this issue, you automatically are able to see the RAPL values, or is there something else to do, as with my last ticket (same kind of issue, but was about Enterprise w/o LTSC), after solving the issue and installing the update, there hasn't been any error messages; but I still was not able to see the RAPL values.

Many Thanks and Greets from Germany

Cheers,
Freddy

### Steps to reproduce (optional)

Admin rights didn't help ;)

### Actual behavior (optional)

Error on Startup

### Environment (optional)

```shell
Windows 11 24H2 10.0.26100
Kernel 10.0.26100.863
System Informer 3.0.7660 (08de40d)
```

**Comment by jxy-s** [comment]
Duplicate: https://github.com/winsiderss/systeminformer/issues/1823

This kernel is already supported, your version is our of date. For the latest kernel support, switch to the Canary channel:
`Help > Check for updates > Canary > Check`

It's also available for download here: https://system-informer.com/canary.php
