### ISSUE TITLE
High cpu usage in SystemInformer.exe!PhDnsFree+0x19160

### ISSUE THREAD

**Issue by kotenok2000** [winsiderss/systeminformer#2127]
### Brief description of your issue

Systeminformer uses CPU a lot.

### Actual behavior (optional)

![image](https://github.com/winsiderss/systeminformer/assets/8822292/29fee8a4-01f6-4f0f-8b0a-0a28e90dd163)

### Environment (optional)

```shell
3.1.24184.1
Microsoft Windows [Version 10.0.22631.3810]
```

**Comment by dmex** [comment]
`SystemInformer.exe!PhDnsFree+0x19160` this is 102752 bytes from PhDnsFree which could be anything.

You'll need to capture a memory dump of the process and either zip+upload or email:
![image](https://github.com/winsiderss/systeminformer/assets/1306177/9754604f-b4e3-4f64-a0a5-56f97c7c903b)

**Comment by kotenok2000** [comment]
What email?

**Comment by dmex** [comment]
You won't be able to send emails > 50mb. Upload the dump to your onedrive, gdrive or somewhere:
https://onedrive.live.com/ or https://drive.google.com/ (or somewhere else)

You can create links to the file and post the link here or email to dmex04@gmail.com

**Comment by kotenok2000** [comment]
I have sent it.

**Comment by dmex** [comment]
What's `0patchLoaderX64.dll`?

**Comment by kotenok2000** [comment]
This:
https://0patch.com/

**Comment by MagicAndre1981** [comment]
Windows Performance Toolkit is the tool to analyze cpu usage as a dump only show a snapshot.

Open cmd.exe as admin and run 

**wpr -start CPU && timeout -1 && wpr -stop %USERPROFILE%\HighCPUusage.etl -compress** 

when you captured around 30 - 60s of the usage, press a key to stop it.

Install the [analyzer from store](https://apps.microsoft.com/detail/9n0w1b2bxgnz?hl=en-US&gl=EN) and open WPA.exe, download the PDB zip for your version like [this](https://github.com/winsiderss/si-builds/releases/download/3.1.24184/systeminformer-3.1.24184-pdb.zip), extract the zip[ configure the symbols in WPA.exe](https://learn.microsoft.com/en-us/windows-hardware/test/wpt/load-symbols-or-configure-symbol-paths) to add the path of your extracted zip.

Now load the PDBs in WPA.exe (On the Trace menu, click **Load Symbols**) and [drag & drop the **CPU Usage (Sampled)** graph from the left side to the Analysis pane](https://learn.microsoft.com/en-us/shows/defrag-tools/77-wpt-example#time=07m18s) and expand the stack of systeminformer.exe and look where the cpu usage splits up and now look which functions are called.

**Comment by kotenok2000** [comment]
I don't know how to interpret this:
![image](https://github.com/winsiderss/systeminformer/assets/8822292/dd425a4b-bfc4-4596-b52e-9d0b702e6e2e)

**Comment by MagicAndre1981** [comment]
Ok, [PhEnumProcessesEx](https://github.com/winsiderss/systeminformer/blob/fc2a978e924f0f72f59928e74a5cfccbb48dfd10/phlib/native.c#L7141) is causing the usage which is called by PhProcessProviderUpdate, but the later called functions are Windows kernel functions.

And here a split is at ExpGetProcessInformation and [here are some details about it](https://revers.engineering/breaking-down-system-routines-2-ntquerysysteminformation/).

I have no idea if this can be improved. On my Windows 10 22H2 I only see some usage enumerating the GPU and getting the data in HardwareInfo plugin. Maybe MS changed something in Windows 11

**Comment by MagicAndre1981** [comment]
ok, I booted Windows 11 and here I also don't see your cpu usage. So this related to your system

**Comment by ge0rdi** [comment]
According to WPA `SystemInformer` process consumed 0.26% of CPU time during the trace (that's rather negligible).
So it probably wasn't done at time of big CPU usage the OP mentioned originally.
