### ISSUE TITLE
System Informer - Update dialog do not follow Theme (Dark)

### ISSUE THREAD

**Issue by jeansagi** [winsiderss/systeminformer#2130]
### Brief description of your issue

If Theme Support is enabled (Dark mode) selecting the option from menu "Help > Check for updates" don't follow dark mode settings:
![image](https://github.com/winsiderss/systeminformer/assets/24227857/5af8bf35-a1f4-4cc8-8127-c68046e16fd0)

### Steps to reproduce (optional)

- Enable Theme Support
- Select option "Check for updates" from "Help menu"
- The window dialog that is shown don't the dark theme

### Expected behavior (optional)

The update dialog should follow the theme settings as other System Informer windows does.

### Actual behavior (optional)

A dialog window is shown that do not follow the theme rules.

### Environment (optional)

```shell
System Informer version: 3.1.24184.1 (Canary)
Windows version        : Windows 11 23H2 (22631.3810)
```

**Comment by dmex** [comment]
Fixed in latest nightly build
