### ISSUE TITLE
SystemInformer/peview crash with lower case drive letter in executable command line

### ISSUE THREAD

**Issue by harig** [winsiderss/systeminformer#2131]
### Brief description of your issue

SystemInformer and peview both crash if started by absolute path with lower case drive letter (c: instead of C: etc.) or with a relative path in console where the cwd is having lower case drive letter.

### Steps to reproduce (optional)

- Open cmd console.
- Enter full path to systeminformer or peview starting with a lower case drive letter and press enter to execute the cmd.

### Expected behavior (optional)

Both applications to run without crash.

### Actual behavior (optional)

SystemInformer and peview crashes with access violation error.

### Environment (optional)

```shell
System Informer 3.1.24192.0 Canary on Win10
```

**Comment by jxy-s** [comment]
Fixed here: https://github.com/winsiderss/systeminformer/commit/c24ab337c8265b761c194a241dd268fd2c969b44
