### ISSUE TITLE
Process Hacker still being detected after uninstall

### ISSUE THREAD

**Issue by StormingChaos** [winsiderss/systeminformer#2134]
### Brief description of your issue

So I have no idea if this is something you can even fix, because it may not be on your end. Previously, when launching Honkai Star Rail with Process Hacker installed and running, the anticheat would flag it as a hacking tool. Obviously it is not, and I always found it strange that other hoyoverse games would launch fine, but Star Rail was the only one that had an issue with it. The solution was that any time I wanted to play Star Rail, I would simply close Process Hacker, and it would run fine. It only blocked launch if it was running. Unfortunately, that is no longer the case.

Now since switching to HoYoPlay launcher, Star Rail refuses to launch no matter what I do, and it claims Process Hacker is the issue. I tried shutting down the process, I tried upgrading to the new System Informer version, and I tried uninstalling from the windows app menu, and I have restarted my computer multiple times, including full shutdown, and starting the game as administrator. Star Rail tries to launch, but then crashes, blaming process hacker for the issue.

I am at a loss, and I know it is likely this cannot be fixed from your end, and it is simply the fault of the horrid kernel level anticheat, but I need to at least ask in case someone knows something that will work. I cannot find any remnant of process hacker left on my system, but somehow Hoyoverse can. 

Here is the error I am given when the game force closes.
!["Warning (13, 131107, 1) [kprocesshacker.sys] Some irregular events are detected in your system. Please close related applications that may affect anti-cheat modules, or check system abnormal events with anti-virus softwares. Reboot system and try to start the game process in administrator."](https://github.com/user-attachments/assets/9305445a-0812-467f-9eee-d78b79e5d3da)

### Steps to reproduce (optional)

Try to launch new version of Honkai Star Rail with Process Hacker installed

### Expected behavior (optional)

The game launches and runs fine. 

### Actual behavior (optional)

The game closes itself upon detecting kprocesshacker.sys

### Environment (optional)

```shell
Windows 10 Enterprise LTSC (10.0.19044 Build 19044)
Honkai Star Rail V2.3, HoYoPlay launcher
Originally Process Hacker version 2.39, updated to System Informer 3.0.7660, and uninstalled both.
```

**Comment by Vasilich** [comment]
i suggest that you need to scan all your harddrive for "kprocesshacker.sys" and delete it.
In case this file is locked, you need to find service "KProcessHacker", stop it, set the start mode to "disabled" and reboot. You can do it with SystemInformer on tab "Services".

**Comment by StormingChaos** [comment]
Thank you! It seems to be working now. Of course it was something so simple
