### ISSUE TITLE
I can no longer use "Reduce Working Set."

### ISSUE THREAD

**Issue by razvanab** [winsiderss/systeminformer#2136]
### Brief description of your issue

I no long can use "Reduce Working Set" on edge or any other browser.

### Steps to reproduce (optional)

1.Select all browser process.
2.Go to Miscellaneous > Reduce working set.
3.I get the Access denied message error

### Expected behavior (optional)

To reduce the memory use of the selected process.

I like to open a lot of browser tabs on YouTube and then watch them one after the other instead of one by one. And most of the time, I use the "Reduce Working Set" feature to make room for a few more tabs to open. I know this might be stupid, but it works for me.

### Environment (optional)

```shell
------------------
System Information
------------------
      Time of this report: 7/16/2024, 23:28:11
             Machine name: MAIN-PC
               Machine Id: {B8D33341-4E55-4310-B038-477958D40A69}
         Operating System: Windows 11 Pro 64-bit (10.0, Build 22631) (22621.ni_release.220506-1250)
                 Language: English (Regional Setting: English)
      System Manufacturer: Gigabyte Technology Co., Ltd.
             System Model: X470 AORUS ULTRA GAMING
                     BIOS: F62d (type: UEFI)
                Processor: AMD Ryzen 7 2700X Eight-Core Processor          (16 CPUs), ~3.7GHz
                   Memory: 32768MB RAM
      Available OS Memory: 32690MB RAM
                Page File: 44929MB used, 2609MB available
              Windows Dir: C:\Windows
          DirectX Version: DirectX 12
      DX Setup Parameters: Not found
         User DPI Setting: 120 DPI (125 percent)
       System DPI Setting: 96 DPI (100 percent)
          DWM DPI Scaling: Disabled
                 Miracast: Available, no HDCP
Microsoft Graphics Hybrid: Not Supported
 DirectX Database Version: 1.5.7
           DxDiag Version: 10.00.22621.3527 64bit Unicode
```

**Comment by MagicAndre1981** [comment]
works for me in 23H2 with Edge while having Youtube on. Edge already has a buildin feature to reduce memory usage for background tabs:

https://www.microsoft.com/en-us/edge/features/sleeping-tabs-at-work?form=MA13FJ

**Comment by razvanab** [comment]
I know Edge does have that feature, but it's mostly a hit or miss for me. 
The issue has been solved in System Informer 3.0.7660.
Thank you.

**Comment by MagicAndre1981** [comment]
>  The issue has been solved in System Informer 3.0.7660. Thank you.

ok, so you can close the issue

**Comment by MagicAndre1981** [comment]
is there still an issue related to the function? @dmex 🤔

**Comment by dmex** [comment]
Yes

**Comment by dmex** [comment]
Fixed https://github.com/winsiderss/systeminformer/commit/de6d1c9c11106632834d351f6da24c4c1bc52fe3
