### ISSUE TITLE
Unable to load kernel driver

### ISSUE THREAD

**Issue by KingAmirTheHunter** [winsiderss/systeminformer#2139]
### Description of the feature, modification, idea or suggestion

Unable to load kernel driver

The kernel driver is not yet supported on this kernel version. Request support by submitting a GitHub issue with the Windows Kernel version.

Windows 11 23H2 10.0.22631
Windows Kernel 10.0.22621.3880
System Informer 3.0.7660 (08de40d)

**Comment by MagicAndre1981** [comment]
click on Help > Check for updates > Canary > Check to update to 3.1 Canary version which supports that new kernel updates.

**Comment by GiaNTizmO** [comment]
> click on Help > Check for updates > Canary > Check to update to 3.1 Canary version which supports that new kernel updates.

I have the same version of the system and your method helped me. Thank you!
