### ISSUE TITLE
Crashed on start

### ISSUE THREAD

**Issue by lc-official** [winsiderss/systeminformer#2140]
### Brief description of your issue

![image](https://github.com/user-attachments/assets/eee7e650-1a0e-4d30-93cc-1a38b8a1d62d)

### Environment (optional)

```shell
System Informer 3.0.7660
Windows 11 23H2 10.0.22631
Windows Kernel 10.0.22621.3880
```

**Comment by MagicAndre1981** [comment]
click on **Full** to get a full crash dump, (7)zip the dmp and send the compressed file via OneDrive/Dropbox link to the team 

![image](https://github.com/user-attachments/assets/c11f2f10-db9b-4b8b-9033-e2e3a235126f)

**Comment by MagicAndre1981** [comment]
try to update SI to latest 3.1.24208.0 (ae1dd2f4) and look if this fixed your issue
