### ISSUE TITLE
Bitdefender Flanging  as Malware from Today after attempt to update for last stable versiion 

### ISSUE THREAD

**Issue by Rault1** [winsiderss/systeminformer#2142]
![image](https://github.com/user-attachments/assets/99da7b7b-496a-484e-8f05-0d290db59659)

![image](https://github.com/user-attachments/assets/8ede009f-15c8-4556-a775-cc1a05f86731)

**Comment by dmex** [comment]
Report the issue to Bitdefender?

**Comment by Rault1** [comment]
That app as working fine just start all the sudden .
