### ISSUE TITLE
Unable to load kernel driver

### ISSUE THREAD

**Issue by Odnerka11566** [winsiderss/systeminformer#2152]
The kernel driver is not yet supported on this kernel version. Request support by submitting a GitHub issue with the Windows Kernel version.

Windows 11 23H2 10.0.22631
Windows Kernel 10.0.22621.3880
System Informer 3.0.7660

![image](https://github.com/user-attachments/assets/8209ead0-557c-4e92-a3a0-2f1bc0a6d55a)

**Comment by MagicAndre1981** [comment]
click on Help > Check for updates > Canary > Check to update to 3.1 Canary version which supports new kernel updates.

Tomorrow is patchday so the message comes back and we need to wait for a new update.

**Comment by dmex** [comment]
#1823
