### ISSUE TITLE
Using System Informer on windows 11 create sound issues - pops and cracks

### ISSUE THREAD

**Issue by mmacura311** [winsiderss/systeminformer#2154]
Hi, I recently upgraded from windows 10 to windows 11 and I was using nightly builds of processhacker and later system informer for many years.
After the upgrade to windows 11 I started to have sound issues, pops and cracks in the sound (youtube in any browser, local movie file, etc). After updating (and downgrading) every possible driver I did a clean Windows 11 23H2 installation and sound worked fine. Only after installing programs, updating eg graphics drivers etc the cracks started to appear again.
After more tinkering I noticed that just exiting system informer (I usually have it running in taskbar all the time) the sound is OK.
Starting system informer make sound bad again with cracks and pops every ~1 second or so (depends on the audio being played, it is not regularly timed cracks)
The machine is lenovo legion y530 laptop with 8th gen intel cpu, nvidia 1060 and realtek sound card.

I have no clue what could be the reason but this prevents me from using system informer on my machines at the moment.
Let me know and I can provide some logs, whatever diagnostics is needed, tinker with some settings etc....

thx

**Comment by MagicAndre1981** [comment]
>  Let me know and I can provide some logs, whatever diagnostics is needed, tinker with some settings etc....

open a cmd.exe as admin and run the following command while having **System Informer** running:

**wpr -start GPU && timeout -1 && wpr -stop %USERPROFILE%\SoundIssuesRunningSystemInformer.etl -compress**

After you heared the sound issues go back to cmd and press a key to stop logging.

Now reboot to make sure the **System Informer**  driver is not running, open a cmd.exe as admin again and run this:

**wpr -start GPU && timeout -1 && wpr -stop %USERPROFILE%\NoSoundIssuesNotRunningSystemInformer.etl -compress**

capture here 30-60s to have a reference how your Windows works without having **System Informer** running.

Zip both ETL files, upload the zips to OneDrive/Dropbox and share the link.

**Comment by dmex** [comment]
Your model of laptop apparently has a hardware issue and requires BIOS updates, changes to BIOS settings and new audio drivers:

https://www.reddit.com/r/Lenovo/comments/fckye7/crackling_noise_on_legion_540_isnt_going_away/

https://forums.lenovo.com/t5/Gaming-Laptops/crackling-sound-SOLUTION-for-Legion-Y530-and-probably-other/m-p/4652164
