### ISSUE TITLE
⚙️ Show a Process count at the bottom of the SystemInformer window

### ISSUE THREAD

**Issue by User4716** [winsiderss/systeminformer#2168]
### Description of the feature, modification, idea or suggestion

Current state:
![image](https://github.com/user-attachments/assets/0446bf5b-c59d-4432-8fdb-2db68ef7cc3a)

How it used to be in ProcessHacker:
![image](https://github.com/user-attachments/assets/fa94815b-7201-491f-b969-e773aa1dec88)

**Comment by jxy-s** [comment]
Right click the bottom bar > Customize > Add "Number of processes"
