### ISSUE TITLE
Can't build 

### ISSUE THREAD

**Issue by Avtukhoff** [winsiderss/systeminformer#2171]
### Brief description of your issue

Can't build last 7 days. 

### Environment (optional)

```shell
Windows 10
```

**Comment by dmex** [comment]
```
git checkout master
git fetch -p
git reset --hard origin/master
git reflog expire --expire-unreachable=now --all
git gc --prune=now
```

![image](https://github.com/user-attachments/assets/18ec9451-4869-48f5-bc12-c034776d1cc2)
