### ISSUE TITLE
Unable to load kernel driver - Windows 11 23H2 10.0.22631

### ISSUE THREAD

**Issue by jakabok24** [winsiderss/systeminformer#2177]
### Description of the feature, modification, idea or suggestion

I tried selecting the option to allow the kernel boot driver and got an error stating the kernel driver is not yet supported on this kernel version. Request support by submitting a GitHub issue with the Windows Kernel version. 
Windows 11 23H2 10.0.22631
Windows Kernel 10.0.22621.4111
System Informer 3.0.7660 (08de40d)

**Comment by jxy-s** [comment]
Switch to the canary build.

Help > Check for updates > Canary > Check
