### ISSUE TITLE
Child process in tree view is indicated but not visible

### ISSUE THREAD

**Issue by kunom** [winsiderss/systeminformer#2183]
### Brief description of your issue

The second line here should actually list a child process, as indicated by the `>` symbol, but it doesn't:
![image](https://github.com/user-attachments/assets/b22c5f15-6cea-423f-acef-b1a4b2eccf86)

I tried to activate/deactivate various columns, but it didn't help. No Ctrl-K filter is active.

When running System Informer from a different user account, it works (i.e. the previously hidden `ssh.exe` is there, also the parenting `cmd.exe` instance):
![image](https://github.com/user-attachments/assets/c1a042ed-1faf-4b27-b50d-ff79c50ad010)

### Steps to reproduce (optional)

If you can hint me on how to reset/switch config settings, then I am happy to help.

### Environment (optional)

```shell
System Informer 3.0.7660 (08de40d)
Windows 11
```

**Comment by dmex** [comment]
Remove text from the searchbox or disable the view menu > hide processes option.

**Comment by kunom** [comment]
Thanks, the _hide system processes_ filter was active.
