### ISSUE TITLE
Changing System Infromers Name

### ISSUE THREAD

**Issue by Zorikos3** [winsiderss/systeminformer#2184]
How can I change the name of System Informer and ensure that plugins still load properly? I want to test a malware file that has anti-debug mechanisms and detects the name 'System Informer.' However, when I change the name to bypass this detection, the plugins fail to load!

**Comment by dmex** [comment]
Changing the setting `EnableWindowText` to `0` should be enough?

**Comment by Zorikos3** [comment]
> Changing the setting `EnableWindowText` to `0` should be enough?

I'm sorry, but could you please tell me where to find the "EnableWindowText" setting?

**Comment by Zorikos3** [comment]
Found it! Thank you so much @dmex for the help.
