### ISSUE TITLE
Colors for CPU utilisation like Process Explorer

### ISSUE THREAD

**Issue by Zeroes1** [winsiderss/systeminformer#2188]
### Description of the feature, modification, idea or suggestion

I use Process Explorer like ~20 years and habit see color CPU usage/history:
kernel - red
user - green

but SystemInformer use reverse colors  
kernel - green
user - red

i wish options for custom this colors
I use systeminformer-3.1.24244-canary
![image](https://github.com/user-attachments/assets/64d9c0fc-3251-4657-bb4c-e127f8db578d)
![image](https://github.com/user-attachments/assets/cea2bec3-251a-4744-a3fa-f089bc33f386)

**Comment by diversenok** [comment]
You can change the colors in the advanced options. 
1. Options -> General -> Show advanced options
2. Then go into the Advanced category and swap the values of `ColorCpuKernel` and `ColorCpuUser` settings
3.  Restart System Informer.

![image](https://github.com/user-attachments/assets/32314533-9c0e-4c59-9550-308bebc84105)

**Comment by Zeroes1** [comment]
wow, i lost Advanced options :)
thx for info, it's works!
