### ISSUE TITLE
cant build plugins

### ISSUE THREAD

**Issue by henrypp** [winsiderss/systeminformer#2194]
### Brief description of your issue

all plugins:
`error D8016: '/ZI' and '/GL' command-line options are incompatible`

**Comment by dmex** [comment]
![image](https://github.com/user-attachments/assets/e2b18a0e-2a84-4deb-a6ab-d4d2c6adb579)

**Comment by dmex** [comment]
![image](https://github.com/user-attachments/assets/ffee0882-e5d1-48e4-af08-9939efe30c91)

**Comment by henrypp** [comment]
i dont open in VS, only build_release.cmd
