### ISSUE TITLE
Plugins failed to load after updating to latest version

### ISSUE THREAD

**Issue by ToddIndry37** [winsiderss/systeminformer#2204]
### Brief description of your issue

After I update to the latest version of System Informer, all plugins except .NET Tools are failed to load because *"The operating system cannot run %1"*. I never seen this error before after updating several System Informer Canary builds.

### Steps to reproduce (optional)

1. Open System Informer like normal (either in normal run or in administrator mode)
2. Enable plugins in Settings
3. Restart System Informer

### Expected behavior (optional)

It should load all the plugins.

### Actual behavior (optional)

![image](https://github.com/user-attachments/assets/3362c404-a0bf-49bd-b120-8b8312ff81ab)

### Environment (optional)

```shell
System Informer 3.1.24244.0 Canary
Windows 10 22H2 Pro build 19045.4894
```

**Comment by dmex** [comment]
What happens when you extract everything from the binaries release and run systeminformer.exe?
https://systeminformer.sourceforge.io/canary

**Comment by ToddIndry37** [comment]
## Update
So, I think it just my side like corrupted randomly after update. Reinstalling System Informer back to normal now.
