### ISSUE TITLE
Don't builded

### ISSUE THREAD

**Issue by Avtukhoff** [winsiderss/systeminformer#2207]
### Brief description of your issue

Errors while build

Build report:

Перестроение начато в 11:09...
1>------ Перестроение всех файлов начато: проект: kphlib, Конфигурация: Release x64 ------
1>Системе не удается найти указанный путь.
1>C:\Program Files\Microsoft\IDE\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: выход из команды ""I:\systeminformer-master\tools\CustomBuildTool\bin\Release\AMD64\CustomBuildTool.exe" -dyndata "I:\systeminformer-master\bin\Release64"
1>C:\Program Files\Microsoft\IDE\MSBuild\Microsoft\VC\v170\Microsoft.CppCommon.targets(156,5): error MSB3073: :VCEnd" с кодом 3.
1>Сборка проекта "kphlib_um.vcxproj" завершена с ошибкой.
2>------ Перестроение всех файлов начато: проект: phlib, Конфигурация: Release x64 ------
2>apiimport.c
2>appresolver.c
2>appruntime.c
2>avltree.c
2>basesup.c
2>circbuf.c
2>colorbox.c
2>cpysave.c
2>data.c
2>dspick.c
2>emenu.c
2>error.c
2>extlv.c
2>fastlock.c
2>filepool.c
2>format.c
2>global.c
2>graph.c
2>guisup.c
2>handle.c
2>hexedit.c
2>hndlinfo.c
2>http.c
2>hvsocketcontrol.c
2>icotobmp.c
2>filestream.c
2>imgcoherency.c
2>mapldr.c
2>json.c
2>kph.c
2>kphcomms.c
2>lsasup.c
2>mapexlf.c
2>mapimg.c
2>maplib.c
2>native.c
2>provider.c
2>queuedlock.c
2>ref.c
2>secdata.c
2>secedit.c
2>secwmi.c
2>settings.c
2>strsrch.c
2>theme.c
2>util.c
2>svcsup.c
2>symprv.c
2>sync.c
2>treenew.c
2>verify.c
2>workqueue.c
2>wslsup.c
2>bcd.cpp
2>directdraw.cpp
2>format_std.cpp
2>symprv_std.cpp
2>LINK : fatal error LNK1181: не удается открыть входной файл "kphlib_um.lib"
2>Сборка проекта "phlib.vcxproj" завершена с ошибкой.
3>------ Перестроение всех файлов начато: проект: peview, Конфигурация: Release x64 ------
4>------ Перестроение всех файлов начато: проект: SystemInformer, Конфигурация: Release x64 ------
3>cfgprp.c
3>chcol.c
3>delayhook.c
3>mappings.c
3>pechpeprp.c
3>clrprp.c
3>clrtableimportprp.c
3>clrprptables.c
4>about.c
4>actions.c
4>admintask.c
4>affinity.c
4>anawait.c
4>appsup.c
4>chcol.c
4>chdlg.c
3>colmgr.c
3>attributes.c
3>debugprp.c
3>ehcontprp.c
3>exlfdynamic.c
3>exlfexports.c
3>exlfimports.c
3>exlfprp.c
4>chproc.c
4>colmgr.c
4>colsetmgr.c
4>dbgcon.c
3>hashprp.c
4>delayhook.c
4>delayload.c
3>layout.c
4>devprv.c
4>extmgr.c
3>pedynrelocprp.c
3>peheaderprp.c
4>findobj.c
3>pemuiprp.c
4>gdihndl.c
4>heapinfo.c
3>peprpwnd.c
3>options.c
3>peexceptprp.c
4>hidnproc.c
4>hndllist.c
4>hndlmenu.c
3>perelocprp.c
4>hndlprp.c
4>hndlprv.c
3>pesectionprp.c
3>pepogoprp.c
3>richprp.c
4>hndlstat.c
4>infodlg.c
4>itemtips.c
4>jobprp.c
3>secprp.c
4>kdump.c
3>ldprp.c
3>expprp.c
4>ksidbg.c
3>impprp.c
3>libprp.c
4>informer.c
3>links.c
4>memmod.c
4>ksisup.c
4>ksyscall.c
3>main.c
4>log.c
3>misc.c
4>logwnd.c
4>main.c
4>mainwnd.c
3>pdb.c
3>pdbprp.c
3>pedirprp.c
3>peprp.c
3>previewprp.c
4>mdump.c
3>processes.c
4>memedit.c
4>memlist.c
4>memlists.c
4>memprot.c
4>memprv.c
4>memrslt.c
3>propstore.c
3>prpsh.c
3>resprp.c
3>searchbox.c
4>memsrch.c
3>settings.c
3>streams.c
3>strings.c
4>miniinfo.c
4>modlist.c
4>modprv.c
4>mtgndlg.c
3>tlsprp.c
4>mwpgdev.c
4>mwpgnet.c
4>mwpgproc.c
4>mwpgsrv.c
3>versioninfoprp.c
3>volatileprp.c
4>netlist.c
4>netprv.c
4>notifico.c
4>ntobjprp.c
4>options.c
4>pagfiles.c
4>clapi.c
4>svcapi.c
4>svcapiport.c
4>svcclient.c
4>svcmain.c
4>plugin.c
4>plugman.c
4>procgrp.c
4>procmtgn.c
4>procprp.c
4>procprv.c
4>procrec.c
4>proctree.c
3>clrtableimports.cpp
4>prpgenv.c
4>prpggen.c
4>prpghndl.c
4>prpgjob.c
4>prpgmem.c
4>prpgmod.c
4>prpgvdm.c
4>prpgperf.c
4>prpgsrv.c
4>prpgstat.c
4>prpgthrd.c
4>prpgtok.c
4>prpgwmi.c
4>runas.c
4>searchbox.c
4>sessprp.c
4>sessshad.c
3>LINK : fatal error LNK1181: не удается открыть входной файл "phlib.lib"
4>settings.c
4>srvcr.c
4>srvctl.c
4>srvlist.c
4>srvprp.c
4>srvprv.c
4>sessmsg.c
4>sysinfo.c
3>Сборка проекта "peview.vcxproj" завершена с ошибкой.
4>syssccpu.c
4>sysscio.c
4>sysscmem.c
4>thrdlist.c
4>thrdprv.c
4>thrdstk.c
4>thrdstks.c
4>tokprp.c
4>notiftoast.cpp
4>LINK : fatal error LNK1181: не удается открыть входной файл "phlib.lib"
4>Сборка проекта "SystemInformer.vcxproj" завершена с ошибкой.
========== Перестроить все: успешно — 0, неудачно — 4, пропущено — 0 ==========
========== Перестроить завершено в 11:11 и заняло 01:37.175 мин ==========

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++                 Please consider donating to VSColorOutput                    +++
+++                       https://mike-ward.net/donate/                          +++
+++            (this message can be turned off in the settings panel)            +++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

### Steps to reproduce (optional)

Start build in Visual Studio 2022

### Environment (optional)

```shell
Window 10 x64
```

**Comment by dmex** [comment]
You need to execute `build\build_init.cmd` before you can build other parts of the project.

**Comment by Avtukhoff** [comment]
> You need to execute `build\build_init.cmd` before you can build other parts of the project.

With error's, BUT BUILD OK
![Снимок экрана (103)](https://github.com/user-attachments/assets/3d4b4f55-9d8d-4a91-878e-8e70fb0672f9)

**Comment by dmex** [comment]
You don't have the C++ workload installed and you're missing the MSVC build tools?

Mandatory:
* MSVC v143 - VS 2022 C++ x64/x86 build tools (latest)
* MSVC v143 - VS 2022 C++ x64/x86 Spectre-mitigated libs (latest)

Optional:
* MSVC v143 - VS 2022 C++ ARM build tools (latest)
* MSVC v143 - VS 2022 C++ ARM Spectre-mitigated libs (latest)
* MSVC v143 - VS 2022 C++ ARM64/ARM64EC build tools (latest)
* MSVC v143 - VS 2022 C++ ARM64/ARM64EC Spectre-mitigated libs (latest)
