### ISSUE TITLE
Unable to load kernel driver

### ISSUE THREAD

**Issue by oguh43** [winsiderss/systeminformer#2214]
### Brief description of your issue

<img width="278" alt="image" src="https://github.com/user-attachments/assets/2e933133-b201-45ce-9d37-a00c0e036bb2">

**Comment by jxy-s** [comment]
Duplicate: https://github.com/winsiderss/systeminformer/issues/1823

@oguh43, switch to the canary build `Help > Check for updates > Canary > Check`

**Comment by oguh43** [comment]
> Duplicate: #1823
> 
> @oguh43, switch to the canary build `Help > Check for updates > Canary > Check`

thanks :)
