### ISSUE TITLE
Suspend/resume process

### ISSUE THREAD

**Issue by kal0b0k** [winsiderss/systeminformer#2216]
### Brief description of your issue

After suspending the process, there is no option to resume it. It disappears in the latest Canary versions
![Снимок экрана 2024-09-26 162224](https://github.com/user-attachments/assets/3fea87d8-e7f4-42b1-a117-551110243a7d)
![Снимок экрана 2024-09-26 162333](https://github.com/user-attachments/assets/57427d32-7115-4eeb-bb1b-e5804d934458)
As temporarly solution I use resource monitor for resuming process.

### Environment (optional)

```shell
System informer 3.1.24266.0
Windows 10 22H2
```

**Comment by dmex** [comment]
As a temporary workaround resume one of the threads and the process resume option will be visible
