### ISSUE TITLE
[Feature Request] Process location column

### ISSUE THREAD

**Issue by TuTAH1** [winsiderss/systeminformer#2220]
### Description of the feature, modification, idea or suggestion

Add process location as a column

**Comment by dmex** [comment]
> Add process location as a column

What would be different from the existing `File name` column?

**Comment by TuTAH1** [comment]
> > Add process location as a column
> 
> What would be different from the existing `File name` column?

Actually, `File name` column is what I was looking for, but I misunderstood what it outputs by its name. Thanks for your help.
