### ISSUE TITLE
[BUG]: Copying Services stops at certain items

### ISSUE THREAD

**Issue by DerekZiemba** [winsiderss/systeminformer#2226]
## Background:  
My Win11 22H2 PC takes a long time to shutdown with it getting stuck at "Shutting down services" for a minute or more. I'm trying to troubleshoot which service may be causing the issue.  
I've found ChatGPT/Github Copilot to be extremely helpful regarding what a service is for, what's safe, & what potential negative side effects there are changing how or if a service/driver starts.  For Copilot to know WTF I'm talking about: from SystemInformer I navigate to the `Services` tab, select all, copy, then past to VSCode tmp file, change language mode to CSV, format as table, then start asking questions. 

## Problem

For some reason only some of what I attempt to copy actually goes to the clipboard. It seems to stop at specific Service entries _(which I'll provide in "`Steps to reproduce`")_.  

Basically it takes a while to get the list of services into VSCode.   I have to find the last entry it stopped at, then copy from there.  
Maybe this was always a bug, I know I've probably not tried to copy a list of items  since at least the `ProcessHacker --> SystemInformer` changeover, and definitely probably not the `Services` list specifically.  
_(aside: is it possible to export this list as HTML or something I can open in VSCode?)_  

These are the columns I use: 
![image](https://github.com/user-attachments/assets/75b2fb79-5d83-4f1c-ab1b-8300281f3dc3)

It seems to be stopping at the `Binary Path` column. I can copy the `Binary Path` column specifically, but if I copy the whole entry it stops just before `Binary Path`. If several entries are selected, the copy operation will stop at whatever entries has an issue.  

**If I remove `Binary Path` or `Description` columns, it will still stop at the 362nd entry. But if I remove _BOTH_, it will successfully copy all 826 of my services**

![image](https://github.com/user-attachments/assets/6abb87c8-77b4-400e-ba39-716ddc92b199)

### Steps to reproduce 

 
Usually I sort by `Start Type` but for this example I'll sort by `Name` to minimize variances. 

1. Go to `Services` tab & hotkey: `Ctrl + A` then `Ctrl + C`
1. It copies 362 services, from `1394ohci` to `mpssvc`, stopping just before `MQAC` 
   - **For `mpssvc`** the binary path path is `C:\Windows\system32\svchost.exe -k LocalServiceNoNetworkFirewall -p`, but for some reason the copy operation stopped just before it, after the description:  
`Windows Defender Firewall helps protect your computer by preventing unauthorized users from gaining access to your computer through the Internet or a network.`
1. Copy to end of list starting from `MQAC`. The next service is `MRxDAV` & the end service being `ZoomCptService`. There is about half & list of entries in between (so ~370ish).  However, the copy stops at just the `MRxDAV` service so only a single entry is copied... 
    - This might be a problematic entry, the content of what can be copied is as follows:
    `, MRxDAV, , WebDav Client Redirector Driver, Stopped, FS driver, Demand start, Network Redirector that provides WebDAV file access for the WebClient service`
    - **For `MRxDAV`** the binary path path is `\SystemRoot\system32\drivers\mrxdav.sys`, but for some reason the copy operation stopped just before it, after the description:  
`Network Redirector that provides WebDAV file access for the WebClient service`
1. Copy to end of list starting from FS Driver `mrxsmb` _^(366th entry)_ which directly follows `MRxDav` _^(365th entry)_ & paste to VSCode.  Even though there's ~370 entries selected, only 52 entries are copy/pasted. 
1. The copy stoped at entry 417 `2288, netprofm, , Network List Service, Running, Share process, Demand start, Identifies the networks to which the computer has connected, collects and stores properties for these networks, and notifies applications when these properties change.` The next entry, which is where copy stopped, is `NetSetupSvc`
1. Copy to end of list starting from `NetSetupSvc`, etc..  Only 8 entries are pasted with the paste stopping at the 425th entry:  
`, NlaSvc, , Network Location Awareness, Stopped, Share process, Demand start, Collects and stores configuration information for the network and notifies programs when this information is modified. If this service is stopped, configuration information might be unavailable. If this service is disabled, any services that explicitly depend on it will fail to start.`   
1. ### After typing this far I finally noticed the pattern & added it to the end of the **Problem** section. 

### Expected behavior (optional)

It would copy everything selected. 

### Actual behavior (optional)

> It seems to be stopping at the `Binary Path` column. I can copy the `Binary Path` column specifically, but if I copy the whole entry it stops just before `Binary Path`. If several entries are selected, the copy operation will stop at whatever entries has an issue.  
> **If I remove `Binary Path` or `Description` columns, it will still stop at the 362nd entry. But if I remove _BOTH_, it will successfully copy all 826 of my services**

### Environment (optional)

```shell
Win 11 22H2 EDU   
System Informer versions I tried:   
  - whatever older version I was on (in the range of: 2weeks to 2months ago)
  - updated to latest `Stable` to see if it changed (idk version but whatever stable version is @ time of the canary version below) 
  - updated to latest `Canary` to see if it changed (v3.1.24278.0 Canary)
```

### Suggestion: 

- You're copying to the clipboard as CSV.  You should perhaps quote the descriptions as they contain commas. Or do a `.includes(",")` on every cell then escape & wrap with quotes as needed. 
- The ability to include Headers would be nice

**Comment by dmex** [comment]
> For some reason only some of what I attempt to copy actually goes to the clipboard. It seems to stop at specific Service entries (which I'll provide in "Steps to reproduce").

There were two extra null terminators added to some of the service strings and the terminator truncates the string copied to the clipboard. The previous nightly skipped the extra null and fixed the issue 👍
