### ISSUE TITLE
[BUG] Module load count show "Static" for all modules

### ISSUE THREAD

**Issue by DartVanya** [winsiderss/systeminformer#2229]
### Brief description of your issue

In latest canary build module load counts are broken.

<details>
  <summary>Module list of explorer in canary build:</summary>
   <img alt="Canary" src="https://github.com/user-attachments/assets/cc91b792-e84e-4c89-b2ee-8e4a1ebfcdfa"/>
</details>

<details>
  <summary>Module list of explorer in stable build:</summary>
 <img alt="Canary" src="https://github.com/user-attachments/assets/da4727b4-1178-4dbc-8851-35ecb1fe96f2"/>
</details>

I tried to fix it but unable to understand what happens in module provider code and give up

### Steps to reproduce (optional)

1. Open process properties.
2. Go to module list.
3. Show "Load count" column.

### Expected behavior (optional)

Show correct real load count.

### Actual behavior (optional)

Always show static for all modules

**Comment by jxy-s** [comment]
Fixed in `3.1.24283.0` 👍
