### ISSUE TITLE
Compilation Error on Windows 11

### ISSUE THREAD

**Issue by JustinJayL** [winsiderss/systeminformer#2233]
### Brief description of your issue

I'm running into an error while compiling the systeminformer solution (Both from command line and inside of Visual Studio). I searched the issues and discussions, and no solution was found.

Visual Studio appears to be throwing an error in the file "windot11.h"

### Actual behavior (optional)

Severity	Code	Description	Project	File	Line	Suppression State	Details
Error	C2288	preprocessing number '0x6cb9a43e+' is not a valid integer or floating literal	phlib	C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared\windot11.h	2401		
Error	C2064	term does not evaluate to a function taking 0 arguments	phlib	C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared\windot11.h	2404		
Error	C2078	too many initializers	phlib	C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared\windot11.h	2404		
Error	C2064	term does not evaluate to a function taking 0 arguments	phlib	C:\Program Files (x86)\Windows Kits\10\Include\10.0.22621.0\shared\windot11.h	2405		

### Environment (optional)

```shell
Windows: 10.0.22621.4169 (WinBuild.160101.0800)
WindowsSDK: 10.0.22621.0 (17.11.35102.94)
VisualStudio: VisualStudio/17.11.4+35312.102
SystemInformer: 3.1.24282.0 (37654a92) [master]
```

**Comment by jxy-s** [comment]
`WindowsSDK: 10.0.22621.0 (17.11.35102.94)` looks like you're using and older SDK -latest is `10.0.26100.1741`.

**Comment by JustinJayL** [comment]
After re-running build_init and build_init, this worked for me. 

Apologies, I thought I had the latest version of everything, however, the Visual Studio UI for installing components is a bit obtuse. Thanks!

**Comment by MagicAndre1981** [comment]
[Vs 2022 17.11.5 ](https://learn.microsoft.com/en-us/visualstudio/releases/2022/release-notes#version-17115)updates SDK to latest version:

> Updated the Windows 11 SDK (10.0.26100.0) installed by Visual Studio to the October 2024 servicing build.
