### ISSUE TITLE
Updating portable 3.1.24278 to 3.1.24283 not working

### ISSUE THREAD

**Issue by MagicAndre1981** [winsiderss/systeminformer#2234]
>  closing SI and reopening SI my correct settings are loaded from the xml.

but when I do this, I'm still at the old version 3.1.24278, because the updater installs into `C:\Program Files\SystemInformer\` but not my portable folder

_Originally posted by @MagicAndre1981 in https://github.com/winsiderss/systeminformer/issues/2138#issuecomment-2401899666_

**Comment by jxy-s** [comment]
> this is the first time this happens. normally the portable folder gets updated fine.
> 
> @jxy-s is this related to your installer / updater changes related to winget support? Do you no longer support updating portable installs?

Maybe, will investigate 👍

**Comment by jxy-s** [comment]
I know where the problem is and will have a fix for this in the next build 👍

**Comment by jxy-s** [comment]
fix here: https://github.com/winsiderss/systeminformer/commit/14c269bb70b7358bfebe42a511721c9fd31e53e9

**Comment by MagicAndre1981** [comment]
> fix here: [14c269b](https://github.com/winsiderss/systeminformer/commit/14c269bb70b7358bfebe42a511721c9fd31e53e9)

update of portable to 3.1.24290 worked fine
