### ISSUE TITLE
Can the mouse hover content view window be closed?

### ISSUE THREAD

**Issue by xxxdo1** [winsiderss/systeminformer#2235]
### Description of the feature, modification, idea or suggestion

Can the mouse hover content view window be closed?
The windows identified by the red boxes below.

![2024101110851353](https://github.com/user-attachments/assets/f1b52ae0-44c5-4227-8d51-7682efb67b68)

**Comment by dmex** [comment]
It's visible when you move the move over the Name column otherwise to disable completely change `EnableTooltipSupport` to 0

**Comment by xxxdo1** [comment]
@dmex  Thank you
