### ISSUE TITLE
Don't change Focus

### ISSUE THREAD

**Issue by Zeroes1** [winsiderss/systeminformer#2242]
### Brief description of your issue

Wish:
If Set option: [x] Start hidden -
don't change Focus from current window (where start SystemInformer.exe)

### Steps to reproduce (optional)

Real example problem:
I many time manually start/restart SystemInformer.exe from Far Manager
my SystemInformer.exe.settings.xml have option  [x] Start hidden
and after start program every time I lost focus from Far Manager window.

### Expected behavior (optional)

May be need add logic:

    main()
    Old_hwnd: HWND;
    Old_hwnd:= GetForegroundWindow();

    ...
    if option.hide == true
       {
        SetForegroundWindow(Old_hwnd);
       }

where "option.hide" it's:
ListView_GetCheckState(listViewHandle, PHP_OPTIONS_INDEX_START_HIDDEN) == BST_CHECKED
from options.c

### Environment (optional)

```shell
SI 3.1.24290.0
WIN32_NT 10.0.19045.3448 (22H2)
```

**Comment by dmex** [comment]
> May be need add logic:

SetForegroundWindow is always skipped for SW_HIDE (StartHidden)

https://github.com/winsiderss/systeminformer/blob/4a6573b066d4f4c015007cde78168ddc622705ef/SystemInformer/mainwnd.c#L406-L413

> I many time manually start/restart SystemInformer.exe from Far Manager

I just tested this and works fine so either Far Manager or another program is causing the issue 🤷‍♂️
