### ISSUE TITLE
HideOnClose - Not Wotking

### ISSUE THREAD

**Issue by vruzin** [winsiderss/systeminformer#2244]
### Brief description of your issue

It doesn't matter if I'm running under an administrator account or not. If I click on close the window, it doesn't minimize to the tray, but closes. The HideOnClose parameter is not set to 1. Or rather, it is set, but is restored back to 0 after closing the options window.

**Comment by Zeroes1** [comment]
what your version program, OS??????????

I check latest release systeminformer-3.0.7660-release-bin.zip
and latest canary systeminformer-3.1.24290-canary-bin.zip
under windows 10 - both work fine!

**Comment by dmex** [comment]
HideOnClose requires at least 1 tray icon enabled under the View menu > Tray Icons
