### ISSUE TITLE
Download PDBs instead of hardcoded addresses in driver?

### ISSUE THREAD

**Issue by Vasilich** [winsiderss/systeminformer#2249]
### Description of the feature, modification, idea or suggestion

Right now SI uses hardcoded offsets (?) for undocumented functions in kernel driver, and these offsets are calculated from published Symbols. 

### Proposed implementation details (optional)

This project https://github.com/valinet/ExplorerPatcher/wiki/Symbols downloads symbols on start (to calculate offsets for some system functions) if there are changes in relevant system files detected (e.g after Windows update). 
Maybe this mechanic can be used also in SystemInformer?

**Comment by jxy-s** [comment]
We already do this. We do not use hard coded offsets. We sign the dynamic data which we validate before shipping. The client provides this data to the driver. The checked in binary blob is used for known offsets that are built into the driver. But the driver supports out of band updates to the dynamic data, which we use regularly.
