### ISSUE TITLE
Systeminformer crashes when attempting to open file location  of WSL process.

### ISSUE THREAD

**Issue by kotenok2000** [winsiderss/systeminformer#2262]
### Brief description of your issue

When i right click boinc and press "Open frile location" it crashes.

### Steps to reproduce (optional)

Run ununtu on WSL1
Attempt to open bash executable location

### Expected behavior (optional)

Open E:\wsl\ubuntu\rootfs\home\user\BOINC\

### Actual behavior (optional)

![image](https://github.com/user-attachments/assets/3fde7355-bfb2-4268-abad-682d36086282)

### Environment (optional)

```shell
3.1.24305.0
10.0.22631.4317
```

**Comment by kotenok2000** [comment]
[SystemInformer_DumpFile_JHUPZSVDCHMQMQA.zip](https://github.com/user-attachments/files/17603377/SystemInformer_DumpFile_JHUPZSVDCHMQMQA.zip)

**Comment by ge0rdi** [comment]
It crashes because `processItem->FileNameWin32` is null (for some reason) and there is no check for that (`FileName` is checked instead):
https://github.com/winsiderss/systeminformer/blob/561370ad9dafe5b5fe74fc8171e950615db0e25c/SystemInformer/mainwnd.c#L1888-L1894

The fix of the crash would be trivial (just add proper check), but there is some deeper issue as SI was unable to obtain Win32 file name for the process image.

**Comment by kotenok2000** [comment]
It worked in the past.

**Comment by ge0rdi** [comment]
It seems that `General` tab of process properties resolves Win32 file name on its own and doesn't use the one from `processItem`.

But `processItem->FileNameWin32` seems to be populated when processes are enumerated:
https://github.com/winsiderss/systeminformer/blob/561370ad9dafe5b5fe74fc8171e950615db0e25c/SystemInformer/procprv.c#L1202-L1205

So it is weird why it was uninitialized in your case ...

**Comment by ge0rdi** [comment]
If you enable `File name` column (in main window), will it show proper name in case of those WSL processes?

**Comment by kotenok2000** [comment]
No.

**Comment by ge0rdi** [comment]
So it would seem that `PhGetProcessImageFileNameWin32` has some problem with resolving the file name.

`General` tab uses `PhGetFileName` as fallback (when `PhGetProcessImageFileNameWin32` failed) and it seems to work in this case.
Maybe we should do the same in `PhpFillProcessItem` when populating `ProcessItem->FileNameWin32`.
@dmex @jxy-s
