### ISSUE TITLE
Hovering over any CPU graph in System Information crashes with 0xC0000005

### ISSUE THREAD

**Issue by StanleyChristmas** [winsiderss/systeminformer#2265]
### Brief description of your issue

app crashes with 0xC0000005 (Invalid access to memory location.) whenever hovering over CPU graphs

![2024-11-02 Show one graph per CPU](https://github.com/user-attachments/assets/defb4912-48b2-4a5e-a79c-9201d77e2103)
![2024-11-02 ACCVIO at hovering over any graph](https://github.com/user-attachments/assets/d8f40404-0174-43fe-b8d2-16e494a4a4e4)

### Steps to reproduce (optional)

Steps to reproduce this app crash: 
> open System Informer
> open System Information
> enable "Show one graph per CPU"
> move mouse cursor into any of the graph boxes
> System Informer has crashed :( 0xC0000005 (Invalid access to memory location.)

### Expected behavior (optional)

app kindly not to crash :)

### Actual behavior (optional)

meeting black hole faster than lightspeed similar to disappearance of MH370 thoroughly analyzed by Ashton Forbes

### Environment (optional)

```shell
System Informer 3.1.24298.0 Release
Windows 11 Version 23H2 (OS Build 22631.4317)
```

**Comment by jxy-s** [comment]
@StanleyChristmas could you email me the dump file? johnny.shaw@live.com

**Comment by jxy-s** [comment]
This bug was introduced in the following commit inside of `PhIsCoreParked`: https://github.com/winsiderss/systeminformer/commit/ec374c3c42f0316702c541478f54a1fda5767181

The number of cores aligns with the `initialBufferSize` boundary of 4098... (128 * 32) = 4096. So we never add the necessary extra `RTL_SIZEOF_THROUGH_FIELD(SYSTEM_CPU_SET_INFORMATION, Size)` and the loop reads past the bounds of the buffer.

**Comment by jxy-s** [comment]
Fixed here: https://github.com/winsiderss/systeminformer/commit/84a0a3161d1afe11c4f8dd98ee27833eb63b68e4

Will be in next build 👍

**Comment by rpodric** [comment]
Does the mentioned fix cover a crash with the same code ( 0xC0000005 ) but achieved differently? I can make it happen by double-clicking a process in the tray icons (I have ones for both memory and CPU).
