### ISSUE TITLE
Tool:AndroidOS/ZkarletFlash trigger from system informer

### ISSUE THREAD

**Issue by ak33tah** [winsiderss/systeminformer#2267]
### Brief description of your issue

Getting warning from microsoft defender about "Tool:AndroidOS/ZkarletFlash"
<img width="196" alt="Capture" src="https://github.com/user-attachments/assets/4d832baa-1e3d-4a6d-9644-da243d39e5f6">

I've had system informer for months now and from my knowledge this is a completely legit copy I've downloaded from the official systeminformer sourceforge site.  But after running a microsoft defender scan i suddenly get this threat detection. Do you know what this is?  Is this a false positive?  And why is this triggering on the zip file itself and not the extracted executables lol? 

### Steps to reproduce (optional)

Run microsoft defender

### Environment (optional)

```shell
Windows 10 home
Systeminformer v3.0.7660
```

**Comment by ak33tah** [comment]
I want to add that I ran the .zip file on virus total and i got 13 warnings.  Is this version of the file just a bit full of false positives?  What's going on here?
![image](https://github.com/user-attachments/assets/0347934f-97ff-4462-8160-b75f6c93b96c)

**Comment by dmex** [comment]
> I want to add that I ran the .zip file on virus total and i got 13 warnings. Is this version of the file just a bit full of false positives? What's going on here?

@ak33tah 

The latest version is 3.1.24305 but your screenshot shows you're uploading 3.0.7680 from 2022? Those versions would pre-date signing of the nightly branch and +2500 other changes.

**Comment by dmex** [comment]
> Do you know what this is? Is this a false positive? And why is this triggering on the zip file itself and not the extracted executables lol?

Microsoft releasing Android signatures that flag Windows software as malicious but only zip files not the content of the zip like the executables or binaries makes no sense. 

You can submit the binary to Microsoft and ask them: https://www.microsoft.com/en-us/wdsi/filesubmission

Re-open this thread if they don't resolve the issue 👍

**Comment by ak33tah** [comment]
> > I want to add that I ran the .zip file on virus total and i got 13 warnings. Is this version of the file just a bit full of false positives? What's going on here?
> 
> @ak33tah
> 
> The latest version is 3.1.24305 but your screenshot shows you're uploading 3.0.7680 from 2022? Those versions would pre-date signing of the nightly branch and +2500 other changes.

Hmmm idk if we're looking at the same thing but according to the source forge page v3.0.7660 is released June 2024, not 2022.
![image](https://github.com/user-attachments/assets/e26c497d-1e54-41f5-b380-ef77b23db50a)

**Comment by ak33tah** [comment]
> > Do you know what this is? Is this a false positive? And why is this triggering on the zip file itself and not the extracted executables lol?
> 
> Microsoft releasing Android signatures that flag Windows software as malicious but only zip files not the content of the zip like the executables or binaries makes no sense.
> 
> You can submit the binary to Microsoft and ask them: https://www.microsoft.com/en-us/wdsi/filesubmission
> 
> Re-open this thread if they don't resolve the issue 👍

My only theory is that the contents inside v3.0.7660.zip file is triggering something from defender whereas the already extracted executables probably underwent changes from auto updates that no longer trigger defender.   I mean it's still weird bc that zip file never triggered anything from Microsoft defender until now.  I just want to check if its my specific pc issue or a microsoft defender as a whole issue.  When you run v v3.0.7660 do you get a "Tool:AndroidOS/ZkarletFlash trigger" as well?

**Comment by ak33tah** [comment]
Reopen

**Comment by jxy-s** [comment]
> > > Do you know what this is? Is this a false positive? And why is this triggering on the zip file itself and not the extracted executables lol?
> > 
> > 
> > Microsoft releasing Android signatures that flag Windows software as malicious but only zip files not the content of the zip like the executables or binaries makes no sense.
> > You can submit the binary to Microsoft and ask them: https://www.microsoft.com/en-us/wdsi/filesubmission
> > Re-open this thread if they don't resolve the issue 👍
> 
> @dmex My only theory is that the contents inside v3.0.7660.zip file is triggering something from defender whereas the already extracted executables probably underwent changes from auto updates that no longer trigger defender. I mean it's still weird bc that zip file never triggered anything from Microsoft defender until now. I just want to check if its my specific pc issue or a microsoft defender as a whole issue. When you run v3.0.7660.zip on defender do you get a "Tool:AndroidOS/ZkarletFlash trigger" as well?

> I mean it's still weird bc that zip file never triggered anything from Microsoft defender until now. I just want to check if its my specific pc issue or a microsoft defender as a whole issue.

@ak33tah Security products update their definitions/signatures all the time. Looks like a clear false positive to me. System Information has nothing to do with "AndroidOS" or "ZkarletFlash". Report it to Microsoft or ignore it. @dmex already provided you instructions.

**Comment by dmex** [comment]
Microsoft says there are no detections. 

![image](https://github.com/user-attachments/assets/205bd03f-0ff8-4954-a706-4e106d403db3)


> My only theory is that the contents inside v3.0.7660.zip file is triggering something from defender 

We haven't changed anything related to the setup since last year and our zip support hasn't changed in almost 10 years.... Google search shows that signature targeting something different every month so it's something that Microsoft does to cause the issue:

https://www.google.com/search?q=Tool:AndroidOS/ZkarletFlash
