### ISSUE TITLE
 Difference between Tray Icons "CPU Usage" and "CPU History"

### ISSUE THREAD

**Issue by poundonu** [winsiderss/systeminformer#2268]
Regarding Tray Icons, what is the difference between "CPU Usage" and "CPU History"?

**Comment by Vasilich** [comment]
Ever tried to compare?
All  * hostory entries ahow values dor laat aeveral swconds as graph ,  and * usage show only cirrent value as graph with flat form

**Comment by dmex** [comment]
"CPU Usage" fills the entire icon with a single value of the current utilization (progress style).
"CPU History" shows the last ~ 15 seconds of utilization using multiple values (graph style).
