### ISSUE TITLE
Integrate the unsupported PCMeter v0.4 service driver function into System Informer and co-work with 8GadgetPack gadgets.  

### ISSUE THREAD

**Issue by WilliamFulk** [winsiderss/systeminformer#2272]
Would you be open to integrate the unsupported "PCMeter v0.4" service function into System Informer and co-work with 8GadgetPack gadgets.  The latest Norton 360 upgrade has made it harder to start the PCMeter service driver that supports getting the CPU, GPU, Drives gadgets hardware temp and other usage info.
Thanks,
Dale

**Comment by dmex** [comment]
What's PCMeter?

**Comment by WilliamFulk** [comment]
Just found out that the "PCMeter" app and "All CPU Meter" gadget (by
addgadgets.com *No Longer Listed*) has been replaced by the "Core Temp" app
(by alcpu.com)  which supplies hardware device CPUID, Clock, CPU core
Temperature information for the replacing gadget "System Monitor II" (by
windows10gadgets.pro).
Issue #2272 should be closed/deleted.
Thanks
