### ISSUE TITLE
Unable to load kernel driver

### ISSUE THREAD

**Issue by Morrigan-Ship** [winsiderss/systeminformer#2277]
### Brief description of your issue

![image](https://github.com/user-attachments/assets/a219db1c-2558-4a12-908f-ef66eef3c5fc)

[Window Title]
System Informer

[Main Instruction]
Unable to load kernel driver

[Content]
The kernel driver is not yet supported on this kernel version. Request support by submitting a GitHub issue with the Windows Kernel version.

Windows 10.0.27744
Windows Kernel 10.0.27744.1000
System Informer 3.1.24305.0 Canary

Windows Insider

**Comment by jxy-s** [comment]
Duplicate: https://github.com/winsiderss/systeminformer/issues/1823

@Morrigan-Ship your version was added recently, I will do a build this weekend to support it 👍
