### ISSUE TITLE
Unable to load kernel windows 11 23H2 10.0.22631 kernel 10.0.22621.4455

### ISSUE THREAD

**Issue by davitof** [winsiderss/systeminformer#2279]
### Description of the feature, modification, idea or suggestion

Since this morning's windows update, System Informer is unable to load the kernel driver.

**Comment by davitof** [comment]
I forgot to mention my version of System Informer:
3.1.24315.0 Canary

**Comment by Rdxcj** [comment]
you updated windows right ?

**Comment by davitof** [comment]
Yes, this morning.

**Comment by davitof** [comment]
I was expecting this, so I installed the latest Canary. But latest was not enough :-)

**Comment by jxy-s** [comment]
Duplicate: https://github.com/winsiderss/systeminformer/issues/1823

I'm generating and testing now. Will have a new build available soon.

**Comment by davitof** [comment]
Wow, that's fast !

**Comment by jxy-s** [comment]
`3.1.24318.0` - `Help > Check for updates > Canary > Check` - 👍

**Comment by davitof** [comment]
It was night here, I was sleeping :-) I just did the upgrade and all is fine now.

Just a question for the next Windows update: is it useful that I report it here, or should I just wait for someone to create a new version because it will necessarily happen? I am in no hurry to have an updated version, and I don't want to stress you devs unnecessarily.

**Comment by jxy-s** [comment]
Kernel support is usually picked up within 24-48 hours. Sometimes it can take a week (rarely these days). We do 1-2 builds a week. I tend to do a build Wednesdays (day after patch Tuesday). So no need to open an issue unless it's been a while. Very rarely Microsoft neglects to provide necessary information for our automation and it takes some extra effort and manual intervention.
