### ISSUE TITLE
Skip confirmation dialog option on advanced settings for Start/Stop/Restart a service

### ISSUE THREAD

**Issue by thecocce** [winsiderss/systeminformer#2292]
### Description of the feature, modification, idea or suggestion

Hi, I always use SI to perform a start/stop service execution during development and debug.

I use the start/end service function very often and I find confirmation dialog very annoying.

Is there be the possibility to put it on advanced settings?

**Comment by dmex** [comment]
You mean the `Enable warnings` checkbox on the General settings page?

![image](https://github.com/user-attachments/assets/6f285523-ac59-44b1-860d-1ae5e9b41cc7)

**Comment by thecocce** [comment]
I need to skip this dialog on start/stop/restart services

![immagine](https://github.com/user-attachments/assets/e90cd3d0-1631-42f6-b4b5-cb94efea6aa2)
