### ISSUE TITLE
Clicking on Default token when System Informer is running as SYSTEM crashes the application with error  0xC0000005 (Invalid access to memory location.)

### ISSUE THREAD

**Issue by amithegde** [winsiderss/systeminformer#2299]
### Brief description of your issue

If I try to view Default Token for a process when SystemInformer is running as System, it displays crash message:

[Window Title]
System Informer

[Main Instruction]
System Informer has crashed :(

[Content]
0xC0000005 (Invalid access to memory location.)

[Full] [Normal] [Minimal] [Restart] [Ignore] [Exit]

### Steps to reproduce (optional)

+ Open a cmd.exe as `SYSTEM` using `psexec` using command `psexec -i -s cmd`
+ Open System Informer from the cmd.exe executing as System
+ Pick a process, right click > Properties > Token, click `Default token` button at the right bottom

### Expected behavior (optional)

It should display the default token

### Actual behavior (optional)

it is crashing the application

### Environment (optional)

```shell
System Informer Version: 3.1.243224.0 Canary
Windows Version:24H2 Build 26100.2314
```

**Comment by amithegde** [comment]
Just noticed it works fine some times

**Comment by jxy-s** [comment]
I'm having trouble reproducing this myself. Could you attach here or email me the dump file?
