### ISSUE TITLE
New memory strings dialog hangs and drain all system memory if opens for System Informer itself

### ISSUE THREAD

**Issue by DartVanya** [winsiderss/systeminformer#2302]
### Brief description of your issue

1. Enable new memory strings dialog.
2. Open System Informer process properties (NtCurrentProcess).
3. Go to Memory tab.
4. Open Options - Strings.

### Steps to reproduce (optional)

![image](https://github.com/user-attachments/assets/1a33cd01-5f27-445d-bd0a-f3f45d531d9e)

**Comment by jxy-s** [comment]
Fixed here: https://github.com/winsiderss/systeminformer/commit/0e9066352e1912df21dee5d0e7a95b2311ccfaed
