### ISSUE TITLE
Once more dont't builded

### ISSUE THREAD

**Issue by Avtukhoff** [winsiderss/systeminformer#2305]
### Brief description of your issue

Перестроение начато в 11:54...
1>------ Перестроение всех файлов начато: проект: kphlib, Конфигурация: Release x64 ------
1>Building dynamic data...
1>Dynamic header -> I:\systeminformer-master\kphlib\include\kphdyn.h
1>Dynamic source -> I:\systeminformer-master\kphlib\kphdyn.c
1>Dynamic config -> I:\systeminformer-master\bin\Release64\ksidyn.bin
1>kphdyndata.c
1>kphmsg.c
1>kphmsgdyn.c
1>kphdyn.c
1>kphlib_um.vcxproj -> I:\systeminformer-master\kphlib\bin\Release64\kphlib_um.lib
2>------ Перестроение всех файлов начато: проект: phlib, Конфигурация: Release x64 ------
2>apiimport.c
2>appresolver.c
2>appruntime.c
2>avltree.c
2>basesup.c
2>circbuf.c
2>colorbox.c
2>cpysave.c
2>data.c
2>dspick.c
2>emenu.c
2>I:\systeminformer-master\phlib\cpysave.c(480,13): warning C4013: IListView_GetColumn: нет определения; предполагается "extern" с возвратом типа "int"
2>error.c
2>I:\systeminformer-master\phlib\cpysave.c(570,13): warning C4013: IListView_GetItem: нет определения; предполагается "extern" с возвратом типа "int"
2>I:\systeminformer-master\phlib\cpysave.c(632,13): warning C4013: PhFindIListViewItemByFlags: нет определения; предполагается "extern" с возвратом типа "int"
2>I:\systeminformer-master\phlib\cpysave.c(740,5): warning C4013: IListView_GetItemCount: нет определения; предполагается "extern" с возвратом типа "int"
2>I:\systeminformer-master\phlib\cpysave.c(746,14): warning C4013: IListView_GetItemState: нет определения; предполагается "extern" с возвратом типа "int"
2>extlv.c
2>fastlock.c
2>filepool.c
2>format.c
2>I:\systeminformer-master\phlib\emenu.c(22,7): error C2065: PH_EMENU_RIGHTORDER: необъявленный идентификатор
2>I:\systeminformer-master\phlib\emenu.c(17,30): error C2099: инициализатор не является константой
2>I:\systeminformer-master\phlib\emenu.c(636,13): error C2065: PH_EMENU_RIGHTORDER: необъявленный идентификатор
2>global.c
2>graph.c
2>guisup.c
2>handle.c
2>hexedit.c
2>hndlinfo.c
2>http.c
2>I:\systeminformer-master\phlib\global.c(109,30): error C2039: "MaximumTimerResolution": не является членом "_PH_SYSTEM_BASIC_INFORMATION".
2>    I:\systeminformer-master\phlib\include\phconfig.h(90,16):
2>     см. объявление "_PH_SYSTEM_BASIC_INFORMATION"
2>I:\systeminformer-master\phlib\global.c(124,30): error C2039: "MaximumTimerResolution": не является членом "_PH_SYSTEM_BASIC_INFORMATION".
2>    I:\systeminformer-master\phlib\include\phconfig.h(90,16):
2>     см. объявление "_PH_SYSTEM_BASIC_INFORMATION"
2>hvsocketcontrol.c
2>icotobmp.c
2>filestream.c
2>imgcoherency.c
2>mapldr.c
2>json.c
2>kph.c
2>kphcomms.c
2>lsasup.c
2>mapexlf.c
2>mapimg.c
2>maplib.c
2>native.c
2>nativeflt.c
2>nativepipe.c
2>nativemodule.c
2>nativethread.c
2>ntuser.c
2>provider.c
2>queuedlock.c
2>ref.c
2>searchbox.c
2>secdata.c
2>secedit.c
2>secwmi.c
2>settings.c
2>strsrch.c
2>theme.c
2>util.c
2>svcsup.c
2>symprv.c
2>sync.c
2>treenew.c
2>verify.c
2>workqueue.c
2>wslsup.c
2>Сборка проекта "phlib.vcxproj" завершена с ошибкой.
3>------ Перестроение всех файлов начато: проект: peview, Конфигурация: Release x64 ------
4>------ Перестроение всех файлов начато: проект: SystemInformer, Конфигурация: Release x64 ------
3>cfgprp.c
3>chcol.c
3>delayhook.c
3>mappings.c
3>pechpeprp.c
3>clrprp.c
3>clrtableimportprp.c
3>clrprptables.c
3>colmgr.c
3>attributes.c
3>debugprp.c
3>ehcontprp.c
3>exlfdynamic.c
3>exlfexports.c
3>exlfimports.c
3>exlfprp.c
4>about.c
4>actions.c
4>admintask.c
4>affinity.c
4>anawait.c
4>appsup.c
4>chcol.c
4>chdlg.c
3>hashprp.c
3>layout.c
3>pedynrelocprp.c
3>peheaderprp.c
3>pemuiprp.c
3>peprpwnd.c
3>options.c
4>chproc.c
4>colmgr.c
3>peexceptprp.c
4>colsetmgr.c
4>dbgcon.c
4>delayhook.c
4>I:\systeminformer-master\SystemInformer\actions.c(2283,9): error C2065: result: необъявленный идентификатор
4>I:\systeminformer-master\SystemInformer\actions.c(2294,9): error C2065: result: необъявленный идентификатор
4>I:\systeminformer-master\SystemInformer\actions.c(2297,10): error C2065: result: необъявленный идентификатор
4>delayload.c
4>devprv.c
3>perelocprp.c
4>extmgr.c
4>findobj.c
4>gdihndl.c
3>pesectionprp.c
3>pepogoprp.c
3>richprp.c
3>secprp.c
4>heapinfo.c
3>ldprp.c
4>hidnproc.c
4>hndllist.c
3>expprp.c
3>impprp.c
4>hndlmenu.c
4>hndlprp.c
4>hndlprv.c
4>hndlstat.c
4>infodlg.c
4>itemtips.c
3>libprp.c
3>links.c
3>main.c
3>misc.c
3>pdb.c
3>pdbprp.c
4>jobprp.c
4>kdump.c
3>pedirprp.c
4>ksidbg.c
4>informer.c
4>memmod.c
4>ksisup.c
3>peprp.c
3>previewprp.c
4>ksyscall.c
4>log.c
3>processes.c
3>propstore.c
4>logwnd.c
3>prpsh.c
4>main.c
3>resprp.c
3>searchbox.c
4>mainwnd.c
3>settings.c
4>mdump.c
4>memedit.c
4>memlist.c
3>streams.c
3>strings.c
4>memlists.c
3>tlsprp.c
4>memprot.c
3>versioninfoprp.c
4>memprv.c
3>volatileprp.c
4>memrslt.c
4>memsrch.c
4>memsrcht.c
4>I:\systeminformer-master\SystemInformer\mainwnd.c(644,36): error C2197: void PhInitializeFont(HWND): слишком много аргументов для вызова
4>I:\systeminformer-master\SystemInformer\mainwnd.c(648,49): error C2197: void PhInitializeMonospaceFont(HWND): слишком много аргументов для вызова
4>I:\systeminformer-master\SystemInformer\mainwnd.c(2401,51): error C2197: void PhGuiSupportUpdateSystemMetrics(HWND): слишком много аргументов для вызова
4>miniinfo.c
4>modlist.c
4>I:\systeminformer-master\SystemInformer\mainwnd.c(4318,41): error C2197: void PhInitializeMonospaceFont(HWND): слишком много аргументов для вызова
4>modprv.c
4>mtgndlg.c
4>mwpgdev.c
4>mwpgnet.c
4>mwpgproc.c
4>mwpgsrv.c
4>netlist.c
4>netprv.c
4>notifico.c
4>ntobjprp.c
4>options.c
4>pagfiles.c
4>clapi.c
4>svcapi.c
4>svcapiport.c
4>svcclient.c
4>svcmain.c
4>plugin.c
4>plugman.c
4>procgrp.c
4>procmtgn.c
4>procprp.c
3>clrtableimports.cpp
4>procprv.c
4>procrec.c
4>proctree.c
4>prpgenv.c
4>prpggen.c
4>prpghndl.c
4>prpgjob.c
4>prpgmem.c
4>I:\systeminformer-master\SystemInformer\procprv.c(1191,18): error C2039: "IsSecureSystem": не является членом "_PH_PROCESS_ITEM".
4>    I:\systeminformer-master\SystemInformer\include\procprv.h(140,16):
4>     см. объявление "_PH_PROCESS_ITEM"
4>I:\systeminformer-master\SystemInformer\procprv.c(1268,31): error C2039: "IsSecureSystem": не является членом "_PH_PROCESS_ITEM".
4>    I:\systeminformer-master\SystemInformer\include\procprv.h(140,16):
4>     см. объявление "_PH_PROCESS_ITEM"
4>prpgmod.c
4>prpgvdm.c
4>prpgperf.c
4>prpgsrv.c
4>prpgstat.c
4>prpgthrd.c
4>prpgtok.c
4>prpgwmi.c
4>runas.c
4>searchbox.c
4>sessprp.c
4>sessshad.c
4>settings.c
4>srvcr.c
4>srvctl.c
4>srvlist.c
4>srvprp.c
4>srvprv.c
4>sessmsg.c
4>sysinfo.c
4>syssccpu.c
4>sysscio.c
4>sysscmem.c
4>thrdlist.c
4>thrdprv.c
4>thrdstk.c
4>I:\systeminformer-master\SystemInformer\srvprv.c(130,36): error C2061: синтаксическая ошибка: идентификатор "NotifyServiceStatusChange_I"
4>thrdstks.c
4>tokprp.c
4>I:\systeminformer-master\SystemInformer\srvprv.c(130,36): error C2059: синтаксическая ошибка: ;
4>I:\systeminformer-master\SystemInformer\srvprv.c(130,64): error C2513:  : нет переменных, объявленных перед "="
4>I:\systeminformer-master\SystemInformer\srvprv.c(131,45): error C2061: синтаксическая ошибка: идентификатор "SubscribeServiceChangeNotifications_I"
4>I:\systeminformer-master\SystemInformer\srvprv.c(131,45): error C2059: синтаксическая ошибка: ;
4>I:\systeminformer-master\SystemInformer\srvprv.c(131,83): error C2513:  : нет переменных, объявленных перед "="
4>I:\systeminformer-master\SystemInformer\srvprv.c(132,47): error C2061: синтаксическая ошибка: идентификатор "UnsubscribeServiceChangeNotifications_I"
4>I:\systeminformer-master\SystemInformer\srvprv.c(132,47): error C2059: синтаксическая ошибка: ;
4>I:\systeminformer-master\SystemInformer\srvprv.c(132,87): error C2513:  : нет переменных, объявленных перед "="
4>I:\systeminformer-master\SystemInformer\srvprv.c(1204,30): warning C4013: NotifyServiceStatusChange_I: нет определения; предполагается "extern" с возвратом типа "int"
4>I:\systeminformer-master\SystemInformer\srvprv.c(1329,10): error C2065: SubscribeServiceChangeNotifications_I: необъявленный идентификатор
4>I:\systeminformer-master\SystemInformer\srvprv.c(1341,13): warning C4013: SubscribeServiceChangeNotifications_I: нет определения; предполагается "extern" с возвратом типа "int"
4>I:\systeminformer-master\SystemInformer\srvprv.c(1384,10): error C2065: UnsubscribeServiceChangeNotifications_I: необъявленный идентификатор
4>I:\systeminformer-master\SystemInformer\srvprv.c(1389,9): warning C4013: UnsubscribeServiceChangeNotifications_I: нет определения; предполагается "extern" с возвратом типа "int"
4>I:\systeminformer-master\SystemInformer\srvprv.c(1430,13): error C2106: =: левый операнд должен быть левосторонним значением
4>I:\systeminformer-master\SystemInformer\srvprv.c(1431,13): error C2106: =: левый операнд должен быть левосторонним значением
4>I:\systeminformer-master\SystemInformer\srvprv.c(1435,13): error C2106: =: левый операнд должен быть левосторонним значением
3>LINK : fatal error LNK1181: не удается открыть входной файл "phlib.lib"
3>Сборка проекта "peview.vcxproj" завершена с ошибкой.
4>Сборка проекта "SystemInformer.vcxproj" завершена с ошибкой.
========== Перестроить все: успешно — 1, неудачно — 3, пропущено — 0 ==========
========== Перестроить завершено в 11:55 и заняло 01:00.118 мин ==========

++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
+++                 Please consider donating to VSColorOutput                    +++
+++                       https://mike-ward.net/donate/                          +++
+++            (this message can be turned off in the settings panel)            +++
++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++

**Comment by dmex** [comment]
Use a revision
