### ISSUE TITLE
Unable to load kernel driver when escalating to admin privileges

### ISSUE THREAD

**Issue by FelixIsaac** [winsiderss/systeminformer#2306]
### Brief description of your issue

Trying to escalate the System Informer process on my Windows 11 system by right-clicking on taskbar icon, it does not give the option to "Run as administrator". So, I decided to click on the "Administrator" icon located at the top right of System Informer like so:

![image](https://github.com/user-attachments/assets/7e2a6b52-3b60-4d9d-85d4-008d9989e230)

After clicking "yes" on the UAC dialogue, it gives the following error
![image](https://github.com/user-attachments/assets/44f5c0ca-ad3a-4ad8-a12a-f8fd29bd2caa)

Error: Unable to load kernel driver
Message: The kernel driver is not yet supported on this kernel version. Request support by submitting a GitHub issue with the Windows Kernel version.

Windows version: **Windows 11 23H210.02631**
Kernel version: **Windows Kernel 10.02621.4455**
System Informer version: **3.124298.0 Release 00-8664-d17ee503-01047000**

### Steps to reproduce (optional)

1. Open System Informer
2. Escalate to running the process as administrator

### Expected behavior (optional)

Should open System Informer with administrator privileges.

### Actual behavior (optional)

Gives error dialogue shown above.

### Environment (optional)

```shell
System Informer version: **3.124298.0 Release 00-8664-d17ee503-01047000**
Windows version: **Windows 11 23H210.02631**
Kernel version: **Windows Kernel 10.02621.4455**
```

**Comment by jxy-s** [comment]
Duplicate: https://github.com/winsiderss/systeminformer/issues/1823

For the latest kernels support, switch to the canary channel, `Help > Check for updates > Canary > Check`
