### ISSUE TITLE
Where is Virus Total score?

### ISSUE THREAD

**Issue by the-insulter** [winsiderss/systeminformer#2311]
Hi,

did you deactivated it?

No choice in Options?
You could have also deleted the column, if the option is not available.

Would help to know.

Regards

**Comment by the-insulter** [comment]
Ah,
sending by clicking only works with:
https://virusscan.jotti.org/en-US/filescanjob/t41gsjch0d

Please then add a Joti-column.

Regards

**Comment by dmex** [comment]
#936
