### ISSUE TITLE
System infromer canary doesn't work through anydesk or teamviewer

### ISSUE THREAD

**Issue by xtikoo** [winsiderss/systeminformer#2320]
System infromer canary doesn't work through anydesk or teamviewer obv used for pc checking purposes , it crashes and closes a second or 2 after opening .

any fix or workaround ???

**Comment by dmex** [comment]
I couldn't find any issues with Teamviewer or Anydesk?

<img width="1103" alt="image" src="https://github.com/user-attachments/assets/6acf1a8f-2f17-4f9f-acec-a304f72ae7be">

> any fix or workaround ???

You would have to enable WER dumps and upload the file to OneDrive or somewhere and send the link, or email as an attachment to the email on my profile.

1) Save as .reg and import:
```
Windows Registry Editor Version 5.00

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps]

[HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\Windows Error Reporting\LocalDumps\SystemInformer.exe]
"DumpFolder"="%APPDATA%\SystemInformer\CrashDumps"
"DumpCount"=dword:00000010
"DumpType"=dword:00000002
```
2) Attach dump `%APPDATA%\SystemInformer\CrashDumps`

**Comment by dmex** [comment]
Re-open when more information can be provided 👍
