### ISSUE TITLE
self issued key pair & .sig files clarification

### ISSUE THREAD

**Issue by inoperable** [winsiderss/systeminformer#2325]
Hello everyone!

first: project builds is the most pleasant experience i worked with on msvc/msbuild stack. it just works! (which is not 97 times of 100 with other .sln projects i had to work with) - compared to, say windows terminal, this, well, dont take it wrong but it feels like archlinux typing makepkg 👍 - it works 

Im just confused about where to put the generated key bytes inside the verify.c array exactly:
replace the first, or both, or append a new one? (what name should i thave) 
this is probably not a question one versed in vs would have - but im not. 
Some guidance would be appreciated. Thank you in advance!

**Comment by jxy-s** [comment]
Add it to the array in `verify.c`. You do not need to replace them, you can just add it to the array of keys :
https://github.com/winsiderss/systeminformer/blob/a6aea48ff12cfa93ab0bc3476066742e48ef7c50/KSystemInformer/verify.c#L42

`KphKeyTypeProd` keys are enabled always.

`KphKeyTypeTest` are only permitted when test signing is enabled, see `KphTestSigningEnabled`.

**Comment by inoperable** [comment]
Thank you for clarifying this, maybe consider amending the .md with the info as well, might help some other confusion victims :)

**Comment by jxy-s** [comment]
It's already there?:
https://github.com/winsiderss/systeminformer/blob/39f77ed2553b147860b627215c7e02b92afe05da/KSystemInformer/README.md?plain=1#L40-L48

**Comment by inoperable** [comment]
I know, i read it, but I didn't understood, so its should be like this
![image](https://github.com/user-attachments/assets/9aa3c31d-51a7-47c1-a250-c0d788af85af)
and not like this
![image](https://github.com/user-attachments/assets/8fad5a58-1e4f-44a1-8f72-61cdc6e85cd0)

**Comment by inoperable** [comment]
btw. this looks sooo good i just like to watch those graphs :>
![image](https://github.com/user-attachments/assets/706e1796-70cf-4aa2-9a94-e6f1122048d3)

**Comment by inoperable** [comment]
after installing from setup.exe (and/or) .zip, i get this message (never seen this form before),
- .sig files are present for all files (plungins, peview and systemifnormer)
- bcd is configured with testsigning, flightsigning and nointegritychecks
- see my verify.c attached, if you could take a look that would be much appriciated, probably im getting not enough sleep lately and major msbuild anger management issues
[verify.txt](https://github.com/user-attachments/files/18075000/verify.txt)

**Comment by jxy-s** [comment]
That is an odd error. What's in the driver service key?
