### ISSUE TITLE
Inject DLL

### ISSUE THREAD

**Issue by Villiance** [winsiderss/systeminformer#2327]
Where placed button "inject DLL"?
<img width="548" alt="111" src="https://github.com/user-attachments/assets/ebe10109-79a6-4c62-898f-7ae3db31fa46">

**Comment by dmex** [comment]
The menu was moved to the modules tab.

These days you don't need programs to inject and can use the command prompt: https://gist.github.com/dmex/8880b31a0c9bba5c211c020506b90be1

**Comment by Insolvenzberater** [comment]
but where is the modules tab?
