### ISSUE TITLE
Incorrect Address Calculation

### ISSUE THREAD

**Issue by secnam** [winsiderss/systeminformer#2328]
### Brief description of your issue

Good day, 

Would like to raise an error related to searching for strings. 

The image below shows the Address being wrong, the offset side (last part as correct).

![Screenshot_2024-12-11_at_08 13 12](https://github.com/user-attachments/assets/331cd073-f952-4ade-aa8a-9e035ef6cd70)

The image below shows an error when double clicking.

![Screenshot_2024-12-11_at_08 26 14](https://github.com/user-attachments/assets/5d58da6f-1a39-475d-9c45-2ce4d129ca5a)

### Steps to reproduce (optional)

Double click process --> Memory --> Strings... --> Search string --> Output (check the Address and Base Address)

### Expected behavior (optional)

If the correct address and location showing, should take you to that location in memory upon double click.

### Actual behavior (optional)

An error is occurring unfortunately.

**Comment by ge0rdi** [comment]
This is fixed in latest Canary build already.
`Help` -> `Check for updates` -> `Canary`

See #2280.
