### ISSUE TITLE
win7 crashed with no import found

### ISSUE THREAD

**Issue by henrypp** [winsiderss/systeminformer#2337]
### Brief description of your issue

just run:
![Безымянный](https://github.com/user-attachments/assets/78398560-acf7-4b47-8465-8833d8a8b4cf)

code search did not find any of func. call:
![sshot-001](https://github.com/user-attachments/assets/b4a9eb79-2f63-4994-aadd-50cdb42c966d)

### Environment (optional)

```shell
si: with latest commit
win7 7600 with latest updates
```

**Comment by MagicAndre1981** [comment]
> ### Environment (optional)
> ```shell
> si: with latest commit
> win7 7600 with latest updates
> ```

7600 is Windows 7 RTM without Sp1. SI runs on Windows 7 Sp1 for me, I only get a warning that the driver is not supported:

![_win7_sp1_SI_01](https://github.com/user-attachments/assets/8d2233c1-1ef4-477c-801c-7af2bacf1e62)

and **LdrSystemDllInitBlock** is found in ntdll.dll:

![image](https://github.com/user-attachments/assets/d72f29ea-b9f8-478d-bebd-adbe04534f8e)

**Comment by MagicAndre1981** [comment]
as said, your Windows is not fully patched. Your file has Timestamp from 2010, so update your Windows 7 and try again. LdrSystemDllInitBlock was added in Windows 8 or 8.1 in 2012/2013 and later backported. So your old filke from 2010 is missing this.

**Comment by henrypp** [comment]
@MagicAndre1981

yes, i am stupid, i use not updated win7, but i install [all win7 updates](https://blog.simplix.info/update7/) and then error gone!

i am just not using win7, and think all people have this problem!
