### ISSUE TITLE
 Unable to load kernel driver

### ISSUE THREAD

**Issue by ccsimplyspolit** [winsiderss/systeminformer#2338]
[Window Title]
System Informer

[Main Instruction]
Unable to load kernel driver

[Content]
The kernel driver is not yet supported on this kernel version. Request support by submitting a GitHub issue with the Windows Kernel version.

Windows 10 22H2 10.0.19045
Windows Kernel 10.0.19041.5247
System Informer 3.1.24333.0 Canary

00-8664-1aa75f33-01046000

[ ] Don't show this message again  [ОК]

**Comment by dmex** [comment]
Duplicate of #1823
