### ISSUE TITLE
SearchApp.exe cannot be resumed from a suspended state

### ISSUE THREAD

**Issue by romanholidaypancakes** [winsiderss/systeminformer#2339]
### Brief description of your issue

I tried to resume SearchHost.exe using Resume but it failed.

![image](https://github.com/user-attachments/assets/f7704127-1878-4828-9f41-f8c7019c950f)

It seems that the built-in applications of Windows cannot be forced to resume operation unless I switch to the corresponding program page

**Comment by diversenok** [comment]
It's a UWP application that is frozen by the Process Lifetime Manager. Unfreezing it requires asking PLM to do so. You can achieve that via checking `Miscellaneous -> Execution required` on the specified process.
