### ISSUE TITLE
crashing if some process started (maybe)

### ISSUE THREAD

**Issue by henrypp** [winsiderss/systeminformer#2348]
### Brief description of your issue

just crash, idk reasons

dump:
[SystemInformer_DumpFile_WOUHCBAGTXYDOWT.dmp](https://github.com/user-attachments/files/18267049/SystemInformer_DumpFile_WOUHCBAGTXYDOWT.dmp)

### Environment (optional)

```shell
latest commit, compiled

v3.1.24363 and week before
```

**Comment by dmex** [comment]
No symbols for a stack trace.
