### ISSUE TITLE
 Feature Request: Calculate "Private bytes" of all selected process

### ISSUE THREAD

**Issue by GitUser200607** [winsiderss/systeminformer#243]
![ph3-selectedprocessestotalmemory](https://user-images.githubusercontent.com/17235450/36533136-be4453f2-17d3-11e8-9c0b-e3b85dbdabbd.png)
I have selected 10 processes of Firefox, but there is no way to display CALCULATED total size of memory, used by all Firefox processes. The parent Firefox.exe only displays its own private bytes usage. But it has 9 child processes and they using memory.
Can you please add a feature to display in Status bar calculated total memory usage of SELECTED processes?
For example, I select CMD.EXE, Firefox.EXE, Calc.EXE and in status bar shows calculated sum of Private bytes.
I have tested it in PH3.0.1335 and there is still no such feature.
Thank you!

**Comment by dmex** [comment]
>  there is no way to display CALCULATED total size of memory

If you enable the "Include usage of collapsed processes" option in the settings window then it'll show the total size of memory for Firefox (when the node is collapsed).

> please add a feature to display in Status bar calculated total memory usage of SELECTED processes

Does "Memory of selected items" sound like the correct name for this statusbar column?

**Comment by UnityUser** [comment]
>If you enable the "Include usage of collapsed processes" option in the settings window then it'll show >the total size of memory for Firefox (when the parent node is collapsed).
Thank you!

> Does "Memory of selected items" sound like the correct name for this statusbar column?
Yes, or do you mean, that it is there already?

**Comment by redactedscribe** [comment]
I'd like to see this become a feature too. Keep finding myself wanting to know the memory usage of several processes.

There could also be a "Memory of filtered items", though the "Memory of selected items" would be more useful until the search bar supports wildcards/regex (maybe one day?).

The name could be "Selected processes:" and then have it be configurable via the options what shows after that.
```
<default status bar values> | Selected processes: CPU usage: 39.81%, Physical memory: 9.62 GB (60.48%), ...
```

When no selection, the "Selected ..." text could be hidden.

Thanks!

**Comment by dmex** [comment]
Added with the next nightly build 👍

**Comment by GitUser200607** [comment]
Cant find how to activate it. Nothing like "Selected Private Bytes" option. Maybe it will be after 3.0.5578?

**Comment by dmex** [comment]
@GitUser200607 

3.0.5706 nightly was just updated with the changes

**Comment by redactedscribe** [comment]
> Cant find how to activate it. Nothing like "Selected Private Bytes" option. Maybe it will be after 3.0.5578?

@GitUser200607 Right-click > Customize... on the Status Bar then add the relevant Status Bar entries.
