### ISSUE TITLE
Feature Request: Make filter more usable

### ISSUE THREAD

**Issue by NN---** [winsiderss/systeminformer#506]
If filter could filter out processes with dlls or have negative search it would be awesome.

**Comment by dmex** [comment]
> filter out processes with dlls

Every process has a DLL except system? 

> negative search

Adding a NOT operator with ! or another character could work. The filtering callbacks need to be rewritten for this to work though.

**Comment by NN---** [comment]
I mean with particular dlls.

**Comment by dmex** [comment]
Merging with issue #1231 👍
