### ISSUE TITLE
Remove unnecessary Check for updates window state

### ISSUE THREAD

**Issue by gemal** [winsiderss/systeminformer#548]
After I go to: `Help -> Check for updates` I'm presented with this window
![image](https://user-images.githubusercontent.com/69105/73539629-22b9ae80-442e-11ea-9cf5-3c39d6fffe55.png)

I think the window should just start the checking right way instead of me having to press another button for doing what I just thought that the dialog would do "checking for updates"

So I think that after you click on `Help -> Check for updates` the following dialog should be shown:
![image](https://user-images.githubusercontent.com/69105/73539748-6f04ee80-442e-11ea-90dd-fa6e060ef147.png)

**Comment by dmex** [comment]
I've tried to implement this previously but for some reason the TaskDialogIndirect API messages from the separate updater thread are blocking the main window thread from redrawing.

**Comment by dmex** [comment]
Next nightly build includes an option to start checking automatically 👍 

![image](https://user-images.githubusercontent.com/1306177/209905846-7f8a5fd3-6566-4b32-bbd6-def984106b5a.png)
