### ISSUE TITLE
a title for graphic tips

### ISSUE THREAD

**Issue by myshzzx** [winsiderss/systeminformer#552]
I think it's better to add a title to the graphic tips, or I can't tell what the graphic is about...

![image](https://user-images.githubusercontent.com/2025090/73858995-49d01000-4874-11ea-9388-354040b94c6b.png)

like this 

![image](https://user-images.githubusercontent.com/2025090/73859429-fca06e00-4874-11ea-8e06-cc73a6fed7f2.png)

**Comment by dmex** [comment]
Most generally have single letter titles or otherwise don't include a title because of the extra memory usage/string concentration/formatting 👍
