### ISSUE TITLE
Add winget support

### ISSUE THREAD

**Issue by dmex** [winsiderss/systeminformer#620]
Add support for the Windows Package Manager included with Windows 10.

`winget install processhacker`

PR pending:
` https://github.com/microsoft/winget-pkgs/pull/373`

**Comment by Biswa96** [comment]
Process Hacker 2.39? So old.

**Comment by dmex** [comment]
@Biswa96 

The nightly isn't stable yet and winget requires signed binaries

**Comment by dmex** [comment]
https://github.com/microsoft/winget-pkgs/pull/373
