### ISSUE TITLE
Update status. Wrong measurement. kB instead of mB

### ISSUE THREAD

**Issue by falcon4fun** [winsiderss/systeminformer#707]
Latest versions have units visual bug. Program always shows wrong units. Should be mB actually instead of kB :) 
https://i.imgur.com/R5zZ1wz.png
I suppose the speed is incorrect too in this window. :) Or my fiber channel got a [modem speed upgrade](https://youtu.be/QDS4B0mM-ew) :D 

Exist in: 3.0.3477 (96f20096)

**Comment by dmex** [comment]
> Latest versions have units visual bug

The build tools capture the filesize before uploading the binaries to the build server. The latest netcore seems to have changed the ().Length returned and later when the updater checks for updates the description includes the incorrect size / 1024

> I suppose the speed is incorrect too in this window

Yep. The calculation requires correct length to determine the bits per second.

**Comment by dmex** [comment]
Fixed 👍
