### ISSUE TITLE
Interfaces of \Device\ConDrv device objects are not shown

### ISSUE THREAD

**Issue by Biswa96** [winsiderss/systeminformer#739]
* Latest Process Hacker version. Running as asmin.
* Open a simple cmd.exe process.
* In ProcessHacker, Double click on it. Go to Handles tab. Only \Device\ConDrv is shown.
* There should be 5 interfaces of that object. 
  - \Device\ConDrv\Connect
  - \Device\ConDrv\Reference
  - \Device\ConDrv\Input
  - \Device\ConDrv\Output
  - \Device\ConDrv\Output (StdErr)
* These are shown in Process Explorer.

**Comment by fade2gray** [comment]
Running as asmin -> admin maybe?

**Comment by dmex** [comment]
> These are shown in Process Explorer.

Process Explorer incorrectly concentrates the device strings giving ConDrv handles a name which doesn't exist.

> Only \Device\ConDrv is shown

This is the name returned by ObQueryNameString which is correct.

The ConDrv file handles don't have waiters/busy flags set so KPH doesn't go into the path for device objects and don't query the RelatedFileObject:

https://github.com/processhacker/processhacker/blob/4fee64ee28a58628c0be2ce4877331a8b7d3cdc2/KProcessHacker/object.c#L394-L397

There would need to be an explicit check for ConDrv which might introduce a deadlock. Process Explorer avoided the issue by only querying the tail device string but this isn't correct and ends up showing names for devices which don't actually exist.

NPFS.sys (pipes) has the exact same design as ConDrv.sys and doesn't have that same problem so isn't this issue a bug in ConDrv?

**Comment by Biswa96** [comment]
I have zero idea about kernel mode stuff. But I can aggree that ConDrv is different that other typical km drivers. Whatever the Process Explorer does it helps me to poke around.

Maybe you could check the process subsystem to CUI.

**Comment by dmex** [comment]
> ConDrv is different that other typical km drivers.
> Maybe you could check the process subsystem to CUI.

We could ask about it on their github issues?
https://github.com/microsoft/terminal

**Comment by Biswa96** [comment]
🤷‍♂️

**Comment by Biswa96** [comment]
BTW, forgot to say that there is one interface in it's full form in cmd.exe process's handle list, this one `\Device\ConDrv\Server\Reference\Connect\Input`. But it only shows if cmd.exe is executed from Win+X menu. So, something is working _at full potential_ but not always :)

**Comment by jxy-s** [comment]
Could probably remove the check for ` (((PFILE_OBJECT)Object)->Busy || ((PFILE_OBJECT)Object)->Waiters)) ` and have all FO's go through `KphQueryNameFileObject`.

**Comment by Biswa96** [comment]
Instead of removing anythin frim kernel mode driver, I would like to suggest add an option/ioctl to disable it from user mode.

**Comment by dmex** [comment]
> have all FO's go through KphQueryNameFileObject

This would probably work better.

> I would like to suggest add an option/ioctl to disable it from user mode.

Why would it need to be disabled?

**Comment by Biswa96** [comment]
I mean to change the check or state or whatever the code does, like an experimental option.
