### ISSUE TITLE
How to silent install v3?

### ISSUE THREAD

**Issue by rgl** [winsiderss/systeminformer#759]
From the source code at https://github.com/processhacker/processhacker/blob/7edcf88278c3b9852afcdcb7816b0ffef148b2a7/tools/CustomSetupTool/main.c#L256 it seems the `-silent` would work, but the following does not really work:

```powershell
processhacker-3.0.3683-setup.exe install -silent | Out-String -Stream
```

So, how can we silent install v3?

**Comment by dmex** [comment]
> it seems the -silent would work

It used to work until recently.

> So, how can we silent install v3?

The silent parameter was partially commented out after some other changes and the support changed to require two extra parameters for the installation directory path string as base64. This is not what you would expect from previous versions and for the same parameter found in other installers.

It would be a compatibility issue with the /silent parameter and needs to be fixed. I'll update the setup this week. Thanks for reporting it 👍

**Comment by itsmeboy0** [comment]
Any updates on this?

**Comment by Biswa96** [comment]
Download the zip file from https://processhacker.sourceforge.io/nightly.php

**Comment by bibimagic** [comment]
Hi,
I was able to install System Informer in silent mode until v3.0.5727 by running:
`systemformer-3.0.5727-setup.exe -silent`.
Since v3.0.5847, the silent mode does not work anymore.
Is this option expected to be replaced in future versions of System Informer?

**Comment by bibimagic** [comment]
Hi,
I could not install **_System Informer 3.0.5988_** with the `-silent` option. 
Is there still nothing to install the application in silent mode?
Thank you.

**Comment by fabiorzfreitas** [comment]
@dmex I hate bumping stuff on free software, but I think it's needed here. A silent switch is a must for many deploying scenarios and, if I understood correctly, it may be a single uncomment fix or a substitution of `-silent` for 2 or more parameters.

Either way, deploying can probably use any fix or be rebuilt to use other release resources, like binaries or even building from source.

This software is awesome and I'd really appreciate including it as easily as possible on my setup, thanks for your all your work on this!

**Comment by Biswa96** [comment]
Wouldn't it be possible to "install" silently using zip file? The release page provides ZIP files here https://github.com/winsiderss/si-builds/releases

**Comment by fabiorzfreitas** [comment]
> Wouldn't it be possible to "install" silently using zip file? The release page provides ZIP files here [winsiderss/si-builds/releases](https://github.com/winsiderss/si-builds/releases)

@Biswa96 Perhaps I should expand on the previous reply. I requested for `-silent` simply to make it possible for @bibimagic to update (or accept a PR for) their Chocolatey package.

Chocolatey packages are sometimes distributed as `.portable` and `.install`. Using the zip file likely would be enough (but I'm not sure on how preferences/settings are handled in `.portable` deploys). I believe this kind of package is probably harder to maintain, as all the work usually done by a setup file would have to manually scripted. 

On the other hand, a `.install` package is usually way more straight forward: either the link for every update would be the only thing to update in the script, or there'll be a `latest-release` link. Then the maintainer simply specifies what's the silent switch for the installer.

Actually, I described a sloppy, but functional, implementation. The proper way would include adjusting hashes and package versioning and maintaining a changelog. Still, the sloppy job is more than enough.

The big advantage is that, while Chocolatey works via PowerShell, users (like myself) who don't know the language can also maintain packages by using simple templates. Big packages such as Telegram or Firefox are maintained by very knowledgeable people who probably already coded and set up automatic updates for each package.

Not all packages can be maintained by a small group of people, of course, so lots of packages are maintained by the devs themselves or by regular users. A good example is RegCool, a software with not that many users. Every single time I run `choco update all`, RegCool.install throws me a checksum error. I have inspected the `.ps1` file and noticed it was a simple link to `latest` without actually updating the hashes.

This allows me to run `choco update all` and then `choco update regcool.install --ignore-checksums`, which avoids passing the argument to `all`. No PowerShell experts involved, and barely no hard-work needed from a maintainer who wouldn't be able to do much more than filling a template (again, I would be this kind of maintainer).

---

As the silent switch seem to simply have been "partially commented out", I'm hoping it can be implemented back without much effort :)

**Comment by sitiom** [comment]
@jxy-s Can you close this issue now? Seems like you fixed it in https://github.com/winsiderss/systeminformer/commit/37654a92955b2d69b8de5f0b6a6861d0615978e6 and https://github.com/winsiderss/systeminformer/commit/749be5882841d31b52f3c0d85baa316432ecc34a.
