### ISSUE TITLE
KphCaptureStackBackTraceThread may hang

### ISSUE THREAD

**Issue by jxy-s** [winsiderss/systeminformer#764]
# Description
`KphCaptureStackBackTraceThread` may hang in the path where it queues an APC a thread to capture the stack of that thread. There is no guarantee that the APC will fire, in the event the APC is queued to a thread wherein the APC queue is never given an opportunity to drain, the `KeWaitForSingleObject` will indefinitely wait and hang. Furthermore, while this APC is queued we can not safely unload KPH as it may fire sometime later. This path needs attention:

https://github.com/processhacker/processhacker/blob/ed81bf36e6ceb44fc2a9f094450f4d8faf95d229/KProcessHacker/thread.c#L427-L450

# Steps to reproduce the behavior:
1. Trigger a stack capture on a thread that is not the current thread and that won't drain the APC queue
2. Observe that the APC will never fire, `KeWaitForSingleObject` will never unblock
3. This results in a hang

# Expected behavior
Capturing the stack of a thread using KPH should not hang.

# Additional Context

**Screenshots**: N/A

**Affected Versions**: Windows - All Versions

**Comment by jxy-s** [comment]
@dmex I don't look to have permission to update tags/assignees, feel free to tag this and assign it to me.

**Comment by dmex** [comment]
Similar issue reported here:
https://wj32.org/processhacker/forums/viewtopic.php?f=24&t=2391
