### ISSUE TITLE
Streamer Mode

### ISSUE THREAD

**Issue by dmex** [winsiderss/systeminformer#780]
When Process Hacker is configured as the system default Task Manager and when the user is streaming on youtube/twitch... Running PH while streaming (for example; ctrl+alt+del) reveals potentially sensitive and personal information about the streamer including:

* Machine name
* User name
* Processes (Chat programs/Security software)
* Services (Security software)
* Drivers (Security software)
* Network connections (Connected servers)
* Disk activity (Folder paths)
* Firewall activity

Process Hacker should include a Steamer Mode similar to other software (Discord/Games) to prevent information disclosure and unintentionally revealing sensitive information to the streamer's audience.

**Comment by diversenok** [comment]
Perhaps, [SetWindowDisplayAffinity](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-setwindowdisplayaffinity) with WDA_EXCLUDEFROMCAPTURE?

**Comment by dmex** [comment]
> Perhaps, SetWindowDisplayAffinity

The streamer mode built into Discord/COD/PUBG/Fortnite was implemented by randomizing strings... If we randomized strings (for example: process1/process2/process3) you wouldn't be able to differentiate processes (notepad and chrome from discord) and might accidentally terminate the wrong program.

It just doesn't make sense to randomize strings for a task manager application so the idea was based on using SetWindowDisplayAffinity to exclude the entire window from capture.

> WDA_EXCLUDEFROMCAPTURE

Yes, that's the only viable option available. I'm testing the implementation with different applications before pushing it live.

**Comment by dmex** [comment]
> Perhaps, SetWindowDisplayAffinity

This function doesn't exclude menus, tooltips and shadows so the implementation requires more work.

**Comment by AltF5** [comment]
Why not just open task manager instead... if you have a cmd.exe or Run dialog and you create a copy of taskmgr.exe (call it taskmgr2.exe in system32), then in \system32\en-US create a copy of taskmgr.exe.mui and rename that copy to taskmgr2.exe.mui

Just a thought.

If you didn’t have an explorer or cmd to execute anything, I bet it wouldn’t be hard to have the Debugger regval instead execute some PowerShell or AutoIt script IF the left or right mouse button is held down when triggering Ctrl+Shift+Esc

**Comment by dmex** [comment]
@AltF5 

What are you talking about?

This issue isn't about the binary name. It's about sharing images of your processes/services/drivers/networks connections from both PH and taskmgr while streaming to thousands of people just because you needed to open taskmgr and terminate a faulty game.

> create a copy of taskmgr.exe (call it taskmgr2.exe in system32)

You still have the same problem with taskmgr2 showing everything running on your machine to viewers. If they can see you're running defender then they can tailor attacks for defender by emailing a game suggestion/executable binary that isn't currently detected by defender... In other cases if they can see discord connected to XYZ address then they know which region you live in and where to swat based on the caller id region.

The whole point of this feature is excluding the UI from streaming programs so you don't share that information about your machine to thousands of people who will analyse it for information - renaming the binary won't prevent taskmgr or PH from showing everything else on your machine while you're live - you have to exclude the entire window.

**Comment by AltF5** [comment]
Ah I thought the issue was that Taskmgr = Fine but PH = exposes too much AIO. This is what through me off “When Process Hacker is configured as the system default Task Manage”... sounds like what persons need is to run a taskkill /im some.exe /f.

**Comment by dmex** [comment]
Streamer mode added in latest nightly

**Comment by ge0rdi** [comment]
> Streamer mode added in latest nightly

Cool.
Any plans to release another nightly build?
There were quite many changes since last one.
