### ISSUE TITLE
No white Windows theme support and black background for usage/history tray icons does not match white OS theme

### ISSUE THREAD

**Issue by Ne0niq** [winsiderss/systeminformer#823]
Honorable dev's! Please hear me out.

**Describe the bug**
1. Hardware usage/history tray icons have black background (unable to change) and I barely see numbers on lback backgound among light windows theme. If in process hacker options 

To reproduce this, simply go to Windows 10 Settings (20H2) / Colors > "Change your color" = light. 
When light Windows theme is active, whole taskbar is in strong contrast with Process Hacker tray icons, thus reading icons text becoming very inconvenient. 

I don't know if this related or not, but just in case: the "use old color (clack background)" setting is disabled in options / graphs and the background is still black.

2. Overall, white Windows theme is not supported. I enable the "Enable theme support..." setting, I getting black theme despite the white Windows theme is currently active (Windows build 2009 20H2). 

**Screenshots**
[screenshot](https://i.imgur.com/ZX0OJWS.png)

**Desktop (please complete the following information):**
 - OS: Windows pro 20H2
 
**Additional context**
Dear author, if you be so kind and find some time for my humble request/report, I would like to see an option to change tray icons background, not only font color for text and graphs. Also mathcing windows theme would be nice for tray icons (e.g. take taskbar color for icons background).

Wishing you all the best! Thank you for such wonderful software!

**Comment by dmex** [comment]
The nightly build includes an experimental setting named `IconTransparencyEnabled` for enabling transparent backgrounds when using the white theme
