### ISSUE TITLE
feature request: ability to restart ALL services on contextual menu of a process

### ISSUE THREAD

**Issue by mailinglists35** [winsiderss/systeminformer#84]
currently i can only restart service one by one manually.
it would very useful to have in the right click context menu:

- a menu item that stops and starts all services, one by one (stop and start service1, stop and start service2, etc), in background (without blocking the user interface)
- a menu item that terminates process then starts all services that were running under it

![image](https://cloud.githubusercontent.com/assets/2054302/21137892/ac2bd8f0-c13c-11e6-93f5-db4c52227031.png)

**Comment by mailinglists35** [comment]
useful context: some services leaking memory. a one shot approach at reclaiming memory and have the services up again.

**Comment by AltF5** [comment]
Hi, I’ve written code to do this in the Services tab. It allows a context menu to display operations for a bulk-selection. Then a minor change to handle that list passed in
