### ISSUE TITLE
Paste in memory editor only works for printable ascii characters.

### ISSUE THREAD

**Issue by EB4FBZ** [winsiderss/systeminformer#851]
**Describe the bug**
Pasting any content into memory editor only works for ascii data containing only printable characers. 

**To Reproduce**
Copying and pasting ascii data results in corruption of non printable bytes. 
You can copy hex or ascii, but paste is allways done in ascii section and non printable characters are corrupted.

**Expected behavior**
I would expect to be able to copy and paste both hex or ascii (printable characters or not) sections.

**Describe the solution you'd like**
It would be great being able to paste hex data, or even import binary files.

**Desktop**
- OS: Windows 10 Pro 64bit
- Process Hacker 2.39.124

Thanks a lot for your awesome work.

**Comment by dmex** [comment]
Merging bug with #851
