### ISSUE TITLE
Add start/stop button for saving process/memory period histoy by filter

### ISSUE THREAD

**Issue by Jelle-Wu** [winsiderss/systeminformer#875]
easier for performance analysis

**Comment by dmex** [comment]
F6 already starts/stops the interval updates?

**Comment by Jelle-Wu** [comment]
the current version only can save a snapshot of process/memory.If process hacker can save a period time of process/memory should be better.

**Comment by dmex** [comment]
Period related logging is outside the scope for this tool. You should use ETW/Xperf for logging process/memory related data.
