### ISSUE TITLE
Random system freezes with KPH enabled

### ISSUE THREAD

**Issue by parkovski** [winsiderss/systeminformer#889]
**Describe the bug**
If I have the KPH driver enabled, my system will eventually freeze, requiring a hard reset. This is extremely unreliable but I've been observing this over a few months and while the freeze comes at an unreliable time, it does happen within a few hours, and only when the KPH driver is enabled. I also looked into loopMIDI, the only other non-standard driver I have installed, and it's not that. It seems tied to high disk or CPU usage, but I couldn't say for sure.

This seems really difficult to track down, so I'd like to see at least if anyone else has had this issue and notices it resolving when KPH is disabled.

**To Reproduce**
It's not really reproducible, but if anyone's noticed random system freezes it's worth looking into.

**Expected behavior**
The system should not crash.

**Desktop (please complete the following information):**
 - OS: Windows 10.0.19042 20H2

**Additional context**
I'm on a Surface Pro 2017. I use WSL 2, so I have Hyper-V on. As I said before, loopMIDI is the only other 3rd party driver I've installed. Crashes seem to happen more when doing things like opening a ton of browser tabs or building a C++ or Rust project but can also happen when I'm not doing anything.

**Comment by parkovski** [comment]
I'd have to leave WSL off for days at a time which is unrealistic. If I'm really the only one that's seeing this, I can accept that it's a quirk of my machine, but turning off KPH does seem to be a real solution for me. Is there really no way to trace WSL2 memory usage? WSL1 used to leak non-paged pool early on for me which was obviously a problem but it was much more easily traceable.

**Comment by dmex** [comment]
@parkovski 

This might help check the utilization:
https://docs.microsoft.com/en-us/windows-server/administration/performance-tuning/role/hyper-v-server/detecting-virtualized-environment-bottlenecks
