### ISSUE TITLE
[feature] Update modern icons

### ISSUE THREAD

**Issue by 1280px** [winsiderss/systeminformer#949]
Current modern icons are pretty nice, but they don't support dark mode and also don't fit with current Windows 10/11 UI at all!

I can suggest use [this](https://feathericons.com/) iconset - it fits pretty good with current Windows UI and can be easily transported to any size or color because of .svg format.

Here's my concept of PH with new icons based on iconset above with tiny toolbar UI fixes (can we get rid of this horrible 1px white line in dark mode pleeeease?)
![phicon-l](https://user-images.githubusercontent.com/71165491/129616842-ad353ff6-c4c9-4ea3-81dc-4caf50ada0fd.png)
![phicon-d](https://user-images.githubusercontent.com/71165491/129616847-4653a4b9-414f-4697-993a-04d88c31515b.png)

**UPD: I found out Microsoft has a HUGE free-to-use Fluent icons collection on GitHub: https://github.com/microsoft/fluentui-system-icons, which makes things even better :D**

**Comment by codeworks-studio** [comment]
Looks cleaner

**Comment by jxy-s** [comment]
I do agree the icons need a bit of a refresh overall. Work is in progress for dark mode (which is still an experimental feature https://github.com/processhacker/processhacker/issues/98) and the modern icons should eventually support that more gracefully.

**Comment by dmex** [comment]
> can we get rid of this horrible 1px white line in dark mode pleeeease?

win32k inserts that line... I haven't found anything that would let me remove it without completely replacing the entire menu.

Windows 7 classic theme:
![image](https://user-images.githubusercontent.com/1306177/131576529-3d7e560e-6839-47bc-9b7b-d1caf8e693e3.png)

Windows 11 theme:
![image](https://user-images.githubusercontent.com/1306177/131576672-ea2a82a5-51aa-4b1b-89a0-7bd5bb4cba1b.png)


What you can do though is right-click the toolbar and set the menu to 'auto-hide':
![image](https://user-images.githubusercontent.com/1306177/131576782-d7311a70-4d43-402b-b5b0-788a23c497d9.png)

You can press the ALT key to hide/show the menu. There are some solutions for replacing the menu control entirely but they all come with their own set of problems and issues... It's not a great solution but this works for now.

The icons will probably be updated soon. The idea is allowing them to be customized by changing the files on disk separate from the DLL.

**Comment by MagicAndre1981** [comment]
don't add such ugly icons, this is what I hate about the new sysinternals tool updates. I still want colored icons to find things much faster

**Comment by 1280px** [comment]
> I still want colored icons to find things much faster

Classic icons still will be available, I only suggest to update **modern** icons (which look pretty bad right now, not to mention they don't even support dark mode)

**Comment by dmex** [comment]
> can we get rid of this horrible 1px white line in dark mode pleeeease?

The white line will be removed in the next update. There were 3 undocumented window messages on Windows 7 and above required to draw the menu and remove the line... Not sure why MS hasn't documented these messages but now we know 👍

![image](https://user-images.githubusercontent.com/1306177/136098176-532407f8-0330-4e99-b193-1f2d6a21d03d.png)

**Comment by dmex** [comment]
Menubar was updated in latest nightly build.
